### ISSUE TITLE
Big problems with tcp offload

### ISSUE THREAD

**Issue by guilhem** [virtio-win/kvm-guest-drivers-windows#1]
I use KVM in my company with a mix Linux/WIndows.

I use them with vhost_net, bridge and/or macvtap.

Problems com with macvtap on Windows.
without any management of tcp offload :
1) Windows reject any packet send from another vm on the same host (and in macvtap too). (can be correct by a tricky rule in iptables... but it's quite awful
2) More painful, when GRO is activated on host, ALL packets are dropped by windows...

**Comment by sameehj** [comment]
Hi,

we are currently in a process of closing all github's issues that have been resolved or expired. I'm currently closing this issue, please reopen the issue or else open a new issue if needed.
