### ISSUE TITLE
virtio-mem Windows guest support 

### ISSUE THREAD

**Issue by ohault** [virtio-win/kvm-guest-drivers-windows#1000]
MmAddPhysicalMemory has just been [documented](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-wdm-mmaddphysicalmemory)

In follow-up of https://ourwindowsman.wordpress.com/2020/11/03/virtio-mem-goes-to-windows/, the virtio-mem Windows guest support can continue.

**Comment by YanVugenfirer** [comment]
@ohault Thanks!

**Comment by Directox01** [comment]
Hello @YanVugenfirer, may I ask if it's related to the feature I've asked about https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/989 ?
Thank you in advance.

**Comment by YanVugenfirer** [comment]
@Directox01 It is an alternative method for memory over commit in the guest, when the memory is added\removed by the hypervisor and the driver.

**Comment by YanVugenfirer** [comment]
virtio-mem implementation was added to the tree.

**Comment by ohault** [comment]
@YanVugenfirer , thank you. Would it be possible to have a public release soon on https://github.com/virtio-win/kvm-guest-drivers-windows/releases or somewhere else ?

**Comment by YanVugenfirer** [comment]
There was a discussion: https://github.com/virtio-win/kvm-guest-drivers-windows/pull/794#issuecomment-2074467063

**Comment by YanVugenfirer** [comment]
@ohault I think the latest build should contain it.

**Comment by vrozenfe** [comment]
Yes, viomem is a part of virtio-win ios and rpm 
https://github.com/virtio-win/virtio-win-pkg-scripts/commit/1431fa0624d7f16077030a1d42c81023bc29c185
and also included in installer https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/daf2701f3430c9285743cc1124b6af21afd8c94e

Just be advice that if I'm not mistaken, the driver itself is still release as a preview.

Vadim.
