### ISSUE TITLE
netkvm: some piece of code in RSSCalcHash_Unsafe seems like it will never execute.

### ISSUE THREAD

**Issue by zjmletang** [virtio-win/kvm-guest-drivers-windows#1006]
**Describe the bug**
In RSSCalcHash_Unsafe function.The condition "if(hashTypes & NDIS_HASH_IPV6)" seems like it will never be executed. Because the condition "if(hashTypes & (NDIS_HASH_IPV6 | NDIS_HASH_IPV6_EX))" includes "if(hashTypes & NDIS_HASH_IPV6)".

![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/114464945/91b4d1b3-f1ae-49b6-858a-cf557d68bc01)

**Expected behavior**
Perhaps the code under the condition "if(hashTypes & NDIS_HASH_IPV6)" can be removed.

**Comment by ybendito** [comment]
Indeed. Thanks, we'll remote it.

**Comment by zjmletang** [comment]
ok, you're welcome.
