### ISSUE TITLE
Mini ISO

### ISSUE THREAD

**Issue by kroese** [virtio-win/kvm-guest-drivers-windows#1030]
Im distributing the drivers ISO along my application, but it's pretty huge (> 500 MB) and even compressed its still a couple of hundred MBs.

As far as I can tell the bulk of this space is occupied by the PDB (debugging files) which are not really necessary for production use. 

Would it be an idea to generate also a tiny ISO with all stuff removed that is not strictly required?

**Comment by vrozenfe** [comment]
Unfortunately we don't build vfd images any more. 
But customising and rebuilding the virtio-win iso can be easily done by using  mkisofs  utility
https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/virtio-win.spec#L142

**Comment by vrozenfe** [comment]
* Do you want to rebuild the iso image only or repackage the entire rpm?
* It shouldn't be a problem with the binaries redistribution as it stated in our LICENSE file  https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/LICENSE#L6
* we trying to keep the tag to build map as much accurate and updated as possible https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Builds-and-tags-mapping

Best,
Vadim.
