### ISSUE TITLE
Windows Server 2025 drivers

### ISSUE THREAD

**Issue by kroese** [virtio-win/kvm-guest-drivers-windows#1037]
Two days ago, Microsoft released a preview for Windows Server 2025, see https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver

I tried to install it, but it does not accept the Windows Server 2022 drivers for `vioscsi`, nor the Windows 11 one.

Maybe it just needs a modified `.inf` file, as I don't assume anything changed in the driver API compared to Win11/Win22?

Anyway, it would be nice to be able install the 2025 version, so my feature request is to include a `w2k25` release of the drivers.

**Comment by kostyanf14** [comment]
Hi @kroese 

What build number of Windows Server do you have?

**Comment by vrozenfe** [comment]
@kroese 
Did you try a "normal" vNext preview rather than Azure version ?
Vadim

**Comment by vrozenfe** [comment]
Tried to install vNext  26040.1000.240122-1157 Standard Server on 
my F37 laptop
[vrozenfe@milly vms]$ uname -r
6.5.12-100.fc37.x86_64
and 
(qemu) info version 
8.2.50v8.2.0-645-g977542ded7
![Screenshot from 2024-01-29 23-36-57](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/1526363/b7c384e6-7083-4021-8606-788f76f594a6)

seems to work fine with viostor, netkvm and viogpudo drivers build for ws2022
![Screenshot from 2024-01-29 23-38-53](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/1526363/6f100ba6-0f1b-421a-b781-2bf3407fd082)

my qemu command line:

#!/bin/sh
IMG='/home/vrozenfe/work/images/vnext.qcow2'
QEMU='/home/vrozenfe/work/upstream/qemu/build/x86_64-softmmu/qemu-system-x86_64'
CDROM='/home/vrozenfe/work/isos/26040.1000.240122-1157.rs_prerelease_SERVER_OEMRET_x64FRE_en-us.iso'
ISO='/home/vrozenfe/work/isos/virtio-win-0.1.240.iso'

FLAGS=',hv_stimer,hv_synic,hv_vpindex,hv_relaxed,hv_spinlocks=0xfff,hv_vapic,hv_time,hv_frequencies,hv_runtime,hv_tlbflush,hv_reenlightenment,hv_stimer_direct,hv_ipi,+kvm_pv_unhalt'

VGA='-device virtio-vga,edid=on,xres=1280,yres=800'
CPU='host'
sudo $QEMU -name vNext \
        -M q35 -S \
        -L /home/vrozenfe/work/upstream/qemu/pc-bios/ \
        -cpu $CPU$FLAGS \
        -machine hpet=off \
        -monitor stdio \
        -enable-kvm \
        -rtc base=localtime,clock=host,driftfix=slew \
        -usb -device usb-tablet,id=input0 \
        -global kvm-pit.lost_tick_policy=discard \
        -m 4G -smp 4,maxcpus=4,cores=4,threads=1,sockets=1 \

**Comment by vrozenfe** [comment]
$VGA \
        -drive file=$IMG,if=none,media=disk,format=qcow2,rerror=stop,werror=stop,cache=none,id=drive-vioscsi0 \
        -device virtio-scsi-pci,id=scsi-vioscsi0 \
        -device scsi-hd,drive=drive-vioscsi0,id=vioscsi0,bus=scsi-vioscsi0.0,lun=0,scsi-id=0,bootindex=1 \
        -device virtio-net-pci,mac=9a:55:56:57:30:25,id=id18Xcuo,vectors=4,netdev=idGRsMas \
        -netdev tap,id=idGRsMas,script=/etc/qemu-ifup \
        -drive id=drive_cd0,if=none,snapshot=off,aio=threads,cache=none,media=cdrom,file=$CDROM \
        -device ide-cd,id=cd0,drive=drive_cd0,bootindex=2,bus=ide.0,unit=0 \
        -drive id=drive_cd1,if=none,snapshot=off,aio=threads,cache=none,media=cdrom,file=$ISO \
        -device ide-cd,id=cd1,drive=drive_cd1,bootindex=-1,bus=ide.1,unit=0 \
#       $SER \

**Comment by kostyanf14** [comment]
I try both viostor and vioscsi (with corresponding device), and both work fine

**Comment by kostyanf14** [comment]
@kroese 

Do you run Windows with OVMF (secure-boot or no) or SeaBIOS? 
Do you run QEMU directly or via libvirt?

**Comment by fkonradmain** [comment]
So, I got almost all of the drivers to work, by hard code activating directly via powershell. I just wanted to share it with you, because it seems to be a certificate issue as well.

My environment:
- Proxmox 8.1
- CPU AMD GX-424CC
- SeaBios
- pc-q35-8.1
- Virtio SCSI Single
- Virtio NIC
- Windows Server Datacenter Core Version 10.0.26063.1

About the installation:
I had no issues here, as disk driver I selected the directory `amd64\2k22`and then picked the driver.


I wrote a script, that
1. runs the main installer on the root path of the virtio disk
2. installs the certificates to the Windows Certificate Store
3. installs all drivers, one after another
4. installs the qemu guest agent

```powershell
# Define the paths to the MSI files
$virtioWinMSI = "D:\virtio-win-gt-x64.msi"
$guestAgentMSI = "D:\guest-agent\qemu-ga-x86_64.msi"

# Install Virtio-Win MSI
Start-Process msiexec.exe -ArgumentList "/i `"$virtioWinMSI`" /qn" -Wait


# Add the Root CA for the drivers to the TrustedPublisher and the Root CA store
Import-Certificate -FilePath "D:\cert\Virtio_Win_Red_Hat_CA.cer" -CertStoreLocation "Cert:\LocalMachine\TrustedPublisher"
Import-Certificate -FilePath "D:\cert\Virtio_Win_Red_Hat_CA.cer" -CertStoreLocation "Cert:\LocalMachine\Root"

# Install Virtio drivers
pnputil -i -a "D:\amd64\2k22\vioscsi.inf"
pnputil -i -a "D:\amd64\2k22\viostor.inf"
pnputil -i -a "D:\Balloon\2k22\amd64\balloon.inf"
pnputil -i -a "D:\NetKVM\2k22\amd64\netkvm.inf"
pnputil -i -a "D:\fwcfg\2k22\amd64\fwcfg.inf"
pnputil -i -a "D:\pvpanic\2k22\amd64\pvpanic.inf"
pnputil -i -a "D:\pvpanic\2k22\amd64\pvpanic-pci.inf"
pnputil -i -a "D:\qemufwcfg\2k22\amd64\qemufwcfg.inf"
pnputil -i -a "D:\qemupciserial\2k22\amd64\qemupciserial.inf"
pnputil -i -a "D:\smbus\2k22\amd64\smbus.inf"
pnputil -i -a "D:\sriov\2k22\amd64\vioprot.inf"
pnputil -i -a "D:\viofs\2k22\amd64\viofs.inf"
pnputil -i -a "D:\viogpudo\2k22\amd64\viogpudo.inf"
pnputil -i -a "D:\vioinput\2k22\amd64\vioinput.inf"
pnputil -i -a "D:\viorng\2k22\amd64\viorng.inf"
pnputil -i -a "D:\vioscsi\2k22\amd64\vioscsi.inf"
pnputil -i -a "D:\vioserial\2k22\amd64\vioser.inf"
pnputil -i -a "D:\viostor\2k22\amd64\viostor.inf"

# Install QEMU Guest Agent MSI
Start-Process msiexec.exe -ArgumentList "/i `"$guestAgentMSI`" /qn" -Wait
```

At the end, only one device is not recognized (no idea, which it actually is, though):
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/88140888/d64e945a-1f03-4714-9595-7aca7b6cc05e)

**Comment by vrozenfe** [comment]
@fkonradmain 
It will be better to use Win11 drivers for WS2025
Vadim.
