### ISSUE TITLE
virtio-win scsi - driver does not scan scsi target 0

### ISSUE THREAD

**Issue by thedesertfox** [virtio-win/kvm-guest-drivers-windows#105]
I am running virtio user scsi, and the problem I run into is that Windows (I tried Win10 and Win7) does not scan scsi target 0 for scsi devices. I am wondering if there is anything I could do to try to resolve this issue. My QEMU command line contains the following:
-chardev socket,id=as00,path=/var/run/as00.sock -device vhost-user-scsi-pci,chardev=as00,num_queues=6,max_sectors=32768,bootindex=4 

On the target side, I see Windows scanning target1-lun0, target2-lun0... so on up to target0xfe-lun0. Notice how target0-lun0 is not scanned.

Please advise. I am willing to try out patches or experimental changes to the windows driver.

**Comment by vrozenfe** [comment]
Hi thedesertfox
Thank you for reporting this issue.

vioscsi driver does check PathId, TargetId and Lun number, but it doesn't filter TargetId 0

    if( (SRB_PATH_ID(Srb) > (UCHAR)adaptExt->num_queues) ||
        (TargetId >= adaptExt->scsi_config.max_target) ||
        (Lun >= adaptExt->scsi_config.max_lun) ) {
        SRB_SET_SRB_STATUS(Srb, SRB_STATUS_NO_DEVICE);
        StorPortNotification(RequestComplete,
                             DeviceExtension,
                             Srb);
        return FALSE;
    }
 
I personally never tried vus on my own, probably should do now. Do you observe the same problem on vhost-scsi, or virtio-scsi-pci ?

Thanks and best regards,
Vadim.

**Comment by thedesertfox** [comment]
Hi Vadim,

In have not tested vhost-scsi or virtio-scsi-pci with windows. I can try to test this tomorrow.

I did notice the "if" statement you mentioned in your comment. I have already tried commenting it out. That did not fix the problem (as you also suspected).

I am not familiar with windows drivers, but I read somewhere that a problem like this could be related to not setting the InitiatorBusId in PORT_CONFIGURATION_INFORMATION properly. I don't think that is the problem here, but I thought I would mention it anyway.

Thanks. Please let me know if I could provide any debugging information, or if you have any ideas.

Thanks again.

**Comment by vrozenfe** [comment]
Did you try it on Linux? Does it work as expected?

All the best,

Vadim.

**Comment by thedesertfox** [comment]
Hi Vadim,

Yes, it works as expected in Linux. Further, it seems that SeaBios also correctly scans all targets to look for boot devices. Thus the problem seems to be related to Windows somehow.

As an experiment, I changed the scsi user storage to support target-1 instead of target-0, then all luns showed up in Windows disk manager. 

Thanks

**Comment by vrozenfe** [comment]
Thank you.

I will take a look into this.

All the best,
Vadim.

**Comment by thedesertfox** [comment]
Hi Vadim,

It appears that req->lun[2] != 0x40 when the requests come through from Windows. This was causing the user space vhost-user-scsi app not not decode target 0 commands properly. Sorry about this. It is not a bug in the Windows drivers.

My apologies. And thanks.
Thanks

**Comment by vrozenfe** [comment]
Hi thedesertfox,

Thanks a lot for your update, 
and glad to know that the troubles were
not caused by our driver.

All the best.
Vadim.
