### ISSUE TITLE
Virtio drivers - Version 0.1.248

### ISSUE THREAD

**Issue by erdebugger** [virtio-win/kvm-guest-drivers-windows#1054]
I installed the new version of the drivers yesterday and I have encountered TWO major problems. Tested with W10 Pro LTSC guest in PROXMOX

The first is that when installing it, the graphics card driver configuration is lost and then you have to install it manually. You have to go to the device manager and install the graphics card driver manually by searching for the driver in the ISO of the new drivers (that is automatic)

The second is that the QEMU Agent is not installed correctly and the SPICE agent that allows dragging and dropping content from the host to the guest is not enabled. A message appears that the Agent is not running.

Therefore, I have reverted to the previous version 0.1.240

**Comment by YanVugenfirer** [comment]
@erdebugger Thank you for submitting the issue. 
I want to separate something that might be several separate topics.

1. Spice - we are removing spice support from the latest installers. We are not Spice maintaners, nor we manage this project. We provided spice (QXL driver) and agent previously - but no longer going to do it. If you need them please install them separatly.
2. Can you describe the issues with qemu-ga?

Thanks,
Yan.

**Comment by vrozenfe** [comment]
spice and qxl  not supported by Red Hat anymore.  
We removed these two components from the virtio-win bundle.
I would suggest using virtio-win msis (virtio-win-gt-x64.msi/virtio-win-gt-x86.msi) to update or install virtio-win driver and bundle (virtio-win-guest-tools.exe)  to update or install virtio-win drivers and qemu agent.
If the user needs to install the qxl drivers it needs to be done as a separate step, manually. The drivers are located in qxldod sub directory.

Btw, what kind of graphics solution PROXMOX uses - qxl or virtio-gpu ?

Best,
Vadim.

**Comment by vrozenfe** [comment]
For the spice related stuff please see
https://github.com/virtio-win/virtio-win-guest-tools-installer/issues/25
and
https://github.com/virtio-win/virtio-win-pkg-scripts/issues/76
It should be resolved now.
