### ISSUE TITLE
wiki update for virtiofs

### ISSUE THREAD

**Issue by Inilien** [virtio-win/kvm-guest-drivers-windows#1071]
**Is your feature request related to a problem? Please describe.**
Sorry, do not know of a proper way to suggest a wiki update. Decided to submit information here for now.

Currently [virtiofs wiki](https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Virtiofs:-Shared-file-system) leads to a configuration not usable by some applications.  
The problem I was having was already [discussed once in this project](https://github.com/virtio-win/kvm-guest-drivers-windows/issues/517#issuecomment-1015521904) and the same solution worked for me.  
Please add to the wiki:

> For some use-cases you may need to mount your drive as a global one. To achieve that with WinFSP you need to 
> - specify mount point `\\.\M:` (to create drive `M:`) 
> - run `virtiofs.exe` as an administrator
>     - either from administrator console
>    - or [specifying an administrator](https://superuser.com/questions/1694930/do-windows-services-have-elevated-privileges) user for your service 

Also would be great if [case insensitivity](https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Virtiofs:-Shared-file-system#case-insensitivity) section explained what exactly to do in the registry
Please replace  

> Case insensitivity can be turned on by `-i` command-line parameter of `CaseInsensitive` registry key.  

with  

> Case insensitivity can be turned on by 
> - `-i` command-line parameter 
> - `CaseInsensitive` registry key with type `DWORD` and value `1`.

**Additional context**
Note: For some reason, after I mounted my drive as a global one, Windows created recycle bin in it and wouldn't stop complaining about the bin being corrupted...  
Deleting the folder `$RECYCLE.BIN` by hand or using fancy methods from the internet didn't help.  
Asking Windows to [not use it](https://www.howtogeek.com/366395/how-to-change-recycle-bin-settings-on-windows-10/#stop-using-the-recycle-bin-and-have-items-deleted-immediately) - finally stopped the errors.  
After that I deleted the bin on the drive.  But after I restarted the VirtioFS service, Windows applied default behaviour and started to use recycle bin in this mount again.  
But for some reason it was no longer corrupted and there were no errors.  

Not sure if this info is useful or not :shrug:

**Comment by YanVugenfirer** [comment]
@Inilien Can you please open a separate issue about the Recycle Bin?

Thanks.

**Comment by kostyanf14** [comment]
@Inilien We moved the wiki to a separate repo (https://github.com/virtio-win/virtio-win.github.io/), to allow everyone to send fixes or suggestions.
Please send PR to https://github.com/virtio-win/virtio-win.github.io/blob/main/Knowledge-Base/Virtiofs%3A-Shared-file-system.md
