### ISSUE TITLE
Download link for pre built drivers doesn't work?

### ISSUE THREAD

**Issue by Usulyre** [virtio-win/kvm-guest-drivers-windows#1076]
The download link for the prebuilt drivers doesn't work for:

(https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943)

(https://gitlab.freedesktop.org/uploads/195b600a19ee5dacdf9f217066b99505/viogpu3d.zip)

Can we get a working link for viogpu3d.zip?

Thanks in advance.

**Comment by kostyanf14** [comment]
Hi @Usulyre,

Thanks for your interest in this project.

Currently, you are talking about PR that was not merged. We don't plan to support Vgpu3D in the near release, as a result we don't build this driver and don't investigate its issues. 

Our team does not have a driver's binary to provide. All links that you see in messages were provided by the author or community members.

If the driver will be merged, you will get it as all other drivers now.

Thanks,
Konstantin Kostiuk.

**Comment by mincore** [comment]
fix the link:

https://gitlab.freedesktop.org/mesa/mesa/uploads/195b600a19ee5dacdf9f217066b99505/viogpu3d.zip

**Comment by nicman23** [comment]
sorry for commenting here, but except the bin windows drivers linked above, what else is needed - guest and host wise?

**Comment by Eggmanplant** [comment]
THANK YOU. I would need to install Crap 11 Home on my main PC directly, but not with this, as I can create an VM. And spoof my hardware to make Microsoft not fingerprint me as easily.

EDIT: Unfortunately, bsod. What?

**Comment by Eggmanplant** [comment]
> sorry for commenting here, but except the bin windows drivers linked above, what else is needed - guest and host wise?

Enable 3D accel in the VM settings, and enable test signing in Windows. If THAT doesn't work, advanced startup and 7.

**Comment by Eggmanplant** [comment]
> > fix the link:
> > https://gitlab.freedesktop.org/mesa/mesa/uploads/195b600a19ee5dacdf9f217066b99505/viogpu3d.zip
> 
> Thank you. Is this version up to date with all the commits made so far?

Yes, it is.

Maybe test https://github.com/arehnman/kvm-guest-drivers-windows/releases/tag/viogpu3d-2025-09-07 for less issues? EDIT: IT WORKS! But it's super slow.
