### ISSUE TITLE
Latest Win11 netkvm.cat files mention netkvmpoll.inf instead of netkvm.inf

### ISSUE THREAD

**Issue by ybendito** [virtio-win/kvm-guest-drivers-windows#1081]
**Describe the bug**
Looking at latest upstream build we can see that Win11 netkvm.cat file include hash for netkvmpoll.inf instead of netkvm.inf

**To Reproduce**
Steps to reproduce the behaviour: Just to build the netkvm Win11

**Expected behavior**
It would be natural to see netkvm.inf

**Additional context**
Probably the problem existed for long time. Old builds for Win8 and Win8.1 have similar same problem (netkvm_no_uso.inf) appears.
After removal of < Win10 we did not see the problem as the intermediate inx file was always named netkvm.inx
After addition of poll mode we see the problem again with Win11

Surprisingly this does not affect the installation (probably name of INF file is ignored in validation). But anyway this seems weird. Worth fix.

**Comment by YanVugenfirer** [comment]
Fixed by https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1080
