### ISSUE TITLE
viostor: It seems that RhelScsiVerify has an improperly handled boundary condition.

### ISSUE THREAD

**Issue by zjmletang** [virtio-win/kvm-guest-drivers-windows#1095]
**Describe the bug**
In the RhelScsiVerify function, I understand that the case where lba + blocks == adaptExt->lastLBA should be a normal SRB. As shown in the figure below.  If I am mistaken, please point it out to me.

![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/114464945/37d32d58-e21f-42ba-93a2-9392fdc9cefe)

**Comment by vrozenfe** [comment]
Right, we probably missed this case when applied https://github.com/virtio-win/kvm-guest-drivers-windows/commit/67f64d01967769d4b9673e4c1bd08fab184469d7

Thank you for spotting it out.
The fix is welcome.
Vadim.

**Comment by MaxXor** [comment]
Other location I found it seems to be correct: https://github.com/virtio-win/kvm-guest-drivers-windows/blob/657ad7efb539dd186cec1fd33cf31ba710f5dfb1/viostor/virtio_stor.c#L1333

**Comment by zjmletang** [comment]
> Right, we probably missed this case when applied [67f64d0](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/67f64d01967769d4b9673e4c1bd08fab184469d7)
> 
> Thank you for spotting it out. The fix is welcome. Vadim.
@vrozenfe 
ok, I submit a patch to fix it
JianMing

**Comment by zjmletang** [comment]
yes, it can be closed
