### ISSUE TITLE
netkvm: HLK NDISTest 6.5 - [1 Machine] - GenericMiniportRequirements test failed

### ISSUE THREAD

**Issue by zjmletang** [virtio-win/kvm-guest-drivers-windows#1097]
This is a query regarding an issue I encountered while running HLK tests. I noticed that the "NDISTest 6.5 - [1 Machine] - GenericMiniportRequirements" test case failed due to the absence of the Port1DeviceNumber or Port1FunctionNumber in the INF file. However, I observed that this particular test passes successfully during the automated HLK testing we carry out when submitting patches. I'm quite puzzled by this discrepancy. Could you please explain why this might be happening? thanks

![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/114464945/4eadf72d-5e8f-4fa3-83a5-50b7332e0ab7)

**Comment by sb-ntnx** [comment]
I've seen this failure when I had multiple virtio-net vNICs added to the guest.

**Comment by YanVugenfirer** [comment]
In any case, virtio-net is not multiport device (yet? we will see what happens with SR-IOv). https://learn.microsoft.com/en-us/windows-hardware/drivers/network/ddinstall-section-in-a-network-inf-file
So it looks like a bug in the test confusing several separate devices with a multiport device.

**Comment by YanVugenfirer** [comment]
No problem.

Closing.
