### ISSUE TITLE
After upgrading virtio-win-guest-tools on Windows Server 2016, the CPU usage of the Balloon service and WMI Provider Host skyrocketed.

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/kvm-guest-drivers-windows#1098]
Describe the bug
After upgrading virtio-win-guest-tools on Windows Server 2016, the CPU usage of the Balloon service and WMI Provider Host skyrocketed.

To Reproduce
Steps to reproduce the behaviour:
1、Install virtio-win-0.1.240-1,
2、then install virtio-win-0.1.248-1,don't reboot vm
3、restart the BallonService(blnsvr.exe) service.
Expected behavior
null

Screenshots
null

Host:

Kernel version
5.10
QEMU version
6.2
VM:

Windows version
windows 2016 Standard
Which driver has a problem
ballon
Balloon Service is generating the following WMI errorID:5858
"
Id = {00000000-0000-0000-0000-000000000000}; ClientMachine = HOSTNAME; User = NT AUTHORITY\SYSTEM; ClientProcessId = 964; Component = Unknown; Operation = Start IWbemServices::ExecQuery - root\cimv2 : SELECT * FROM Win32_PerfRawData_PerfOS_Memory; ResultCode = 0x80041032; PossibleCause = Unknown

https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/Balloon/app/memstat.cpp
suggest:https://learn.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/wmi-activity-event-5858-logged-with-resultcode-0x80041032

driver is download form:
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.248-1/

Additional context
After reboot vm，CPU usage is down

**Comment by ChendongSun** [comment]
It looks like this problem, https://github.com/virtio-win/kvm-guest-drivers-windows/issues/614

**Comment by xiagao** [comment]
Hi @ChendongSun , I can reproduce this issue. Yes ,it indeed the same one with https://github.com/virtio-win/kvm-guest-drivers-windows/issues/614
In your steps, it happend after updating the drivers via the installer, actually even only with your first step, and plus restart blnsvc service, it also can be reproduced.
The trigger condition is:
1. install blnsvc by the installer.
2. restart blnsvc in service manager.
