### ISSUE TITLE
[netkvm]windows traceview netkvm error 

### ISSUE THREAD

**Issue by bbbccvbvv** [virtio-win/kvm-guest-drivers-windows#1126]
Windows server 2022 install virtio driver(100.93.104.24000).
<img width="932" alt="截屏2024-08-12 19 53 26" src="https://github.com/user-attachments/assets/733ebd34-94b4-48b4-87ec-76650985e3b4">
I want to trace the session.So i use traceview.
But i can trace viostor, cant trace netkvm.
<img width="1117" alt="截屏2024-08-12 19 56 35" src="https://github.com/user-attachments/assets/563e8da7-d2f6-4cf2-96ec-1dc3b67a65d8">
The netkvm's PDB version is right.
<img width="711" alt="截屏2024-08-12 19 59 46" src="https://github.com/user-attachments/assets/36626a8a-158a-44e6-baa6-c800e3bc7b08">
I want to know the reason.
Thanks.

**Comment by ybendito** [comment]
Try disable/enable the network adapter when the traceview is configured and running. Do you see some logs from it?

**Comment by bbbccvbvv** [comment]
> Try disable/enable the network adapter when the traceview is configured and running. Do you see some logs from it?
I can see logs from traceview after  disable/enable the network adapter.
<img width="1033" alt="截屏2024-08-13 19 26 23" src="https://github.com/user-attachments/assets/11e40ea4-d7e0-423b-bec3-9a4b362d2734">
But the log's Event Count  stop at 575.I open new page in edge,it still doesn't incrase.

**Comment by bbbccvbvv** [comment]
> Try disable/enable the network adapter when the traceview is configured and running. Do you see some logs from it?

My fault.I forget to change logging level in driver's configuration. Thanks.
<img width="469" alt="截屏2024-08-13 19 33 23" src="https://github.com/user-attachments/assets/e456c31f-4cce-4b35-8e15-911cc8abd070">

**Comment by heywji** [comment]
I want to inform you that there are no issues with traceview.exe for tracing the session.

![image](https://github.com/user-attachments/assets/3e57118a-0d9b-47e1-8e13-3b0d981a8335)
