### ISSUE TITLE
Whether windows memory balloons can be made insensitive? 

### ISSUE THREAD

**Issue by yangni2017** [virtio-win/kvm-guest-drivers-windows#1146]
**Is your feature request related to a problem? Please describe.**
Hi, I started the windows virtual machine through qemu and set the value of the memory balloon use cmd "virsh setmem". When I see the memory usage in windows, the part occupied by the memory balloon driver has be counted. Is there any way to make the memory usage not count this part of the memory:
![image](https://github.com/user-attachments/assets/52f90405-e46c-4c50-9d84-97ec04a9e7cf)

**Describe the solution you'd like**
I want to implement automatic management, so I don't want the user to know that I'm doing memory balloon operations

**Describe alternatives you've considered**
Is it possible to add options to implement this so that the system does not count the memory of the balloon driver used

**Comment by YanVugenfirer** [comment]
@yangni2017 I don't think it is possible. The whole idea of the Balloon mechanism is to allocate memory from the system during inflation and the guest OS will see this memory as allocated and thus not use it.
