### ISSUE TITLE
NetKvm: 'm_VirtQueue' NULL pointer dereference

### ISSUE THREAD

**Issue by wangyan0507** [virtio-win/kvm-guest-drivers-windows#1197]
**Describe the bug**
Open windows ‘verifier’ for Netkvm, I found a blue screen when starting the windows virtual machine.
The code as follows:
```
ParaNdis_PowerOn
    ->pContext->CXPath.Renew()
        ->CVirtQueue::Renew()
            ->status = virtio_find_queue()
                -> allocate memory failed, return error
            ->if (!NT_SUCCESS(status))
                ->m_VirtQueue = nullptr;  // Now, m_VirtQueue is NULL.
    ->ParaNdis_RestoreDeviceConfigurationAfterReset()
        ->ParaNdis_FinishInitialization()
            ->ParaNdis_ConfigureMSIXVectors()
                ->SetupMessageIndex()
                    ->m_pVirtQueue->SetMSIVector(vector)  // m_pVirtQueue NULL pointer dereference
```

**Comment by YanVugenfirer** [comment]
@wangyan0507 Can you describe the scenario that you are using to get the blue screen?

**Comment by wangyan0507** [comment]
> @wangyan0507 Can you describe the scenario that you are using to get the blue screen?

I use qemu to start a windows virtual machine, open windows Driver Verifier for all drivers, and repeat boot and shutdown windows. 
For Driver Verifier, I choose as follows:
    'Create custom settings (for code developers)'  and then select all form the full list.
I think the 'systematic low resources simulation' option may cause alloc memory failed, and caused this problem.
It caused blue screen when booting the windows vm, the minidump stack is as follows:
![image](https://github.com/user-attachments/assets/8f83dd22-fa7f-427b-951d-8f014c6d8cfb)

We can find the NULL pointer dereference in the NetKvm code. It seems pretty obvious.

**Comment by wangyan0507** [comment]
I have updated the description：
![image](https://github.com/user-attachments/assets/8451dbcc-2559-4c69-8c88-1bbd76977b79)

**Comment by ybendito** [comment]
@wangyan0507 Do you have hibernation enabled? (powercfg /a)

**Comment by heywji** [comment]
Hi @wangyan0507, Did you encounter the BSOD stop code as "KMODE EXCEPTION NOT HANDLED"?
![image](https://github.com/user-attachments/assets/a2c2f799-9247-4a7f-8306-042006ce9c47)

**Comment by wangyan0507** [comment]
> Hi @wangyan0507, Did you encounter the BSOD stop code as "KMODE EXCEPTION NOT HANDLED"? ![image](https://private-user-images.githubusercontent.com/17078378/389278101-a2c2f799-9247-4a7f-8306-042006ce9c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0OTkzMzksIm5iZiI6MTczMjQ5OTAzOSwicGF0aCI6Ii8xNzA3ODM3OC8zODkyNzgxMDEtYTJjMmY3OTktOTI0Ny00YTdmLTgzMDYtMDQyMDA2Y2U5YzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAxNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTViODU1NTEyZDgwNDJlOTJiZDcxZTNjMDk4MTQyZDVlNzExYzBhMGVhYmY3NTQzNzQ3Zjc5MTA0MDYxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yQerJj9nWrZm1IcsRGXKA8bDpx8SJy3i5SFCgnmy4QE)

Yes, it is "SYSTEM_THREAD_EXECPTION_NOT_HANDLED (7e)" in the full dump file.

**Comment by wangyan0507** [comment]
> @wangyan0507 Do you have hibernation enabled? (powercfg /a)

No, just enabled 'Fast Startup' .

**Comment by heywji** [comment]
Open a downstream Jira to track this issue: https://issues.redhat.com/browse/RHEL-68725

**Comment by YanVugenfirer** [comment]
> No, just enabled 'Fast Startup' .

Fast startup uses hibernate

**Comment by wangyan0507** [comment]
> > No, just enabled 'Fast Startup' .
> 
> Fast startup uses hibernate
hibernation can cause this problem?

**Comment by wangyan0507** [comment]
> > No, just enabled 'Fast Startup' .
> 
> Fast startup uses hibernate

hibernation can cause this problem?

**Comment by YanVugenfirer** [comment]
Combination of driver verifier with low resource simulation and hibernation. On hibernation, the driver will reinitialize and re-allocate some of the internal data structures.

**Comment by ybendito** [comment]
@wangyan0507 Driver from https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1206
[NetKVM-Win2019x64.zip](https://github.com/user-attachments/files/17988940/NetKVM-Win2019x64.zip)

**Comment by wangyan0507** [comment]
> @wangyan0507 Driver from #1206 [NetKVM-Win2019x64.zip](https://github.com/user-attachments/files/17988940/NetKVM-Win2019x64.zip) Please close the issue if the problem is solved

I will test it.

**Comment by wangyan0507** [comment]
The problem is solved
