### ISSUE TITLE
Windows Server 2012 R2 does not pick up hard disks.

### ISSUE THREAD

**Issue by CoilDomain** [virtio-win/kvm-guest-drivers-windows#12]
Hello,

I'm an early adopter customer at Microsoft, we have been given access to an early preview build of Server 2012 R2 and I decided to load it up on Ubuntu and KVM. After loading the SCSI driver the disks do not appear. I am using virtio-win-0.1-59.iso on an update Ubuntu 12.04 server. Please let me know if you need anything else from me.

**Comment by vrozenfe** [comment]
This issue has been resolved quite a long time ago. Nowadays we build and successfully HCK  not only Win8.1/WS2012R2 but also WIn10/WS2016.

Closing this issue.
Vadim.
