### ISSUE TITLE
virtio-net not recognized anymore

### ISSUE THREAD

**Issue by mr-manuel** [virtio-win/kvm-guest-drivers-windows#1203]
**Describe the bug**
After updating the virtio-win to `0.1.262-1` or higher drivers on my Windows 11 VM, the Ethernet-Controllers are not recognized anymore. If I uninstall them and reinstall `0.1.248-1` it works again. No special settings, everythis is on default.

**To Reproduce**
Install the latest virtio-win version on a Windows 11 VM with a VirtIO network card.

![grafik](https://github.com/user-attachments/assets/4dc5a3d2-f8ae-4510-b4e9-d4241e9f4800)

**Expected behavior**
The network card should be recognized.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/9b45e3de-60a2-4c5d-ab13-fa707d6a7707)

**Host:**
 - Disto: `Proxmox VE 8.3.0`
 - Kernel version: `6.8.12-2-pve`
 - QEMU version: `QEMU emulator version 9.0.2 (pve-qemu-kvm_9.0.2-4)`
 - QEMU command line: `/usr/bin/kvm -id 103 -name manuel-vpc.domain.local,debug-threads=on -no-shutdown -chardev socket,id=qmp,path=/var/run/qemu-server/103.qmp,server=on,wait=off -mon chardev=qmp,mode=control -chardev socket,id=qmp-event,path=/var/run/qmeventd.sock,reconnect=5 -mon chardev=qmp-event,mode=control -pidfile /var/run/qemu-server/103.pid -daemonize -smbios type=1,uuid=564d16e8-e9df-33bf-7640-5f5b00f3eb89 -drive if=pflash,unit=0,format=raw,readonly=on,file=/usr/share/pve-edk2-firmware//OVMF_CODE.fd -drive if=pflash,unit=1,id=drive-efidisk0,format=raw,file=/dev/zvol/rpool/data/vm-103-disk-0,size=131072 -smp 4,sockets=1,cores=4,maxcpus=4 -nodefaults -boot menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg -vnc unix:/var/run/qemu-server/103.vnc,password=on -cpu host,hv_ipi,hv_relaxed,hv_reset,hv_runtime,hv_spinlocks=0x1fff,hv_stimer,hv_synic,hv_time,hv_vapic,hv_vpindex,+kvm_pv_eoi,+kvm_pv_unhalt -m 8192 -object iothread,id=iothread-virtio0 -object iothread,id=iothread-virtio1 -device pci-bridge,id=pci.1,chassis_nr=1,bus=pci.0,addr=0x1e -device pci-bridge,id=pci.2,chassis_nr=2,bus=pci.0,addr=0x1f -device pci-bridge,id=pci.3,chassis_nr=3,bus=pci.0,addr=0x5 -device vmgenid,guid=7934bf48-00fb-4d83-9554-4995c88d4347 -device piix3-usb-uhci,id=uhci,bus=pci.0,addr=0x1.0x2 -device qxl-vga,id=vga,bus=pci.0,addr=0x2 -chardev socket,path=/var/run/qemu-server/103.qga,server=on,wait=off,id=qga0 -device virtio-serial,id=qga0,bus=pci.0,addr=0x8 -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 -device virtio-serial,id=spice,bus=pci.0,addr=0x9 -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -spice tls-port=61001,addr=127.0.0.1,tls-ciphers=HIGH,seamless-migration=on -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3,free-page-reporting=on -iscsi initiator-name=iqn.1993-08.org.debian:01:4adad7243ea1 -drive file=/dev/zvol/rpool/data/vm-103-disk-1,if=none,id=drive-virtio0,discard=on,format=raw,cache=none,aio=io_uring,detect-zeroes=unmap -device virtio-blk-pci,drive=drive-virtio0,id=virtio0,bus=pci.0,addr=0xa,iothread=iothread-virtio0,bootindex=100 -drive file=/dev/zvol/rpool/data/vm-103-disk-2,if=none,id=drive-virtio1,discard=on,format=raw,cache=none,aio=io_uring,detect-zeroes=unmap -device virtio-blk-pci,drive=drive-virtio1,id=virtio1,bus=pci.0,addr=0xb,iothread=iothread-virtio1 -device ahci,id=ahci0,multifunction=on,bus=pci.0,addr=0x7 -drive file=/var/lib/vz/template/iso/virtio-win-0.1.248.iso,if=none,id=drive-sata0,media=cdrom,aio=io_uring -device ide-cd,bus=ahci0.0,drive=drive-sata0,id=sata0,bootindex=101 -netdev type=tap,id=net0,ifname=tap103i0,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown,vhost=on -device virtio-net-pci,mac=00:0c:29:00:00:00,netdev=net0,bus=pci.0,addr=0x12,id=net0,rx_queue_size=1024,tx_queue_size=256 -netdev type=tap,id=net1,ifname=tap103i1,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown,vhost=on -device virtio-net-pci,mac=00:0c:29:00:00:00,netdev=net1,bus=pci.0,addr=0x13,id=net1,rx_queue_size=1024,tx_queue_size=256 -rtc driftfix=slew,base=localtime -machine hpet=off,type=pc-i440fx-9.0+pve0 -global kvm-pit.lost_tick_policy=discard`
 - libvirt version: not found?
 - libvirt XML file: not found?

**VM:**
 - Windows version: `22H2 (Build 22621.4460)`
 - Which driver has a problem: Network card is not recognized
 - Driver version or commit hash that was used to build the driver: Tried with `0.1.262-1`, `0.1.262-2` and `0.1.266-1`

**Additional context**
Strange that it seems that I'm the only one with this problem.

**Comment by mr-manuel** [comment]
Possibly related, but in my case it workes with an older VirtIO driver version.

* https://github.com/virtio-win/kvm-guest-drivers-windows/issues/750
* https://github.com/virtio-win/kvm-guest-drivers-windows/issues/745
* https://github.com/virtio-win/kvm-guest-drivers-windows/issues/998

The Windows installation is German, but it worked before. So this probably is a regression.

**Comment by vrozenfe** [comment]
@mr-manuel 
Did you try to install/update the netkvm driver manually from the Device Manager Dialog or only with virtio-win msi installer/bundle ?
Thanks,
Vadim.

**Comment by mr-manuel** [comment]
First I installed it via the MSI, the I tried via the device manager, but it does not recognize the driver.

**Comment by YanVugenfirer** [comment]
<img width="776" alt="Screenshot 2024-12-01 at 1 40 15 PM" src="https://github.com/user-attachments/assets/e5ac2345-20f3-4c89-a371-8582b3e7dd66">

Please check what is the PNP ID of the virtio-net device. 
Also please provide setupapi logs located in the C:\windows\INF directory.

Thanks,
Yan

**Comment by mr-manuel** [comment]
Hardware ID when it's working:

![grafik](https://github.com/user-attachments/assets/52a2cc67-5680-4623-8ecf-4d57373b22b7)

Hardware ID when it's not working:

![grafik](https://github.com/user-attachments/assets/c170f595-abde-4374-aa9a-0adcea2a5d2f)


Here the log: [setupapi.dev.log](https://github.com/user-attachments/files/18007573/setupapi.dev.log)

**Comment by heywji** [comment]
QE tries to reproduce this issue, but the main variables (kernel and QEMU-KVM versions) differ from the reported setup. 
 * kernel-5.14.0-518.el9.x86_64
 * edk2-ovmf-20240524-7.el9.noarch
 * qemu-kvm-core-9.1.0-1.el9.x86_64

Specifically:
 * Kernel: The latest version available in our repository is 6.8.0-1, which does not match the reported 6.8.12-2-pve.
 * QEMU-KVM: The latest version in our repository is qemu-kvm-core-9.1.0, with qemu-kvm-core-9.0.0 being slightly lower, but still different from the reported pve-qemu-kvm_9.0.2-4.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/69c29454-b6cd-421f-83df-2263d2d89816" />


Despite these differences, I have not encountered problems upgrading the netkvm driver from 0.1.248  to 0.1.262.

**Comment by mr-manuel** [comment]
Only for curiosity. Could you try with a german Windows installation? I can provide you one, if you can't find one. I will try today with a english installation, to see if it works there. It makes no sense, but I read in a issue somewhere that strange behavior.

**Comment by heywji** [comment]
@mr-manuel Hello, sure, you can give me a German Windows installation. We can do more tries to find the root cause.

**Comment by mr-manuel** [comment]
I send a link to your Red Hat e-Mail in your profile.

**Comment by JonKohler** [comment]
@mr-manuel 
This is likely tangential to this issue: 
Issue #750
https://forum.proxmox.com/threads/no-network-adapter-in-fresh-windows-server-after-upgrade-to-proxmox-7.92094/page-7
https://gitlab.com/qemu-project/qemu/-/issues/774

_**Supposedly**_ there was changes to german windows in the Nov 2024 windows update to address the behavior noted from the issue above, perhaps we're running afoul in another way?

Assuming this is related to the original issue: 
@heywji - can you ping Igor Mammedov internally? He should be in the loop on this, as we've got him connected with our team, as well as connected with Microsoft on this issue

**Comment by mr-manuel** [comment]
I made a few more tests. The weird outcome is, that the driver installed correctly after uninstalling NordVPN. I tried to remove the VirtIO drivers again, install NordVPN and check, if it fails again, but I was not able to reproduce it again.

If someone has the same problem, try to uninstall all VPN clients or other virtual network adapters.

**Comment by powellnorma** [comment]
I had a similar problem with "Cisco Secure Client - AnyConnect VPN". 
Fixed it by clicking "Update driver" in the device manager for the unknown device (after uninstalling the VPN Software, not 100% sure if that step is necessary though).
On another machine without any VPN Software installed, it worked fine immediately. I migrated the VMs from VirtualBox.
