### ISSUE TITLE
All drivers not working Windows 10 & 11 

### ISSUE THREAD

**Issue by adoma25** [virtio-win/kvm-guest-drivers-windows#1205]
**Describe the bug**
Cant seem to install any driver. It started with the VirtIO disk, during windows installation I couldn't load the drivers. Every virtio driver version i tried wouldn't load, if I uncheck the "Hide drivers that are not compatible.." I see some drivers but they won't install i tried all of them. So I installed windows on a Sata disk and add another VirtIO disk and wanted to install the driver from inside windows. The Setup finish's with no errors but in device manager it seems that drivers are not installed. I try to install them from there but with no luck and i tried all versions of windows in the Virtio iso. Just now i tried installing by going to Action>Add Drivers> Select just the iso driver and it starts giving me something and some errors as in the screenshot still with no luck tho. 

I only still didnt try Windows 10 21h2 its downloading but for every other Windows version of 10 & 11 it's the same thing. Can someone show me what i'm doing wrong ? 
Also i tried a VM with UEFI and a VM with BIOS same thing
I tried the windows versions in the screenshot and every Virtio driver available.

My host is a razer laptop blade pro 17 2019 RTX 2070, 64GB DDR4, i7 9th gen, NVMe m2

**To Reproduce**
Steps to reproduce the behaviour:
Install Ubuntu 
Sudo apt update
Sudo Install qemu usin : sudo apt install qemu-kvm bridge-utils virt-manager libosinfo-bin -y
Create VM with Windows ISO VirtIO drivers ISO VirtIO disk and VirtIO NIC (I tried both)

**Expected behavior**
Can't load disk drivers

**Screenshots**
![vm2](https://github.com/user-attachments/assets/4169a10d-e092-43fc-b830-52272bc35c89)
![vm4](https://github.com/user-attachments/assets/f3b0b202-ec6e-4fa3-9390-7908c0b25884)
![vm5](https://github.com/user-attachments/assets/314f8667-9807-403c-b707-7042b13b0e8d)

![vm3](https://github.com/user-attachments/assets/15d783f8-1155-452f-b486-301f7d262e38)

![vm1](https://github.com/user-attachments/assets/fb1c4f03-423a-45d4-8503-31f8c341a257)
![when Installing xxx 17](https://github.com/user-attachments/assets/f05ed0ed-eb0e-4674-b0af-28efeb38bfde)

**Host:**
 - Disto: Ubuntu
 - Kernel version
 - QEMU version 
 - QEMU command line 
 - libvirt version
 - libvirt XML file

VM XML:

[vmconfig.txt](https://github.com/user-attachments/files/17963011/vmconfig.txt)

**VM:**
 - Windows version 10 & 11
 - Which driver has a problem 0.1.262 0.1.217 0.1.215 .. I tried all available

**Comment by adoma25** [comment]
**Qemu version: 8.2.2**

**Fix:**
Built new `qemu version 9.2.0` and specified it in the vm's xml

I guess it's not compatible with qemu 8.2.2 or something went wrong there but the issue is fixed now. As soon as I booted the VM everything was recognized and even during windows installation it recognizes the drivers and the Virtio disk

**Comment by YanVugenfirer** [comment]
I am wondering what are the device IDs for the virtio devices in a built in QEMU in Ubuntu.
