### ISSUE TITLE
VirtIO Ethernet Adapter becomes slow after some time

### ISSUE THREAD

**Issue by DanielRRowe** [virtio-win/kvm-guest-drivers-windows#14]
I have a number of VMs running on a couple of Dell servers (lots of RAM 8 cores etc). Running a mixture of Windows and Linux VMs. The hosts are running Fedora 19 simple setup using libvirt.

The Windows guest which is currently a mix of Windows 7 Enterprise 64bit and Windows Server 2008R2 all seem to suffer from an issue where after a while (about a week or so) the networking become very slow, I think it is dependant on how much traffic has been passed. Rebooting the guest fixes the issue for a while. I have not been able to nail down the issue. After the start it all runs fine and nice and fast. When I say slow it is just about unusable, RDPing into the guests (how the users use access the machines) 

When we had XP guests they did not suffer from this issue nor do any of the Linux guests.

The drivers before 0.1-52 seems to be not less effected by this.

All guests use bridge networking. We are using the latest drivers from either http://alt.fedoraproject.org/pub/alt/virtio-win/stable/ or http://www.spice-space.org/download.html.

I probably have not provided a enough information here so please let me know what I can provide.

**Comment by sameehj** [comment]
Hi @DanielRRowe,

We are currently in a process of closing all github's issues that have been resolved or expired. I'm currently closing this issue, please reopen the issue or else open a new issue if needed. This issue was opened in 2014, Since then NetKVM have gone through many changes, go ahead and give it test :)
