### ISSUE TITLE
Warning Message for viostor drivers from windows

### ISSUE THREAD

**Issue by Parth6288** [virtio-win/kvm-guest-drivers-windows#144]
Hi Team,

We are running Windows machin on KVM hypervisor and found few machines are getting unresponsive -but do not fail - and the only way to get them running is to restart the VM. I checked windows logs and found a lot of Viostor Warning message as below.

> Reset to device, \Device\RaidPort0, was issued Reset to device, \Device\RaidPort01, was issued

Can this cause the VM getting unresponsive. Below is the screenshot for the virtio drivers details.

![viostor](https://cloud.githubusercontent.com/assets/16204776/26572499/ce5e3902-4537-11e7-8249-a8765340a7e9.JPG)

**Comment by vrozenfe** [comment]
You probably use NFS storage, right? If so, we can expect device/bus resets if TimeOutValue has been exceeded. Try to figure out the reason why the storage back-end failed to completer request even after 30 sec time out.

btw, build 94 is a pretty old one, you should update viostor driver with a more recent one.

Best,
Vadim.

**Comment by vrozenfe** [comment]
Closing this issue based on my previous comment. We can improve LUN/bus reset logic in one of the next releases. But in any case it will not help to solve a slow NFS or SAN network connection problems.

Vadim.
