### ISSUE TITLE
Current HLK failures on vioscsi

### ISSUE THREAD

**Issue by ben-skyportsystems** [virtio-win/kvm-guest-drivers-windows#152]
I'm trying to pass the HLK test suite for Windows 10/Server 2016 and have a few failures that seem to be code-related, rather than setup.

- Storage Query Property (both Win10 and 2k16): Error is "0 is an invalid value for SerialNumberOffset".  This test doesn't have any parameters.
- Static Tools Logo Test (2k16): This requires running of the Static Driver Verifier in Visual Studio, but it fails the "MustFix Defect" rules in **storportfindadapter** and **storportspinlock3**.  If I go ahead and install the DVL files on my HLK test machine, the STL test fails, mentioning the "MustFix" failures.
- Storage Firmware Update: I imagine this can be made to pass.  What do you put as a firmware file for this test?

In addition, the CHAOS tests fail on both targets for "Reliability" and "Development and Integration", but when I look in the test logs, there are no failures.  I expect this is an HLK problem, not a code problem, so will ask MSFT for clarity.

Note that I'm testing code very close to top-of-tree (commit 7b4c78b), and am compiling on VS15.  I've used your scripts for partitioning the hard disks (Thanks!)

If you know how to get around the above-mentioned failures, I'd love to hear it.  If not, I'll try to fix them in code, but will take some time to familiarize myself to the code base.

**Comment by vrozenfe** [comment]
For SerialNumberOffset test did you specify serial number (name) in the command line?

**Comment by ben-skyportsystems** [comment]
Command line of what?  Compile-time or test-time?

**Comment by vrozenfe** [comment]
test-time. should be something like this
"-device ...,serial=xxxxxxxxxxx,..." (up to 12 symbols iirc)

**Comment by ben-skyportsystems** [comment]
Thanks Vadim.  Sorry, but I'm a little dense.  This is the command line when instantiating the device (through pnputil maybe?) or some kind of HLK command line?  I'm running HLK from the GUI, and don't see any options on this particular test for command line or test parameters.

**Comment by YanVugenfirer** [comment]
Hi Ben,

This is part of the QEMU command line. You need to specify serial number to disk device.

Best regards,
Yan.

**Comment by ben-skyportsystems** [comment]
Hi Yan,

OK, that makes sense.  Thanks a lot.

--Ben

**Comment by ben-skyportsystems** [comment]
Thanks again for your help on this guys.  Do you have any thoughts on the other failures?  I assume for the firmware that you either tag the device somehow as not being firmware-upgradeable or have a dummy file?  For the static analysis failure, have you seen this?  Is it a setup problem on my side, or do we need to do some development work to fix this up?

**Comment by vrozenfe** [comment]
I will ask our QE engineers to take a look at that. To the best of my knowledge both recent storage drivers (viostor and vioscsi) successfully passed HLK testing and MS WHQL submission.

**Comment by ben-skyportsystems** [comment]
Hi Vadim,
I'm down to one test left - 'Storage Firmware Update':
http://msdn.microsoft.com/en-us/library/windows/hardware/bba16fe1-2164-4a15-8b6a-75a967c5e6c3 

There's only one parameter to supply: FirmwareImageFile, which is the path to a firmware file on the test machine.  I've tried leaving this blank, and providing a dummy file, but the test fails
```
Start Test 8/7/2017 11:29:34.821 PM Download firmware to device using IOCTL_STORAGE_FIRMWARE_DOWNLOAD. 
Error 8/7/2017 11:29:34.829 PM DeviceStorageFirmwareUpgrade - firmware download IOCTL failed. Error code: 1 
```
I don't see any handling of this ioctl in the driver, nor do I see any configuration for stating that this driver doesn't have upgradeable firmware. 

Any ideas?

thanks,
Ben

**Comment by vrozenfe** [comment]
Hi Ben,

That's strange. In my understanding, we shouldn't be there with IOCTL_STORAGE_FIRMWARE_DOWNLOAD request. Give me some 
time to figure out what is wrong here.

Best regards,
Vadim.

**Comment by lijinlijin** [comment]
Hi Ben,
QE pass all the certification submissions.
When we ran vioscsi/viostor whql job for win10/2016,we didn't run job "Storage Firmware Update".
Did you load the playlist when you submit jobs in HLK?I guess this job is removed after playlist loaded.
The playlist we used is https://sysdev.microsoft.com/en-US/Hardware/compatibilityplaylists/

For "Storage Query Property" and "Static Tools Logo Test",this two jobs passed easily during our test.

Anything else,please let me know.

**Comment by ben-skyportsystems** [comment]
Hi,

Yes, I re-downloaded this playlist and it's the same, see here:

<img width="1399" alt="screen shot 2017-08-10 at 6 29 28 am" src="https://user-images.githubusercontent.com/8432404/29172653-729f29be-7d95-11e7-9db2-02be4109ebb3.png">

Pay no attention to the failing "Storage Query Property" tests, I just haven't had time yet to change the QEMU command line for drive serial number but will hopefully get to that today.

As for the "Static Tools Logo Test", I was able to get it to pass after changing the "Rules Set" in SDV to "VirtualStorport".  If set to "All", there's one spinlock test that can only pass by essentially removing all multi-queue capabilities, and that seems like a really stupid and intrusive thing to do in order to pass a test.

Thanks again for all the help!
--Ben

**Comment by lijinlijin** [comment]
Hi Ben,
Your playlist is for 1703,I think you should use "HLK Version 1607 CompatPlaylist".
Because your HLK and win10/2016 is 1607 version,1703 is for latest windows 10 version.

**Comment by vrozenfe** [comment]
Hi Li Jin,
Do we have any plans for running 1703 in the nearest future?
Thanks,
Vadim.

**Comment by lijinlijin** [comment]
Hi Vadim,
We did use 1703 for windows 10 during rhel7.4 release.
For win2016,HLK 1607 is required;
For win10,we used latest 15063 build,so HLK 1703 is required.

Ben's win10 is still 14393 build,so he also need to load 1607 playlist,same with win2016.

https://blogs.msdn.microsoft.com/windows_hardware_certification/2017/04/05/submissions-using-windows-10-version-1703-are-now-being-accepted/

**Comment by vrozenfe** [comment]
Hi Li Jin
Thank you for the clarification.
Vadim.

**Comment by ben-skyportsystems** [comment]
Thanks a lot for the clarification!  This is pretty confusing and annoying stuff!  It looks like the firmware update test only applies to Windows 2k16, so all the Win10 tests passed using the 1703 HLK.  I'll stash these results, install the 1607 HLK and re-run on the 2k16 images only.  Too bad the 1703 HLK can't load 1607 playlists or I'd be done :(

**Comment by ben-skyportsystems** [comment]
Update: Once running the correct version of HLK and playlist, I was able to get all HLK tests to pass for vioserial, vioscsi and balloon.  I'm still working on the NetKVM driver, but setup is a bit trickier there.  Thanks a lot for the help.

Separately, how do you know which tests are necessary in HCK to get WHLK certification?  I filter on 'Certification', but some of the SCSI tests fail (all of the LUN reset and bus reset tests), but the test description for them says "these optional tests...."  In your experience, are they truly optional?

**Comment by lijinlijin** [comment]
use latest msft playlist,hlk will load the needed tests automatically.

"The Windows Hardware Compatibility Program uses an official playlist to determine which devices meet the requirements for compatibility with Windows 10."
https://msdn.microsoft.com/en-us/library/windows/hardware/dn914993%28v=vs.85%29.aspx

**Comment by ben-skyportsystems** [comment]
Hi Li Jin,

Thanks for responding.  I probably didn't phrase my question well enough.  I'm working with the HCK, which is used for Win7/Server2k8 and Win8/Server2k12, not HLK.  HCK doesn't have playlists, only categories, and my confusion is that some of the tests under the 'Certification' category are described as "optional".  I'm asking if, in your experience, these tests need to pass or if thy really are optional.

thanks,
Ben

**Comment by lijinlijin** [comment]
Sorry for misunderstanding.
For HCK,all the loaded tests must pass if you want get the certification.So bus rest and lun reset tests are actually not optional.

**Comment by ben-skyportsystems** [comment]
Closing this issue.  I was able to get all HLK tests to pass.
