### ISSUE TITLE
netkvm:  windows 2012 server get bsod.

### ISSUE THREAD

**Issue by jackli577** [virtio-win/kvm-guest-drivers-windows#168]
recently i met a  bsod in netkvm, condition is only one  nPathbundles( is only one back end hardware queue).

this situation,  all cpu will to process m_virtqueue data throught ProcessRxRing funtion. this result one cpu
acquire spinlock in this function,  the other cpu will wait to get,  dpc timeout, so dpc watch dog, bosd.

in my understand, i thought, msi 0/1 to cpu 0 ,  cpu 0  queue dpc to cpu 0,   on cpu 0 dpc,  rss insert to all cpu queue,  then queue dpc to other cpu,  the other cpu only to indicate packet.

so  we need to change code in ParaNdis_DPCWorkBody.  source is:
if (pContext->nPathBundles == 1)
    {
        pathBundle = pContext->pPathBundles;
    }
    else
    {
        ULONG procIndex = ParaNdis_GetCurrentCPUIndex();
        if (procIndex < pContext->nPathBundles)
        {
            pathBundle = pContext->pPathBundles + procIndex;
        }
    }

change to:
  ULONG procIndex = ParaNdis_GetCurrentCPUIndex();
        if (procIndex < pContext->nPathBundles)
        {
            pathBundle = pContext->pPathBundles + procIndex;
        }

only the netkvm msi coorespond to cpu to process virtqueue data. in default, the msi is bound to cpu begin for 0.

saw svn log, this code is add in 2014. i alse try to make lots of tests for reproduction, no reproduction again. 

anyone have  some advances?  thanks.

**Comment by sameehj** [comment]
Hi @jackli577,

Thanks for reporting this and sorry for the very late reply. We are aware of this issue, I guess that you didn't specify Hyper-v enlightenment parameters in your command line which triggered the DPC timeout. You should use hv_relaxed with "-cpu" as this disables the watchdog for DPCs timeouts. Moreover I'd advise you to enable all Hyper-v enlightenment settings
as follows:

"-cpu ...,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time"

Please update me in case does or doesn't resolve the issue

**Comment by jackli577** [comment]
thanks，  this will fix the problem, thanks very much.  in the begin, i thought nPathBundles == 1 whether need to special do with. now get the answer.
