### ISSUE TITLE
Disk conflicts

### ISSUE THREAD

**Issue by sundarchi1** [virtio-win/kvm-guest-drivers-windows#171]
I have a standard Windows Server 2016 boot disk and also a block storage disk. Restarting the server, I get these events logged. seems like an issue with the drivers, and the info in that KB was not useful. Reformatting the disks and such aren't helping.

![diskerr1](https://user-images.githubusercontent.com/31782486/31241670-a38e19cc-a9d2-11e7-939a-5d19ac95bada.PNG)
![diskerr2](https://user-images.githubusercontent.com/31782486/31241671-a38e2ba6-a9d2-11e7-91a7-f1dcdced422c.PNG)

**Comment by vrozenfe** [comment]
Hi sundarchi1,
Did you specify a unique serial name for each drive?
If you can, please post the qemu command line.

Thanks,
Vadim.

**Comment by sundarchi1** [comment]
This is from a 100% clean install. Shouldn't all serials be generated and be unique the first time?

**Comment by vrozenfe** [comment]
not sure about libvirt, but if you create qemu command line by yourself, the serial number needs to be explicitly specified like this "-drive file=.........,serial=XXXXXXXXXXXX,..."

**Comment by vrozenfe** [comment]
Hi sundarchi1,

Any update on this case? 
Did "serial" help to solve your problem?
If it did, let's close the issue.

Thanks,
Vadim

**Comment by sundarchi1** [comment]
I do not really know what qemu command line is. I just install my ISO through a custom VPS provider and they tell me to also add these drivers, and these errors show up.

**Comment by vrozenfe** [comment]
can you please do the following things:
- start command prompt as administrator and run diskpart,
- type "list disk" to see all the disk attached (you should see at least two),
- then go to the first one "select disk 0" and ask for details "detail disk",
- repeat the above step for all other disks in your system,
- post the results to this thread.

Apart from that, you can try converting your data disk into GPT (if it is not GPT yet),
and see if it solved the problem. But don't forget to backup your data on that disk first.

**Comment by sundarchi1** [comment]
Two disk results:

![0](https://user-images.githubusercontent.com/31782486/34910643-b2cd4bca-f887-11e7-9510-2453403a3e7f.PNG)
![1](https://user-images.githubusercontent.com/31782486/34910644-b2dad7a4-f887-11e7-9cb7-10bba6780e4f.PNG)

**Comment by sundarchi1** [comment]
@vrozenfe ^^^

**Comment by vrozenfe** [comment]
Hi sundarchi1.

Sorry for delay in reply. I just overlooked your previous message somehow.
We have at least two bugs, reported recently,  that might be related to this issue
https://bugzilla.redhat.com/show_bug.cgi?id=1538546
https://bugzilla.redhat.com/show_bug.cgi?id=1538559
I'm going to start working on them asap. Hopefully, at the moment that we are able to 
understand the reason why the disk subsystem raises Event Id 158, we will be able to fix it.

Best,
Vadim.

**Comment by EatonZ** [comment]
I see the same issue on a fresh Server 2016 install on a VPS. Definitely seems like a bug somewhere.

**Comment by vrozenfe** [comment]
Hi EatonZ

Could you post the qemu command line, as well as qemu and kernel versions?

Thanks,
Vadim.

**Comment by EatonZ** [comment]
@vrozenfe I'm not quite sure how to get the command line. I don't use qemu - it's just what my VPS provider uses on their KVM VPS servers.

However, I do see this when the OS boots: (ignore CD error)
![seabios](https://user-images.githubusercontent.com/3020941/35605704-7fda7942-0618-11e8-9580-1fc5f309daf7.png)

**Comment by vrozenfe** [comment]
Do you know the type of storage devices on that VM (viostor/vioscsi), number of disks attached to VM, and type of storage backend (direct LUN, file, iSCSI target, etc.,) ?

Thanks,
Vadim.

**Comment by EatonZ** [comment]
There are 2 disks (1 internal SSD, and 1 attached block storage device).

Both of them show in Device Manager as "Red Hat VirtIO SCSI Disk Device".

**Comment by vrozenfe** [comment]
What is the viostor.sys driver version?
Will it be possible to run diskpart /"select disk x" /"detail disk" and check that both disks have different 
disk ids?
Thanks,
Vadim.

**Comment by EatonZ** [comment]
I am using the August 4th release (0.1.141-1)

Interestingly, they appear to have different IDs, yet the event log still complains - "Disk 1 has the same disk identifiers as one or more disks connected to the system."

There's only 2 disks and here they are in detail:

![disks](https://user-images.githubusercontent.com/3020941/36112076-6bc77f44-0ff6-11e8-8e80-74e693269731.png)

**Comment by vrozenfe** [comment]
Thanks, 

Do you run Windows Server 2016 as well? Which build?

Best,
Vadim.

**Comment by EatonZ** [comment]
Yes - Server 2016 Standard build 14393.2035 (the latest at the time of writing).

**Comment by EatonZ** [comment]
@vrozenfe When can we expect the next set of driver updates? August 4th was a long time ago.
Will the next set have any type of fix for this?

**Comment by vrozenfe** [comment]
sundarchi1 & EatonZ,
First of all thank you for reporting the problem. It can be reproduced on Win10 as well. Not a hundred percent sure yet, but we might have some IOCTL_STORAGE_* support missing. Will try to fix it asap.

Regarding to the latest virtio-win build - the most recent one was maid on Dec 4 2017 (build 145). 
I will try to contact fedora people and ask them to update the binaries on fedoraprogect site. 
We don't have an exact schedule for a new build, I think me can be ready to do it a couple of weeks.

Vadim.

**Comment by EatonZ** [comment]
@vrozenfe Thanks, didn't know there was an updated version. The "Releases" tab seems to list old versions here. Is there another place to download the binaries?

Let me know when you have a potential fix and I'll be glad to try it.

**Comment by vrozenfe** [comment]
I opened a new bug https://bugzilla.redhat.com/show_bug.cgi?id=1549455 for tracking this issue.
Patches on the way.
Vadim.

**Comment by sundarchi1** [comment]
@vrozenfe Thank you for a fix.
When will ISO downloads on Fedora site see updates?

Will test/close issue when fix confirmed.

**Comment by vrozenfe** [comment]
Hopefully by mid of next week. (We need to prepare and run a new official build first.) 

Best,
Vadim.

**Comment by vrozenfe** [comment]
The latest Win10 viostor  drivers are available at http://people.redhat.com/vrozenfe/viostor.zip
According to https://bugzilla.redhat.com/show_bug.cgi?id=1549455#c14 the problem 
seems to be fixed now.

Vadim.

**Comment by sundarchi1** [comment]
@vrozenfe Thank you.
Where should we check for future updates?
Still no updates here in a while: https://fedorapeople.org/groups/virt/virtio-win/

If that site is dead, please post new site.

**Comment by vrozenfe** [comment]
Unfortunately, the most recent build, that we wanted to make public, has some problems "Bug 1551918 - Lack of viorng* files in virtio-win-prewhql-0.1-148" (https://bugzilla.redhat.com/show_bug.cgi?id=1551918). We will try to run a new build and make it public through fedorapeople.org as soon as this problem is solved,

**Comment by vrozenfe** [comment]
We finally have it here https://fedorapeople.org/groups/virt/virtio-win/repo/latest/virtio-win-0.1.149-1.noarch.rpm

**Comment by sundarchi1** [comment]
Confirmed fixed - thanks!

@vrozenfe Please keep the Fedora People site up to date with latest driver downloads if you can.

**Comment by vrozenfe** [comment]
We will do our best. But it is not always up to us.

And thank you for your feedback. 

Cheers,
Vadim..
