### ISSUE TITLE
Support building with Visual Studio 2017

### ISSUE THREAD

**Issue by ladipro** [virtio-win/kvm-guest-drivers-windows#181]
WDK for Windows 10, version 1709 now officially supports Visual Studio 2017:
https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit

We should make it possible to build virtio-win with VS 2017, ideally without breaking VS 2015.

Note that VS 2017 no longer writes its installation directory to the registry where our build script (currently Tools\checkWin8Tools.bat) looks for it. See:
https://blogs.msdn.microsoft.com/heaths/2016/09/15/changes-to-visual-studio-15-setup/

**Comment by YanVugenfirer** [comment]
Could be a good idea to add support for the Enterprise WDK as well.

**Comment by vrozenfe** [comment]
Especially after Microsoft finally updated EWDK to support SDV.

**Comment by oscarbg** [comment]
+1! any update?

**Comment by YanVugenfirer** [comment]
Working on it.

**Comment by morphinz** [comment]
@YanVugenfirer any update?

**Comment by YanVugenfirer** [comment]
I just pushed configuration cleanups to current projects as a step before moving to VS2017. Probably next week I will have a branch with VS2017 support.

**Comment by brucechang** [comment]
Any update on this? Thanks!

**Comment by oscarbg** [comment]
+1

**Comment by YanVugenfirer** [comment]
Not done yet...

**Comment by YanVugenfirer** [comment]
We are going to move soon upstream build to Visual Studio 2017. The main motivation is ARM64.

Here is the branch you can check now:
https://github.com/virtio-win/kvm-guest-drivers-windows/tree/arm64

What is needed on the build machine:
https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers#coming-soon-building-virtio-win-drivers-including-arm64-using-visual-studio-2017

**Comment by YanVugenfirer** [comment]
Yes.
We are finishing some build and deployment infrastructure changes and then it is going to be merged.

Best regards,
Yan.

**Comment by mcarabas** [comment]
Dear Yan,

Can you express a timeframe when this will be merge to upstream? (in 
terms of weeks)

Thank you,
Mihai

**Comment by YanVugenfirer** [comment]
Hello Mihai,

Now as everyone is back from new year vacation, my expectation is 3 weeks.

Best regards,
Yan.

**Comment by mcarabas** [comment]
Hello Yan,

On 09.01.2019 19:29, Yan Vugenfirer wrote:
> Hello Mihai,
> 
> Now as everyone is back from new year vacation, my expectation is 3 weeks.

Any news on the merge?

Thank you,
Mihai

> 
> Best regards,
> Yan.
> 
>

**Comment by YanVugenfirer** [comment]
Hi,

arm64 branch was rebased to master as reparation for the merge.

For all the practical purposes you can already use arm64 branch.

Best regards,
Yan.
