### ISSUE TITLE
driver bluescreens in R2 VM

### ISSUE THREAD

**Issue by jrgruher** [virtio-win/kvm-guest-drivers-windows#2]
We are running an Ubuntu-based Linux cluster using qemu/KVM to create a virtualized environment.  Guest OS is Win2k8 R2 SP1 x64.  Our system has dual redundant storage controllers and the Linux hypervisors are configured for multipathed IO.  When we run failover testing on the storage controllers the HV appears to be fine but we are getting occasional bluescreens from the VirtIO storage driver in the guest.

DRIVER_IRQL_NOT_LESS_OR_EQUAL
STOP: 0xD1 (0x168, 0x2, 0x0, 0xXFFFFF88000FDA1D2)
viostor.sys

Driver version is 61.63.103.2200 pulled from http://alt.fedoraproject.org/pub/alt/virtio-win/latest/images/bin/.

Is there any driver update which might address this issue, or is anyone interested in trying to debug the problem?  We can reproduce the issue as needed and provide memory dumps and other debug information.

Thanks!

**Comment by YanVugenfirer** [comment]
This issue was moved to virtio-win/virtio-win#2
