### ISSUE TITLE
NetKVM assumes synchronous processing of control queue, drops buffers

### ISSUE THREAD

**Issue by ladipro** [virtio-win/kvm-guest-drivers-windows#206]
The way NetKVM handles the control queue appears to be broken.

This assumption in CParaNdisCX::SendControlMessage does not hold:

```
            /* Control messages are processed synchronously in QEMU, so upon kick_buf return, the response message
              has been already inserted in the queue */
```

QEMU processes the queue asynchronously with respect to the vCPU thread.

This can be reproduced by running the debug build of NetKVM and watching the logs produced on startup. I get a flood of:

`CParaNdisCX::SendControlMessage - ERROR: add_buf failed
`

as the driver executes SetAllVlanFilters and manages to push only the first few control messages. Then the virtqueue fills up and the driver never pops anything from it because the only 
CVirtQueue:GetBuf is in CParaNdisCX::SendControlMessage and runs only if a buffer was successfully pushed. So the queue stays full forever.

@sameehj , @YanVugenfirer , can you guys take a look? For what it's worth, virtio serial uses a somewhat similar setup and has a simple poll loop to wait for buffers to be returned by the host. See VIOSerialSendCtrlMsg.

Not sure why this hasn't come up before. I see this with upstream QEMU and the simplest command line:

```
...
-device virtio-net,netdev=netdev2 \
-netdev user,id=netdev2 \

```

My guest OS is Windows Server 2016.

**Comment by sameehj** [comment]
Thanks for investigating this, I'll check this out and send some patches =)

**Comment by sameehj** [comment]
For documenting history:
I couldn't reproduce with vhost=on but with vhost=off it reproduces successfully.

**Comment by sameehj** [comment]
I have posted a fix:
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/208

**Comment by sameehj** [comment]
commit : 4837781496314580b07824885d9dbeca6152a297 fixes the issue, this can be closed now.
