### ISSUE TITLE
Storage test failures on Win2k8R2

### ISSUE THREAD

**Issue by ben-skyportsystems** [virtio-win/kvm-guest-drivers-windows#216]
Hi,

I'm trying to get the viostor and vioscsi devices to pass HCK tests.  I have them both passing completely on WIndows 8.1, Server 2012R2 and Windows 7, but am stuck with Server 2008R2.

I'm using your VirtHCK test bed (great tool, BTW!).
Failing tests:
* Bus Teset Test
* LUN Rest Tests

With just a vanilla Windows installation (2008R2 SP1), the tests fail at **Runjob - PingPong - Create Storage Parameters** in the **Create Parameters** subtask.

Following this advice:
https://bugzilla.redhat.com/show_bug.cgi?id=1349724

I installed KB2506143 (Windows Management Framework 3.0) on both machines.  With this in place, things progress a bit further.  Now the **Set StorageParameters - Server 2** subtest fails with this message:

![screen shot 2017-12-05 at 3 20 52 pm](https://user-images.githubusercontent.com/8432404/33636177-00fcfea2-d9d0-11e7-9ea7-2b0e8bd07249.png)

When i try to run this command on CL1-WIN2K8, I get an "access denied" error, so maybe this is related to an ACL of some kind?

Has anybody seen this?

thanks,
Ben

**Comment by vrozenfe** [comment]
I've just rechecked https://bugzilla.redhat.com/show_bug.cgi?id=1349724 again.
We were using a manual errata with HCK package submission. I will ask QE to 
confirm if it is still what we do. Meanwhile could you please check that you have 
all the latest HCK filters installed?

Best regards,
Vadim.

**Comment by ben-skyportsystems** [comment]
Thanks a lot for looking into this Vadim.  The HCK filters that I'm using were downloaded on 11/6, but I'll see if there are newer ones available.  What do you mean "manual errata"?  Do you submit a failing package file with an explanation?

**Comment by vrozenfe** [comment]
If it still doesn't work with the latest filters, you should contact MS and ask them for a manual errata.

**Comment by ben-skyportsystems** [comment]
@vrozenfe : I understand that what I'm reporting here isn't necessarily a bug with the Windows guest drivers.  I have a handful of tests that I can't get to pass HCK and am hoping to avoid doing Windows kernel debugging, especially if the problems are ones that you and your colleagues have seen during your experiences with WHQL.  What's the best way to ask for help without taking up too much of your time?  Is the VirtHCK repo more appropriate, since it's more concerned with HCK/HLK testing?

thanks,
Ben

**Comment by vrozenfe** [comment]
Hi Ben. I totally understand your concern. This list is quite well monitored by RH people. The problem 
is that some of them can be very busy and not be able to respond immediately. I'm quite sure that one
of our QE engineers, involved into WHQL submission process, will get in touch with you soon. Apart from that I will be glad to help you with any storage, balloon, or vioseral related technical issues you have.

Best,
Vadim.

**Comment by lijinlijin** [comment]
Hi Ben,
Yes, "Bus Teset Test" and  "LUN Rest Tests" fail on win2008R2.
Redhat pass the whql certification with manual errata 5906:
https://sysdev.microsoft.com/en-US/Hardware/EC/FilterDetail.aspx?id=32016

If you need anything about hck/hlk testing, redhat qe would like to help.
I will check the github issues from time to time(may not response very fast during our busy testing period)

Thanks.

**Comment by ben-skyportsystems** [comment]
Hi @lijinlijin ,

Thanks for pointing out this errata.  I guess I assumed that all errata were part of the HCK filters that you can download.  I just downloaded the latest filters and clicked "Apply filters" and it didn't make these tests pass.  Do you submit an HCK results package with failing tests and point out the errata in a note or something?

Thanks again for all your help and hard work.
--Ben

**Comment by lijinlijin** [comment]
Hi Ben,
Yes, we need to append a readme.doc with the hck/hlk packages to list our failures and which errata can cover them.
I can't find the original link where we downloaded readme.doc file, I can mail to you if you need.
After fill the readme file, then append it when package the logs, details can refer to step 4 of following link:
https://msdn.microsoft.com/en-us/library/windows/hardware/jj124955%28v=vs.85%29.aspx

**Comment by ben-skyportsystems** [comment]
Thank you so much!  Now that I know about manual errata, I should be able to most if not all of the remaining errors.  I'll create my own readme document, don't worry about trying to find yours.

**Comment by ben-skyportsystems** [comment]
Hi,

I just got WHQL certification for viostor and vioscsi using the manual errata that you mentioned for Windows 8/2012 and Windows 7/2008.   Commit was 15767b46a1b8bebba8064f058be0566948435d42 (12/5/2017).  Thanks a lot for the help guys!

--Ben

**Comment by shivarajamingad** [comment]
Ben can u please help how to run lun reset test cases on 2012 R2 OS...Am seeing the similar failure as u on 2012 R2 OS also...
