### ISSUE TITLE
Signed build of IVSHMEM

### ISSUE THREAD

**Issue by gnif** [virtio-win/kvm-guest-drivers-windows#217]
I know I have raised this before, and to work around the problem I obtained a personal driver signing certificate so I could continue working on this project, but I am nearing release and I would like the Red Hat signed build to be available before I open my code up to the public.

The project that uses this is "Looking Glass", it has garnered an enormous amount of publicity and hundreds of users are extremely excited to use it, but without the ivshmem driver it will not work. This project bridges the last hurdle in consumer space VM integration with full 3D Acceleration.

https://forum.level1techs.com/t/a-little-teaser-of-what-is-to-come
https://www.youtube.com/watch?v=tHv9qh2F3NU

Once all our ducks are all lined up I will be publishing the source under GPL 2.0 on GitHub, I don't want people to grab this and be disappointed that it doesn't function yet.

**Comment by vrozenfe** [comment]
Technically we can run a build from upstream virtio-win repository. But let me check first with some other guys here at RH if they are fine with that.

Vadim.

**Comment by gnif** [comment]
Thanks @vrozenfe, please let me know how it goes.

**Comment by vrozenfe** [comment]
We are trying to arrange a public location for hosting the entire upstream build(s).
Meanwhile, you can find ivshmem RH-signed binaries at
http://people.redhat.com/vrozenfe/ivshmem/ivshmem.zip 
Please give it a try and let me know if you any problems.
Vadim.

**Comment by gnif** [comment]
Thank you Vadim!

**Comment by vrozenfe** [comment]
No worries.
Vadim.

**Comment by cameronleger** [comment]
I think this signed driver is for Windows 10, but I'm on 8.1. I haven't seen anyone else ask for this, so I assume they've upgraded or perhaps I'm doing something wrong. If this is only for 10, how can I go about getting one for 8.1? Is there a timeframe for the rest of the build, or in the meantime is this something you or I can make a temporary build?

**Comment by gnif** [comment]
Correct, this is a Windows 10 build, which for now is all [Looking Glass][1] officially supports.

[1]: https://github.com/gnif/LookingGlass

**Comment by vrozenfe** [comment]
It shouldn't be a problem to build Win 7/8/8.1 drivers as well. We can address this issue in one of the following builds, after adjusting VS project and the build script files.

**Comment by DragoonAethis** [comment]
Is there any chance we could see signed 8.1 drivers in the upcoming days?

**Comment by vrozenfe** [comment]
Will do it during the week. Vadim.

**Comment by gnif** [comment]
Please be aware that I have some incoming changes for this driver over the next few days

**Comment by bash64** [comment]
I am doing qemu with gpu passthrough on an msi gt70-2pe laptop.
This laptop has nvidia optimus (intel/nvidia) video hardware.
I am only able to to run qemu with gpu passthrough using seabios, not uefi.
For this reason I can only run windows 7 and not windows 10.
It's a long story.
I will not be able to use lookingglass without a windows 7 driver.
Please post when you have this.
I began the process of adding lookingglass to my existing setup today.
After starting the ivshmem server and booting qemu windows 7 cannot see any new hardware for ivshmem. Should it show up in the device manager?
Thanks

**Comment by gnif** [comment]
@bash64 Don't ask for support here, either go to the #LookingGlass channel on FreeNode and ask your question or the Level1Tech forums, this question has been answered numerous times.

**Comment by DragoonAethis** [comment]
@vrozenfe Any news on this? Or are there any problems we could help with?

**Comment by vrozenfe** [comment]
Just waiting for an update on pull request #225 https://github.com/virtio-win/kvm-guest-drivers-windows/pull/225#issuecomment-356539524

Btw, do you need Win7 as well or Win8/8.1 will be enough?

Cheers,
Vadim.

**Comment by DragoonAethis** [comment]
Thanks for the update. Just Win8.1 for now would be great, but Win7 support would be nice to have in the future (since those patches have a few interesting uses outside of Looking Glass which I'm looking into for some time).

**Comment by vrozenfe** [comment]
Sure,
Will try to do it today. If not, then on weekend or beginning of the next week.
Vadim.

**Comment by vrozenfe** [comment]
http://people.redhat.com/vrozenfe/ivshmem/ivshmem2.zip
Completely untested! Use on your own risk :)

**Comment by DragoonAethis** [comment]
Awesome, thanks!

**Comment by DragoonAethis** [comment]
The driver works perfectly fine and stable on Windows 8.1, Looking Glass also works "out of the box" (a10). 👍

**Comment by bash64** [comment]
verified, ivshmem2 works on windows 10. lookingglass fully functional for me.
still want the windows 7 driver.
thanks

**Comment by bash64** [comment]
Well, that blows.
Then I need to get W10 audio to stop crackling when using pulseaudio.

**Comment by Vaporeon** [comment]
Seconding a request for a windows 7 ivshmem driver and any later time.

**Comment by gnif** [comment]
@Vaporeon, what for? LookingGlass doesn't work in W7.

**Comment by Vaporeon** [comment]
Maybe not as it stands, but it could in the future. (maybe roll out own capture using the same ugly DWM hooks vmware, and I think virtual box used?)
The IVSHMEM device itself can also be used for other things.

Having a signed driver available will be helpful to anyone who may wish to take on such an endeavour.

**Comment by vrozenfe** [comment]
Will try to make it available soon.
Vadim.

**Comment by xtf1** [comment]
Anything new?

**Comment by vrozenfe** [comment]
Just was busy with other stuff. Will try to make it available by the end of this week.
Vadim.

**Comment by Vaporeon** [comment]
ping?

**Comment by vrozenfe** [comment]
In order to build Win7 I've made the relevant changes some time ago:
 https://github.com/virtio-win/kvm-guest-drivers-windows/commit/0465da2c205d627121b3414d7db5bc3d587720d6
You can build it and give it a try with a testing signature.
For the RH-signed binaries I have to run a new build which can be ready 
in a day or two.
Vadim.

**Comment by vrozenfe** [comment]
It's a bit complicated, but latest-virtio and stable-virtio are based on our internal builds that only include virtio-win  drivers officially distributed with RHEL.  ivshmem is not one of them.
We started maintaining upstream-virtio repository at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/ for hosting upstream builds. I initiated a new upstream build that will contain RH-signed ivshmem driver some time ago, but it may take a couple of days before the upstream binaries will be updated.
Best,
Vadim.

**Comment by dracwyrm** [comment]
@vrozenfe Many thanks for taking the time to clarify this. :) I guess this bug can be closed soon then!

**Comment by vrozenfe** [comment]
Please check  build 161 from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/  It should include RH-signed drivers that you need.

Best regards,
Vadim.

**Comment by T-vK** [comment]
Would it be possible for you to provide the driver(s) individually? So that we could avoid downloading the whole zip file when we only need that one driver? I need this for a script that I'm planning to release and I feel like it would be a waste of resources to download the whole zip file just to throw away 99% of it afterwards.

I would really appreciate that.

At the moment I have no choice, but to do it like this:
```
if [ ! -f "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver/ivshmem.cat" ] || [ ! -f "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver/ivshmem.inf" ] || [ ! -f "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver/ivshmem.pdb" ] || [ ! -f "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver/ivshmem.sys" ]; then
    echo "> Downloading IVSHMEM driver..."
    rm -rf "${PROJECT_DIR}/mobile-passthrough-iso/tmp"
    mkdir -p "${PROJECT_DIR}/mobile-passthrough-iso/tmp"
    wget "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/virtio-win10-prewhql-0.1-161.zip" -O "${PROJECT_DIR}/mobile-passthrough-iso/tmp/virtio-win10-prewhql.zip"
    unzip "${PROJECT_DIR}/mobile-passthrough-iso/tmp/virtio-win10-prewhql.zip" -d "${PROJECT_DIR}/mobile-passthrough-iso/tmp"
    rm -f "${PROJECT_DIR}/mobile-passthrough-iso/tmp/virtio-win10-prewhql.zip"
    rm -rf "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver"
    mkdir -p "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver"
    cp "${PROJECT_DIR}/mobile-passthrough-iso/tmp/Win10/amd64/ivshmem*" "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver/"
    #cp -r "${PROJECT_DIR}/mobile-passthrough-iso/tmp" "${PROJECT_DIR}/mobile-passthrough-iso/bin/ivshmem-driver"
    rm -rf "${PROJECT_DIR}/mobile-passthrough-iso/tmp"
else
    echo "> IVSHMEM driver already exist in iso folder..."
fi
```

**Comment by YanVugenfirer** [comment]
Hi,
We don't have such plans for now. I will discuss it internally.

Best regards,
Yan.

**Comment by T-vK** [comment]
Thank you

**Comment by Verequies** [comment]
Would it possible to generate a new upstream build including the latest ivshmem changes?

**Comment by vrozenfe** [comment]
We will have a new build in a couple of weeks or even less.
Vadim.

**Comment by 8BallBomBom** [comment]
@vrozenfe Any updates?
As it stands currently if anyone wants to use Looking Glass on Windows 11 then they have to disable secure booting.
