### ISSUE TITLE
Design document...

### ISSUE THREAD

**Issue by vbusireddy** [virtio-win/kvm-guest-drivers-windows#218]
For the netkvm virtio driver, is there a design document (or some such README) that describes the design of the driver? I know the driver is written based on the "Virtual I/O Device" specification, but while debugging or fixing the code, it helps to understand why certain things are done a certain way.

Thanks,

Venu

**Comment by YanVugenfirer** [comment]
There is very old document here: http://www.linux-kvm.org/page/Internals_of_NDIS_driver_for_VirtIO_based_network_adapter , unfortunately since then the data path changed significantly due to multi-queue implementation.

**Comment by vbusireddy** [comment]
This is great! Thank you so much!!
