### ISSUE TITLE
NetKVM Regression: NDISTest 6.0 1c_FaultHandling fails

### ISSUE THREAD

**Issue by ben-skyportsystems** [virtio-win/kvm-guest-drivers-windows#226]
Current top of tree fails this test on HCK/HLK on all Windows versions I've tested so far (2016, 2008R2 and Windows 7).
git bisect results:
```
PS C:\Users\Administrator\Source\Repos\kvm-guest-drivers-windows> git bisect bad
42f683e08c4f62529c54f3bcdb678d81d1607c70 is the first bad commit
commit 42f683e08c4f62529c54f3bcdb678d81d1607c70
Author: Sameeh Jubran <sameeh@daynix.com>
Date:   Mon Dec 4 14:15:53 2017 +0200

    NetKVM: SM: Integrate CX path into state machine

    Signed-off-by: Sameeh Jubran <sameeh@daynix.com>

:040000 040000 556a9bfe90c09ff767cf8ffcb2ff4e12c73044c4 85c191cf3634c657acb5147c5fbd2cde3f58dd42 M  NetKVM
```

The symptom is that the client hangs as shown here:
<img width="598" alt="screen shot 2018-01-05 at 7 13 51 pm" src="https://user-images.githubusercontent.com/8432404/34635986-ac659a62-f24c-11e7-918f-9b73c17a5976.png">

On a passing run, it continually starts and stops the driver and is finished within a couple of minutes.

**Comment by sameehj** [comment]
Hi @ben-skyportsystems,

Thanks for reporting this, I'll take an in depth look tomorrow. Meanwhile can you please run "nmi" in side Qemu monitor during the hang and then provide me with the resulting dump file? That would be great!

I think this has to do with cleanup of the CX path, but not exactly sure where.

**Comment by ben-skyportsystems** [comment]
Minidump output after issuing NMI is attached.  Hopefully this is what you're looking for.

[minidump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/1609062/minidump.zip)

**Comment by sameehj** [comment]
@ben-skyportsystems Hi,

Actually the minidump wasn't that helpful but thanks anyway. I was able to reproduce the issue and create a fix, can you please confirm that?

Please checkout the following branch:
https://github.com/sameehj/kvm-guest-drivers-windows/commits/sm_fix

**Comment by ben-skyportsystems** [comment]
@sameehj :  I've confirmed that the test passes on Server 2016, although I haven't had a chance to test on the other versions of Windows.  Thanks for the quick turnaround.

**Comment by sameehj** [comment]
@ben-skyportsystems Thanks for confirming =)

I have tested this too on Win2012, and I think it should be working on all OS versions. The commits are already in master.
