### ISSUE TITLE
How to pass NDISTest 6.5 MPE_Ethernet.xml?

### ISSUE THREAD

**Issue by ben-skyportsystems** [virtio-win/kvm-guest-drivers-windows#236]
Hi,
I only have one HCK test left for NetKVM that I can't find a manual errata for: **MPE_Ethernet.xml**.  I found older RedHat bug reports related to this test, but they seem to be fixed.  This is one of those fun tests where using 4GB of RAM on the clients brings the "Unexpected reboot" failure message, while 3GB proceeds much further.  The failure I see is on the server, where it blue screens after about 3 hours:
![screen shot 2018-01-15 at 4 13 22 pm](https://user-images.githubusercontent.com/8432404/35026681-4fbfa79a-fb01-11e7-8480-266de79b30d7.png)

I've tried going back in time to find a version of the net driver that passes (in order to bisect), but no luck.  I'm using your awesome VirtHCK testbed, so test setup shouldn't be an issue.  HLK doesn't have this test, but HCK does, and it fails on all 4 operating systems: Win7/2008R2 and Win8.1/2012R2.

Do you have any hints on either how to get this test to pass, or point to an errata that is applicable?

thanks,
Ben

**Comment by lijinlijin** [comment]
Which version are you testing with?
We tested with 143 and 144 version last month, this job passed on all windows platforms.

**Comment by ben-skyportsystems** [comment]
I'm not sure how your versions map, but I've tested the following commits:
15767b46a1b8bebba8064f058be0566948435d42 (top of tree when I built the drivers)
eb2996de43b5aaa9638500be293947e7fd33e7c4 (switch to BSD license)

**Comment by lijinlijin** [comment]
Oh, I tested with the version our developers built, there hasn't have the same build in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/

There is nothing special requirement to run this case.I checked our testing history:
win2012r2: 6G mem, 8 smp

BTW, we also turn on mq of virtio network

**Comment by YanVugenfirer** [comment]
Hi Ben,

Can you please upload the dump file and the pdb file for the sys?

Thanks,
Yan.

**Comment by ben-skyportsystems** [comment]
Thanks!  I didn't have multiqueue turned on, and that seems like it may be important.  I'll try running with it enabled, and if it still fails will post the dump files.

**Comment by YanVugenfirer** [comment]
Should pass with single queue as well. So we will be happy to look at the dump file.

**Comment by ben-skyportsystems** [comment]
With multiqueue enabled and more cores (6G, 8c), the test passed on Win2k8R2.  That's all I've had a chance to try so far.  This seems to be a very resource-intensive test, I don't think I can run two concurrent instances of HCK on my server with this test running, so it'll take a while to know for sure if everything's OK, but thanks for the support guys.

**Comment by YanVugenfirer** [comment]
Closing. If the issue still exists on your setup - please reopen.
