### ISSUE TITLE
netkvm enable multi-queue, but performance worse than the multi-queue disable

### ISSUE THREAD

**Issue by zyb521** [virtio-win/kvm-guest-drivers-windows#237]
Hi, everyone,

We are check the multi-queue capabilities of the virtio-net, found that enable mq on Windows 2012, network performance worse than the mq is disable;

This is a bit unexpected, in the same test environment, CentOS 7.3 with mq, the performance has improved significantly;
We try 4-8-16 queues, all about that, performance is worse than the single queue.

Contrast the CentOS test results, I think the bottleneck may be in the netkvm driver, we are continuing to investigate this issue, do you have any suggestions?

Thanks all.
zyb

Some Info:
2 same type vms on the same host,  and using iberf3 test network performance with mq,
GuestOS: Windows server 2012, CentOS 7.3
driver version: virtio-win-0.1.141
server: iperf3 -s
client: iperf3 -t 10 -b 0 -c ip_addr -P 8

**Comment by zyb521** [comment]
sorry i cann't upload images, the test results:

Guest: Windows 2012， sq,  vm0  (IP: 192.168.1.2) <->vm1 (IP: 192.168.1.3) :  bandwidth 4.3G bps
Guest: Windows 2012， 16 mq, vm2  (IP: 192.168.1.4) <->vm3 (IP: 192.168.1.5) : bandwidth 2.3G bps

Guest：Centos，sq，centos0 (ip：192.168.1.6)<-> centos1 (ip: 192.168.1.7): bandwidth 15.3G bps
Guest：Centos， 32 mq,  centos0 (ip：192.168.1.6)<-> centos1(ip: 192.168.1.7): bandwidth 25.2G bps

**Comment by sameehj** [comment]
Hi @zyb521 ,

Thanks for reporting this, we are aware of NetKVM performance issues however the results that you are getting are very low and there are few thigns to do about that:

* Try and use iperf2 instead of iperf3, for some reason iperf3 gives very poor performance on Windows.
* In case not using the default sized MTU (1500) you should change it in both the device (host_mtu=9000) and the driver's advanced tab MTU field from Windows.
* Make sure that you have enough Vpcus , queues and vectors as follows: The #vcpu should be at least equal to the number of queues and the number of vectors should be #num_queues * 2 + 2 that is for 4 queues, you'd need 4 vcpus at least and 10 vectors.
* is vhost on?

What packet sizes are you using? in small packet sizes the Linux guest performs much better at the moment.

**Comment by zyb521** [comment]
@sameehj 
Thank you for your reply.

- Try and use iperf2 instead of iperf3, for some reason iperf3 gives very poor performance on Windows.
**OK, i will try iperf2**
- In case not using the default sized MTU (1500) you should change it in both the device (host_mtu=9000) and the driver's advanced tab MTU field from Windows.
**MTU keep default value of 1500**
- Make sure that you have enough Vpcus , queues and vectors as follows: The #vcpu should be at least equal to the number of queues and the number of vectors should be #num_queues * 2 + 2 that is for 4 queues, you'd need 4 vcpus at least and 10 vectors.
**Sure, we give the same vcpus as the queues num to vm**
- is vhost on?
**we use vhost-user** 

Linux guest performs better than Windows is the expected result.
However, it is surprising that sq is better than mq, whether it's happening on Windows or Linux.
:)

**Comment by sameehj** [comment]
> Linux guest performs better than Windows is the expected result.
However, it is surprising that sq is better than mq, whether it's happening on Windows or Linux guest.
:)

I agree please retest with iperf2 / netperf and update us on the findings =)

**Comment by zyb521** [comment]
@sameehj 
Thank you for your suggest.

It is true that the editions of WS 2012 and the benchmark tool parameters affect the test result.
Using essentials editions and iperf3, the result as bad as my first report.
Using datacenter editions and iperf2, the result is better then the first time, and the mq is better than sq, just like linux guest.

**Comment by YanVugenfirer** [comment]
As far as we know iperf3 is not built for multi-stream benchmarking.

**Comment by sameehj** [comment]
@zyb521 Thanks for reporting back, can you please share your benchmark results here?

**Comment by zyb521** [comment]
ok.

Using datacenter editions and iperf2 multi-stream tcp:
8 vcpu, sq  <---> bandwidth 4.3G bps
8 vcpu, 8 mq  <---> bandwidth 8.5G bps

iperf test cmd:
server: iperf.exe -s -w 512k
client: iperf.exe -c ip_addr -t 100 -l 64k -w 512k
