### ISSUE TITLE
netkvm: 32 queues boot time take much longer

### ISSUE THREAD

**Issue by oyzw0720** [virtio-win/kvm-guest-drivers-windows#243]
Hi,
We found that when multi-queue was enabled, the more the number of queues the longer the windows boot time will take. If set the queue number to 32, the boot time will take about 3 min 30 sec.

I check the boot log and found that the most time is take in function 'ParaNdis_VirtIONetInit'. There is a for loop:
```
    for (i = 0; i < pContext->nPathBundles; i++)
    {
        if (!pContext->pPathBundles[i].rxPath.Create(pContext, i * 2))
        {
            DPrintf(0, ("%s: CParaNdisRX creation failed\n", __FUNCTION__));
            return status;
        }
        pContext->pPathBundles[i].rxCreated = true;

        if (!pContext->pPathBundles[i].txPath.Create(pContext, i * 2 + 1))
        {
            DPrintf(0, ("%s: CParaNdisTX creation failed\n", __FUNCTION__));
            return status;
        }
        pContext->pPathBundles[i].txCreated = true;
    }
```

This loop will take minutes to finish initialize the nic, I wonder is there any way to improve this? Thanks!

The boot time is list below:
Queue num | First boot | Normal boot
-- | -- | --
1 | 50sec | 30sec
2 | 50sec | 30sec
4 | 50sec | 30sec
8 | 1min5sec | 35sec
12 | 1min10sec | 40sec
16 | 1min20sec | 50sec
20 | 1min50sec | 1min5sec
24 | 2min15sec | 1min30sec
28 | 2min50sec | 2min
32 | 3min10sec | 2min30sec

**Comment by YanVugenfirer** [comment]
Thanks for reporting it!

We can try to mitigate this issue by allocating large chunk (or large chunks) during driver boot.
The allocation should be "adaptive" - if the driver disabled\enabled you might not get from OS large chunk of memory during driver load, and will have to fallback to the current method of allocation.

BTW: What exactly Windows version was affected? There were some initial patches on the subject from Google: https://github.com/virtio-win/kvm-guest-drivers-windows/pull/30/commits/c9b113eaf621dbb926b17694902847da13752b6a

**Comment by oyzw0720** [comment]
Thanks for your reply! We test this on windows 2012 R2, we'll try to apply this patch to see if there is any improvement.

**Comment by YanVugenfirer** [comment]
Keep in mind that the patch is very old and some adjustments might be
needed.

Best regards,
Yan.

**Comment by oyzw0720** [comment]
OK, thanks for reminding this~

**Comment by sameehj** [comment]
Hi @oyzw0720 .

You may want to check the following Qemu patches as well. Please update us with your results in case you do try them :)

http://patchwork.ozlabs.org/cover/867134/

**Comment by YanVugenfirer** [comment]
@oyzw0720  - do you have any updates regarding the patches that you tried?

Thanks,
Yan.

**Comment by oyzw0720** [comment]
@YanVugenfirer 
We checked our source code and found that  it has already applied that patch, and the issue is not caused by this bug.
But we also found that if we set the memory much larger (32 GB for instance), the boot time will take much shorter. So the more queues you set, the more memory you need to keep the boot time normal.

**Comment by YanVugenfirer** [comment]
Thank you for the update.

**Comment by oyzw0720** [comment]
My pleasure~

**Comment by sameehj** [comment]
I am closing this issue, please reopen if you believe this has not been resolved.
Thanks for reporting :)
