### ISSUE TITLE
Mouse side buttons don't work with vioinput

### ISSUE THREAD

**Issue by EggheadDash** [virtio-win/kvm-guest-drivers-windows#247]
I am attempting to use evdev passthrough on my Logitech G502 in a Windows 10 VM, which is using libvirt. While every other button on my mouse and keyboard works flawlessly, those two buttons don't work, and pressing them results in the following appearing in `/var/log/libvirt/qemu/Windows.log` whenever I press one of them

```
virtio_input_handle_event: unmapped button: 5 [side]
virtio_input_handle_event: unmapped button: 6 [extra]
```

where 5 is the bottom button and 6 is the top button.

Running `evtest /dev/input/by-id/usb-Logitech_Gaming_Mouse_G502_157D356F3034-event-mouse` and pressing those buttons gives the following output

```
Event: time 1518930554.125180, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1518930554.125180, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1518930554.125180, -------------- SYN_REPORT ------------
Event: time 1518930554.278200, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1518930554.278200, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1518930554.278200, -------------- SYN_REPORT ------------
Event: time 1518930555.139163, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1518930555.139163, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1518930555.139163, -------------- SYN_REPORT ------------
Event: time 1518930555.277172, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1518930555.277172, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1518930555.277172, -------------- SYN_REPORT ------------
```
The code values are indeed the ones defined in `vioinput/sys/vioinput.h` when you convert the hex to decimal, so I am not sure why they aren't working (I admit my knowledge of C or any programming is limited, so this is about my limit of attempting to do this myself). I also am using the binary drivers from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/, of which version 1.141-1 is for some reason both "stable" and "latest". It also was released 2017-08-04, meaning 1680088 is the most recent commit that could have been included. However, I don't see any commits since then that could have fixed this issue. I also cannot build the drivers as I do not have access to VS15 as it asks me to purchase a subscription for older VS versions.

EDIT: Immediately after I posted this I found a page that indicates it may be a qemu problem, namely that it's not defined in qemu's `hw/input/virtio-input-hid.c` file. Will mess around with that and report back.

**Comment by YanVugenfirer** [comment]
Thank you for the reporting.

Could you please add the link that has a description of QEMU issue?

Also, you could try VS express or community edition to compile the drivers - https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads

**Comment by EggheadDash** [comment]
It was Qemu's fault. It's actually already patched on git, but the overall current git appears to be broken. Patching just that file from earlier based on the current stable Arch package fixed it. Sorry I didn't report back earlier.

**Comment by YanVugenfirer** [comment]
Thanks for the update!

**Comment by jkendall-cc** [comment]
Sorry to resurrect an old thread. I have an existing kvm/qemu set up with a Windows 10 guest using virt-manager. I have spent a lot of time configuring it so I am not in a position to mess around too much. Could you give an explanation of how I could patch this file? I installed via the AUR. Would I need to rebuild qemu? if so, how could I do this safely?

Any advice would be greatly appreciated. This is the only thread I could find that explains my problem.

**Comment by bughunter2** [comment]
Possibly related. In Linux guests it's relatively easy to get the back/forward mouse side buttons to work, but in Windows guests it might not yet be possible:

**extra mouse button support in Windows guests with spice-vdagent**
https://gitlab.freedesktop.org/spice/win32/vd_agent/-/issues/27

**Comment by YanVugenfirer** [comment]
@bughunter2 we might have a similar issue with virtio-input (need to double check), but the Spice issue https://gitlab.freedesktop.org/spice/win32/vd_agent/-/issues/27 is not related to virtio drivers as it uses a completely different mechanism to transfer events to the guest.

**Comment by bughunter2** [comment]
> @bughunter2 The Spice issue https://gitlab.freedesktop.org/spice/win32/vd_agent/-/issues/27 is not related to virtio drivers as it uses a completely different mechanism to transfer events to the guest.

I'm sorry. I was in fact aware of that, but thought this could be helpful for those who find this issue on the net, since it is related in terms of symptoms. Perhaps I should have been clearer about my intention. Thanks for understanding.

**Comment by YanVugenfirer** [comment]
No problem!
Thanks for pointing out the spice issue
