### ISSUE TITLE
Questions about the device queue depth for vioscsi and viostor.

### ISSUE THREAD

**Issue by zyb521** [virtio-win/kvm-guest-drivers-windows#251]
Hi, eveyone

From the code, if enable INDIRECT mode, queue depth of viostor is 4 times then vioscsi.

viostor:
> #if (INDIRECT_SUPPORTED)
    if(adaptExt->indirect) {
        adaptExt->queue_depth = queueLength;
    }
#else
    adaptExt->indirect = 0;
#endif

vioscsi:
>if(adaptExt->indirect) {
        adaptExt->queue_depth = max(20, (queueLength / 4));
    } else {
        adaptExt->queue_depth = queueLength / ConfigInfo->NumberOfPhysicalBreaks - 1;
    }

queueLength mean the num of vring desc.

In my opinion, the queue depth represents the number of requests that a single device (or a single queue) can process, so the queue depths for viostor and vioscsi can be the same value.

Is there any special meaning for this different setting?

Thanks all.
zyb521

**Comment by vrozenfe** [comment]
Just a quite terrible workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1013443

Cheers,
Vadim.

**Comment by zyb521** [comment]
@vrozenfe thank you for your reply.
I found the original change commit 5c600bc938347c7962fd750aea868c5431d54657

Queue depth has a significant impact on storage performance. Are there any suggestions or plans for optimization?

thanks,
zyb521

**Comment by vrozenfe** [comment]
The alternative (and honestly a way better) solution was to maintain a linked list of SRBs that failed to be added to a vq and then try to resubmit these SRBs from ISR routine or on next StartIo call. That solution worked fine but needs some cancellation logic to be added. Unfortunately I didn't have enough time to fix the problem properly at that time.  Will try to make it better now :)
Best,
Vadim.

**Comment by vrozenfe** [comment]
I can try to see if I have it somewhere. The patch itself is quite simple, the only problem is to make sure that all SRBs are completed properly and probably give some priority to FUA requests. If you want give it a try and craft such patch by yourself - you are more than welcome. Otherwise , I can try writing such patch on weekend. 

Best,
Vadim.
