### ISSUE TITLE
WS 2012 R2 OS

### ISSUE THREAD

**Issue by shivarajamingad** [virtio-win/kvm-guest-drivers-windows#294]

**Comment by shivarajamingad** [comment]
Hi Vadim,

This is WS 2012 R2 but still i am facing the same error as indicated for WS 2008R2, I referred the error in the blog u shared in above comment.

Can you please let me know if there is a separate procedure to run these test cases ?
I am running these tests  on our storage controller .

Is that manual ERRATA 5906 can be used for for 2012 R2 OS also.
https://sysdev.microsoft.com/en-US/Hardware/EC/FilterDetail.aspx?id=32016

**Comment by vrozenfe** [comment]
5906 is for Windows 8 / Windows Server 2008 as mentioned in the description.

I'm a bit confused with "our storage controller". If it is not any of our "official" qemu 
virtio-win drivers, then I suggest you to check if you properly handle
SRB_FUNCTION_RESET_BUS, SRB_FUNCTION_RESET_DEVICE, and SRB_FUNCTION_RESET_LOGICAL_UNIT requests.

Cheers,
Vadim.

**Comment by vrozenfe** [comment]
If the problem happens with virtio storage device then please let us know the kernel, qemu, and driver versions as well as qemu command line. Then we should be able to reproduce, investigate and find a way how fix the problem.
If there is  your own physical or virtual HBA and your own miniport driver then you first need to be sure that your driver handles  and complete SRB_FUNCTION_RESET_LOGICAL_* requests properly, including completion all pending requests.

**Comment by vrozenfe** [comment]
Results of the optional tests can be omitted.

**Comment by shivarajamingad** [comment]
Results of the optional tests can be omitted

What is the procedure to do this can u help..
I am running for server 2012R2 OS..
Is there a filter or manual errata ...How to ommit these test cases

**Comment by lijinlijin** [comment]
Did you follow below steps when running the jobs?
1. nonboot disk
2. two machines connected to shared storage

“Running the test
This test should be run on a nonboot storage controller. Running on a boot controller is possible, but requires at least one nonboot disk attached. This test will not execute on the boot disk. The expected result is for there to be no IOs stuck in the miniport after the RESET_LUNs and RESET_BUSs. Verification is done by restarting the machine after the test. To run this in a dual initiator setup, schedule this test on two machines connected to shared storage. Resets on one initiator should not adversely affect the other initiator. For Single Disk tests, double check that the two initiators are testing against the same physical disk in the shared storage.“

https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/f42046f1-ebf4-49dd-9eba-6ee766727fa9
