### ISSUE TITLE
Windows 2008r2 mtu 9000 issue. (Jumbo frames)

### ISSUE THREAD

**Issue by jsm222** [virtio-win/kvm-guest-drivers-windows#300]
Hi.
In an openstack environment with physical mtu 9000:
When netkvm gets mtu size from dhcp 9000, I have to manually set int.MTUSize in the advanced properties of the netKVM driver from 1500 to 9000 in order to make the net connection work.
(shift-f10 during initial boot and devmgmt.msc in cmd...)
It works out of the box on windows 2012r2.

The problem seems to also be described here:
https://bugzilla.redhat.com/show_bug.cgi?id=1467797

Is it fixable in any way?

**Comment by YanVugenfirer** [comment]
Hi,

You can try setting EnablePMTUDiscovery in the registry (if it is not already set) https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc957539(v=technet.10) .

Best regards,
Yan.

**Comment by jsm222** [comment]
Thanks for your reply. As per [this]( https://social.technet.microsoft.com/Forums/en-US/de3924d2-268b-473c-9575-05b3ccccfd15/howto-enabledisable-path-mtu-discovery-on-windows-server-2008-r2?forum=Forefrontedgegeneral) it is ON by default. (And it was not set e.g it did not exist) I do not have access to the OpenStack environment with jumbo frames before Monday. (But the windows system image was the same)

**Comment by jsm222** [comment]
Well. I recreated the image and manually set init.MTUSize on the NIC device propeties before sysprep. A reg add database change of the setting during install in unattend.xml did not work..

**Comment by sameehj** [comment]
Is the device provided with the mtu parameter by Openstack? The virtio-net's host_mtu should be set to 9000 by OpenStack, please make sure that Openstack does that.

**Comment by jsm222** [comment]
It does not. Do you know a setting in queens/libvirt I could look for? It is not documented as a glance property..

**Comment by YanVugenfirer** [comment]
Addressed by PR#495
