### ISSUE TITLE
Installer ?

### ISSUE THREAD

**Issue by stuaxo** [virtio-win/kvm-guest-drivers-windows#306]
Hi Thanks for the virtio windows drivers,
   I grabbed the iso, but having to go through the device manager is a lot less convenient than being able to use an installer.
   Are there any plans to provide an installer ?

S

**Comment by YanVugenfirer** [comment]
Hi,

There are no current plans to create the installer.

But the driver packages are DPInst ready (https://technet.microsoft.com/en-us/ff544842(v=vs.96)). You can get it from MS and put it in the specific driver directory and then run it to install the driver.

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
Hello All,

We are open sourcing our installers: https://github.com/virtio-win/virtio-win-guest-tools-installer

Best regards,
Yan
