### ISSUE TITLE
NetKVM driver for aarch64

### ISSUE THREAD

**Issue by wangmir** [virtio-win/kvm-guest-drivers-windows#322]
Hi, I'm trying to install virtio driver to aarch64 with using WoA (Windows on ARM).

I successfully install virtio-blk driver (viostor), and it seems work appropriately, but I have a problem with virtio-net driver (NetKVM) (for the record, it installed fine with emulation, but at the device, it has problems).

When I install the NetKVM driver (both legacy and modern), the system crushed (blue screen), and emit exception error.

So, I tried to follow the error point, and I found there are something awkward behavior.

For example, at the vring_new_virt_queue (from legacy driver), when vring_init function is called, and performing 

`vr->desc = (struct vring_desc *)p;`

Write accessing to vr->desc causes exeption (I think memory execption for bad accessing).

I'm not a expert on windows device driver (actually it is first time), but I found this [article](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nf-ndis-ndismallocatesharedmemory) that mention do not use ndis DMA, and recommend to use WDF DMA instead for aarch64.

And also, when I separate vq structure with info->queue similar to modern driver, with mem_alloc_nonpaged_block function (uses NdisAllocateMemoryWithTagPriority), that point was not a problem (although, after that point, install was failed too with other problems).

So, I tried to change NdisMRegisterScatterGatherDma and NdisMAllocateSharedMemory to WDF DMA APIs, but I found that WDF DMA API is tightly linked to WDF device driver format, so I need to allocate WDF device structure for that rather than NDIS device structure (I think whole bunch of driver code should be rewritten to use WDF DMA, right?).

So, are these Ndis API really problems? and can I switch this memory allocation to WDF-like APIs easily?

thanks,

**Comment by YanVugenfirer** [comment]
Hi,

Can you describe your configuration when you have a crash? Sorry, I am confused about the configuration that has BSOD.
Did you build the driver for ARM64? Can you share you VS project so we can check its settings?

Regarding your questions:
**So, are these Ndis API really problems?** - I don't know why MS is claiming they are a problem. They might have a reason, but I, unfortunately, I am not aware of it.

**and can I switch this memory allocation to WDF-like APIs easily?** - unfortunately not that easy... You can use NetAdapter Class extensions for WDF (meaning re-writing the driver, and it could be used on Windows 10 only) https://channel9.msdn.com/Blogs/WinHEC/introducingnetadapter). Or try to use the WDF functions you need in existing driver (still will need some work) https://blogs.msdn.microsoft.com/ndis/2014/07/20/using-wdf-in-an-ndis-driver/

**Comment by wangmir** [comment]
Unfortunately, I cannot upload or share VS project files because the file cannot be out in here, but the configuration is simple.

1. Install Windows 10 OS and vistual studio 2017 (including C++ compilers and libraries for ARM/ARM64)

2. Install WDK for Windows 10 (16299)

3. From original VS project from here --> change to VS2017 projects.

Change Configuration properties (global solution):

Configuration: Win10Release

Platform: New -> ARM64, import settings from x64

Also needed to change global solution settings:

In file Tools\Driver.Common.props add:

  <PropertyGroup Condition="'$(Platform)'=='arm64'">
    <TargetArch>arm64</TargetArch>
  </PropertyGroup>

In file Tools\Driver.PackOne.targets comment AfterBuild section:

  

3-1. Change project into test-signing mode

4. Build VirtioLib and VirtioLib-WDF

5. Build NetKVM for NDIS6

6. Install to Windows VM with device manager.


Anyway, if the NDIS APIs are really problems, then it seems I might re-write the device driver with NetAdapter CX for WDF..

**Comment by wangmir** [comment]
Moreover, do you know how can I use WDF function at existing NDIS driver?

I also read the linked [blog](https://blogs.msdn.microsoft.com/ndis/2014/07/20/using-wdf-in-an-ndis-driver/) but they didn't write about how it can be done.

**Comment by YanVugenfirer** [comment]
There are some discussions here with instructions: https://www.osronline.com/showthread.cfm?link=254061

**Comment by YanVugenfirer** [comment]
But are you sure you need this? Can you share dump file?

**Comment by wangmir** [comment]
I'm not sure actually, I also wrote a question to MS too about the NDIS issue, but they don't have any answer. I'm currently setting up windbg environment so, I'll try to get a dump after crash.

**Comment by wangmir** [comment]
Bad new, virtio-serial driver also gets error on installing, so I cannot get any debugging data. Moreover, I think WoA doesn't support general serial device driver too. Serial device emulation was also failed.

**Comment by YanVugenfirer** [comment]
Can't you create crash dump file? It can be loaded by the WinDbg later.

**Comment by wangmir** [comment]
I successed to attach windbg with remote device, so I got some error point from netkvm. 
Unfortunately, I cannot share the dump file directly (I'm looking for way to get a permission to share this), 
but the erro point was virtqueue_add_buf+0x48 (line 93), and exception code was 80000002 (Data misaligned).

Arm instruction was stur x9 [x10, #-8].

So, possible problem, I think, can be data or structure alignment between windows VM and QEMU or aarch system.

**Comment by YanVugenfirer** [comment]
You are right - there is a problem of access to un-aligned data on ARM architecture.

Let's look at the code:
```
        for (i = 0; i < out + in; i++) {
            desc[i].flags = (i < out ? 0 : VIRTQ_DESC_F_WRITE);
            desc[i].flags |= VIRTQ_DESC_F_NEXT;
            desc[i].addr = sg[i].physAddr.QuadPart;
            desc[i].len = sg[i].length;
            desc[i].next = (u16)i + 1;
        }
```

When desc is
```
/* Virtio ring descriptors: 16 bytes.  These can chain together via "next". */
struct vring_desc {
    /* Address (guest-physical). */
    __virtio64 addr;
    /* Length. */
    __virtio32 len;
    /* The flags as indicated above. */
    __virtio16 flags;
    /* We chain unused descriptors via this, too */
    __virtio16 next;
};
```

So access to flags and next fields as is is problematic on some non x86 architectures as they require 32bit aligned access. And this is an issue here.

You need to create some helper function that will access 16bit fields similar to: https://elixir.bootlin.com/linux/v4.18-rc8/source/include/linux/virtio_byteorder.h

Best regards,
Yan.

**Comment by vrozenfe** [comment]
I'm a bit confused then. If the problem is really hiding there than why it doesn't crash in the storage stack? (IIUC viostor driver is operating normally, right?). 
I can be missing something, but in my understanding, the only place where we should pay  attention to the ARM related specific alignment requirements is when we allocate data. When calculating  the size of allocation we need to do something like this:
size=ALIGN_UP_BY(size,KeGetRecommendedSharedDataAlignment());
And it should satisfy  the ARM requirements. However, as I said before I can be completely wrong in my assumptions. 

Cheers,
Vadim.

**Comment by wangmir** [comment]
Ok, it was alignment issue, and I solve the problem with alignment issue with your advice, but netkvm still has problem with installing.

I think initialzing of driver is finished well, but after that, netkvm failed on ParaNdisCX::SendControlMessage.
This function call is from ParaNdis6_OidRequest, and this mainly failed because when m_virtQueue.Kick is requested after AddBuf, Getbuf was always failed, so doing infinite loop things.

**Comment by YanVugenfirer** [comment]
Just as an experiment you can try to disable the control queue for the device. Add "ctrl_vq=off" to command line of virtio-net device.

**Comment by YanVugenfirer** [comment]
Can you publish the whole stack? From very quick glance there could be an issue with a code when control queue might be used, even if ctrl_vq is set to "off".

**Comment by YanVugenfirer** [comment]
Can you please post the whole stack, I want to see were exactly from ParaNdisCX:: SendControlMessage is called?

**Comment by wangmir** [comment]
Call stack is like this,

```
Ndis::BindEngine::UpdateBindingsWorkItem
Ndis::BindEngine::UpdateBindings
Ndis::BindEngine::Iterate
ndisBindProtocol
ndisBindNdis6Protocol
FlBindAdapter
FlpOpenAdapterComplete
ndisMOidRequest
ndisQueueOidRequest
KeExpandKernelStackAndCalloutInternal
ndisFDoOidRequestInternal
PcFilterRequest
NdisFOidRequest
ndisQueueOidRequest
KeExpandKernelStackAndCalloutInternal
ndisFDoIOidRequestInternal
LwfLowerOidRequest
NdisFOidRequest
ndisQueueOidRequest
ndisMDoOidRequset
ndisMInvokeOidRequest
ParaNdis6_OidRequest
ParaNdis_OnSetPacketFilter
ParaNdis_UpdateDeviceFilters
ParaNdis_DeviceFiltersUpdateRxMode
CParaNdisCX::SendControlMessage
```

So, when I check QEMU BE driver (hw/net/virtio-net.c), at virtio_net_handle_ctrl, virtqueue_pop just return NULL, so I continuously failed to get virtqueue cmd after kick I think.

I'll look up deeply too.

Thanks,

**Comment by wangmir** [comment]
After turning off ctrl_vq, installation is successfully done with no error, but after that ip, MAC was not set at all at network adaptor, so network was not available.

I don't know about what ctrl_vq is, but is this ctrl_vq for handling configuration and setting?

**Comment by YanVugenfirer** [comment]
I think you need to look at the host side as well to see what is happening and why Mac update stuck

**Comment by wangmir** [comment]
I found that when virtqueue_kick is requested at SendControlMessage, it seems used index is not properly modified at QEMU (host) side despite of appropriate modification in guest driver. 

So, I doubt about cache coherent problem because the system only send physical memory address, not virtual address, and arm or aarch64 architecture don't guarantee cache coherent problem at DMA transfer (it's not actual DMA transfer, but because they only share physical address, not virtual address, so..)

In this manner, I think the meaning of MS's comment that NdisMAllocateSharedMemory is not for aarch64, is because NdisMAllocateSharedMemory does not support cache flush or no cache options.

I'll try other memory allocations to handle this problem for next.

**Comment by YanVugenfirer** [comment]
You can try using MmAllocateContiguousMemorySpecifyCache
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmallocatecontiguousmemoryspecifycache

**Comment by wangmir** [comment]
I actually tried MmAllocateContiguousMemorySpecifyCache, but it was failed (I don't know the reason exactly, but it failed too), but after that, I tried MMAllocateContigousMemory with KeIoFlushBuffers and KeMemoryBarrier, and it works. Count increases properly, and CX works fine too. 

So, currently I successfully enable to install the virtio-net, 
but still I have a problem with setting MAC address with arp protocol. I checked that QEMU received the data, but it didn't be treated as normal. So, I am currently tracking down this problem.

At this point, I think it can be endian issue, or structure packing issue, but I don't know exact reason. If I find any clue, I'll post it.

**Comment by wangmir** [comment]
I successfully installed NetKVM driver on aarch64, the problem on arp protocol was because of aligning up of the header size. So, I let the size of header as usual, and only alignup the size calculation on VQ allocation, and after that I could see the network connection between host and guest.

**Comment by YanVugenfirer** [comment]
Can you post your changes please?

Thanks,
Yan.

**Comment by wangmir** [comment]
I'm looking for contribution way from here because I need permission for that.

After that I'll do PR for that.

Thanks,

**Comment by driver1998** [comment]
I am testing the driver and BSoDs on the exact same spot. 
```
*** Fatal System Error: 0x0000007e
                       (0xFFFFFFFF80000002,0xFFFFD4802EBFF00C,0xFFFFFD0A3A504FE8,0xFFFFFD0A3A504BE0)
```
Are there any updates about this issue?

**Comment by ybendito** [comment]
[netkvm-ARM64.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/2863766/netkvm-ARM64.zip)
Attached driver should fix the problem with misalignment mentioned in previous message. Please check whether this solves all problems or we have next one. Thanks in advance.

**Comment by hitmoon** [comment]
@ybendito 
> netkvm-ARM64.zip
Attached driver should fix the problem with misalignment mentioned in previous message. Please check whether this solves all problems or we have next one. Thanks in advance.

I install this driver to windows 10 arm64 build (build 18865.rs_prerelease.190322-1503) ,  it also leads to a blue screen as bellow:
![2019-04-11 16-12-54屏幕截图](https://user-images.githubusercontent.com/3981296/55941821-99a27280-5c75-11e9-8615-5ba6c69b5a94.png)

Is there any updates?

**Comment by ybendito** [comment]
@hitmoon we are still working on that

**Comment by hitmoon** [comment]
@ybendito  Ok, I will wait. Thank you!

**Comment by hitmoon** [comment]
@ybendito Any progress ?
