### ISSUE TITLE
Windows WFP API FwpmTransactionCommit() will hung when this virtio driver runs on 64 bits Windows 8 and Windows 2012

### ISSUE THREAD

**Issue by huangyong5** [virtio-win/kvm-guest-drivers-windows#326]
We are developping a windows network filter driver which is based on microsoft WFP framework,  we find that the WFP API FwpmTransactionCommit() will hung if this virtio driver is running. We tested on  64 bits Windows 2008, Windows 8, Windows 2012 and Windows 10,  the problem only happened on windows 8 and Windows 2012
   We also tried another sample on https://github.com/Microsoft/Windows-driver-samples/tree/master/network/trans/inspect , the problem also happened when calling the WFP API FwpmTransactionCommit()
   Could anybody help to investigate and resolve the problem?
   If you need more information, please kindly contact with me by the mail huangyong5@asiainfo-sec.com

**Comment by sameehj** [comment]
Sure,
First, which driver version are you using?

Can you please do the following steps:
* Reproduce the issue
* Connect to the Qemu monitor and run the nmi command, A BSOD should occur in the guest.
* Copy the MEMORY.dmp file from c:/windows, compress it and share it with me through some file share.
* Provide me  with the NetKVM driver used along with the pdb file and I'll look into it.

Thanks!

**Comment by huangyong5** [comment]
hi, sameehj
     thank you very much for the help, I upgrade the netkvm.sys to the latest stable build, and the problem is resolved.
     
![image](https://user-images.githubusercontent.com/42603774/44709317-ea48cf00-aadb-11e8-8096-42fe4adfc628.png)
