### ISSUE TITLE
BALLOON install problems on Vista and WS 2008 original

### ISSUE THREAD

**Issue by jeremygaither** [virtio-win/kvm-guest-drivers-windows#33]
I am unable to install the balloon.sys driver automatically with an unattended setup file on plain Windows VISTA and Windows Server 2008 (original) with no service packs. I also receive errors when attempting to manually install the driver using pnputil.

Test guest: Windows Server 2008 (original, no SP)
Driver Source: virtio-win-0.1-81.iso

error log during unattended setup:
![screenshot 2015-03-18 16 55 07](https://cloud.githubusercontent.com/assets/8432406/6720922/0dd3b736-cd96-11e4-8cc4-f6ab01e1b88e.png)

Errors when installing manually:
![screenshot 2015-03-18 17 38 16](https://cloud.githubusercontent.com/assets/8432406/6720955/578d9e1e-cd96-11e4-97f3-e9faf1adcf03.png)
![screenshot 2015-03-18 17 38 50](https://cloud.githubusercontent.com/assets/8432406/6720957/5e1b6c84-cd96-11e4-90dc-0f06249fac00.png)

**Comment by YanVugenfirer** [comment]
Hi,

Let's separate it into two issues.

1. WDF update

1.1. There is a required reboot because inbox KMDF is older than the one that is supplied with the driver. This is not a problem (although additional reboot is annoying). You might want to install newer version of KMDF before drivers installation to offset this reboot from driver installation process http://www.microsoft.com/en-us/download/details.aspx?id=38423.

1.2. There is also an error message in the log that is partially cut so I cannot understand its meaning. Can you paste the text as is?

2. No "signature" warning. 
The community released drivers are drivers without MS signature (without WHQL certification). This is not an error, just a warning from MS.
You can try to use "dpinst" and specify legacy options. Just add depicts.exe to the specific OS and platform directory, INF file should be already customised to work with it.
https://msdn.microsoft.com/en-us/library/windows/hardware/ff544775(v=vs.85).aspx

Best regards,
Yan.

**Comment by jeremygaither** [comment]
1.1: Is KMDF 1.9 required for the balloon driver to operate, or could it be
compiled with the Vista WDK against KMDF 1.7? I think the required reboot
will prevent automatic unattended installation, unless there is a trick I
don't know about. I have tried it in the WinPEDriver folder, in the PNP
WinPE setup phase, and NonPE phase. This works fine on anything beyond
Vista and WS2008. I think it even works on Vista SP1; I will verify...

1.2: I will attempt to get full logs and attach them here.

2: These indeed are two separate issues. My apologies for combining them. I
will look further at options for installing after Windows Setup, as
suggested, and open a separate issue if needed.

Thanks!

On Mar 19, 2015, at 7:28 AM, Yan Vugenfirer <notifications@github.com>
wrote:

Hi,

Let's separate it into two issues.

   1. WDF update

1.1. There is a required reboot because inbox KMDF is older than the one
that is supplied with the driver. This is not a problem (although
additional reboot is annoying). You might want to install newer version of
KMDF before drivers installation to offset this reboot from driver
installation process
http://www.microsoft.com/en-us/download/details.aspx?id=38423.

1.2. There is also an error message in the log that is partially cut so I
cannot understand its meaning. Can you paste the text as is?

   1. No "signature" warning. The community released drivers are drivers
   without MS signature (without WHQL certification). This is not an error,
   just a warning from MS. You can try to use "dpinst" and specify legacy
   options. Just add depicts.exe to the specific OS and platform directory,
   INF file should be already customised to work with it.
   https://msdn.microsoft.com/en-us/library/windows/hardware/ff544775(v=vs.85).aspx

Best regards,
Yan.

—
Reply to this email directly or view it on GitHub
<https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/33#issuecomment-83536598>
.

**Comment by jeremygaither** [comment]
The cropped error is reporting the KMDF installer is not in the temp
folder. I verified that file is never extracted into the temp folder.

**Comment by YanVugenfirer** [comment]
1.1 I think you can try and compile with 1.7. Balloon driver is very simple and I don't think we use any specific APIs from 1.9. Also you can try and install the version for XP\2003 (save the compilation and build configuration time).

**Comment by YanVugenfirer** [comment]
I am wondering what happened after reboot - did you get working driver?

On Thu, Mar 19, 2015 at 2:43 PM, Jeremy Gaither <notifications@github.com>
wrote:

> The cropped error is reporting the KMDF installer is not in the temp
> folder. I verified that file is never extracted into the temp folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/33#issuecomment-83539856>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by jeremygaither** [comment]
No, the error prevents windows setup from completing.

It never installed, even after reboot, when installing manually after
setup using pnputil, either.
---

**Comment by YanVugenfirer** [comment]
Is it not installed even if you click on "Install this driver software
anyway"?

On Thu, Mar 19, 2015 at 2:50 PM, Jeremy Gaither <notifications@github.com>
wrote:

> No, the error prevents windows setup from completing.
>
> It never installed, even after reboot, when installing manually after
> setup using pnputil, either.
> ---
> > On Mar 19, 2015, at 7:45 AM, Yan Vugenfirer <notifications@github.com>
> wrote:
> >
> > I am wondering what happened after reboot - did you get working driver?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/33#issuecomment-83543455>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by jeremygaither** [comment]
Correct.

**Comment by YanVugenfirer** [comment]
Adding Gal to the thread (he is responsible for the ballon driver).

On Thu, Mar 19, 2015 at 2:55 PM, Jeremy Gaither <notifications@github.com>
wrote:

> Correct.
>
>
>
> > On Mar 19, 2015, at 7:54 AM, Yan Vugenfirer <notifications@github.com>
> wrote:
> >
> > Is it not installed even if you click on "Install this driver software
> > anyway"?
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/33#issuecomment-83545485>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by hammerg** [comment]
AFAIK it is not possible to install WDF drivers during unattended install before Windows installation is completed. Installation of WDF drivers requires the "Windows Update Standalone Installer" (wusa.exe) and this file is not existing at that time.

You should probably use pnputil.exe to install the driver after Windows installation is completed.

**Comment by sameehj** [comment]
Hi @jeremygaither ,

We are currently in a process of closing all github's issues that have been resolved or expired. I'm currently closing this issue, please reopen the issue or else open a new issue if needed.
