### ISSUE TITLE
Windows Server 2019

### ISSUE THREAD

**Issue by excel-gg** [virtio-win/kvm-guest-drivers-windows#335]
Windows Server 2019 will be released soon.
When will these drivers support it? Each driver from the download on fedorapeople.org has a `2k16` folder for Windows Server 2016. Will be there be a `2k19` folder soon?

**Comment by YanVugenfirer** [comment]
Hi,

Windows 10 drivers were tested and found compatible for Windows Server 2019. So, for now, you should use the drivers from Win10 or 2k16 folder.
For next package releases, we will add Windows Server 2019 separate folder (but for now those will be the same Windows 10 drivers).

Best regards,
Ysan.

**Comment by excel-gg** [comment]
Hi guys, ok, thanks.
FYI, it's now officially released: https://cloudblogs.microsoft.com/windowsserver/2018/10/02/windows-server-2019-now-generally-available/

**Comment by YanVugenfirer** [comment]
Thanks! We will add it to our HCK-CI project soon.
