### ISSUE TITLE
Several WHCK tests broken due to change of reported speed

### ISSUE THREAD

**Issue by ybendito** [virtio-win/kvm-guest-drivers-windows#337]
I think this commit is incomplete, need to change it consistently and correctly in every place when the speed is reported regardless whether speed configuration is provided in qemu command line. This presents regression from previous state.

I've no problem to do that, just let me know.

https://github.com/virtio-win/kvm-guest-drivers-windows/commit/1adaf6ffb21d37aad8e2c2f8a55491d49cd668a5#diff-d8652d874c2be0c4eb0b8bf1bf90da59

**Comment by YanVugenfirer** [comment]
Please do.

**Comment by YanVugenfirer** [comment]
Fixed by #340
