### ISSUE TITLE
qemu-system-x86_64: virtio: zero sized buffers are not allowed

### ISSUE THREAD

**Issue by di-le** [virtio-win/kvm-guest-drivers-windows#342]
Hallo,

I use a debian testing with qemu and Windows 10 with the last Red Hat VirtIO Ethernet Adapter and Red Hat VirtIO SCSI pass-throug controller.

Currently debian testing has a qemu of 1:2.12+dfsg-3  and I became the follow error at start of the virtual machine:

qemu-system-x86_64: virtio: zero sized buffers are not allowed

My virtual machine has a status of October 2017. Without Windows Updates, the error does not occur, as soon as I import the Windows Updates it comes to this problem. If I use an older version of qemu, I can also do the Windows updates without any problems. The last Debian release with which I do not have this problem is the QEMU emulator version 2.11.0 (Debian 1: 2.11+dfsg-1)

Thanks for your help und sorry for my english

dile

**Comment by YanVugenfirer** [comment]
Hello,

Thank you for the report.

1. Please send us the version of the drivers 

2. Try to bring up windows after error occurs (change network device to e1000 for example and storage to IDE) and check if the driver version changed

Thanks,
Yan.

**Comment by di-le** [comment]
I've tested the following:

Today's Windows 10 boots with qemu 2.11+dfsg-1
The following drivers are installed:
Red Hat virtIO Ethernat Adapter
08/03/2018
100.76.104.16000
Red Hat VirtIO SCSI pass-through controller
08/03/2018
100.76.104.16000

I've updated qemu to 2.12+dfsg-3 now
When you first started Windows, the following error occurred:
qemu-system-x86_64: Guest says index 16778 is available

In the other try came then each:
qemu-system-x86_64: virtio: zero sized buffers are not allowed

I then changed the hard drive from Windows10 to -device ide-drive and Windows 10 boots normally again.
In the Device Manager, the version of the Red Hat VirtIO SCSI pass-through controller and Red Hat virtIO Ethernet Adapter is unchanged.

**Comment by YanVugenfirer** [comment]
1. Please post QEMU command line

2. I am confused about this sentence: "My virtual machine has a status of October 2017". Is it a VM from October 2017? But then how has it 160 driver version?

**Comment by di-le** [comment]
Here is my qemu command line:

`QEMU_AUDIO_DRV=pa taskset -c 0,1,2 qemu-system-x86_64 -enable-kvm -cpu host,kvm=off,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_vendor_id=whatever -m 8024 \
-D /tmp/qemu-debug-log \
-smp 3,sockets=1,cores=3,threads=1 \
-rtc base=localtime \
-vga none \
-drive if=pflash,format=raw,readonly,file=/usr/share/edk2.git/windows10/ovmf-x64/OVMF_CODE-pure-efi.fd \
-drive if=pflash,format=raw,file=/usr/share/edk2.git/windows10/ovmf-x64/OVMF_VARS-pure-efi.fd \
-nographic \
-device vfio-pci,host=01:00.0,x-vga=on -device vfio-pci,host=01:00.1 \
-device virtio-scsi-pci,id=scsi \
-drive file=/var/lib/libvirt/images/windows10.ovl,id=disk,format=qcow2,if=none -device scsi-hd,drive=disk \
-drive file=/var/lib/libvirt/images/home.img,id=disk1,format=qcow2,if=none -device scsi-hd,drive=disk1 \
-net nic,model=virtio,macaddr=52:54:00:12:34:56 -net tap \
-usb -device usb-host,vendorid=0x0d8c,productid=0x0012 \
-usb -device usb-host,vendorid=0x046d,productid=0xc29a \
-usb -device usb-host,vendorid=0x03eb,productid=0x0002 \
-usb -device usb-host,vendorid=0x054c,productid=0x0268 \
-usb -device usb-host,vendorid=0x0a12,productid=0x0001 \
-usb -device usb-host,vendorid=0x040b,productid=0x2019 \`

I have a Windows10 with a snapshot from october 2017 on which I can reset it. Of course, in this snapshot an older version of the driver is installed. I have already tested different driver versions.

When I disable the Windows10 updates from my snapshot of October 2017, the Virtio drivers also work with the qemu 1: 2.12+dfsg-3. As soon as I make the Windows updates, it comes to the error. I have already tested this with different driver versions. I installed Debian testing in May 2018 (previously Stable) and have been testing this problem since the beginning of this issue.

As a workaround, I currently use the older qemu version with which everything works without problems. There, the updates are all up to date and I have also installed more recent virtio drivers. Yesterday I simply used this image and started it under the newer qemu version.

**Comment by sameehj** [comment]
From what I understand so far your issues seems to be with the virtio-scsi that was caused by a new version of the Windows drivers on qemu version > 2.11. You can find the error message you are facing from qemu in the following document:

https://github.com/qemu/qemu/blob/784c2e4f232adf5ef47a84a262ec72a07d068d6a/hw/virtio/virtio.c#L744

I suggest that you compile your own qemu from upstream and try and reproduce with it. You can run it using gdb, use qemu's tracing mechanism or simply add printf around.

**Comment by di-le** [comment]
Hello,

I found the cause of the error. With a newer version, I had the error much more frequently and completely independently of the Windows Update. Even a reinstallation did not work and brought the error message. Because of the fact that I could reproduce the error better, I have taken out more and more components from the virtual machine and tested what it is related. It was ultimately the UEFI OVMF. I had a very old version and updated it. Since then I have not gotten the mistake anymore.

Thank you and nice greetings
