### ISSUE TITLE
ivshmem not support win7

### ISSUE THREAD

**Issue by zhongguo1987** [virtio-win/kvm-guest-drivers-windows#349]
when use ivshmem device,win7 not work,Following chart:
   
![image](https://user-images.githubusercontent.com/3292981/49267217-58fb4700-f494-11e8-9c6f-a579610b15ac.png)

**My environment is**:
    host  :centos 7.5
    qemu: qemu-kvm-ev-2.12.0
    guest:  Windows 7 Ultimate SP1
            gueset   xml  configure :
![image](https://user-images.githubusercontent.com/3292981/49267177-281b1200-f494-11e8-8f33-4ff90f76c537.png)
     ivshmem-server:use qemu-kvm-ev-2.12.0 Compile ivshmem-server,use chart:
     
![image](https://user-images.githubusercontent.com/3292981/49267302-c0b19200-f494-11e8-94d2-bd8b33eef39f.png)
       
       why not work?  Is it an environmental problem or is it not supported by itself?

**Comment by vrozenfe** [comment]
Does it work with "-device ivshmem-plain" ?
Can you post the qemu command line?

Thanks,
Vadim.

**Comment by zhonggguo1987** [comment]
>           Does it work with "-device ivshmem-plain" ?
> Can you post the qemu command line?
> Thanks,
> Vadim.

this is win7.xml
[win7.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/2646918/win7.zip)

1. when device is ivshmem-plain ,the device can be driven in Win7,
but the ivshmem-test project will not succeed in sending DeviceIoControl IOCTL_IVSHMEM_REQUEST_MMAP.
2. when device is ivshmem-doorbell,the device can't be driven in Win7.
so,ivshmem device, How should it be used?
Thanks.

**Comment by vrozenfe** [comment]
- I will check what can be wrong with IOCTL_IVSHMEM_REQUEST_MMAP on Win7
- ivshmem-doorbell at the moment is a kind of unsupported configuration, I would say. If you can, please try using ivshmem-plain instead.

**Comment by kingoverworld** [comment]
My environment is:
qemu: qemu-kvm-ev-2.12.0
guest: Windows 7 Ultimate SP1

It seems to work fine. When some data are written to the map buffer by ivshmem-test  in win7, The data from  nahani in centos7 are not same with guest. Why?

**Comment by kingoverworld** [comment]
My environment is:
qemu: qemu-kvm-ev-2.12.0
guest: Windows 7 Ultimate SP1

It seems to work fine. When some data are written to the map buffer by ivshmem-test in win7, The data from nahani in centos7 are not same with guest. Why?

Thanks!

**Comment by vrozenfe** [comment]
Can you post the data from the both sides to see the difference?

Thanks,
Vadim.

**Comment by kingoverworld** [comment]
My environment is:
host: centos7.5
qemu: 3.1.0
guest: win7
guest driver: ivshmem in kvm-guest-drivers-windows

1. qemu command in host:

./qemu-system-x86_64 -M q35 -no-user-config -nodefaults -m 4096M -smp 2,sockets=1,cores=2,threads=1 -spice port=5902,password=123 -drive file=/home/img/win7k1.img,if=none,id=drive-virtio-disk0,format=qcow2,cache=none,werror=stop,rerror=stop -no-hpet -device virtio-blk-pci,scsi=off,bus=pcie.0,addr=0xa,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -net nic,macaddr=20:04:0f:e5:68:66 -net tap -vga qxl -name guest=test3 -device virtio-serial-pci,id=virtio-serial0,max_ports=16,bus=pcie.0,addr=0x5  -device ivshmem-plain,memdev=ivshmem,bus=pcie.0 -object memory-backend-file,id=ivshmem,share=on,mem-path=/dev/shm/ivshmem_wang1.2,size=32M -enable-kvm 

And then start qemu , it seems to work  without any error!

2. driver in guest OS for win7:

![ivshmem](https://user-images.githubusercontent.com/39479310/55297516-5536fb80-5459-11e9-8190-5792f98389d0.png)

When run the ivshmem-test, it is OK!

3. problems:
1) When I paste some data into /dev/shm/ivshmem_wang1.2,  the data  from map_ptr by ivshmem-test are not diffrent in guest. As the similar way, the data in host are not same with guest too!

2) I change vm as win10, and  repeat above. All OK! 

4. conclusion:
Ivshmem driver for win7 maybe have  bugs!

Thank you!

**Comment by kingoverworld** [comment]
By the way, whatever are copied into /dev/shm/ivshmem_wang1.2, random data by ivshmem-test seem to be random numbers.  Even though I clear the map.ptr as zero by memset(map.ptr, 0xAA, map.size) in guest,  the data from /dev/shm/ivshmem_wang1.2 in host are not changed too. I infer map.ptr in guest is not share same memory address with /dev/shm/ivshmem_wang1.2 in host.

**Comment by h1z1** [comment]
FWIW Qemu 4 has dropped ivshmem:

https://wiki.qemu.org/ChangeLog/4.0:

- The legacy "ivshmem" device has been removed. Use "ivshmem-doorbell" or "ivshmem-plain" instead.

**Comment by Vaporeon** [comment]
ivshmem-plain still seems broken on Windows 7.
The project here:https://github.com/duncanthrax/scream will not run under windows 7 when trying to use it.

**Comment by mirh** [comment]
Possibly fixed in #445

**Comment by idarlund** [comment]
Support for Windows 7 ended on January 14, 2020.
https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information

**Comment by Vaporeon** [comment]
I'm not sure why that matters.
Some people have access to ESU support and even without that there can be good reason to run an unsupported OS inside a virtual environment without external networking for compatibility reasons.

**Comment by YanVugenfirer** [comment]
We are stopping the support of Windows 7 in master branch.

**Comment by Vaporeon** [comment]
Very disappointing, the fact Windows 7 is out of support is a prime reason to run/support it on Qemu/KVM.
