### ISSUE TITLE
virtio-stor: 0 serial after init

### ISSUE THREAD

**Issue by andrewjj20** [virtio-win/kvm-guest-drivers-windows#362]
On some boots or drive hot plugs, Windows discovered the drive serial was '0'. This issue was discovered using a build of qemu-kvm-rhev-2.10.0-21.el7_5 with libvirt-3.9.0-14.el7_5. If the issue did not present itself on one boot or hot plug, approximately 1 - 5 reboot would reproduce. Also, after a reboot, a different set of drives may have '0' as the serial number.

**Comment by vrozenfe** [comment]
Thank you for reporting this issue.

Could you please provide a bit more information about how to reproduce the problem?
I particularly need to know the following information - Windows and viostor  driver versions, and initial qemu command line.

Best regards,
Vadim.
