### ISSUE TITLE
vioscsi (scsi-block) broken again against uas drive

### ISSUE THREAD

**Issue by tomty89** [virtio-win/kvm-guest-drivers-windows#364]
I am having problem passing-through uas (usb attached scsi) drive again with vioscsi (virtio-scsi-pci + scsi-block).

The latest working (iso) version appears to be 0.1.140. Neither 0.1.141 (stable) or 0.1.160 (latest) seem to work.

The problem is similar to #44, but instead of getting stuck at the drive loading stage, it stuck at the very beginning when the installation begins (first stage stuck at 0% with the drive's led blinking but without any I/O according to iostat).

I cannot kill qemu by Ctrl+C in this case either unless I unplug the drive after that. And after I replug the drive and check with `lsblk -f`, it appears that the formation of the smaller (Recovery and EFI) partition has been done, but that of the big main/system partition could not be done (FYR, the drive is 256GB).

The uas bridge support UNMAP->TRIM translation, if that could matter.

This is the full command I ran:
`qemu-system-x86_64 -enable-kvm -cpu host,kvm=off -smp cores=4 -m 8G -drive file=/dev/sdb,if=none,format=raw,cache=none,aio=native,id=sys -device virtio-scsi-pci -device scsi-block,drive=sys --bios /usr/share/ovmf/x64/OVMF_CODE.fd -rtc base=localtime -net nic -net bridge,br=bridge0 -drive file=/storage/17763.107.101029-1455.rs5_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso,media=cdrom -drive file=/storage/virtio-win-0.1.1XX.iso,media=cdrom`

**Comment by vrozenfe** [comment]
Hi Tom,
Could you pleas update https://bugzilla.redhat.com/show_bug.cgi?id=1277060 or open a new one to trace the issue?

Vadim.

**Comment by tomty89** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1662418 but cannot reproduce it anymore with any version of vioscsi, so closing both.
