### ISSUE TITLE
Inconsistent license BSD-2 vs BSD-3

### ISSUE THREAD

**Issue by darrenkenny** [virtio-win/kvm-guest-drivers-windows#369]
Looking at the source files in, for example, vioscsi/utils.c, the license there is BSD-3 Clause, but the vioscsi/LICENSE file contains the BSD-2 Clause -  where it is missing the 3rd clause as well as not having the numbering, etc as in the "official" formatting at:

   https://opensource.org/licenses/BSD-3-Clause

Which is it meant to be? BSD-2 Clause, or BSD-3 Clause?

Would it be acceptable to change all the LICENSE files to use the one linked to above and have
both the code and LICENSE file be consistently both BSD-3 Clause?

Thanks,

Darren.

**Comment by YanVugenfirer** [comment]
Hi Darren,

Thank you for bringing up the inconsistency. We are looking at the way to resolve it.

Best regards,
Yan.

**Comment by hammerg** [comment]
Hi Darren,

The license change approval was on the BSD-3 license (starting with commit 71405a22). We will fix the LICENSE files to solve the inconsistent. Although I need to ask for the reason why we have multiple files in each directory.

Thanks for pointing it out.

    Gal.

**Comment by YanVugenfirer** [comment]
Solved by #370
