### ISSUE TITLE
COPYRIGHT_CURRENT_YEAR at 2019

### ISSUE THREAD

**Issue by mcarabas** [virtio-win/kvm-guest-drivers-windows#371]
Hello,

COPYRIGHT_CURRENT_YEAR should be modified to 2019.

**Comment by mcarabas** [comment]
Author: Mihai Carabas <mihai.carabas@oracle.com>
Date:   Wed Feb 6 17:19:31 2019 +0200

    Tools: Driver.Vendor.props: current year to 2019

diff --git a/Tools/Driver.Vendor.props b/Tools/Driver.Vendor.props
index 6050b4d..f5e9847 100644
--- a/Tools/Driver.Vendor.props
+++ b/Tools/Driver.Vendor.props
@@ -17,7 +17,7 @@ Set $(Feature_AlwaysDefaultVendor) to false and set $(_VENDOR_) to override.
 <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <PropertyGroup>
     <_VENDOR_ Condition="'$(_VENDOR_)'=='' OR '$(Feature_AlwaysDefaultVendor)'!='false'">RHEL</_VENDOR_>
-    <COPYRIGHT_CURRENT_YEAR>2018</COPYRIGHT_CURRENT_YEAR>
+    <COPYRIGHT_CURRENT_YEAR>2019</COPYRIGHT_CURRENT_YEAR>
   </PropertyGroup>

   <PropertyGroup Condition="'$(TargetArch)'=='x86'">

**Comment by YanVugenfirer** [comment]
Solved by #372.

Thanks!
