### ISSUE TITLE
virtio-scsi - HLK 1809 "StorIO Testcase: gaps" for 2019 guests fails with "Caught std::exception: invalid stoi argument"

### ISSUE THREAD

**Issue by rob-scheepens** [virtio-win/kvm-guest-drivers-windows#376]
On HLK 1809, "StorIO Testcase: gaps" for 2019 guests fails with "Caught std::exception: invalid stoi argument". This is also documented in 
https://bugzilla.redhat.com/show_bug.cgi?id=1652422.

Since I expect an issue with the HLK tooling itself, I've also opened an issue with Microsoft on this, currently awaiting response from their side.

\Rob

**Comment by YanVugenfirer** [comment]
"Caught std::exception: invalid stoi argument" -  this error in Flush test was caused by unfiled test parameters.

**Comment by rob-scheepens** [comment]
Thanks for the quick response Yan. Which parameters did you use to get around this?

**Comment by YanVugenfirer** [comment]
In case of Flush test - it was the power unit IP. Then the test failed with a different error that could be filtered by errata.
I am not sure about this specific test what are the missing parameters, need to check documentation.

What's the full name of the test?

**Comment by rob-scheepens** [comment]
It's the Flush Test:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/15910576/53485943-83d64680-3a55-11e9-975a-48c831a2532d.png">
Failure log shows:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/15910576/53486032-a6685f80-3a55-11e9-806d-8c03b66d6d4f.png">
What if I don't have a power unit IP? Does it even make sense to have this parameter when testing on virtual machines?

**Comment by YanVugenfirer** [comment]
Apply to MS to get errata for this test.

**Comment by vrozenfe** [comment]
for your reference -
https://bugzilla.redhat.com/show_bug.cgi?id=1652422

**Comment by rob-scheepens** [comment]
We got a waiver from Microsoft and got the driver signed. Closing this now, thanks for the help @YanVugenfirer and @vrozenfe !

**Comment by YanVugenfirer** [comment]
Great!
