### ISSUE TITLE
Windows Server 2019 will not accept Win10/2k16 drivers

### ISSUE THREAD

**Issue by ahmedm** [virtio-win/kvm-guest-drivers-windows#377]
I've seen a couple of closed issues about Windows Server 2019 with the verdict that win10 drivers are fully compatible with Windows Server 2019
Well maybe if you try to force install *.inf files from inside windows? but you can't load the drivers from windows installation to be able to see the Virtio SCSI controller disk

![screenshot from 2019-03-08 03-24-12](https://user-images.githubusercontent.com/17982614/54000991-5f175880-4152-11e9-90ce-62f034dc1ee0.png)

**Comment by vrozenfe** [comment]
Could you please provide the following information 
- qemu version,
- qemu command line,
- virtio drivers and installation media origin - did you build them by yourself, or it is one of our builds available for download from fedoraproject site?

Thanks,
Vadim.

**Comment by ahmedm** [comment]
I'm using latest virtio-win-0.1.164.iso from fedoraproject site
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.164-1/

/usr/bin/qemu-system-x86_64 --version

```
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.10)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

virsh version --daemon
```
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Using API: QEMU 4.0.0
Running hypervisor: QEMU 2.11.1
Running against daemon: 4.0.0
```

Qemu CMD:

`qemu-system-x86_64 -enable-kvm -name guest=Windows,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-Windows/master-key.aes -machine pc-i440fx-bionic,accel=kvm,usb=off,vmport=off,dump-guest-core=off -cpu IvyBridge-IBRS,ss=on,vmx=on,movbe=on,hypervisor=on,arat=on,tsc_adjust=on,3dnowprefetch=on,ibpb=on,xsave=off,avx=off,f16c=off,fsgsbase=off,xsaveopt=off,hv_time,hv_relaxed,hv_vapic,hv_spinlocks=0x1fff -m 16384 -realtime mlock=off -smp 8,sockets=8,cores=1,threads=1 -uuid 2bcb3e45-a17d-4ed5-9f45-b7c62d1ee697 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-1-Windows/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device lsi,id=scsi0,bus=pci.0,addr=0x8 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -drive file=/dev/Storage-Pool/windows,format=raw,if=none,id=drive-scsi0-0-0,cache=none,aio=native -device scsi-hd,bus=scsi0.0,scsi-id=0,drive=drive-scsi0-0-0,id=scsi0-0-0,bootindex=1 -drive file=/var/lib/libvirt/images/17763.253.190108-0006.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso,format=raw,if=none,id=drive-ide0-0-1,readonly=on -device ide-cd,bus=ide.0,unit=1,drive=drive-ide0-0-1,id=ide0-0-1,bootindex=2 -drive file=/var/lib/libvirt/images/virtio-win-0.1.164.iso,format=raw,if=none,id=drive-ide0-1-0,readonly=on -device ide-cd,bus=ide.1,unit=0,drive=drive-ide0-1-0,id=ide0-1-0 -netdev tap,fd=25,id=hostnet0,vhost=on,vhostfd=27 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:09:5e:2c,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input2,bus=usb.0,port=1 -spice port=5900,addr=127.0.0.1,disable-ticketing,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x4 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x7 -msg timestamp=on`

**Comment by ahmedm** [comment]
That's weird I downloaded the 2019 eval iso again and virtio drivers are loading just fine now 
and I even noticed a change in the "loading files" progress bar you see when you start the installation
so maybe the issue was just a corrupt iso
