### ISSUE TITLE
Support for virtio-vsock

### ISSUE THREAD

**Issue by ning-yang** [virtio-win/kvm-guest-drivers-windows#378]
Hey, I am wondering what the current status on support virtio-vsock for Windows guest. Last thread I found is from https://www.spinics.net/lists/kvm/msg164263.html, indicating someone already started the work.

Do we have any update on the process? We are considering to use this device and may budget efforts on bringing the support to it. But we don't want to  step over any existing work and cause merge issues in the future.

**Comment by YanVugenfirer** [comment]
Hi,

We don't have immediate plans for vsock implementation, and current work was stalled.
So if you want to contribute the code, you are more than welcome.

**Comment by tomeuv** [comment]
> We don't have immediate plans for vsock implementation, and current work was stalled.
> So if you want to contribute the code, you are more than welcome.

Could you point to the existing work? I would like to contribute, but first I would need to know what remains to be done.

**Comment by YanVugenfirer** [comment]
@irudakov77 is doing the work on the subject. I am gradually merging his patches.
