### ISSUE TITLE
Windows 2008r2 guest network got unusable accidentally

### ISSUE THREAD

**Issue by dejunldejunl** [virtio-win/kvm-guest-drivers-windows#380]
Hi, everybody:
I got a guest network issue when using vhost-user + dpdk + win2008r2 image, most parts of vhost-user are coming from opensource ovs-2.7.0.
The issue is: win2008r2 guest vm can send packets to host backend, but host backend can't send pakcets to guest vm. It happens accidentally and I don't know how to trigger/reproduce it. When this issue happens, host backend shows some desc_vring[idx].len is 0, and reseting the guest NIC can solve the problem.
We have analyzed win2008r2 frontend and host backend driver, none of them will modify desc_vring[idx].len to zero except the initialization routine. We also captured the packets coming from/sending to the vm, and no special/huge TCP/UDP packets found. 
Any thoughts? Hope for your reply!

**Comment by YanVugenfirer** [comment]
Hello,

Can you try and record driver trace on the guest?
https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/NetKVM/Documentation/Tracing.md

https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/Documentation/Tracing.md

Thanks,
Yan.

**Comment by ybendito** [comment]
Closing the issue as there is no response. Please reopen if needed
