### ISSUE TITLE
Multitouch support

### ISSUE THREAD

**Issue by cagnulein** [virtio-win/kvm-guest-drivers-windows#383]
Is there any plan about adding Multitouch support to Windows guest on KVM?
Thanks

**Comment by YanVugenfirer** [comment]
I guess this is not something very complicated and might even work out of the box with the virtio-input driver.
But we don't have plans for now for the support and testing of multitouch support.

**Comment by ybendito** [comment]
If I'm not mistaken, real multitouch currently is not supported by vioinput. Miltitouch devices that emulate some of Windows gestures are supported, of course.

**Comment by vrozenfe** [comment]
It's probably highly depends on the use case and what kind of multi-touch digitizer device you are going to use, but in addition to virtio-input device (as Yan suggested before) you might be able to use HID (USB) device pass-through.

**Comment by ybendito** [comment]
@vrozenfe Multitouch devices are not always USB, often they are PCI devices with I2C HID

**Comment by cagnulein** [comment]
i'm planning to use 

Mar 20 10:30:15 kvm kernel: [    2.287986] input: DATA MODUL easyTOUCH as /devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.2/0003:7374:1278.0001/input/input9
Mar 20 10:30:15 kvm kernel: [    2.288095] hid-multitouch 0003:7374:1278.0001: input,hidraw0: USB HID v1.11 Device [DATA MODUL easyTOUCH] on usb-0000:00:14.0-5/input2

in this very moment my windows guest emulate a mouse and i can't install the virtio driver over the mouse driver on windows (it tells me that it's not designed for this operating system). Am i missing something?

**Comment by cagnulein** [comment]
> It's probably highly depends on the use case and what kind of multi-touch digitizer device you are going to use, but in addition to virtio-input device (as Yan suggested before) you might be able to use HID (USB) device pass-through.

i read that usb pass-through of HID devices is high discouraged because it's hard to give the device back to the host in case of needing. In my case i have several VMs and each one should need the multitouch support so i can't use PT.

**Comment by vrozenfe** [comment]
in this very moment my windows guest emulate a mouse and i can't install the virtio driver over the mouse driver on windows (it tells me that it's not designed for this operating system). Am i missing something?

Can it be that you are trying to install 32-bit driver on 64-bit OS?

**Comment by cagnulein** [comment]
> Can it be that you are trying to install 32-bit driver on 64-bit OS?
no i'm sure about that. I've already tried 32bit version and 64. I'm using Windows 10 64bit as guest

**Comment by vrozenfe** [comment]
@ybendito 
I always thought that I2C is mostly used by touchscreens.
Cheers,
Vadim.

**Comment by ybendito** [comment]
@cagnulein You should not install virtio driver over mouse driver. IIUC what you're doing, you can try to use something like: "-object input-linux,id=someid,evdev=/dev/input/{your eventdevice}",  but, of course this will attach the HID device to specific VM only.

@vrozenfe Yes, this is one of possible cases of multitouch on the host.

**Comment by cagnulein** [comment]
> @cagnulein You should not install virtio driver over mouse driver. IIUC what you're doing, you can try to use something like: "-object input-linux,id=someid,evdev=/dev/input/{your eventdevice}", but, of course this will attach the HID device to specific VM only.

i can't because i'm accessing the VM through VNC directly on the host and losing the touch from the host side means have no touch at all on the guest. I can't use dma-buf also because i still need access to host machine.

Just to recap the scenario:
- host with multitouch
- more guests with Windows 10 that require multitouch
- multitouch should be avaiable via VNC on the host through the guests

Is it possible?
Thanks for your time!

**Comment by cagnulein** [comment]
maybe i've solved using xfreerdp instead of vnc. The issue now is that FreeRDP isn't supported by Intel GVT

**Comment by cagnulein** [comment]
Ok i definutely solved my issue. I use dynamic attach-device feature of virsh to dinamically use the usb passthrough. In this way i can use vnc using Intel GVT!
