### ISSUE TITLE
Integrate with Coverity's security scanning?

### ISSUE THREAD

**Issue by darrenkenny** [virtio-win/kvm-guest-drivers-windows#384]
Hi,

Coverity hosts a service to perform security scans on open-source projects at:

- https://scan.coverity.com/

Other projects such as the Linux kernel and Qemu have projects integrated there,
so I'm wondering if you have ever considered also adding this project? It says that
it supports VS2017, and I've seen references to some earlier versions in the Community
pages there.

(I noticed that the project is on the SemmLE LGTM.com site, but AFAICS that is restricted
to sources that compile directly on Linux only, but could be wrong)

Thanks,

Darren.

**Comment by YanVugenfirer** [comment]
Hi,

Sound like a good idea. I will look into it.

Thanks,
Yan.

**Comment by YanVugenfirer** [comment]
I was able to build the drivers with Coverity and submitted the build logs for analysis.
Looking now on how to automate the submissions.

**Comment by YanVugenfirer** [comment]
The usage is straight forward.

1. Download the agent: https://scan.coverity.com/download?tab=cxx (from right side panel download Windows 64bit version).

2. Add Coverity bin directory to Windows path  

3. No need to configure compilers

4. Run `cov-build --dir cov-int build_AllNoSdv.bat`

**Comment by YanVugenfirer** [comment]
@Basils we can try adding Coverty check to the weekly CI

**Comment by YanVugenfirer** [comment]
Added to internal CI
