### ISSUE TITLE
vioinput high DPI mouse rubberbanding

### ISSUE THREAD

**Issue by tristanpemble** [virtio-win/kvm-guest-drivers-windows#385]
I find this issue hard to describe so I [made a video](https://streamable.com/yq224) to demonstrate.

Essentially, with my mouse set to 1600 DPI, when I move it quickly enough, the mouse will "rubber band" left and right, instead of moving only rightward.

- Host running Arch with Wayland/SwayWM
- My mouse is a Zowie EC2-A and it is set to 1600 DPI / 500hz polling
- In the video I set the Windows mouse sensitivity to the lowest it can go to more clearly demonstrate the issue

I've tried several configurations, and this only happens when I am using the virtio device with evdev, so I believe it is related to this driver.

- It isn't happening on the host environment
- It does not happen if I pass through the USB device itself

**Comment by tristanpemble** [comment]
changing the libvirt input from "mouse" to "tablet" fixes the mouse movement (but breaks mouse clicks etc being in absolute movement mode)

**Comment by ybendito** [comment]
Thank you for the report. If I understand correctly the device is able to work with different DPI settings. Several questions:
1. How exactly you set the mouse resolution? With which resolution setting the mouse works as expected?
2. Can you please provide 'evtest' output (supported events and properties) for this event device when it is in high DPI mode (will not work correctly) and in other mode(will work correctly)?
3. What is qemu command line parameters related to the input device? What is the diff between 'libvirt' input 'mouse' and 'tablet'?
Thanks

**Comment by tristanpemble** [comment]
there's been a new development. [I can set the mouse to different polling rates](https://zowie.benq.com/en/support/faqlist/application/faq003.html). as you lower the polling rate, the problem becomes more easily reproducible, and I can reproduce at the lowest DPI. at the highest polling rate, it becomes more difficult to reproduce, and is only reproducible at higher mouse speed on higher DPIs.

here's a totally subjective table of the **speed of mouse movement** required for reproducibility. `n/r` means not reproducible, i.e. I couldn't make move my arm fast enough to do it.

|          | 125hz  | 500hz  | 1000hz |
|----------|--------|--------|--------|
| 400 dpi  | high   | n/r    | n/r    |
| 800 dpi  | medium | high   | n/r    |
| 1600 dpi | low    | medium | high   |
| 3200 dpi | lowest | low    | medium |
---
1. The mouse has a button on the bottom that changes DPI, with 400/800/1600/3200 options.
2. I chose to do the two extremes for evtest:
   - [400 dpi @ 1000hz](https://gist.github.com/tristanpemble/ec1c7de47a4dded0575c65f2a33aeb05) being the most difficult/impossible to reproduce
   - [3200 dpi @ 125hz](https://gist.github.com/tristanpemble/6ba718017abb06acfa96029e7650bbc6) being the easiest to reproduce
3. This is how I can reproduce it:
   ```
   -device virtio-mouse-pci,id=input2,bus=pci.0,addr=0xb \
   -object input-linux,id=mouse1,evdev=/dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse \
   ```
   and I noticed that movement when defining it as a tablet does not reproduce in any case:
   ```
   -device virtio-tablet-pci,id=input2,bus=pci.0,addr=0xb \
   -object input-linux,id=mouse1,evdev=/dev/input/by-id/usb-Kingsis_Peripherals_ZOWIE_Gaming_mouse-event-mouse \
   ```

I also tried adding an entry to local HWDB [as described here](http://who-t.blogspot.com/2014/12/building-a-dpi-database-for-mice.html) and saw no change in behavior.

```
~ λ udevadm info /dev/input/event3 | grep MOUSE_DPI
E: MOUSE_DPI=400@500 800@500 1600@500 3200@500
```
---

I know basically nothing about mouse drivers, libinput or evdev. however, given the large differences in event values in the output I am seeing, and the sort of "oscillating" behavior of the mouse when it is happening, this feels like some kind of overflow error.

**Comment by ybendito** [comment]
@tristanpemble Can you please provide the output of 'evtest /dev/input/event3'?

**Comment by tristanpemble** [comment]
yep I provided in above:
https://gist.github.com/tristanpemble/ec1c7de47a4dded0575c65f2a33aeb05
https://gist.github.com/tristanpemble/6ba718017abb06acfa96029e7650bbc6

**Comment by tristanpemble** [comment]
yes, I believe the values are overflowing at this [typecast to UCHAR](https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/vioinput/sys/HidMouse.c#L111)

**Comment by mbinns** [comment]
Hey I just want to jump in on this thread and comment I ran into the same issue, and @tristanpemble DPI to polling rate table seemed to line up with my results as well

**Comment by ybendito** [comment]
[win8-64-fixed.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/3922096/win8-64-fixed.zip)
Finally getting to it (better than never)
Please confirm the attached driver solves the problem (test mode required to install it, i.e. "bcdedit /set testsigning on" + reboot)

**Comment by ybendito** [comment]
the fix was released in build 175, please reopen if needed

**Comment by Boris-Barboris** [comment]
I would like to ask for a re-open. The current fix is simply clamping the input, but the correct solution would not lose the relative input information. The implementation should probably generate multiple HID events (with some sane upper limit) for such an overflow case.
Since UCHAR is windows-specific (HID) limitation, I think doing it on hypervisor/libinput level would not be quite right.
