### ISSUE TITLE
virtio-netkvm: HLK 1809 "RebootForDeviceRecovery::RebootForDeviceRecovery_Test" fails

### ISSUE THREAD

**Issue by rob-scheepens** [virtio-win/kvm-guest-drivers-windows#386]
Test result shows:
```
Message 4/3/2019 10:13:30.520 AM WDTF_TARGETS : Target: Nutanix VirtIO Ethernet Adapter PCI\VEN_1AF4&DEV_1000&SUBSYS_00011AF4&REV_00\3&13C0B0C5&0&18 WexTraceInfo ThreadId=6864 ProcessId=3868 TimeStamp=185157293303 LogSessionId=1 
 
Error 4/3/2019 10:13:30.521 AM WDTF_TEST : Found a device that has a non-zero problem code or is phantom. Logging device info. WexTraceInfo ThreadId=6864 ProcessId=3868 TimeStamp=185157303167 LogSessionId=1  
 
File:    Line: -1 
Error Type:    
Error Code:   0x0 
Error Text:   Error 0x00000000 
```
Have you seen this before? This is with latest filters applied (https://docs.microsoft.com/en-us/windows-hardware/test/hlk/user/windows-hardware-lab-kit-filters).

**Comment by YanVugenfirer** [comment]
No. What test is it?

BTW: PCI\VEN_1AF4&DEV_1000&SUBSYS_00011AF4 - you should change subsystem vendor ID for your device. Otherwise, you are submitting certification for the device that is registered on Red Hat.

**Comment by rob-scheepens** [comment]
The actual test is https://docs.microsoft.com/en-us/windows-hardware/test/hlk/testref/ff5f2837-310a-4448-8f79-580c83faa96e. Could you run this as well and see what result you get?

**Comment by YanVugenfirer** [comment]
As far as I see CHAOS was filtered out on our setup. 

I am going to double check it.

**Comment by rob-scheepens** [comment]
Thanks, I've also filed https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/2518/feedback/wits/Bugs/177509 with Microsoft since it seems strange to get an error when the actual error code is 0.

**Comment by YanVugenfirer** [comment]
Latest results:
https://www.dropbox.com/sh/xe01q0kc262qj3c/AAD-XlRq2JBCTOWF7-cMRbVla?dl=0&lst=&preview=logs.txt

**Comment by YanVugenfirer** [comment]
BTW: is it Windows Server 2019 or one of the Windows 10 flavors?

**Comment by rob-scheepens** [comment]
This is Server 2019.

Op 4 apr. 2019 om 14:59 heeft Yan Vugenfirer <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


BTW: is it Windows Server 2019 or one of the Windows 10 flavors?

**Comment by rob-scheepens** [comment]
After applying Playlist HLK Version 1809 CompatPlaylist x64 Server the CHAOS tests are indeed filtered out. I'll provide the failed hlkx to Microsoft for further debugging.
