### ISSUE TITLE
windows server 2012 iometer get io error when virtio-scsi driver

### ISSUE THREAD

**Issue by Macrosan-luo** [virtio-win/kvm-guest-drivers-windows#403]
![image](https://user-images.githubusercontent.com/52910828/61202631-a0c89900-a71a-11e9-88e7-c1948baded2d.png)

So many io retry，and iometer get io errors, but vhost scsi in storage doesn't  have any abnormal messages, even no io timeout, anyone who has seen this？

![image](https://user-images.githubusercontent.com/52910828/61203215-52b49500-a71c-11e9-8c44-f53bac623c46.png)

**Comment by vrozenfe** [comment]
Event 153 usually  indicates that a request was timed out in the adapter. IIUC you are using SAN, right. Please make sure that it works properly, otherwise every time when it takes more 30 sec to complete a request storport will trigger an error.

Best,
Vadim.

**Comment by Macrosan-luo** [comment]
Thank you so much! It‘s true that there is something wrong with the storage，I have checked it out.

Best,
MacroSAN, Luo.
