### ISSUE TITLE
[Announcement] Installers repository

### ISSUE THREAD

**Issue by YanVugenfirer** [virtio-win/kvm-guest-drivers-windows#404]
Hello All,

We have a new repository under virtio-win organisation with drivers and guest tools installers:
https://github.com/virtio-win/virtio-win-guest-tools-installer

Huge thanks to @Gal-Zaidman!

Best regards,
Yan.

**Comment by rgl** [comment]
Should https://github.com/crobinso/virtio-win-pkg-scripts also be in the virtio-win organisation?

**Comment by crobinso** [comment]
@rgl yes I think that will happen sometime soon, we are working out details of transferring maintainership of the packaging, moving the repo can be part of that
