### ISSUE TITLE
Balloon memory statistics always are not available

### ISSUE THREAD

**Issue by xs3c** [virtio-win/kvm-guest-drivers-windows#41]
@YanVugenfirer,

I ran into a trouble, when I had enabled the Balloon memory statistics via qmq command,

> {"execute": "qom-set","arguments": { "path": "/machine/peripheral/balloon0","property": "guest-stats-polling-interval", "value": 2 } }

but I always get a empty data on balloon memory statistics.

> {"execute": "qom-get","arguments": { "path": "/machine/peripheral/balloon0","property": "guest-stats" } }
> {"return": {"stats": {"stat-swap-out": -1, "stat-free-memory": -1, "stat-minor-faults": -1, "stat-major-faults": -1, "stat-total-memory": -1, "stat-swap-in": -1}, "last-update": 0}}

my environment is
- qemu-kvm 2.3.0
- virt-win-0.1.102.iso
- windows 2008R2 64 bit

I tried to debug it with gdb, I found that the **virtio_balloon_receive_stats** function inside qemu/hw/virtio/virtio-balloon.c is not called, it seems the windows virtio balloon driver does not kick off the statistics queue of virio balloon device. 

Can you give me a hint about the issue? Need I to debug the windows guest driver?

Thanks
Wei

**Comment by hammerg** [comment]
The memory's statistics are collected by the balloon service. Is the service is installed and running inside your guest?

    Gal.

**Comment by xs3c** [comment]
@hammerg Yes, I installed the virtio Balloon driver.

**Comment by hammerg** [comment]
Not just the driver, the balloon *service*.

**Comment by xs3c** [comment]
@hammerg  You are right, I missed the balloon service, thanks for your help.
