### ISSUE TITLE
viostor bad write performance compared to older version

### ISSUE THREAD

**Issue by Tim-Co** [virtio-win/kvm-guest-drivers-windows#42]
When using version 1.094, 1.02, or 1.110 of viostor.sys I get less than half the write performance compared to using version 1.074 and version 1.81. 

I'm Windows 2012 R2 and Windows 8.1 instances with a host using qemu-kvm version 1.5.3 and a ceph version 0.94.3 storage backend. I have cache=writeback and rbd cache enabled as well.

When using 1.74 of viostor.sys I get the following numbers using crystaldiskmark

| Test | Read MB/s | Write MB/s |
| --- | --- | --- |
| Seq Q32T1 | 716.9 | 120.9 |
| 4K Q32T1 | 58.04 | 9.606 |
| Seq | 321.0 | 112.8 |
| 4K | 5.697 | 11.88 |

When using 1.110 I get 

| Test | Read MB/s | Write MB/s |
| --- | --- | --- |
| Seq Q32T1 | 820.4 | 41.78 |
| 4K Q32T1 | 64.08 | 0.543 |
| Seq | 448.3 | 38.80 |
| 4K | 7.474 | 0.109 |

Version 1.094 and 1.102 have similar write numbers to 1.110

**Comment by vrozenfe** [comment]
Thank you for reporting this problem.

It's a know problem. For more information please visit
the following link:
https://bugzilla.redhat.com/show_bug.cgi?id=1238812

Best regards,
Vadim.

**Comment by vrozenfe** [comment]
We have completed performance testing cycle some time ago.
(https://bugzilla.redhat.com/show_bug.cgi?id=1023894#c11)
No issues have been found so far.

Closing this issue for now. 

If anyone experiences the similar problems when running the resent virtio block or scsi drivers on the latest stable upstream qemu, please feel free to reopen it again or open a new issue.

Vadim.
