### ISSUE TITLE
Windows 10 1909, virtio input, QXL/Spice: installing and starting vdservice breaks host mouse

### ISSUE THREAD

**Issue by intelfx** [virtio-win/kvm-guest-drivers-windows#438]
- Windows 10 1909
- input: virtio tablet + PS/2 mouse (+ a single Logitech Unifying receiver in passthrough with no devices connected)
- video: QXL/Spice (+ a single NVIDIA GPU in passthrough with no displays connected)
- libvirt + virt-manager

Installing virtio guest tools via the provided installer and starting vdservice immediately breaks virtio mouse (the cursor sometimes disappears and sometimes not, but it does not work in any case). Stopping vdservice immediately fixes the issue.

I can provide any logs or debug output if you point me towards it.

**Comment by ybendito** [comment]
vdservice is not related to thins repository.
I'd suggest to open the issue at
https://gitlab.freedesktop.org/spice/win32/vd_agent/issues
