### ISSUE TITLE
Vioserial & viorng build issue

### ISSUE THREAD

**Issue by Oloremo** [virtio-win/kvm-guest-drivers-windows#47]
Hello.

Build Env:
Win 2012 r2, DDK 7.1, WKD 8.1, VS 2013

I'm cloning repo, checkout tag mm131, run buildadd.bat
While building Vioserial & viorng I get a lot of errors. I attached logs of failed build:
[viorng.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/59638/viorng.txt)
[vioserial.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/59639/vioserial.txt)

Could you please to look into them?

**Comment by YanVugenfirer** [comment]
Thank you for the report. Will look into it.

**Comment by YanVugenfirer** [comment]
Fixed in stable branch - https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/285f9f2d28d5b1c44fb20d1d3fa954dfa106307f

**Comment by Oloremo** [comment]
Thank you, I'll try it tommorow.

Btw, should I always use stable branch or tags?

**Comment by YanVugenfirer** [comment]
The release are from stable branch and they are marked with tags. So better
use the latest tag.

Best regards,
Yan.


On Sun, Dec 13, 2015 at 3:01 PM, Proskurin Kirill <notifications@github.com>
wrote:

> Thank you, I'll try it tommorow.
>
> Btw, should I always use stable branch or tags?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/47#issuecomment-164255574>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by Oloremo** [comment]
I tested your fix in stable branch and looks like vioserial is fixed, but viorng is not, logs attached:
[viorng.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/61151/viorng.txt)

**Comment by vrozenfe** [comment]
You have to install Microsoft CNG SDK from http://www.microsoft.com/en-us/download/details.aspx?id=1251

Vadim Rozenfeld.

**Comment by Oloremo** [comment]
It gave me 404 after register\login redirect. I found this link https://www.microsoft.com/en-us/download/details.aspx?id=30688 which sounds like the same thing but viorng wont compile with it.

**Comment by vrozenfe** [comment]
Sad to know this. Looks like MS moved it out of itsusual location. Technically, you should be able to build viorngum.dll after adding the following definitions, taken from bcrypt_provider.h header file, provided as a part of Cryptographic Provider  Development Kit, into viorngum.h file:

diff --git a/viorng/cng/um/viorngum.h b/viorng/cng/um/viorngum.h
index 9878d08..1357281 100755
--- a/viorng/cng/um/viorngum.h
+++ b/viorng/cng/um/viorngum.h
@@ -38,6 +38,60 @@
 #define STATUS_INVALID_PARAMETER    ((NTSTATUS)0xC000000DL)
 #endif

+typedef _Must_inspect_result_ NTSTATUS
+(WINAPI *BCryptOpenAlgorithmProviderFn)(
+    _Out_   BCRYPT_ALG_HANDLE   *phAlgorithm,
+    _In_    LPCWSTR pszAlgId,
+    _In_    ULONG   dwFlags);
+
+//
+//
+typedef _Must_inspect_result_ NTSTATUS
+(WINAPI * BCryptGetPropertyFn)(
+    _In_                                        BCRYPT_HANDLE   hObject,
+    _In_                                        LPCWSTR pszProperty,
+    _Out_writes_bytes_to_opt_(cbOutput, *pcbResult) PUCHAR   pbOutput,
+    _In_                                        ULONG   cbOutput,
+    _Out_                                       ULONG   *pcbResult,
+    _In_                                        ULONG   dwFlags);
+
+
+//
+//
+typedef _Must_inspect_result_ NTSTATUS
+(WINAPI * BCryptSetPropertyFn)(
+    _Inout_                 BCRYPT_HANDLE   hObject,
+    _In_                    LPCWSTR pszProperty,
+    _In_reads_bytes_(cbInput)    PUCHAR   pbInput,
+    _In_                    ULONG   cbInput,
+    _In_                    ULONG   dwFlags);
+
+//
+//
+typedef _Must_inspect_result_ NTSTATUS
+(WINAPI * BCryptCloseAlgorithmProviderFn)(
+    _Inout_ BCRYPT_ALG_HANDLE   hAlgorithm,
+    _In_    ULONG   dwFlags);
+
+typedef _Must_inspect_result_ NTSTATUS
+(WINAPI * BCryptGenRandomFn)(
+_In_opt_                        BCRYPT_ALG_HANDLE   hAlgorithm,
+_Inout_updates_bytes_all_(cbBuffer)   PUCHAR   pbBuffer,
+_In_                            ULONG   cbBuffer,
+_In_                            ULONG   dwFlags);
+
+
+typedef struct _BCRYPT_RNG_FUNCTION_TABLE
+{
+    BCRYPT_INTERFACE_VERSION        Version;
+    BCryptOpenAlgorithmProviderFn   OpenAlgorithmProvider;
+    BCryptGetPropertyFn             GetProperty;
+    BCryptSetPropertyFn             SetProperty;
+    BCryptCloseAlgorithmProviderFn  CloseAlgorithmProvider;
+    BCryptGenRandomFn               GenRandom;
+} BCRYPT_RNG_FUNCTION_TABLE;
+
+
 // CNG RNG Provider Interface.

 NTSTATUS WINAPI VirtRngOpenAlgorithmProvider(OUT BCRYPT_ALG_HANDLE *Algorithm,

**Comment by Oloremo** [comment]
Sounds like a hack. I dont really think what applying this patch everytime is a good idea for me, bacaouse it will break in future with some changes. 

Any idea what happend with MS CNG SDK?

**Comment by hammerg** [comment]
On Mon, Dec 21, 2015 at 7:00 PM, Proskurin Kirill <notifications@github.com>
wrote:

> Sounds like a hack. I dont really think what applying this patch everytime
> is a good idea for me, bacaouse it will break in future with some changes.
>
> Any idea what happend with
> ​​
> MS CNG SDK?
>
> ​It seem that they moved it to a new "Cryptographic Provider Development
Kit" (https://www.microsoft.com/en-us/download/details.aspx?id=30688).

You might need to add or replace the "#include <bcrypt.h>" line with
"#include <bcrypt_provider.h>"

​Thanks,

    Gal.​

**Comment by Oloremo** [comment]
I installed Cryptographic Provider Development Kit, checkout mm132, added "#include <bcrypt_provider.h>" to viorng.h  and to viorngum.c.
1) It cant find  bcrypt_provider.h, but I found this file in Cryptographic Provider Development Kit dir
2) It still has instant compile errors even before including of bcrypt_provider.h
3) replacing "#include <bcrypt.h>" with didnt "#include <bcrypt_provider.h>" helped too

**Comment by hammerg** [comment]
On Tue, Dec 29, 2015 at 5:33 PM, Proskurin Kirill <notifications@github.com>
wrote:

> I installed Cryptographic Provider Development Kit, checkout mm132, added
> "#include " to viorng.h and to viorngum.c.
> 1) It cant find bcrypt_provider.h, but I found this file in Cryptographic
> Provider Development Kit dir
> 2) It still has instant compile errors even before including of
> bcrypt_provider.h
> 3) replacing "#include " with didnt "#include " helped too
>
​My mistake. The new sdk required​

​few more changes. Attached is a patch that should solved the compilation
error with the new sdk.​

**Comment by Oloremo** [comment]
Im sorry I dont get it, I dont see any patch attached to you last message. Are you talking about the one above by vrozenfe?

**Comment by hammerg** [comment]
Trying to attach patch again.
[0001-rng-update-to-new-cryptographic-provider-sdk.zip](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/74094/0001-rng-update-to-new-cryptographic-provider-sdk.zip)

**Comment by Oloremo** [comment]
Thank you, this patch looks like helps, but it still needed to fix path for viorngum.c. I attaching build logs: [viorng.txt](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/74142/viorng.txt)

**Comment by hammerg** [comment]
On Tue, Dec 29, 2015 at 6:57 PM, Proskurin Kirill <notifications@github.com>
wrote:

> Thank you, this patch looks like helps, but it still needed to fix path
> for viorngum.c. I attaching build logs: viorng.txt
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/74142/viorng.txt>
>

​Did you installed the cpdksetup.exe file​?

Does the bcrypt_provider.h file exists in C:\Program Files (x86)\Windows
Kits\8.0\Cryptographic Provider Development Kit\Include ?

​    Gal.

**Comment by Oloremo** [comment]
Yes, I have CPDK installed and yes I have bcrypt_provider.h in this folder(and bcrypt.h too)

**Comment by hammerg** [comment]
On Wed, Dec 30, 2015 at 1:15 PM, Proskurin Kirill <notifications@github.com>
wrote:

> Yes, I have CPDK installed and yes I have bcrypt_provider.h in this
> folder(and bcrypt.h too)
>
Check the project's properties. There is a macro​ which should expand to
right location in the include directories.


​    Gal.​
