### ISSUE TITLE
The 32-bit QXL driver blocks installation on a 64-bit Windows

### ISSUE THREAD

**Issue by fredo-m** [virtio-win/kvm-guest-drivers-windows#474]
Hi,

I installed a windows 10 pro 64 bit on a virtualization server which uses Proxmox.

I wanted to install the virtio win drivers with ISO (0.1.185) and the virtio-win-guest-tools launcher. Part of the drivers are installed, but I have an error with the spice driver which blocked the installation. The other drivers have not been installed.

The VM is configured with a VGA display, only the sound uses the spice driver.

The screenshots are attached as well as the log file.

It's annoying that the installation of all drivers is blocked by one of them.

Regards.
![remmina_WIN 10 3_WIN-10-3_202072-1](https://user-images.githubusercontent.com/16595693/86373995-579f8b00-bc84-11ea-9db7-bfd66db245b9.png)
![remmina_WIN 10 3_WIN-10-3_202072-2](https://user-images.githubusercontent.com/16595693/86373999-58382180-bc84-11ea-9e44-58795a2762e5.png)
[Virtio-win-guest-tools_20200702150113.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/4865031/Virtio-win-guest-tools_20200702150113.log)

**Comment by ybendito** [comment]
@fredo-m As a temporary workaround until the root cause is fixed, can you try to define the display as qxl and retry the installation. If it succeeds, you can then redefine the display as VGA again.

**Comment by Gal-Zaidman** [comment]
This has been fixed on:
https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/6bdf73bc92eda3d723cad3703513503c688cbc8e
We just need to create a new release for upstream with the fix

**Comment by fredo-m** [comment]
Hi,

I installed version 0.1.189 and the bug is fixed.

Regards.
