### ISSUE TITLE
Windows 7 Pro 64 bit

### ISSUE THREAD

**Issue by Elf36** [virtio-win/kvm-guest-drivers-windows#485]
We installed the drivers and now the system is not booting, the drive is seen in windows recovery as it allows you to enter a password for a local user.
We have rolled back to a restore point before the installation but the system still does not boot and seems un recoverable.
the xml file is sane.
How can we restore the original drivers or get the system booting again ?

**Comment by YanVugenfirer** [comment]
Hello,

Can you post XML file, the versions of the drivers and what exact driver did you update.

Thanks,
Yan.

**Comment by OrbitalSystems** [comment]
Hi file below

I installed drivers 0.1.185

and i installed the guest agent (OK)

Then tried to install the Virtio drivers

Now the machine boots to windows repair and does see the drive but can’t repair it.

Windows says bad driver…

I have rolled back the OS pre installation but that also does not resolve the situation.

I have eattached the Drive as IDE and Virtio

I have attached as IDE and created a dummy Vitio disk (same qcow2 img…

Nothing





linux-0a7s:/etc/libvirt/qemu # cat FinishedNavision.xml


<domain type='kvm'>
  <name>FinishedNavision</name>
  <uuid>4ccbed9a-06aa-41e9-a31a-38213c9b9cae</uuid>
  <memory unit='KiB'>25165824</memory>
  <currentMemory unit='KiB'>16777216</currentMemory>
  <vcpu placement='static' current='6'>8</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-2.12'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
    <vmport state='off'/>
  </features>
  <cpu mode='custom' match='exact' check='partial'>
    <model fallback='allow'>Nehalem-IBRS</model>
  </cpu>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <target dev='hdc' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='1' target='0' unit='0'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/home/vms/postmalnav.qcow2'/>
      <target dev='hdd' bus='ide'/>
      <address type='drive' controller='0' bus='1' target='0' unit='1'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/home/suseadmin/Downloads/GSP1RMCPRFREO_EN_DVD.iso'/>
      <target dev='sda' bus='scsi'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </controller>
    <controller type='scsi' index='0' model='lsilogic'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x0a' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='52:54:00:c9:40:32'/>
      <source bridge='br1'/>
      <model type='rtl8139'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice' port='5900' autoport='no'>
      <listen type='address'/>
    </graphics>
    <sound model='ich6'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </memballoon>
  </devices>
</domain>
linux-0a7s:/etc/libvirt/qemu #

**Comment by OrbitalSystems** [comment]
The issue is windows does not like the viostor driver I guess I need to remove it or replace with the original but system rollback doesn’t let me.

it’s windows 64 bit so the drivers are not easily installable.

**Comment by vrozenfe** [comment]
It must be a bug in RPM. We discontinued building Win7 drivers due to several reasons. One of them is that we cannot use SHA-1 anymore for signing  kernel binaries.  However we decided to ship old drivers for pre-Win8 Windows versions. For Win7 it supposed to be drivers from build 175, but it seems like I messed up with the builds and took drivers from a wrong build, where Win7 binaries were signed with SHA256 instead of SHA1.  

Really sorry for any trouble caused. Will fix this problem in next RPM.
Vadim.

**Comment by OrbitalSystems** [comment]
Thanks Vadim,

Any thing I can install in it’s place in windows 7 to help or do I just leave out and Vitio drivers for now ?

**Comment by vrozenfe** [comment]
@OrbitalSystems 
Can you please give a try to the new RPM available at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.189-1 ?  It should contain Win7 drivers properly sighed with SHA1 signature. 
Thanks,
Vadim.

**Comment by mirh** [comment]
Patched W7 should actually support SHA-2
https://kerneldrivers.com/dual-signed-binaries-windows-7-beyond/

**Comment by vrozenfe** [comment]
That's true, but the problem is that here, at RH, we don't have a valid SHA-2 certificate that can be used for cross-certification of Win7 binaries, especially because cross-signed root certificate will be expired in a week https://docs.microsoft.com/en-us/windows-hardware/drivers/install/deprecation-of-software-publisher-certificates-and-commercial-release-certificates.

Best,
Vadim.

**Comment by Mantrayana** [comment]
What is the last version that is supporting Windows 7?

**Comment by PrplHaz4** [comment]
> 
> 
> What is the last version that is supporting Windows 7?

I've been trying to chase down something else and ran across this post - I believe the version I have running on Windows 7 x64 is `0.1.171`.  Like you, I tried `0.1.185` and had problems - not sure if anything has been fixed/improved since then...
