### ISSUE TITLE
virtio-fs: Unable to remove empty directory

### ISSUE THREAD

**Issue by kevinoid** [virtio-win/kvm-guest-drivers-windows#497]
When sharing a host directory with a Windows 10 guest via [virtio-fs](https://virtio-fs.gitlab.io) using `viofs.sys` and `virtiofs.exe` from [`virtio-win-0.1.189.iso`](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.189-1/virtio-win-0.1.189.iso) and [WinFSP 2020.1](https://github.com/billziss-gh/winfsp/releases/download/v1.7/winfsp-1.7.20172.msi), when I run the following from a command prompt (assuming the virtio-fs directory is mounted as `z:` in the guest and initially empty):

```bat
z:
md foo
rd foo
```
It prints:

    The directory is not empty.

and the directory is not removed.  This behavior occurs when the host directory is `ext4` or `ntfs-3g`, but not `tmpfs`.

<details>
<summary><code>virtiofs.exe -d -1</code> debug log</summary>

    *** VirtFsFuseRequest: >>req: 26 unique: 2 len: 56
    *** VirtFsFuseRequest: <<len: 80 error: 0 unique: 2
    virtiofs[TID=0908]: FFFF830F0D323510: >>QueryVolumeInformation
    *** VirtFsFuseRequest: >>req: 17 unique: 3 len: 40
    *** VirtFsFuseRequest: <<len: 96 error: 0 unique: 3
    *** GetVolumeInfo: VolumeLabel: Kevin
    virtiofs[TID=0908]: FFFF830F0D323510: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=71:aecea000, FreeSize=12:710f4000, VolumeLabel="Kevin"}
    virtiofs[TID=17c4]: FFFF830F0DF6A460: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=000000000000025C[PID=13a8], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
    *** GetSecurityByName: "\"
    *** VirtFsFuseRequest: >>req: 1 unique: 4 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 4
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** Open: "\" CreateOptions: 0x01200000 GrantedAccess: 0x00000080
    *** VirtFsFuseRequest: >>req: 1 unique: 5 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 5
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** VirtFsFuseRequest: >>req: 27 unique: 6 len: 48
    *** VirtFsFuseRequest: <<len: 32 error: 0 unique: 6
    *** Open: fh: 4 nodeid: 3
    *** SetFileInfo: ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    virtiofs[TID=17c4]: FFFF830F0DF6A460: <<Create IoStatus=0[1] UserContext=0000000000000000:000001A78E9FC570, GrantedAccess=80, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2020-08-27T14:41:39.630Z, LastAccessTime=2020-08-27T14:37:41.531Z, LastWriteTime=2020-08-27T14:41:39.630Z, ChangeTime=2020-08-27T14:41:39.630Z, IndexNumber=0:0}
    virtiofs[TID=0908]: FFFF830F0D323510: >>Close 0000000000000000:000001A78E9FC570
    *** Close: fh: 4 nodeid: 3
    *** VirtFsFuseRequest: >>req: 29 unique: 7 len: 64
    *** VirtFsFuseRequest: <<len: 16 error: 0 unique: 7
    virtiofs[TID=0908]: FFFF830F0D323510: <<Close IoStatus=0[0]
    virtiofs[TID=0908]: FFFF830F0E52F460: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=21, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000260[PID=9b0], DesiredAccess=100000, GrantedAccess=0, ShareAccess=3
    *** GetSecurityByName: "\"
    *** VirtFsFuseRequest: >>req: 1 unique: 8 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 8
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** Open: "\" CreateOptions: 0x01000021 GrantedAccess: 0x00100000
    *** VirtFsFuseRequest: >>req: 1 unique: 9 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 9
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** VirtFsFuseRequest: >>req: 27 unique: 10 len: 48
    *** VirtFsFuseRequest: <<len: 32 error: 0 unique: 10
    *** Open: fh: 4 nodeid: 3
    *** SetFileInfo: ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    virtiofs[TID=0908]: FFFF830F0E52F460: <<Create IoStatus=0[1] UserContext=0000000000000000:000001A78E9FC2A0, GrantedAccess=100000, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2020-08-27T14:41:39.630Z, LastAccessTime=2020-08-27T14:37:41.531Z, LastWriteTime=2020-08-27T14:41:39.630Z, ChangeTime=2020-08-27T14:41:39.630Z, IndexNumber=0:0}
    virtiofs[TID=0908]: FFFF830F0EB78A20: >>QueryVolumeInformation
    *** VirtFsFuseRequest: >>req: 17 unique: 11 len: 40
    *** VirtFsFuseRequest: <<len: 96 error: 0 unique: 11
    *** GetVolumeInfo: VolumeLabel: Kevin
    virtiofs[TID=0908]: FFFF830F0EB78A20: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=71:aecea000, FreeSize=12:710f4000, VolumeLabel="Kevin"}
    virtiofs[TID=0908]: FFFF830F0E0CD460: >>Close 0000000000000000:000001A78E9FC2A0
    *** Close: fh: 4 nodeid: 3
    *** VirtFsFuseRequest: >>req: 29 unique: 12 len: 64
    *** VirtFsFuseRequest: <<len: 16 error: 0 unique: 12
    virtiofs[TID=0908]: FFFF830F0E0CD460: <<Close IoStatus=0[0]
    virtiofs[TID=17c4]: FFFF830F0EB78A20: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=21, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=000000000000025C[PID=9b0], DesiredAccess=100020, GrantedAccess=0, ShareAccess=3
    *** GetSecurityByName: "\"
    *** VirtFsFuseRequest: >>req: 1 unique: 13 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 13
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** Open: "\" CreateOptions: 0x01000021 GrantedAccess: 0x00100020
    *** VirtFsFuseRequest: >>req: 1 unique: 14 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 14
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** VirtFsFuseRequest: >>req: 27 unique: 15 len: 48
    *** VirtFsFuseRequest: <<len: 32 error: 0 unique: 15
    *** Open: fh: 4 nodeid: 3
    *** SetFileInfo: ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    virtiofs[TID=17c4]: FFFF830F0EB78A20: <<Create IoStatus=0[1] UserContext=0000000000000000:000001A78E9FC390, GrantedAccess=100020, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2020-08-27T14:41:39.630Z, LastAccessTime=2020-08-27T14:37:41.531Z, LastWriteTime=2020-08-27T14:41:39.630Z, ChangeTime=2020-08-27T14:41:39.630Z, IndexNumber=0:0}
    virtiofs[TID=17c4]: FFFF830F0DB564A0: >>Create [UT---C] "\foo", FILE_CREATE, CreateOptions=200021, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=000000000000025C[PID=9b0], DesiredAccess=100001, GrantedAccess=0, ShareAccess=3
    *** GetSecurityByName: "\"
    *** VirtFsFuseRequest: >>req: 1 unique: 16 len: 42
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 16
    *** SubmitLookupRequest: nodeid=3 ino=8650753 size=4096 blocks=8 atime=1598539061 mtime=1598539299 ctime=1598539299 atimensec=531760090 mtimensec=630477314 ctimensec=630477314 mode=41ed nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** Create: "\foo" CreateOptions: 0x02200021 GrantedAccess: 0x00100001 FileAttributes: 0x00000010 AllocationSize: 0
    *** VirtFsFuseRequest: >>req: 9 unique: 17 len: 52
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 17
    *** SetFileInfo: ino=8683527 size=4096 blocks=8 atime=1598539409 mtime=1598539409 ctime=1598539409 atimensec=945565650 mtimensec=945565650 ctimensec=945565650 mode=41fd nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    virtiofs[TID=17c4]: FFFF830F0DB564A0: <<Create IoStatus=0[2] UserContext=0000000000000000:000001A78E9FC420, GrantedAccess=100001, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2020-08-27T14:43:29.945Z, LastAccessTime=2020-08-27T14:43:29.945Z, LastWriteTime=2020-08-27T14:43:29.945Z, ChangeTime=2020-08-27T14:43:29.945Z, IndexNumber=0:0}
    virtiofs[TID=17c4]: FFFF830F0DB564A0: >>Cleanup 0000000000000000:000001A78E9FC420
    *** Cleanup: "" Flags: 0x22
    virtiofs[TID=17c4]: FFFF830F0DB564A0: <<Cleanup IoStatus=0[0]
    virtiofs[TID=0908]: FFFF830F0E9E44D0: >>Close 0000000000000000:000001A78E9FC420
    *** Close: fh: 18446744073709551615 nodeid: 2
    *** VirtFsFuseRequest: >>req: 29 unique: 18 len: 64
    *** VirtFsFuseRequest: <<len: 16 error: -9 unique: 18
    virtiofs[TID=0908]: FFFF830F0E9E44D0: <<Close IoStatus=0[0]
    virtiofs[TID=0908]: FFFF830F0EE45C10: >>Create [UT---C] "\foo", FILE_OPEN, CreateOptions=200021, FileAttributes=10, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000260[PID=9b0], DesiredAccess=110080, GrantedAccess=0, ShareAccess=7
    *** GetSecurityByName: "\foo"
    *** VirtFsFuseRequest: >>req: 1 unique: 19 len: 44
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 19
    *** SubmitLookupRequest: nodeid=2 ino=8683527 size=4096 blocks=8 atime=1598539409 mtime=1598539409 ctime=1598539409 atimensec=945565650 mtimensec=945565650 ctimensec=945565650 mode=41fd nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** Open: "\foo" CreateOptions: 0x01200021 GrantedAccess: 0x00110080
    *** VirtFsFuseRequest: >>req: 1 unique: 20 len: 44
    *** VirtFsFuseRequest: <<len: 144 error: 0 unique: 20
    *** SubmitLookupRequest: nodeid=2 ino=8683527 size=4096 blocks=8 atime=1598539409 mtime=1598539409 ctime=1598539409 atimensec=945565650 mtimensec=945565650 ctimensec=945565650 mode=41fd nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** VirtFsFuseRequest: >>req: 27 unique: 21 len: 48
    *** VirtFsFuseRequest: <<len: 32 error: 0 unique: 21
    *** Open: fh: 5 nodeid: 2
    *** SetFileInfo: ino=8683527 size=4096 blocks=8 atime=1598539409 mtime=1598539409 ctime=1598539409 atimensec=945565650 mtimensec=945565650 ctimensec=945565650 mode=41fd nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    virtiofs[TID=0908]: FFFF830F0EE45C10: <<Create IoStatus=0[1] UserContext=0000000000000000:000001A78E9FC420, GrantedAccess=110080, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:1000, FileSize=0:1000, CreationTime=2020-08-27T14:43:29.945Z, LastAccessTime=2020-08-27T14:43:29.945Z, LastWriteTime=2020-08-27T14:43:29.945Z, ChangeTime=2020-08-27T14:43:29.945Z, IndexNumber=0:0}
    virtiofs[TID=0908]: FFFF830F0EE45C10: >>SetInformation [Disposition] "\foo", 0000000000000000:000001A78E9FC420, Delete
    *** GetFileInfo: fh: 5 nodeid: 2
    *** VirtFsFuseRequest: >>req: 3 unique: 22 len: 56
    *** VirtFsFuseRequest: <<len: 120 error: 0 unique: 22
    *** SetFileInfo: ino=8683527 size=4096 blocks=8 atime=1598539409 mtime=1598539409 ctime=1598539409 atimensec=945565650 mtimensec=945565650 ctimensec=945565650 mode=41fd nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    *** CanDelete: "\foo"
    *** VirtFsFuseRequest: >>req: 3 unique: 23 len: 56
    *** VirtFsFuseRequest: <<len: 120 error: 0 unique: 23
    *** SetFileInfo: ino=8683527 size=4096 blocks=8 atime=1598539409 mtime=1598539409 ctime=1598539409 atimensec=945565650 mtimensec=945565650 ctimensec=945565650 mode=41fd nlink=2 uid=0 gid=0 rdev=0 blksize=4096
    virtiofs[TID=0908]: FFFF830F0EE45C10: <<SetInformation IoStatus=c0000101[0]
    virtiofs[TID=0908]: FFFF830F0EB2B010: >>Close 0000000000000000:000001A78E9FC420
    *** Close: fh: 5 nodeid: 2
    *** VirtFsFuseRequest: >>req: 29 unique: 24 len: 64
    *** VirtFsFuseRequest: <<len: 16 error: 0 unique: 24
    virtiofs[TID=0908]: FFFF830F0EB2B010: <<Close IoStatus=0[0]

</details>

I have been unable to reproduce the behavior using [Alpine Linux](http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86_64/alpine-virt-3.12.0-x86_64.iso), so I suspect the issue is in the guest, rather than the host.

Thanks for creating/supporting these drivers!  Let me know if there is anything else I can do to help debug.

Thanks again,
Kevin

**Comment by hammerg** [comment]
Nice catch (I only used tmpfs until now). I assume the problem is with the logic that test if a directory is empty (I check for the directory "file" size which is probably not the right way to do it).

**Comment by kevinoid** [comment]
Thanks @hammerg!  The fix looks great.  Are there any publicly available snapshot builds that I could test, or would I need to build+sign myself?
