### ISSUE TITLE
virtio-fs: Support for symlinks?

### ISSUE THREAD

**Issue by DocMAX** [virtio-win/kvm-guest-drivers-windows#499]
Is it possible to allow browsing into symlinks? Right now a symlink is a file on windows guest.

**Comment by hammerg** [comment]
Currently, no. I'll try to add a support for it if possible.

**Comment by DocMAX** [comment]
This would be nice, thank you!

**Comment by menli820** [comment]
bz https://bugzilla.redhat.com/show_bug.cgi?id=1925144  to track this issue.

**Comment by jwatt** [comment]
@YanVugenfirer: I guess this can be closed now?

**Comment by raffaem** [comment]
I have latest 0.1.217 and symlinks are not followed. They are displayed as files on Windows guest

**Comment by raffaem** [comment]
Should we re-open this or I am doing something wrong?

**Comment by YanVugenfirer** [comment]
I think this issues was closed on purpose by @viktor-prutyanov as it contained description of several problems.
I suggest opening a new one and following the template to add the needed info.

Thanks!

**Comment by viktor-prutyanov** [comment]
> Should we re-open this or I am doing something wrong?

If you face some VirtIO-FS issue, please open new issue with exact description of the problem or feature you want us to implement

**Comment by raffaem** [comment]
> > Should we re-open this or I am doing something wrong?
> 
> If you face some VirtIO-FS issue, please open new issue with exact description of the problem or feature you want us to implement

I opened feature request #796

**Comment by davispuh** [comment]
Symlinks still doesn't work with latest winfsp-2.0.23075.

```
Z:\>mkdir test
Z:\>echo a > test\a
Z:\>type test\a
a

Z:\>mklink /D t test
symbolic link created for t <<===>> test

Z:\>type t\a
The filename, directory name, or volume label syntax is incorrect.

Z:\>cd t

Z:\t>dir
 Volume in drive Z is Z
 Volume Serial Number is 0000-0000

 Directory of Z:\

27/03/2023  05:42    <SYMLINK>      t [...]
               1 File(s)              0 bytes
               0 Dir(s)  136,383,930,368 bytes free

Z:\t>type a
The filename, directory name, or volume label syntax is incorrect.
```

Note that they are correctly created and on Linux host everything is correct
```
$ ls -la
lrwxrwxrwx  1 root  users    4 mar 27 05:42  t -> test/
$ cat ./t/a
a
```

**Comment by YanVugenfirer** [comment]
> Symlinks still doesn't work with latest winfsp-2.0.23075.
> 
> ```
> Z:\>mkdir test
> Z:\>echo a > test\a
> Z:\>type test\a
> a
> 
> Z:\>mklink /D t test
> symbolic link created for t <<===>> test
> 
> Z:\>type t\a
> The filename, directory name, or volume label syntax is incorrect.
> 
> Z:\>cd t
> 
> Z:\t>dir
>  Volume in drive Z is Z
>  Volume Serial Number is 0000-0000
> 
>  Directory of Z:\
> 
> 27/03/2023  05:42    <SYMLINK>      t [...]
>                1 File(s)              0 bytes
>                0 Dir(s)  136,383,930,368 bytes free
> 
> Z:\t>type a
> The filename, directory name, or volume label syntax is incorrect.
> ```
> 
> Note that they are correctly created and on Linux host everything is correct
> 
> ```
> $ ls -la
> lrwxrwxrwx  1 root  users    4 mar 27 05:42  t -> test/
> $ cat ./t/a
> a
> ```

Hi @davispuh,

I suggest to open a separate issue with your report.

Thanks,
Yan.

**Comment by davispuh** [comment]
okay, created #897

**Comment by YanVugenfirer** [comment]
Thanks!

**Comment by jurosic** [comment]
Is this feature still planned? The issue has not been reopened and support has not been added.

**Comment by Seramis** [comment]
@YanVugenfirer, is there another (open) ticket tracking the issues with symlinks in a scenario with Linux host and Windows guest?

I can currently confirm in my setup, when i look at the symlink inside a shared folder drive, i see it as unknown file. (`src` is the name of the symlink)

<img width="363" height="509" alt="Image" src="https://github.com/user-attachments/assets/525c3561-90df-4031-8256-402d05038d93" />

**Comment by YanVugenfirer** [comment]
There are another two open issues: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1375 , https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1149

In general: incomplete symlink support is a known issue. Unfortunately we don't have ETA for fixing it.
