### ISSUE TITLE
Problem red hat virtio scsi disk device 6.3.9600.18758

### ISSUE THREAD

**Issue by abcde22** [virtio-win/kvm-guest-drivers-windows#505]
Hello,
 
We have a cloud environment that consists of hosts backed by KVM hypervisors. About half of the virtual machines are running Windows Server operating systems (2008R2, 2012R2, 2016, 2019), there are hundreds of such instances and almost all of them use VirtIO drivers (mostly 0.1.160).
 
Sometimes (it occurred about 3-4 times) we encountered the following glitch: a guest operating decides that its primary disk storage has more size than it actually is. For example, an instance had a virtual drive of 200 GB, it had been worked fine for years, but at some moment (no one knows at which exactly one) primary partition (we mean "drive C:", which usually is the 2nd one, as the 1st one is being used by the operating system) became the size of 210 GB just out of the blue. After that, the system event log started growing with the following error messages: `The driver detected a controller error \ Device \ Harddisk0 \ DR`. Obviously, it happens when the operating system tries to write pieces of data to the sectors that don't exist.
 
Once we expand this virtual drive to 210 GB, the error messages don't appear anymore. Still, after that we find some part of the data corrupted (maybe some fragments of files are being stored to the non-existent sectors), so it seems to be a real problem for us when it happens.
 
Alas, we didn't find a way to reproduce that. As we stated before, it happened only 3-4 times, though each time the outcomes are quite unpleasant.
 
Should we provide with more data regarding this issue? Should we consider upgrading the driver? Perhaps, we just don’t know that it’s a bug that had been fixed after the 0.1.160's release? Just curious, did anyone send a similar bug-report before? We tried to find them, though with no luck.
 
Thanks in advance for your feedback.

**Comment by vrozenfe** [comment]
Please see my comments at
https://bugzilla.redhat.com/show_bug.cgi?id=1879396#c1
Cheers,
Vadim.

**Comment by YanVugenfirer** [comment]
Closing based on the comment https://bugzilla.redhat.com/show_bug.cgi?id=1879396#c16

Best regards,
Yan.
