### ISSUE TITLE
"Failed to read from slave"

### ISSUE THREAD

**Issue by DocMAX** [virtio-win/kvm-guest-drivers-windows#507]
This is what i get after a few minutes using virio-fs on Win10.

**Comment by hammerg** [comment]
Get from who? What did you do? Logs? Which fs is used at the shared folder?

**Comment by YanVugenfirer** [comment]
Closing.

@DocMAX please provide more information about the failure (host and guest configuration, where exactly do you see the failure message and logs) and re-open the issue.
