### ISSUE TITLE
"File Too Large" error when creating files

### ISSUE THREAD

**Issue by InfinityGhost** [virtio-win/kvm-guest-drivers-windows#512]
![The file '<%1 NULL:NameDest>' is too large for the destination file system.](https://user-images.githubusercontent.com/39218853/96778466-be72bc80-13b9-11eb-8b44-c519448c62e0.png)

This occurred while creating an empty text file, and happens every time. The file is still created on the source filesystem, as if nothing is wrong. Copying files and directories back and forth between the host and the guest doesn't appear to have any issues besides this.

**Comment by hammerg** [comment]
Thanks for the bug report. I think this issue was resolved in #506 .

**Comment by InfinityGhost** [comment]
Will try building master, was using latest release when I got this.

**Comment by InfinityGhost** [comment]
Okay, this is resolved since #506.
