### ISSUE TITLE
Consider adding some doc or troubleshooting instructions

### ISSUE THREAD

**Issue by oliviercailloux** [virtio-win/kvm-guest-drivers-windows#520]
I can’t make Windows 10 install the VirtIO disk drivers. I tried various combinations of options, to no avail: Windows tells me that it can’t find any suitable driver to install.

Relatedly, I couldn’t find troubleshooting instructions / detailed instructions about which drivers are supposed to be installed in which situation, and what to do to investigate further if Windows refuses to install them. (I did [read](https://www.qemu.org/documentation) [the](https://docs.fedoraproject.org/en-US/quick-docs/creating-windows-virtual-machines-using-virtio-drivers/) [doc](https://wiki.debian.org/KVM) [I](https://drewdevault.com/2018/09/10/Getting-started-with-qemu.html) [could](https://dennisnotes.com/note/20180614-ubuntu-18.04-qemu-setup/) [find](https://linuxhint.com/install_virtio_drivers_kvm_qemu_windows_vm/), but the information is scarce about what to do when things do not work as indicated.) The iso contains folders `vioscsi` (“Virtio SCSI driver”) and `viostor` (“Virtio block driver”) and in them (and inside the folder corresponding to the Windows version to be installed), sub-folders `amd64` and `x86`. Should I install `vioscsi` or `viostor`? Should I install `amd64` or `x86`? Will Windows try to detect whether it finds a SCSI controller, and if not, refuse to install the `vioscsi` driver? What about `viostor`, is there a similar condition? If so, can I first somehow check that Windows does see a suitable hardware, in order to get some hint about what is wrong with my setup? In summary: please consider adding some troubleshooting instructions to help users when things do not work.

Here is one of the commands I tried.

`qemu-system-x86_64 -enable-kvm -m 4G -nic user,model=virtio -drive "file=win.qcow2,media=disk,if=virtio" -drive "file=Windows10x64_20201116.iso,index=2,media=cdrom" -drive "file=virtio-win-stable.iso,index=3,media=cdrom" -display gtk`

The Windows installer boots, asks me for regional settings, then [tells me that some driver is missing](https://user-images.githubusercontent.com/1244880/99386813-55f0ff80-28d3-11eb-8490-e85b88159dea.png). Pointing it to, for example, `E:\viostor\w10\amd64` results in Windows listing exactly one driver: `Red Hat VirtIO SCSI controller (E:\viostor\w10\amd64\viostor.inf)`. Clicking next results in Windows filling partially the progress bar seven times, then telling me that it [did not detect any new driver](https://user-images.githubusercontent.com/1244880/99386927-74ef9180-28d3-11eb-88d4-c4753a97df23.png). (This is an approximate translation because I can only get my Windows version to speak French.)

Any help or pointer would be appreciated.

**Comment by YanVugenfirer** [comment]
Hello @oliviercailloux,

If you are using drivers that are distributed by the [Fedora](https://docs.fedoraproject.org/en-US/quick-docs/creating-windows-virtual-machines-using-virtio-drivers/) project ([latest ISO](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso)), then on the ISO you should find the virtio-win-guest-tools.exe installer. Just run it, and it should take care of the installation.

If you see issues with the installer, please report them here:
https://github.com/virtio-win/virtio-win-guest-tools-installer/issues

Thanks,
Yan.

**Comment by YanVugenfirer** [comment]
In the case of the boot driver, it depends on the driver type.

For virtio-block device - install virstor driver. For virtio-scsi device - install vioscsi driver.

For 64bit guests (that's what most probably you are using) - use amd64 platform.
For 32bit guests - use x86 platform.

Best regards,
Yan.

**Comment by oliviercailloux** [comment]
Yes, I am using drivers that are distributed by the Fedora project. Yes, Windows 64 bits.

I am specifically trying to load the drivers during the Windows install, thus, install directly using passthrough access. That seems to me more elegant and faster than installing using emulated drive access then switching to VirtIO once Windows is installed. I suppose this is supported as well and should work, and apparently it works for many users, seeing the various tutorials on the internet about this procedure. Installing first then switching seems to me more like a workaround than a solution to the issue. And now I am curious to know why it fails for me.

I do not know if in my case I have a virtio-block device or a virtio-scsi device, but I tried both (selecting the amd64 variant), and Windows will not load any of these drivers: neither virtio-block, nor virtio-scsi. It tells me that it [did not detect any new driver](https://user-images.githubusercontent.com/1244880/99386927-74ef9180-28d3-11eb-88d4-c4753a97df23.png).

**Comment by vrozenfe** [comment]
Hi Oliver,
Can you post the exact qemu command line as well as the output generated by "info pci" command issued from qemu monitor?
It also will be useful, if you can let me know the qemu version.

Thanks,
Vadim.

**Comment by oliviercailloux** [comment]
Thank you for investigating this!

The command line (as displayed above) is: `qemu-system-x86_64 -enable-kvm -m 4G -nic user,model=virtio -drive "file=win.qcow2,media=disk,if=virtio" -drive "file=Windows10x64_20201116.iso,index=2,media=cdrom" -drive "file=virtio-win-stable.iso,index=3,media=cdrom" -display gtk`.

```
$ qemu-system-x86_64 --version
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u8)
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
```

```
QEMU 3.1.0 monitor - type 'help' for more information
(qemu) info pci
  Bus  0, device   0, function 0:
    Host bridge: PCI device 8086:1237
      PCI subsystem 1af4:1100
      id ""
  Bus  0, device   1, function 0:
    ISA bridge: PCI device 8086:7000
      PCI subsystem 1af4:1100
      id ""
  Bus  0, device   1, function 1:
    IDE controller: PCI device 8086:7010
      PCI subsystem 1af4:1100
      BAR4: I/O at 0xc060 [0xc06f].
      id ""
  Bus  0, device   1, function 3:
    Bridge: PCI device 8086:7113
      PCI subsystem 1af4:1100
      IRQ 9.
      id ""
  Bus  0, device   2, function 0:
    VGA controller: PCI device 1234:1111
      PCI subsystem 1af4:1100
      BAR0: 32 bit prefetchable memory at 0xfd000000 [0xfdffffff].
      BAR2: 32 bit memory at 0xfebd0000 [0xfebd0fff].
      BAR6: 32 bit memory at 0xffffffffffffffff [0x0000fffe].
      id ""
  Bus  0, device   3, function 0:
    Ethernet controller: PCI device 1af4:1000
      PCI subsystem 1af4:0001
      IRQ 11.
      BAR0: I/O at 0xc040 [0xc05f].
      BAR4: 64 bit prefetchable memory at 0xfe000000 [0xfe003fff].
      BAR6: 32 bit memory at 0xffffffffffffffff [0x0003fffe].
      id ""
  Bus  0, device   4, function 0:
    SCSI controller: PCI device 1af4:1001
      PCI subsystem 1af4:0002
      IRQ 11.
      BAR0: I/O at 0xc000 [0xc03f].
      BAR1: 32 bit memory at 0xfebd1000 [0xfebd1fff].
      BAR4: 64 bit prefetchable memory at 0xfe004000 [0xfe007fff].
      id ""
```

**Comment by vrozenfe** [comment]
Good,
First of all you have virtio-blk device there (PCI device 1af4:1001) and you need to use viostor.sys driver for it.
The second thing is that your qemu command line looks a bit strange. I don't see devices there  Normally it should be something like this:
-drive file=/home/vrozenfe/work/images/blah_blah_blah.qcow2,if=none,id=drive-virtio-disk0,format=qcow2,cache=unsafe,discard=unmap -device virtio-blk-pci,scsi=off,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1
We have "-drive" and "-device" there and they are linked together by "id=drive-virtio-disk0" and "drive=drive-virtio-disk0" pare.

**Comment by oliviercailloux** [comment]
Now running:
```
qemu-system-x86_64 -enable-kvm -m 4G -nic user,model=virtio -display gtk \
	-drive "file=win.qcow2,if=none,id=drive-virtio-disk0,format=qcow2,cache=unsafe,discard=unmap" \
	-device "virtio-blk-pci,scsi=off,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1" \
	-drive "file=Windows10x64_20201116.iso,index=2,media=cdrom" \
	-drive "file=virtio-win-0.1.189.iso,index=3,media=cdrom"
```
⇒ Same behavior: Windows refuses to install viostor (the amd64 variant), saying that no new driver was detected.

`info pci` gives the exact same result, except for the device id (now `"virtio-disk0"`, previously `""`)
```
QEMU 3.1.0 monitor - type 'help' for more information
(qemu) info pci
  Bus  0, device   0, function 0:
    Host bridge: PCI device 8086:1237
      PCI subsystem 1af4:1100
      id ""
  Bus  0, device   1, function 0:
    ISA bridge: PCI device 8086:7000
      PCI subsystem 1af4:1100
      id ""
  Bus  0, device   1, function 1:
    IDE controller: PCI device 8086:7010
      PCI subsystem 1af4:1100
      BAR4: I/O at 0xc060 [0xc06f].
      id ""
  Bus  0, device   1, function 3:
    Bridge: PCI device 8086:7113
      PCI subsystem 1af4:1100
      IRQ 9.
      id ""
  Bus  0, device   2, function 0:
    VGA controller: PCI device 1234:1111
      PCI subsystem 1af4:1100
      BAR0: 32 bit prefetchable memory at 0xfd000000 [0xfdffffff].
      BAR2: 32 bit memory at 0xfebd0000 [0xfebd0fff].
      BAR6: 32 bit memory at 0xffffffffffffffff [0x0000fffe].
      id ""
  Bus  0, device   3, function 0:
    Ethernet controller: PCI device 1af4:1000
      PCI subsystem 1af4:0001
      IRQ 11.
      BAR0: I/O at 0xc040 [0xc05f].
      BAR4: 64 bit prefetchable memory at 0xfe000000 [0xfe003fff].
      BAR6: 32 bit memory at 0xffffffffffffffff [0x0003fffe].
      id ""
  Bus  0, device   4, function 0:
    SCSI controller: PCI device 1af4:1001
      PCI subsystem 1af4:0002
      IRQ 11.
      BAR0: I/O at 0xc000 [0xc03f].
      BAR1: 32 bit memory at 0xfebd1000 [0xfebd1fff].
      BAR4: 64 bit prefetchable memory at 0xfe004000 [0xfe007fff].
      id "virtio-disk0"
(qemu) 
```

Note that the qemu man page says:
```
-drive option[,option[,option[,...]]]
           Define a new drive. This includes creating a block driver node (the
           backend) as well as a guest device, and is mostly a shortcut for
           defining the corresponding -blockdev and -device options.
```
so I thought that `-device` was unnecessary.

I am not sure my `-drive` commands for the cd-rom entries are correct, should I also try to use an explicit device there? It is a bit more tricky as I want two cd-roms drives. Is there a user manual somewhere about these command line options and the right use of them? I couldn’t understand how to proceed with the man page of qemu. (Incidentally, the man page does not mention how to use `bootindex`, though I suppose this is not the problem here as Windows boots fine.) And, should I use `-blockdev`?

**Comment by oliviercailloux** [comment]
I just realized that the cause is probably a corrupted Windows ISO (the file from which I try to install Windows). It is only 1 GB whereas it is supposed to be around 4 GB, if I understand correctly. I’ll confirm with colleagues and download it again.

I can’t try it now because we’re out of office hours but I wanted to make sure I am not wasting more of your time, in the meantime.

**Comment by oliviercailloux** [comment]
I confirm that with the correct ISO, the install works without a problem with the VirtIO drivers. Sorry for wasting your (and my) time!

**Comment by YanVugenfirer** [comment]
@oliviercailloux no problem!

Great to hear that everything worked out.
