### ISSUE TITLE
Windows 7 qxl driver memory problem

### ISSUE THREAD

**Issue by mirek967** [virtio-win/kvm-guest-drivers-windows#529]
Frequently I use  4k screen for my virtual machines. For normal operation on 4k screen I have to set vgamem="32768" as parameter of QXL driver.
When I do it, my machines suffer of random hanging of the display. When it happen, I cannot do anything with the machine, except forced shut down or shut down from virsh using shut down comman with mode=agent.
I can also ping the machine, which means, that machine is still running.
When hang off, machine cannot be connected via rdp too.

The problem doesn't occur, when I set up vgamem="16384" and connect via spice.
The problem doesn't occur, when I set up vgamem="32768" and connect via rdp.
The problem occur, when I set up vgamem="32768" and connect via spice.

**Comment by ybendito** [comment]
@mirek967 I see you already created an issue in the proper place, https://gitlab.freedesktop.org/spice/win32/qxl/-/issues/2
As far as I know this project (qxl for XP...Win7) is actually EOL as well as all the operating systems it is compliant to.
