### ISSUE TITLE
EWDK 1809 generates various warnings 1303

### ISSUE THREAD

**Issue by rob-scheepens** [virtio-win/kvm-guest-drivers-windows#541]
EWDK 1809 generates various warnings 1303:
```
C:\git\kvm-guest-drivers-windows\viorng\viorng\viorng.inf(98-98): warning 1303: Found legacy AddReg operation defining co-installers (CoInstallers32). [C:\git\kvm-guest-drivers-windows\viorng\VirtRNG Package\VirtRNG Package.vcxproj]
C:\git\kvm-guest-drivers-windows\viosock\sys\viosock_wow_co.inx(99-99): warning 1303: Found legacy AddReg operation defining co-installers (CoInstallers32). [C:\git\kvm-guest-drivers-windows\viosock\sys\viosock.vcxproj]
```

**Comment by hammerg** [comment]
It is a known issue which I'm not sure how to solve. It seems that Microsoft dropped the support for CoInstallers (expect for WDF) without giving alternative solution. So the choice is between having warning for now while the users can still install the driver using only the INF file or remove the CoInstaller and add a requirement an installer program.

**Comment by CaptainFlint** [comment]
As it happens, now it's more than just a warning. When you try to get Microsoft attestation signature, it considers the INF validation failed, and refuses to sign the drivers. The error message is the same: "Found legacy AddReg operation defining co-installers (CoInstallers32)."

**Comment by YanVugenfirer** [comment]
Coinstallers are removed from the INF
