### ISSUE TITLE
viorng: implement rng using CNG instead of CryptoAPI

### ISSUE THREAD

**Issue by rob-scheepens** [virtio-win/kvm-guest-drivers-windows#549]
Microsoft recently took down the CPDK download link. I am consulting with Microsoft on this, but I suspect it is because CryptoAPI is deprecated and superseded by CNG, see https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal.

Building win8/8.1/10 using EWDK fails because of this, since bcrypt_provider.h is not included in EWDK, only bcrypt.h (CNG) is. We need to implement a new rng using the CNG API, likely using BCryptGenRandom(), https://docs.microsoft.com/en-us/windows/win32/api/bcrypt/nf-bcrypt-bcryptgenrandom.

cc: @hammerg

**Comment by ybendito** [comment]
@rob-scheepens The CPDK is not related to CryptoAPI, this is _provider_ part of CNG. The point of virio-rng device and driver is that it installs itself as a provider of cryptographic services, we can't use BCryptGenRandom, we _implement_ it. I've attached the installer files (got from cache of packages on the machine where it is installed).
[CPDK.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/5923511/CPDK.zip)

**Comment by rob-scheepens** [comment]
@ybendito thanks for the insights. Do we have an alternative to remove the dependency on bcrypt_provider.h?

**Comment by rob-scheepens** [comment]
Got confirmation from Microsoft that CPDK download will be up in a few days. Once confirmed, I'll close this issue.

**Comment by rob-scheepens** [comment]
Microsoft confirmed that https://www.microsoft.com/en-us/download/details.aspx?id=30688 is up again. Checked it, and all is ok now. Closing now.
