### ISSUE TITLE
kvm command line options?

### ISSUE THREAD

**Issue by marcello-pietrobon** [virtio-win/kvm-guest-drivers-windows#555]
I am trying to convert these xml lines, that are working quite well with virt-manager
(as described in [https://libvirt.org/kbase/virtiofs.html](https://libvirt.org/kbase/virtiofs.html)):

```
<filesystem type="mount" accessmode="passthrough">
  <driver type="virtiofs" queue="1024"/>
  <binary path="/usr/lib/qemu/virtiofsd" xattr="on">
    <cache mode="always"/>
    <lock posix="on" flock="on"/>
  </binary>
  <source dir="/shr/linux"/>
  <target dir="shared"/>
  <alias name="fs0"/>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x09" function="0x0"/>
</filesystem>

```

into the corresponding options for a command of the like:
`qemu-system-x86_64 -enable-kvm .....`

The reason I'm asking is that, while virtio-fs is beautifully fast, my win10 VM gets very frequent 5 second pauses when I do normal operations when interacting with GUI applications...

Thanks a lot for any answer.

**Comment by hammerg** [comment]
Try to execute your VM using virt-manager and then run "ps auxwww" to see the relevant QEMU command line.

**Comment by marcello-pietrobon** [comment]
I tried quite a bit.

Starting from what suggested and after simplifying, I went down to two problems.

To make my life simpler I switched to a linux guest because the issue doesn't change and I believe this code stays the same.

I copied the folder /var/lib/libvirt/qemu/domain-distro/ from a similar folder created by virt-manager on a previous session:

Here's is the code:

```
/usr/lib/qemu/virtiofsd \
--fd=32 \
-o source=/shared/shrLnx/shrAntix,cache=always,xattr,flock,posix_lock

/usr/bin/qemu-system-x86_64 -enable-kvm \
-name guest=distro,debug-threads=on \
-m 2G \
\
-chardev socket,id=charmonitor,fd=32,server,nowait \
-mon chardev=charmonitor,id=monitor,mode=control \
\
-chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-9-distro/fs0-fs.sock \
-device vhost-user-fs-pci,chardev=chr-vu-fs0,queue-size=1024,tag=shared \
-object memory-backend-file,id=mem,size=4G,mem-path=/dev/shm,share=on -numa node,memdev=mem \
-device vhost-user-fs-pci,queue-size=1024,chardev=chr-vu-fs0,tag=shared \
\
-drive file=/var/lib/libvirt/images/distro.qcow2,format=qcow2,cache=none,if=virtio \
-vga virtio \
& disown


```


- I don't know if I have to run the first '/usr/lib/qemu/virtiofsd' line,
but from that I get the error:
> virtio_session_mount: Waiting for vhost-user socket connection...
> vhost socket accept: Bad file descriptor


- and after that I get the error:

> qemu-system-x86_64: -chardev socket,id=charmonitor,fd=32,server,nowait: File descriptor '32' is not a socket


- if I remove the two 'charmonitor' lines the error above obviously disappear and I get the error:
> $ qemu-system-x86_64: -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock: Failed to connect to '/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock': Permission denied


- if I do (for the moment) chown $USER and chmod 777 on that fs0-fs.sock file
the error becomes:

> $ qemu-system-x86_64: -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock: Failed to connect to '/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock': Connection refused


Can you keep helping me a bit longer?
Thank you.

**Comment by hammerg** [comment]
>     * I don't know if I have to run the first '/usr/lib/qemu/virtiofsd' line,
>       but from that I get the error:

You must run it if you want to use virtiofs for file sharing. Rather than using a file descriptor in the command line you can use a socket, so you command line will look something like:
```
./virtiofsd --socket-path=/tmp/vhostqemu -o source=/tmp/shared -o cache=always -d
```
 
> > qemu-system-x86_64: -chardev socket,id=charmonitor,fd=32,server,nowait: File descriptor '32' is not a socket

Your QEMU command line should include:
```
        -chardev socket,id=char0,path=/tmp/vhostqemu \
        -object memory-backend-file,id=mem,size=4G,mem-path=/dev/shm,share=on -numa node,memdev=mem \
        -device vhost-user-fs-pci,chardev=char0,tag=myfs \
```
 
>     * if I remove the two 'charmonitor' lines the error above obviously disappear and I get the error:
> 
> > $ qemu-system-x86_64: -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock: Failed to connect to '/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock': Permission denied
> 
>     * if I do (for the moment) chown $USER and chmod 777 on that fs0-fs.sock file
>       the error becomes:

This what I do too ;-). I haven't figure out yet how it should be setup properly.

> 
> > $ qemu-system-x86_64: -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock: Failed to connect to '/var/lib/libvirt/qemu/domain-distro/fs0-fs.sock': Connection refused
> 
> Can you keep helping me a bit longer?
> Thank you.

There is nothing to it. I hope it helps.

    Gal.

**Comment by marcello-pietrobon** [comment]
Hi Gal,
thank you so much for your instructions, the helped a lot and they did work.

After 20 days of pause I used them again and discovered that randomly the mapping doesn't work.
I mean that if I reboot (or restart the VM), sometimes the files created on the guest **_do not_** appear on the host (or vice versa)
Sometimes it does work after few minutes, sometimes I see the files created in the previous VM session but not those created on the current one, Other times it works right away no problems.

Now, as I just tried with a Linux (not Windows) guest, **_I wonder if there's a place where I can post about this issue_** and see if somebody can help me. I sure don't want to take your time.

Here's the code I used (run as root for now, as we said).


```

#!/bin/bash

/usr/lib/qemu/virtiofsd --socket-path=/tmp/vhostqemu \
-o source=/tmp/shared/ -o cache=always -d \
& disown

qemu-system-x86_64 -enable-kvm \
-m 2G \
-drive file=/var/lib/libvirt/images/AntiX-19.3.qcow2,format=qcow2,cache=none,if=virtio \
\
-object memory-backend-file,id=mem,size=2G,mem-path=/dev/shm,share=on \
-numa node,memdev=mem \
-chardev socket,id=char0,path=/tmp/vhostqemu \
-device vhost-user-fs-pci,queue-size=1024,chardev=char0,tag=myfs \
\
-vga virtio \
\
& disown

```

The /tmp/shared/ folder is owned by me ($USER) (part of the libvirt group) with 700 permissions,
0 drwx------ 1 marcello marcello 26 Mar 11 18:42 shared
Filesystem is ext4 on btrfs (non encrypted) on Manjaro 511.

**Comment by YanVugenfirer** [comment]
@marcello-pietrobon Hi Marcello,

I think a place to post the issue will be here: https://gitlab.com/qemu-project/qemu/-/issues
