### ISSUE TITLE
我使用了virtio-win-0.1.190.iso 最新版版本，vioscsi.sys出现黑屏 0xc0000428代码，无法进行GPT分区模式下启动引导

### ISSUE THREAD

**Issue by 1265578519** [virtio-win/kvm-guest-drivers-windows#557]
我使用了virtio-win-0.1.190.iso 最新版版本，vioscsi.sys出现黑屏 0xc0000428代码，无法进行GPT分区模式下启动引导
![image](https://user-images.githubusercontent.com/6442439/109540859-050dbb80-7afe-11eb-9248-34e2a1d0ece7.png)

如果分区为MBR，则可以正常使用。

**Comment by vrozenfe** [comment]
Are you trying UEFI or what is your guest configuration?
Thanks,
Vadim.

**Comment by 1265578519** [comment]
对的，我尝试GPT格式，以UEFI启动它

**Comment by 12101111** [comment]
0xc0000428 :Windows cannot verify the digital signature for this file
But why do you install virtio drivers on a Hyper-v guest?

**Comment by 1265578519** [comment]
> 0xc0000428：Windows无法验证此文件的数字签名，
> 但是为什么要在Hyper-v guest虚拟机上安装virtio驱动程序？

我在hyper安装他做成vhdx文件，导入vultr kvm vps进行使用。

**Comment by vrozenfe** [comment]
I'm not fully following the conversation, but if it is UEFI setup, then drivers 
from build 190 will not work in any case, because they are nether WHQL, 
nor Attestation signed .
We do currently have an attestation signed build, but it is not publicly available yet.

Best,
Vadim.

**Comment by 1265578519** [comment]
> I'm not fully following the conversation, but if it is UEFI setup, then drivers
> from build 190 will not work in any case, because they are nether WHQL,
> nor Attestation signed .
> We do currently have an attestation signed build, but it is not publicly available yet.
> 
> Best,
> Vadim.

谢谢回复，看来就是没有WHQL签名引起的，要使用UEFI是因为要用GPT，磁盘大于2TB。

**Comment by 1265578519** [comment]
预计什么时候会发布带WHQL签名的virtio-win-xxxxx.iso

**Comment by jwatt** [comment]
@vrozenfe are the 204 builds attestation signed?

**Comment by vrozenfe** [comment]
Right. 
All Win10 drivers for all platforms (x86/amd64/arm64) are attestation signed.
Vadim.
