### ISSUE TITLE
viosock: BSOD

### ISSUE THREAD

**Issue by kcrazy** [virtio-win/kvm-guest-drivers-windows#558]
Hi,
I got a BSOD while testing 
[minidump.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/6066959/minidump.zip)

**Comment by irudakov77** [comment]
Hi, 

Thanks for the dump, and thanks for waiting, I will make a pull request tomorrow.

Regards,
Ilya

**Comment by jwatt** [comment]
> I will make a pull request tomorrow.

@irudakov77 Did that happen? Can this be closed now?

**Comment by irudakov77** [comment]
https://github.com/virtio-win/kvm-guest-drivers-windows/commit/dfb56d7d6cff1b2be7b8ffeaa31f8457358b55b9#diff-fd758b0f1c679ffc4df380fd8000a970ea873cb5f9a2988bfb9134274bf5453a
Please close

**Comment by jwatt** [comment]
The reporter, @kcrazy, or someone else who has permissions (I do not) will need to close the issue.

**Comment by YanVugenfirer** [comment]
> [dfb56d7#diff-fd758b0f1c679ffc4df380fd8000a970ea873cb5f9a2988bfb9134274bf5453a](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/dfb56d7d6cff1b2be7b8ffeaa31f8457358b55b9#diff-fd758b0f1c679ffc4df380fd8000a970ea873cb5f9a2988bfb9134274bf5453a)
> Please close

Closing.
