### ISSUE TITLE
Windows 10 guest not seeing free memory with balloon driver

### ISSUE THREAD

**Issue by Ristovski** [virtio-win/kvm-guest-drivers-windows#568]
Enabling the balloon driver works as expected - host memory gets released, but this also causes the Windows 10 guest to think that the released memory is in-use and reports upwards of 99% RAM usage.

Here is a screenshot of enabling and disabling the `VirtIO Balloon Driver` device in Device Manager.
The memory on the host side does indeed get released and reclaimed as usual, but on the guest side, enabling the driver causes Windows to think that the memory is in-use (thus the peak in the memory graph).

![1619621519](https://user-images.githubusercontent.com/994445/116424773-1515f300-a842-11eb-8024-513e9f400f0b.png)

The main issue is that this causes Windows to drop caches to disk, which causes degraded performance, and I assume it also will never get more memory ballooned.

**Comment by ybendito** [comment]
@Ristovski Please provide more info about the issue: which hypervisor you use: qemu (which?) or something different, how do you inflate the balloon, what is exactly the sequence of operations to reproduce the problem.

**Comment by Ristovski** [comment]
@ybendito I use `virt-manager` with qemu-system-x86_64 5.2.0.
I don't explicitly balloon it myself, I set the memory settings in `virt-manager` as follows:
![1619623530](https://user-images.githubusercontent.com/994445/116430022-bc952480-a846-11eb-82a7-da192881b197.png)

and also have the following entry in the xml:
```
<memballoon model="virtio" autodeflate="on">
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
</memballoon>
```

From my understanding, the intended behavior would be that the Windows guest would think the memory is free, and the ballooning driver would release/claim more transparently. Instead of this, the Windows guest idles at 99% RAM and doesn't seem to claim more memory. This means that Windows will not attempt to use any memory caches due to it thinking there is not enough free memory.

**Comment by Ristovski** [comment]
For reference, this is how it looks like right after the guest boots up:

![1619624080](https://user-images.githubusercontent.com/994445/116431371-04687b80-a848-11eb-9134-df907bf56a7a.png)

Using the guest like this as-is gives terrible performance, since the cache will quickly fill up and get paged to disk.
From my understanding, the guest balloon driver should be able to automatically request more memory from the host, but this is not the case (or is happening at 100% RAM usage, in which case its completely useless due to the aforementioned issue with caches and paging)

**Comment by ybendito** [comment]
IMO, completely correct behavior of the balloon. The guest is configured to run with [max of] 3.2G memory and use 1G. So the rest of memory is in the inflated balloon. When you disable the balloon driver the memory becomes free. When the balloon is enabled you can change the current allocation to be = max, this will deflate the balloon.
@hammerg Do I miss something?

**Comment by Ristovski** [comment]
@ybendito I assumed the ballooning was dynamic by default, but now I see this is not the case.

Closing as invalid.

**Comment by linuzer** [comment]
I have the very same observation on that behaviour. And although I have not much insight on the technical details behind the scenes, I have a hard time to understand how this could be expected behaviour...

Rather I would expect the same behaviour than with Hyper-V dynamic memory: From the host you tell the guest the range of memory it is allowed to use. The guest starts with the minimum and leaves the rest to the host. Later on, when the guest starts using more and more memory (e.g. opening some programs), in the same way the guest's used memory increases, the host's free memory decreases. And when you over provisioned the guest's memory, the host would even start swapping out the memory to the hard disk.

I thought the memory balloon tries to implement just this. Am I missing out some conceptual details?

**Comment by Ristovski** [comment]
@linuzer From what I was able to gather, I assume Windows does not support memory hot add/remove while Linux does. And indeed virtio memory ballooning with a Linux guest works as intended. 

Meanwhile with Windows guests the following happens:
Lets say you set the max memory to 4GB, and default to 2GB
 - the guest boots and sees 4GB of physical memory attached
 - the virtio balloon driver inside Windows fake "reserves"/locks the spare 2GB (I assume this just marks the pages as in-use)
 - to Windows, this looks like a driver allocating 2GB of RAM which it can not operate on, while in reality this memory gets released to the host

Now if you were to update the virtio ballooning parameters at runtime, this would simply cause the virtio balloon driver to free or reserve additional memory.

I am not sure how Hyper-V does it (perhaps Windows detects its running under Hyper-V and enables different memory management?), but I assume this is the only alternative.

**Comment by linuzer** [comment]
OH, I see. Thanks a lot for the explanation! So in other words, the balloon-driver does it the linux-way, which works perfect in a linux guest, but on a Windows guest it just provokes the above results. Of course, changing the parameters on-the-fly could somehow improve the situation. 

Would it be right to asume, that the Windows-part of the balloon-driver just needs to be adopted to the Hyper-V-way/Windows-way of memory management to get the same behaviour under Windows?

**Comment by vrozenfe** [comment]
Doing it the same way as Hyper-V does can be a problem.
Hyper-V dynamic memory (dmvsc.sys) DmcHotAddPageRange function built around MmAddPhysicalMemory DDI which is reserved for system use https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/_kernel/

**Comment by ohault** [comment]
@vrozenfe MmAddPhysicalMemory is not documented https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-wdm-mmaddphysicalmemory

**Comment by vrozenfe** [comment]
@ohault 
Thanks a lot for the information.
AFAIK Microsoft did it quite recently, still claiming that the following functions  MmAddPhysicalMemoryEx, MmRemovePhysicalMemory and MmRemovePhysicalMemoryEx are " reserved for system use"  https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/_kernel/

Best,
Vadim.

**Comment by qixinwuchen** [comment]
@Ristovski  windows vm only use 1 GB ram，and I allocate it for  3 GB ram， why rss display  3 GB？
the vm has already install virtio balloon driver,  and configured memballoon tag in libvirt xml，
I think rss should display  1 GB，right？
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/33652818/3be4b304-a7e4-4242-baf4-dc661248f55c)



<domain type='kvm'>
  <name>3707e1622a1147965e90781c446bfa16</name>
  <uuid>3707e162-2a11-4796-5e90-781c446bfa16</uuid>
  <description>data_verify_2.216</description>
  <memory unit='KiB'>8377344</memory>
  <currentMemory unit='KiB'>8377344</currentMemory>
  <vcpu placement='static'>15</vcpu>
  <sysinfo type='smbios'>
    <bios>
      <entry name='vendor'>KEPTDATA</entry>
    </bios>
    <system>
      <entry name='manufacturer'>keptdata_verify</entry>
      <entry name='product'>One2Data</entry>
    </system>
  </sysinfo>
  <os>
    <type arch='x86_64' machine='pc-i440fx-rhel7.0.0'>hvm</type>
    <smbios mode='sysinfo'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-model' check='partial'>
    <model fallback='allow'/>
  </cpu>
  <clock offset='localtime'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/byk/656C3B42-DCD2-E911-5EAF-8C3702847410_8d002c5db067fde9287559059cccf3ab/hd0_20240124121045000_esoqnt_realtime_app.qcow2'/>
      <target dev='vda' bus='virtio'/>
      <boot order='1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <interface type='bridge'>
      <mac address='00:50:56:bb:87:ae'/>
      <source bridge='subnet_100_v'/>
      <model type='e1000'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='0.0.0.0'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <video>
      <model type='vga' vram='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>
  </devices>
</domain>
