### ISSUE TITLE
virtio-fs driver for win7 missing in the published binaries

### ISSUE THREAD

**Issue by ratcashdev** [virtio-win/kvm-guest-drivers-windows#576]
As the title says. Is this on purpose?

**Comment by YanVugenfirer** [comment]
@ratcashdev Yes, Win7 is not supported by virtio-fs: https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/viofs/viofs.sln

**Comment by ratcashdev** [comment]
Would it be a huge undertaking to port it (let's disregards for a second that win7 is getting more and more a pain to get installed and used thanks to all the certificate issues), or is it just about linking with the correct headers and creating the corresponding project/inf files?
It's just it's way smaller in terms of GB for a VM than Win10.
Other than that, please feel free to close this. Thanks.

**Comment by YanVugenfirer** [comment]
Closing. Sorry, we decided to stop the support of Win7 in master branch.
