### ISSUE TITLE
Windows 10 1511 x64 install to vioscsi-connected disk hangs

### ISSUE THREAD

**Issue by steven676** [virtio-win/kvm-guest-drivers-windows#58]
The Windows 10 1511 x64 installer stops at "Getting files ready for installation" when attempting to install to a virtio-scsi disk using the vioscsi driver from virtio-win 0.1.112-1 or 0.1.113-1 as distributed by Fedora.  CPU and disk activity (as seen by the host) stops and the installer never shows any progress beyond 4-6%, though I can move the mouse and cancel the installation.

This is a regression from virtio-win 0.1.110-2 -- the Windows 8.1 drivers from that build work fine.  The host is running Linux kernel 4.1.20 and the VM is running in QEMU 2.5.1 using KVM.

**Comment by vrozenfe** [comment]
Thanks, we have this issue reported in bugzilla already:
https://bugzilla.redhat.com/show_bug.cgi?id=1321903
Vadim.

**Comment by vrozenfe** [comment]
Fixed according to https://bugzilla.redhat.com/show_bug.cgi?id=1321903#c12

Vadim.
