### ISSUE TITLE
Driver IRQL Not Less or Equal BSOD Error

### ISSUE THREAD

**Issue by life777eternal** [virtio-win/kvm-guest-drivers-windows#580]
Greetings, I have a Windows Web Server 2008 R2 on a KVM Ubuntu system which was crashing with the `Driver_IRQL_Not_Less_Or_Equal` BSOD Error. It happened again twice recently when extracting a large zip file with 7-zip. It's happened when restoring a backup of files, and other times as well. 

The Virtio drivers are the only ones I've installed, for the network, storage and some kind of 'balloon' driver. Also I thought that I might need updated Virtio Drivers so I found an Updated ISO for the Virtio Drivers and downloaded it to the VPS Control system, though the 64 bit exe setup file doesn't work on Windows Web Server 2008 R2, and when I tried to manually update the drivers from that ISO, I got the message that the most current or best drivers were already installed.

![2021-05-19-Driver-IRQL-Not-Less-Or-Equal-QEMU (v1022) - TightVNC Viewer](https://user-images.githubusercontent.com/25623649/118841462-9121ba80-b885-11eb-8a12-86ab984f2412.png)

![2021-05-17 Virtio-Win-QEMU (v1022) - TightVNC Viewer](https://user-images.githubusercontent.com/25623649/118842183-363c9300-b886-11eb-8341-dc873afa00d1.png)

![2021-05-19Best Driver-Already-Installed - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/118844088-e8288f00-b887-11eb-9aaf-fa3fb052f2ae.png)

Thank you.

Here's the Dump file: https://dropbox.com/sh/dz417bgsf3soj87/AABjQEAXwXMCaf82C-11ofZta?dl=0

**Comment by life777eternal** [comment]
This crash happened again recently when 7Zip was almost finished extracting a large OAR file. So I can't use 7Zip for that again. WinRAR works better for the larger files. 

![2021-09-06 17_11_36-QEMU (v1022) - TightVNC Viewer](https://user-images.githubusercontent.com/25623649/132388341-9e42d10b-27c6-48af-8f80-d335bd7d5301.png)


Then one of the task bar icons disappeared after the next startup, so I scheduled a Disk Check, and the icon reappeared after the disk check.

**Comment by vrozenfe** [comment]
@life777eternal 

Can you please zip the crash dump file and share it through dropbox or google drive ?

Thanks,
Vadim.

**Comment by life777eternal** [comment]
Might be able to later today, after work, and I already restarted my server after the crash. Not sure where to find it now though. I have a Dropbox account, aye.

**Comment by vrozenfe** [comment]
Thanks a lot,

Normally, after the system reboot , it should be stored as  C:\WINDOWS\MEMORY.DMP 

And, yes, the installer includes Win8/Win10 drivers only. It will not work on Web Server 2008 R2

**Comment by life777eternal** [comment]
Are you able to make an installer for Windows 7 / Windows Web Server 2008 R2? Or at least release drivers for Windows Web Server 2008 R2, for manual installation?   The dump file is 268 MB, do you have WinRAR or 7Zip? (for a RAR or 7Z file extraction). The compressed RAR file is 53 MB and the 7Z file is 46 MB. (& I actually made a ZIP file, just for comparison, and it's 68.9 MB)  ... (I'll edit the post above and add in the link, once I have it, so it doesn't get emailed through insecure email.)  Thank you.

**Comment by vrozenfe** [comment]
It looks as the viostor driver is extremely old (built on Jul 31st 2012). Where did you get it from? 
I suggest switching to the more recent one available from
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.196-1/virtio-win.iso

There is no installer for pre-Win8 platforms, but the driver updating procedure is quite straightforward when using "Device Manager"

 Best, Vadim.

**Comment by life777eternal** [comment]
Oh alright, thanks. The Network Administrator at the company hosting my server gave me this https://linux-kvm.org/page/WindowsGuestDrivers/Download_Drivers in a ticket. That might be the drivers I have had.

**Comment by life777eternal** [comment]
> It looks as the viostor driver is extremely old (built on Jul 31st 2012). Where did you get it from?
> I suggest switching to the more recent one available from
> https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.196-1/virtio-win.iso
> 
> There is no installer for pre-Win8 platforms, but the driver updating procedure is quite straightforward when using "Device Manager"
> 
> Best, Vadim.

Which device is supposed to use the Viostor driver? Windows thinks that all the device drivers are already up to date. That viostor.sys has always been on the BSOD Errors. 

![2021-09-09 22_48_53 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/132801775-4008caa3-f564-4f19-8e9e-7f136607f1af.png)

![2021-09-09 22_50_30- Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/132801790-0eb0f643-6f89-4f41-8457-055026178b04.png)

![2021-09-09 22_51_39 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/132801807-4ef42778-446b-4806-9ad5-398c65ffea26.png)

![2021-09-09 22_53_39 - Remote Desktop Connection](https://user-images.githubusercontent.com/25623649/132801822-9c04e3bb-92b1-42b7-afec-a6aa09c7df76.png)

**Comment by vrozenfe** [comment]
Start "Device Manager" go to "Storage Controllers" right click on "Red Hat VirtIO SCSI controller" -> "Update Driver" -> "Browse My Computer.." 
and navigate to virtio-win.iso_mount_point\viostor\2k8R2\amd64\

**Comment by life777eternal** [comment]
Thanks, I tried that and Windows still thinks that the best driver software is already installed and skipping the new driver.

**Comment by life777eternal** [comment]
> It looks as the viostor driver is extremely old (built on Jul 31st 2012). Where did you get it from? I suggest switching to the more recent one available from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.196-1/virtio-win.iso
> 
> There is no installer for pre-Win8 platforms, but the driver updating procedure is quite straightforward when using "Device Manager"
> 
> Best, Vadim.

Greetings Vadim, I've noticed that there's a newer one available as of this year. Should I try to use that one? https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.248-1/virtio-win.iso 

Thank you, Shalom.

**Comment by vrozenfe** [comment]
Hi @life777eternal  ,

It is always a good decision to update the drivers with the latest ones, when it is possible. Just please note that we discontinued building Win8/8.1 and WS2012/2012R2 virtio-win drivers recently and removed these drivers from virtio-win installer (while they are still can be found on ISO and installed manually via the Device Manager).   

All the best and Shalom :)
Vadim.
