### ISSUE TITLE
Is more than one filesystem supported?

### ISSUE THREAD

**Issue by Dave--G** [virtio-win/kvm-guest-drivers-windows#581]
Adding a 2nd `<filesystem>` element in a windows vm.xml and booting the vm results in only the first filesystem showing up.  The expected result is the second filesystem would show up as a second mapped drive but this isn't happening.

How would multiple filesystems be handled when an -m x: argument is specified on the virtiofs.exe command line?

Soft symlinks don't appear to be handled as expected either, in my test a symlink to a directory in the shared folder shows up as a file not a directory.  This would be a nice workaround if available.  It would enable the administrator to set up a single directory per vm that contains a set of symlinks to the local filesystem and cifs/etc mountpoints.

What's the suggested strategy for setting up multiple host shares to windows guests?

**Comment by hammerg** [comment]
Currently you can share only one folder between a guest and host.

As for the symbolic link question, it seem that you describing an old bug that was already resolved. What version of the virtiofs service are you running?

**Comment by davispuh** [comment]
I'm also interested in sharing multiple folders. Current solution with being able to share only single folder is very limiting.

**Comment by noscript** [comment]
Please reopen.

**Comment by noscript** [comment]
Continued in https://github.com/virtio-win/kvm-guest-drivers-windows/issues/590
