### ISSUE TITLE
Virtio-fs fails on vm reboot

### ISSUE THREAD

**Issue by Dave--G** [virtio-win/kvm-guest-drivers-windows#584]
Currently I have virtiofs.exe configured to start using a batch file since running it as a service appears to trigger the read-only filesystem problem I reported earlier.  This batch file is started manually after user login into the vm.  In this scenario it works.

However, if the vm is restarted, virtiofs.exe freezes instead of running correctly.

If the vm is then fully shut down and started, virtiofs.exe starts correctly.

I.e. this failure only occurs on vm reboot.

The problem is 100% reproducible.  The test system is running all the latest versions, host & guest.

**Comment by hammerg** [comment]
Is [my comment](https://github.com/virtio-win/kvm-guest-drivers-windows/issues/473#issuecomment-848630520) in a previous thread relevant to this problem?

Thanks, Gal.

**Comment by Dave--G** [comment]
Your comment was in response to mine :) so I replied there.  I'm happy to close this bug if it's just my running on an old version.
