### ISSUE TITLE
Feature: implement vRDMA

### ISSUE THREAD

**Issue by rob-scheepens** [virtio-win/kvm-guest-drivers-windows#588]
Recently I was reading up on virtio RDMA (vRDMA) at https://www.mikelangelo-project.eu/technology/vrdma-virtio-remote-direct-memory-access/, and this seems like an interesting feature to have.

**Comment by rob-scheepens** [comment]
I suspect implementing NDK support is the first step towards this, see https://docs.microsoft.com/en-us/windows-hardware/drivers/network/initializing-an-ndk-capable-miniport-driver.

**Comment by YanVugenfirer** [comment]
Yes, I thought about support NDK yesterday.
I will see how we can build a roadmap for the support of those features.

**Comment by YanVugenfirer** [comment]
virtio-rdma was removed from QEMU. Closing for now.
