### ISSUE TITLE
viogpu  not work in windows7  x64

### ISSUE THREAD

**Issue by zhongguo1987** [virtio-win/kvm-guest-drivers-windows#591]
I have successfully compiled the viogpu driver project to support Windows 7,The environment configuration is as follows： 
       host:  centos 8.4
       vm:    windows 7 x64
       In Vm,Through the administrator command DevCon update viogpudo. Inf "PCI / ven"_ 1AF4&DEV_ 1050&SUBSYS_ 11001AF4&REV_ 01 "for installation,buf failed
       
![image](https://user-images.githubusercontent.com/3292981/123614174-ab609800-d836-11eb-8fa7-cc9c753893b5.png)
       How should I set up to make viogpu work in Windows 7，Thank you!

**Comment by vrozenfe** [comment]
Unfortunately viogpu was not designed to work on Win7. It is WDDM 1.2 display driver, supposed to work on Win8/Win10 platforms. The current status is that it WHQL-ready on Win10 platforms, fully functional on Win8.1/WS2012R2 and in the process
of bug fixing on Win8/WS2012

Vadim.

**Comment by zhongguo1987** [comment]
> Unfortunately viogpu was not designed to work on Win7. It is WDDM 1.2 display driver, supposed to work on Win8/Win10 platforms. The current status is that it WHQL-ready on Win10 platforms, fully functional on Win8.1/WS2012R2 and in the process
> of bug fixing on Win8/WS2012
> 
> Vadim.

Thank you
