### ISSUE TITLE
Incompatibilites between versions?

### ISSUE THREAD

**Issue by abbbi** [virtio-win/kvm-guest-drivers-windows#592]
hi,

i came accross following situation and wanted to ask some questions:

I have an existing Windows Server 2016 on libvirt  5.0.0-4 (debian buster) with virtio-win drives verison 0.1.141 (yes, pretty old)
using both virtio drives for the network and the virtual disks.

Lately i have attempted to migrate the virtual machine (as it is) to a debian bullseye system, running libvirt 7.x.
The virtual machine boots up nicely, but i noticed two things:

1) The Original network adapter as removed from the list of available windows adapters and was re-assigned
a new adapter with # 2, as scuh the windows system lost its network connectivity.
2) The second disk device was deactivated by the windows group policy, as it appears to have experienced some
duplicate serial number during detection (minor issue)

The virtual machine configuration was imported on the new system "as is" without any changes, mac addresses and
disk assigments were unchanged.

In detail i care more about issue 1), because this is a pretty bad situation in Domain controller or exchange virtual
machine environments. My question is: could the re-assigment of the network adapter be caused by the old virtio driver
versions used?

Edit: the virtual machine configuration, especially the pci enumeration settings have not changed in any noticable
way between export and import on the new host system.

**Comment by YanVugenfirer** [comment]
@abbbi Hi Michael,

Yes, usually the most probable explanation is that network and storage drivers changed their locations on PCI bus. As a result, Windows "thinks" those are new devices and therefore creating additional SW devices for each one of them with default settings.
I suggest double-checking the following:
* Could it be that now it is Q35, and previously it was an old chipset?
* Check or even force the exact PCI bus address in libvirt XML (if possible)
* Use device manager in Windows to compare the PCI topology in general

As far as I know, the old driver version should not drop their settings.

**Comment by abbbi** [comment]
@YanVugenfirer 

hi, thanks for your quick response. There are no obvious differences between the libvirt configuration from
what i can see. Heres a gist between the new and the old libvirt version, PCI id's stay the same:

 https://gist.github.com/abbbi/56dab2ea459dc4b49f7d3aaea1a973dd

so the chipset hasnt changed, too.
I also compared the qemu command line options, with no obvious differences.

**Comment by YanVugenfirer** [comment]
@abbbi Can you please post the qemu command lines as well?

**Comment by abbbi** [comment]
sure, this is from the buster system:

`qemu-system-x86_64 -enable-kvm -name guest=dc01,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-3-dc01/master-key.aes -machine pc-i440fx-2.8,accel=kvm,usb=off,vmport=off,dump-guest-core=off -cpu Skylake-Client,ss=on,hypervisor=on,tsc_adjust=on,clflushopt=on,umip=on,xsaves=on,pdpe1gb=on,hv_time,hv_relaxed,hv_vapic,hv_spinlocks=0x1fff -m 6144 -realtime mlock=off -smp 3,sockets=3,cores=1,threads=1 -uuid 1718d28f-00b9-4b1c-be6f-51ed3423bb8e -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=26,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot menu=off,strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -drive file=/vm/ata2018/dc01.raw,format=raw,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x8,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1,write-cache=on -drive file=/vm/ata2018/dc01-2.raw,format=raw,if=none,id=drive-virtio-disk1,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk1,id=virtio-disk1,write-cache=on -netdev tap,fd=28,id=hostnet0,vhost=on,vhostfd=29 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:bd:45:7a,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0,bus=usb.0,port=1 -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x7 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on`

and from the bullseye (libvirt 7.x):

`/usr/bin/kvm -name guest=dc01,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-4-dc01/master-key.aes -machine pc-i440fx-2.8,accel=kvm,usb=off,vmport=off,dump-guest-core=off,memory-backend=pc.ram -cpu qemu64,hv-time,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff -m 6144 -object memory-backend-ram,id=pc.ram,size=6442450944 -overcommit mem-lock=off -smp 3,sockets=3,cores=1,threads=1 -uuid 1718d28f-00b9-4b1c-be6f-51ed3423bb8e -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=34,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot menu=off,strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -blockdev {"driver":"file","filename":"/vm/ata2018/dc01.raw","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -device virtio-blk-pci,bus=pci.0,addr=0x8,drive=libvirt-2-format,id=virtio-disk0,bootindex=1,write-cache=on -blockdev {"driver":"file","filename":"/vm/ata2018/dc01-2.raw","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-1-storage"} -device virtio-blk-pci,bus=pci.0,addr=0x4,drive=libvirt-1-format,id=virtio-disk1,write-cache=on -netdev tap,fd=36,id=hostnet0,vhost=on,vhostfd=37 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:bd:45:7a,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0,bus=usb.0,port=1 -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x7 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on`

**Comment by YanVugenfirer** [comment]
The problem can be because of the QEMU. I see that Bullseye using 5.2: https://packages.debian.org/bullseye/qemu

The problem is described here: https://bugzilla.redhat.com/show_bug.cgi?id=1934158

The paths to fix were sent upstream, as far as I know.
