### ISSUE TITLE
Unknown ACPI Devices (no drivers for Windows 11 ARM64)

### ISSUE THREAD

**Issue by excelsi** [virtio-win/kvm-guest-drivers-windows#595]
Under Windows 11 ARM64 i have a lot of ACPI Devices with no drivers:

![image](https://user-images.githubusercontent.com/8747559/124510467-29dbad80-ddd4-11eb-8a32-fa1f93628ca3.png)

Would be nice to have there Qemu Virtio Drivers for these ACPI Devices.
Thanks!

**Comment by YanVugenfirer** [comment]
Currently, we only support virtio-pci devices and not virtio-mmio devices.

What's the platform you are using?

**Comment by excelsi** [comment]
Im using Qemu 6 on Windows with this VM Config:

"C:\Program Files\qemu\qemu-system-aarch64.exe" ^
-M virt,virtualization=true ^
-accel tcg,thread=multi ^
-cpu cortex-a57 ^
-smp 2 ^
-m 4G ^
-bios "C:\Program Files\qemu\share\edk2-aarch64-code.fd" ^
-device ramfb ^
-device qemu-xhci ^
-device usb-kbd ^
-device usb-tablet ^
-netdev user,id=net0,hostfwd=tcp::5555-:3389 -device virtio-net,netdev=net0,disable-legacy=on ^
-drive file=E:\VM\Qemu\sys.qcow2,if=virtio

**Comment by excelsi** [comment]
Currently im using a special patched version of Qemu 6 since there was Bug running Windows ARM64 in the orginally released Version:
https://gitlab.com/qemu-project/qemu/-/issues/367

**Comment by YanVugenfirer** [comment]
If you are using QEMU, try to use virt machine type. Check the thread on how other people managed to ran Windows with virtio-net drivers.

**Comment by excelsi** [comment]
is this Option "-M virt" the Virt Machine Type...?
The other devices like storage and network are running fine with the provided drivers.

**Comment by excelsi** [comment]
It's not cirtical for me to get the drivers for the ACPI Devices only want to mention that what i have seen ;-)

**Comment by YanVugenfirer** [comment]
Yes. "-M".
