### ISSUE TITLE
win2008r2 amd64 crash when using same backingfile

### ISSUE THREAD

**Issue by paymentslab** [virtio-win/kvm-guest-drivers-windows#6]
Environment:

labuser@os-cloud-2:~$ uname -a
Linux os-cloud-2 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

labuser@os-cloud-2:~$ kvm --version
QEMU emulator version 1.0 (qemu-kvm-1.0), Copyright (c) 2003-2008 Fabrice Bellard

Multiple version drivers (up to build-48) from:
http://people.redhat.com/vrozenfe/

Openstack Folsom is used for deployment

libvirt:
cache=none
image=qcow2
# 

I've been tracking down an issue that when I deploy multiple win2k8r2 instances that end up using the same backingfile (at it seems this is the issue) I end up with a BSOD for every instance _except_ the first. This happens often directly when applying the new settings to the generalized instance and sometimes to a running instance.  (DRIVER_IRQL_NOT_LESS_OR_EQUAL)

If I make the backingfile unique per instance the problem seems to go away, but needless to say that is not a situation I would like to maintain.

I can provide a minidump and even provide access to the environment if that helps tracking down the issue.

**Comment by vrozenfe** [comment]
Using the same backend file is a quite unusual and dangerous scenario. Modern qemu fails with " Failed to get "write" lock error" to prevent such kind of situation. Using virtio-scsi (+LIO Target) is the right way to establish multiply connection to the same backend storage from single or multiply VM(s).

Closing this issue as it will not be fixed.
Vadim.

**Comment by bolkedebruin** [comment]
That’s a bit strange, cause this is often the default for cloud systems in order to preserve storage. But I’m quite sure you are misinterpreting the issue? One backing file works in a copy on write fashion. It works as the base image and changes are written to a different file. I don’t consider this “dangerous”. 

This issue was opened 5 years ago not sure if it still persists.

**Comment by vrozenfe** [comment]
I'm probably wrong, but in my understanding sharing the same backend storage between several VMs supposed to imply some sort of IO synchronisation like SCSI-3 PR to keep it running safely. viostor driver was not designed to work in this mode.
