### ISSUE TITLE
Windows 10 Pro 1803 Build 17134.1304 BSOD SYSTEM SERVICE EXCEPTION

### ISSUE THREAD

**Issue by nathanshearer** [virtio-win/kvm-guest-drivers-windows#606]
Install a new Windows 10 Pro 1803 VM.
I used SW_DVD9_Win_Pro_Ent_Edu_N_10_1803_64BIT_English_-4_MLF_X21-87129.iso
- Q35 Chipset
- qemu/edk2-x86_64-code.fd UEFI firmware
- qemu SATA disk for the C drive
- qemu VirtIO disk for the D drive
- e1000e network adapter
- QXL video

Extract virtio-win-0.1.189.iso (latest stable version) to C:\tmp
Run C:\tmp\virtio-win-gt-x64.msi with default options
Wait for a few seconds after the install completes

The VM will crash with BSOD error "SYSTEM SERVICE EXCEPTION"
After booting back into windows the virtio SCSI Controller did not have any installed drivers
I manually intalled the Red Hat VirtIO SCSI viostor.sys driver

**Comment by YanVugenfirer** [comment]
@nathanshearer Hi Nathan, can you please provide the QEMU command line and crash dump?

**Comment by nathanshearer** [comment]
Sure, I saved the VM state before I installed the drivers, so reproducing the problem should be easy.
The windows crash dump file may be large, how do I share the file too you? Will a google drive link work?

**Comment by YanVugenfirer** [comment]
Yes, Google drive is OK.

**Comment by nathanshearer** [comment]
Here is the virsh xml file: [windows10-virsh.xml.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/6865951/windows10-virsh.xml.zip)

And here is the resulting qemu command:
`/usr/bin/qemu-system-x86_64 -name guest=windows10,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-63-windows10/master-key.aes -blockdev {"driver":"file","filename":"/usr/share/qemu/edk2-x86_64-code.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/windows10_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-q35-6.0,accel=kvm,usb=off,vmport=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram -cpu Opteron_G5,vme=on,x2apic=on,tsc-deadline=on,hypervisor=on,arat=on,tsc-adjust=on,bmi1=on,arch-capabilities=on,mmxext=on,fxsr-opt=on,cmp-legacy=on,cr8legacy=on,osvw=on,perfctr-core=on,virt-ssbd=on,npt=on,nrip-save=on,rdctl-no=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on -m 4096 -object memory-backend-ram,id=pc.ram,size=4294967296 -overcommit mem-lock=off -smp 4,sockets=4,cores=1,threads=1 -uuid 090291ed-0dac-4f50-b540-97c6ad6b1857 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=29,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global ICH9-LPC.disable_s3=1 -global ICH9-LPC.disable_s4=1 -boot strict=on -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 -device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 -device ich9-usb-ehci1,id=usb,bus=pcie.0,addr=0x1d.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pcie.0,multifunction=on,addr=0x1d -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pcie.0,addr=0x1d.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pcie.0,addr=0x1d.0x2 -blockdev {"driver":"file","filename":"/zpool01/vm/windows10.01.qcow2","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"driver":"qcow2","file":"libvirt-2-storage","backing":null} -device ide-hd,bus=ide.0,drive=libvirt-2-format,id=sata0-0-0,bootindex=1 -blockdev {"driver":"file","filename":"/zpool01/vm/windows10.02.qcow2","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"driver":"qcow2","file":"libvirt-1-storage","backing":null} -device virtio-blk-pci,bus=pci.2,addr=0x0,drive=libvirt-1-format,id=virtio-disk0 -netdev tap,fd=35,id=hostnet0 -device e1000e,netdev=hostnet0,id=net0,mac=52:54:00:f5:5f:50,bus=pci.1,addr=0x0 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 127.0.0.1:4 -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pcie.0,addr=0x1 -device virtio-balloon-pci,id=balloon0,bus=pci.3,addr=0x0 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on`

**Comment by vrozenfe** [comment]
@nathanshearer 

Hi Nathan,
Are you trying to build UEFI system with cross-signed drivers from virtio-win-0.1.189.iso ?
This configuration will not work. Try seabios instead or wait for a few more days  until 
virtio-win rpm with attestation signed drivers will be ready.

Vadim.

**Comment by nathanshearer** [comment]
I'll double-check my setup. I had difficulty reproducing it from my earlier snapshot to save the crash dump, so I have it on my todo list to start again with a fresh install to reproduce the issue.

**Comment by YanVugenfirer** [comment]
Please re-open is still there are crashes
