### ISSUE TITLE
Are there any plan to support "virtosfs" driver in session mode?

### ISSUE THREAD

**Issue by ilos-vigil** [virtio-win/kvm-guest-drivers-windows#618]
I wanted to mount a directory on Windows 10 guest, so i tried to edit guest config using command `virsh edit win10` by adding below codes after the line `<devices...`

```xml
<filesystem type="mount" accessmode="passthrough">
  <driver type="virtiofs"/>
  <source dir="/mnt/shared"/>
  <target dir="shared"/>
</filesystem>
```

However, when i save the config, i encountered this error message

```
error: unsupported configuration: virtiofs is not yet supported in session mode
Failed. Try again? [y,n,i,f,?]:
```

I tried editing guest config without `<driver type="virtiofs"/>`, but Device Manager only show "PCI device" with warning icon.

## Additional Information

* I installed Windows using `virt-install`
* Windows 10 Pro x64 19042.928
* I'm using this driver https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.204-1/virtio-win-0.1.204.iso

**Comment by ilos-vigil** [comment]
Hi, thanks for the suggestion. But i still receive similar error message since i use session mode (`qemu:///session`).

P.S. for other people who experience similar problem, i found workaround by using Windows RDP and SPICE's folder sharing.

**Comment by YanVugenfirer** [comment]
Closing the issue.
This is not a driver specific issues. If anyone else wants a solution that involves libvirt, please post the question on libvirt mailing list.

Thanks,
Yan.
