### ISSUE TITLE
Cannot install VirtIO Driver

### ISSUE THREAD

**Issue by Citarosoftwarerepairs** [virtio-win/kvm-guest-drivers-windows#624]
When I try to install the virtIO x64 driver on my Windows 10 KVM, this will appear
![image](https://user-images.githubusercontent.com/63702050/128871087-15804792-b181-46b9-b42f-770502ed39db.png)
I already checked and I have a lot of space. Can anyone help me with this

**Comment by vrozenfe** [comment]
@Citarosoftwarerepairs 

Can you please let me know the build version? Is it 186 or 204? 
Or the problem is reproducible on both of them?

Thanks,
Vadim.

**Comment by Citarosoftwarerepairs** [comment]
I downloaded it from this ISO https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
My current version is 0.1.185 do I need to download it from https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md instead

**Comment by Citarosoftwarerepairs** [comment]
Is this error caused because I installed Windows on "QEMU/KVM User Session" and not "QEMU/KVM"?

**Comment by vrozenfe** [comment]
I moved stable to 196 recently
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.196-1/

Can you give it a try? 

Best regards,
Vadim.

**Comment by Citarosoftwarerepairs** [comment]
I installed it on QEMU/KVM and used version 0.1.196 and it worked

**Comment by Citarosoftwarerepairs** [comment]
thank you very much! @vrozenfe

**Comment by vrozenfe** [comment]
No worries.
Vadim.
