### ISSUE TITLE
Error when i try to install viostor.sys by devcon tool

### ISSUE THREAD

**Issue by Donoy** [virtio-win/kvm-guest-drivers-windows#629]
Hello everyone:
When I use the tool(DEVCON.exe) with this command "install viostor.inf "PCI\VEN_1AF4&DEV_1001&SUBSYS_00021AF4&REV_00" to install the viostor driver on my vm which the OS version is windows 7, I encountered a problem.
![Snipaste_2021-08-13_15-18-33](https://user-images.githubusercontent.com/24365655/129324085-827331a6-8d58-4d8f-818d-93503ca679a4.png)
I find an error in the device management, the Red Hat Virtio SCSI controller has an exclamation point. And the status of the device is 'the device can't be run! the error code is 10'.
![Snipaste_2021-08-13_15-21-10](https://user-images.githubusercontent.com/24365655/129321930-eed9274d-b7d4-4b4e-8b75-4de9618c4c62.png)
The hardware ids of the viostor device:
![Snipaste_2021-08-13_15-20-53](https://user-images.githubusercontent.com/24365655/129323439-03c2ab0b-71f7-4274-97f9-e37550ef56d4.png)
The device instance path is 'ROOT\SCSIADAPTER\0000':
![Snipaste_2021-08-13_15-20-38](https://user-images.githubusercontent.com/24365655/129323484-8c25903e-4cbd-4295-9268-53e0874c0882.png)

So i did the same in windows 10 20H1. And there appeared a similar error.
![Snipaste_2021-08-13_16-29-52](https://user-images.githubusercontent.com/24365655/129331904-8f0e393e-d72d-4b4e-b690-4885b5846545.png)
The error code is 31.
![Snipaste_2021-08-13_16-30-31](https://user-images.githubusercontent.com/24365655/129331954-f7893a95-9614-41f3-ae40-9ab241f4c998.png)
The hardware ids of the viostor device:
![Snipaste_2021-08-13_16-30-53](https://user-images.githubusercontent.com/24365655/129332059-ff1f746b-fd5f-4e10-a19e-7b0c5f076d3b.png)
The device instance path is 'ROOT\SCSIADAPTER\0000':
![Snipaste_2021-08-13_16-30-44](https://user-images.githubusercontent.com/24365655/129332136-0db10f4d-05b6-48ac-b463-192230a3720f.png)

In my environment, there is no mounted hard drive that uses this type (VirtIO，viostor) device. Maybe this can be the reason for the _problem._

**My problem is if i installed the viostor.sys in  where no mounted hard drive that uses this type device, does the error in device Manager have any impact on the system and why the device instance path is 'ROOT\SCSIADAPTER\0000'? What does it mean to display instances(ROOT\SCSIADAPTER\0000) in device Manager ? Can I manually delete the device in the device management?**

I look forward to hearing from you. Thank you very much.

**Comment by vrozenfe** [comment]
@Donoy 
Do I understand correctly that  you are trying to preinstall the drivers on your system?
(So called software-first installation scenario https://docs.microsoft.com/en-us/windows-hardware/drivers/install/software-first-installation)
If yes, than on Windows 10 I would suggest using msi  from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.204-1/virtio-win-gt-x64.msi
On Windows 7 you can try using devcon dp_add to install the package
devcon install creates a root devnode. This is probably not what you want.

**Comment by Donoy** [comment]
Thank you very much for your reply @vrozenfe.

The background of this question is this:
I want to use the viostor driver feature in Virtio, i use the pre-installation (devcon dp_add infFilePath) method to have some problems in my scene. Then i tried to use the direct installation (devcon install infFilePath HID) method and found that the problem was solved, but a device with an exclamation mark appeared in the device manager. In fact, i am not very familiar with this type of driver, and i don't know much about the device manager, so i can only come to the community for help.

I just want to know about the cause, impact of this exclamation point device and how i can solve this problem, if i have to use direct installation (devcon install infFilePath HID) method.

Supplementary part:
I installed the viostor driver by referring to the commands in the comments in the viostor.inf file. 
![image](https://user-images.githubusercontent.com/24365655/129504055-d6b52e4c-45c6-462f-b041-11dfd4be4493.png)

**Comment by vrozenfe** [comment]
@Donoy 

 If you want to install drivers on a system with virtio devices already attached and Windows cannot find a suitable device driver, then you should use "devcon install".
However, if you want to preinstall a driver then  you should try using "devcon dp_add " .

Best regards,
Vadim.
