### ISSUE TITLE
Windows Server 2022 Update

### ISSUE THREAD

**Issue by EatonZ** [virtio-win/kvm-guest-drivers-windows#634]
[Microsoft's Windows Server 2022 is rolling out to mainstream users](https://www.zdnet.com/article/microsofts-windows-server-2022-is-rolling-out-to-mainstream-users/)

Can you update the download with Windows Server 2022-compatible drivers when you have a chance? (Assuming any work needs to be done). At the very least it seems a new `2k22` folder is warranted.

**Comment by YanVugenfirer** [comment]
Windows 10 drivers are compatible with Windows Server 2022 drivers.

**Comment by EatonZ** [comment]
@YanVugenfirer Ok, but you should create a folder for it so everyone else knows it's ready.

**Comment by YanVugenfirer** [comment]
@EatonZ We will update the ISO together with Installer.
