### ISSUE TITLE
The windows2008r2/win7 guest hang when it use vhost-user backend nic on some new cpu model

### ISSUE THREAD

**Issue by ztetfger** [virtio-win/kvm-guest-drivers-windows#64]
I start windows2008r2/win7 guest which use vhost-user backend nic on the fllowing cpu model.
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x2d

The guest hang when it start windows.But windows xp/2000/2003 guest can start normaly.
The qemu command line like this:
qemu-system-x86_64 -name instance-0000006f_test -machine pc-i440fx-2.5,accel=kvm,usb=off -cpu Haswell-noTSX,+abm,+pdpe1gb,+rdrand,+f16c,+osxsave,+dca,+pdcm,+xtpr,+tm2,+est,+smx,+vmx,+ds_cpl,+monitor,+dtes64,+pbe,+tm,+ht,+ss,+acpi,+ds,+vme,+kvm_pv_eoi -m 8192 -object memory-backend-file,id=mem,size=8192M,mem-path=/dev/hugepages,share=on -numa node,memdev=mem -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 06302b6a-525f-451a-bcf9-188b7240912c -no-user-config -nodefaults  -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/home/liuyb/win7.img,if=none,id=drive-virtio-disk0,format=qcow2,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -chardev socket,id=charnet0,path=/opt/network/ovdk/bin/vhost.sock -netdev type=vhost-user,id=hostnet0,chardev=charnet0,vhostforce -device virtio-net-pci,netdev=hostnet0,id=net0,mac=fa:16:3e:e7:bf:3f,bus=pci.0,addr=0x3 -device usb-tablet,id=input0 -vnc 0.0.0.0:1 -k en-us -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -msg timestamp=on

And in some old cpu model,  the 2008r2/win7 guest also start normaly.
test cpu model:
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
stepping        : 4
microcode       : 0x417

vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E7-4860 v2 @ 2.60GHz
stepping        : 7
microcode       : 0x70a

If the guest don't have nic,it can start.So I think the error has the relationship with the nic.After some tests,I found that the guest hang because bit28(VIRTIO_RING_F_INDIRECT_DESC) of the  host_feature of virito  was set 0.When the bit is set 1，the guest starts normaly.
But the old cpu model don't have this problem,whether the VIRTIO_RING_F_INDIRECT_DESC bit is set 0 or not. So I wonder if  the  netkvm driver of the 2008r2/win7 has the compatibility problem with the new cpu model.

**Comment by YanVugenfirer** [comment]
Thank you for the report.

In general we don't have dependency in virtio-net device or the driver on CPU model. On other hand Windows can turn of MSI interrupts based on CPU model and there could be potentially some bug with legacy interrupt support in NDIS 6.x virtio-net drivers.

I will need to investigate the issue with using the settings you provided.

Best regards,
Yan.

**Comment by ladipro** [comment]
@ztetfger, can you please try enabling the "crash on ctrl+scroll lock" feature and see if you can get the system to crash and generate a memory dump when it hangs? Having access to the dump should help us figure out what's going on.

Here's an article on the ctrl+scroll lock forced crash feature:
https://msdn.microsoft.com/en-us/library/windows/hardware/ff545499

Thanks!
Ladi

**Comment by YanVugenfirer** [comment]
Hi,

Are you using DPDK? If yes - please check this thread: https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/70

And this patch: http://dpdk.org/dev/patchwork/patch/15541/

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
The fix was introduced to DPDK
