### ISSUE TITLE
[Regression] Problem with vioscsi+scsi-block

### ISSUE THREAD

**Issue by tomty89** [virtio-win/kvm-guest-drivers-windows#657]
I am experiencing problem with vioscsi+scsi-block (on SATA and UAS drive): Windows will fail to format a partition to NTFS (yet formatting to exFAT still works). On SATA drive, the error in `diskpart` is `invalid parameter`. On UAS drive, formatting seems to just stall forever. It seems to have problem mounting existing NTFS volume as well (e.g. Disk Management is stalled).

I'm not sure if what I'm seeing is the full picture though (like, whether there could actually be silent read/write error on exFAT as well).

Driver from ISO 0.1.204 works fine. (Like, definitely fine, since I have a Windows installation using that, which has been working perfectly). I've done tests (with Windows installation ISO) to double confirm that it's a regression in the driver from ISO 0.1.208.

No problem with scsi-hd. Windows version is 21H1 (Enterprise evaluation; with September cumulative updates). QEMU version 6.1. Kernel version 5.14.2.

**Comment by vrozenfe** [comment]
@tomty89 

Can you please post the qemu command line along with a brief description how to reproduce the problem.

Thanks,
Vadim.

**Comment by tomty89** [comment]
`qemu-system-x86_64 -enable-kvm -M q35 -cpu host,hv-vpindex,hv-synic,hv-time,hv-stimer,hv-vapic -smp cores=4 -m 8G -nodefaults -display gtk -vga std -rtc base=localtime -drive file=/tmp/OVMF.fd,if=pflash,format=raw -drive file=/dev/sdc,if=none,format=raw,cache=none,aio=native,id=sys -device pcie-root-port,slot=0,id=prp0 -device virtio-scsi-pci,bus=prp0 -device scsi-block,drive=sys -drive file=isos/19043.928.210409-1212.21h1_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso,media=cdrom -drive file=isos/virtio-win-0.1.204.iso,media=cdrom`

![vioscsi_204](https://user-images.githubusercontent.com/8604057/134307262-87869dd2-7359-46fd-a985-3ac140f20db6.png)

`qemu-system-x86_64 -enable-kvm -M q35 -cpu host,hv-vpindex,hv-synic,hv-time,hv-stimer,hv-vapic -smp cores=4 -m 8G -nodefaults -display gtk -vga std -rtc base=localtime -drive file=/tmp/OVMF.fd,if=pflash,format=raw -drive file=/dev/sdc,if=none,format=raw,cache=none,aio=native,id=sys -device pcie-root-port,slot=0,id=prp0 -device virtio-scsi-pci,bus=prp0 -device scsi-block,drive=sys -drive file=isos/19043.928.210409-1212.21h1_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso,media=cdrom -drive file=isos/virtio-win-0.1.208.iso,media=cdrom`

![vioscsi_208](https://user-images.githubusercontent.com/8604057/134307329-e8c8817d-ddc3-46fb-ae98-78fa72ccb3bd.png)

I notice that recently there has been a bump in NumberOfPhysicalBreaks, so I tested with `indirect_desc=off` as well. The first time I did diskpart also gave me an error when I format a volume with NTFS (a different one though, some "your device is not compatible" or something like that), but then I cannot reproduce it anymore in later trials. (Still, it seems fragile to me anyway.)

For the record, AFAIK it had/has been known that NOPB cannot exceed `max_hw_sectors` of the backend drive at least when `scsi-block` is used, which is why I never proposed to bump it away from 65 (which is the maximum optimal with respect to the sacred but mysterious "+1" rule for a drive with `max_hw_sectors_kb` of `512`, i.e. 128 4KiB pages).

**Comment by vrozenfe** [comment]
@lijinlijin  
Hi Li Jin, Can QE reproduce the problem and file a new bug based on the results? 

@tomty89 
Thanks for the detailed explanation.
Regarding to max_sectors defined in virtio spec  https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html "section 5.6.4 Device configuration layout" please feel free to make and submit a patch that trims NOPB to max_sectors value 
(if it was changed from default 0xFFFF)  at https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/vioscsi/vioscsi.c#L510

**Comment by peixiu** [comment]
Reproduced this issue with a SATA SSD disk, filed a Bug 2022656 - [virtio-win][vioscsi] Windows will fail to format a partition to NTFS with vioscsi+scsi-block.

Just one thing different is: I tried test with virtio-win-prewhql-204, also can reproduce this issue.

Thanks~
Peixiu
