### ISSUE TITLE
VirtIO GPU DOD vs QXL

### ISSUE THREAD

**Issue by benbaker76** [virtio-win/kvm-guest-drivers-windows#668]
Is the VirtIO GPU DOD controller superior to the QXL controller? Is there any information you can provide in regard to the viogpudo driver and the performance differences?

Is there a signed version available to download?

Can you add support for [these resolutions](https://github.com/tianocore/edk2/blob/master/OvmfPkg/VirtioGpuDxe/Gop.c#L145)?

**Comment by headkaze** [comment]
I was reading kraxel's blog post [virtio-gpu and qemu graphics in 2021](https://www.kraxel.org/blog/2021/05/virtio-gpu-qemu-graphics-update/) regarding the new virtio-vga and virtio-vga-gl devices in qemu 6.1.

> Second, blob resource support for the simple virtio-vga device is in progress, and it will bring support shared resource mappings to qemu. This will accelerate the display path due to less or no copying of pixel data.

Will the "blob resource support" improve the performance of this driver?

**Comment by vrozenfe** [comment]
You are probably asking about https://patchwork.kernel.org/project/dri-devel/patch/20200814024000.2485-11-gurchetansingh@chromium.org/
Unfortunately, this feature will not be able to improve 2d rendering on Windows VMs

**Comment by BruceMok** [comment]
> As for me virtio gpu dod is a base for the future improvement and extension to
a Full Graphics or Render-Only WDDM driver

Is any plan for this?  I really need a full graphics WDDM driver because DOD driver's capability is so limited, more and more applications i can't run in VM(e.g. some application request VMR9).

**Comment by YanVugenfirer** [comment]
@BruceMok Sorry, the full graphics driver (with DirectX support) is not on a visible horizon.

**Comment by YanVugenfirer** [comment]
@matheuswillder I don't think there is an open issues. You can added.

In any case, technically QXL is not virtio-win driver and not managed in this repo, although our installer includes it. This is a project page: https://gitlab.freedesktop.org/spice/win32/qxl-wddm-dod

For virtio-gpu you can create an issue here.

**Comment by YanVugenfirer** [comment]
@matheuswillder Thanks! The title looks OK.
