### ISSUE TITLE
Virtiofs support for case-insensitivity

### ISSUE THREAD

**Issue by davispuh** [virtio-win/kvm-guest-drivers-windows#669]
Currently if a linux case-sensitive filesystem is mapped to Windows guest using virtiofs then a lot of programs doesn't work trying to access files on this mapped disk because of genius developers unable to stick to single file casing at different parts of program.
eg. one function loads `one.DLL` while different function uses `One.dll` and so on.
It causes this mapping hardly usable...
Are there any plans of adding support for case insensitivity?

**Comment by xiagao** [comment]
davispuh hi,
To be honest, I'm not understand your issue,could you say more about it?such as, which programs are you using?Are those programs using the same file on the mapping disk,but can't work?

Thanks,
Xiaoling

**Comment by davispuh** [comment]
There are many programs with such issues. But one example is Steam (https://store.steampowered.com/about/).

Some parts of code are trying to access `SteamUI.dll` (that's how it's saved on disk) while other places in code are accessing `steamui.dll` which fails to read.
You can easily see it with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)

![image](https://user-images.githubusercontent.com/651800/140236433-2afcad31-5a47-4bd9-aeb4-f7ddbe8431c3.png)


![image](https://user-images.githubusercontent.com/651800/140236217-041fe0d5-cadd-4c80-ae0d-edef6b52c95a.png)

![image](https://user-images.githubusercontent.com/651800/140236531-6a7956d3-a49a-43c4-9a10-7036e3a7e423.png)

If I run it from Samba share then it works fine since Samba handles case insensitivity but that's not using Virtiofs so performance is worse.

Also this isn't only file with such casing issue. You can either symlink it or copy to have both names but that just leads to next issue. So case insensitivity really needs to be implemented in Virtiofs.

**Comment by xiagao** [comment]
@davispuh 
Thanks to propose this issue.
Compared the virtiofs file system and the native NTFS file system, it's indeed a problem.We will track this issue in downstream as well.

Z:\>echo testing > TEST.txt

Z:\>type test.txt
The system cannot find the file specified.

Z:\>echo testing > c:\TEST.txt

Z:\>type c:\TEST.txt
testing

BR,
Xiaoling

**Comment by YanVugenfirer** [comment]
Hello All,

Please help us understanding you use cases for using virtio-fs, and thus make us virtio-fs support better.
Please participate in the discussion and add your use cases: https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/726

Thanks a lot,
Yan.

**Comment by Daniel-Trevitz** [comment]
Ironically, I ran into this while trying to compile virtio-fs. Not exactly self hosting ;)

Reading through the code, am I correct in believing that the case folding would have to be done either
* At the linux filesystem level (I.e. ext4 described [here](collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/))
* Within libvirt/qemu's implementation of the host's filename lookup.

I, for one, don't like that first option because I either have to limit my shared folder to a specific directory or lose case insensitivity on my home folder (not happening).

The second option would be dependent on libvirt/qemu's openness to such behavior (which would certainly need to flaggable), implementing case folding (which will be annoying to get right), and then exposing the new flag in the XML of libvirt.

Specifically, I'm saying does it look to be something this project can not work around. I say this because it looks like the file name lookup request is done via a call to DeviceIoControl, which I suspect passes through a shim driver to qemu's virtio pci device.

**Comment by YanVugenfirer** [comment]
Enhancing QEMU\libvirt is possible. When having concrete proposal, we can discuss it on appropriate mailing lists.
Looking at what Samba did - there is no generic solution, the behaviour is controlled by the configuration, but at least user is aware of expected behaviour.

**Comment by Daniel-Trevitz** [comment]
> Enhancing QEMU\libvirt is possible. When having concrete proposal, we can discuss it on appropriate mailing lists. 

@YanVugenfirer, What mail list do you recommend?

**Comment by YanVugenfirer** [comment]
virtio-fs: https://listman.redhat.com/mailman/listinfo/virtio-fs
qemu-devel: https://lists.nongnu.org/mailman/listinfo/qemu-devel
libvirt: https://listman.redhat.com/mailman/listinfo/libvir-list

**Comment by vananasun** [comment]
Encountered the same issue :( Cannot compile my Visual Studio projects

**Comment by YanVugenfirer** [comment]
Solved by PR#832.

https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#options

**Comment by ZaberKo** [comment]
> 

Hello. If I want to use multiple mount mentioned in [multiple-virtio-fs-instances](https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#multiple-virtio-fs-instances).
Not sure if I understand it correcly, should I change to command to:
```
"C:\Program Files (x86)\WinFsp\bin\fsreg.bat" virtiofs "C:\Program Files\Virtio-Win\VioFS\virtiofs.exe" "-i -t %1 -m %2"
```

**Comment by viktor-prutyanov** [comment]
If I want to use multiple mount points mentioned in [multiple-virtio-fs-instances](https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#multiple-virtio-fs-instances), should I change the command to:
> ```
> "C:\Program Files (x86)\WinFsp\bin\fsreg.bat" virtiofs "C:\Program Files\Virtio-Win\VioFS\virtiofs.exe" "-i -t %1 -m %2"
> ```

 Yes
