### ISSUE TITLE
netkvm change default rss queue to 16 dont take effect 

### ISSUE THREAD

**Issue by jackli577** [virtio-win/kvm-guest-drivers-windows#670]
1: install the driver before change default queue, pre is 8
   2: use the new driver to update the netkvm.
 
update only update the value in reg :
 KEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0001\Ndi\params\*NumRssQueues

but not:
 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0001
   
this will be result to device manager see is 8.  ndis read cfg also is 8. this can be reproduction。

**Comment by YanVugenfirer** [comment]
@jackli577 Hello,

This doesn't looks like current registry settings: KEY_LOCAL_MACHINE\SYSTEM\ControlSet002

How did you update the driver? 
What was the old version and what's the newer version?

Best regards,
Yan.

**Comment by jackli577** [comment]
i remember use decive manage to update ，if u cannot &nbsp; do recurrences，i will try it again tomorrow。
Best Regard.

发自我的iPhone


------------------ Original ------------------
From: Yan Vugenfirer ***@***.***&gt;
Date: Mon,Jan 17,2022 7:28 PM
To: virtio-win/kvm-guest-drivers-windows ***@***.***&gt;
Cc: jackli577 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [virtio-win/kvm-guest-drivers-windows] netkvm change default rss queue to 16 dont take effect  (Issue #670)





 
@jackli577 Hello,
 
This doesn't looks like current registry settings: KEY_LOCAL_MACHINE\SYSTEM\ControlSet002
 
How did you update the driver?
 What was the old version and what's the newer version?
 
Best regards,
 Yan.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
