### ISSUE TITLE
virtiofs fails in windows 10 guest

### ISSUE THREAD

**Issue by zitamus99** [virtio-win/kvm-guest-drivers-windows#675]
virtiofs fails in windows 10 guest

[Host Sepecification] 
ArchLinux x64 - Kernel 5.14.16
Host Packages Version :
libvirt 1:7.9.0-1
virt-install 3.2.0-3
virt-manager 3.2.0-3
virt-viewer  10.0-2
qemu 6.1.0-5

[Guest Sepecification]
Windows 10 X64 20H2 - Build 19042.1288
Installed latest drivers from "virtio-win-0.1.208.iso"
Installed winfsp-1.9.21096

I have installed windows 10 using virt-manager. also installed latest drivers from virtio-win-0.1.208.iso. after adding filesystem to my windows 10 virtual machine, I got a new "PCI Device"(in "Other devices") in device manager with Hardware Id "1AF4:1049" but viofs.inf is valid for Hardware Id "1AF4:105A".

here is Hardware Ids for new "PCI Device": 

PCI\VEN_1AF4&DEV_1049&SUBSYS_11001AF4&REV_01
PCI\VEN_1AF4&DEV_1049&SUBSYS_11001AF4
PCI\VEN_1AF4&DEV_1049&CC_000200
PCI\VEN_1AF4&DEV_1049&CC_0002

none of these methods did not help :

1) right-click -> update driver -> Search automatically for drivers

2) right-click -> update driver -> Browse my computer for drivers -> Let me pick from a list of available drivers on my computer

3) tried to start "VirtIO-FS Service" from windows service manager, I got error :
"Windows could not start the VirtIOFSService service on Local Computer. Error 6: The handle is invalid."

Note: "WinFsp.Launcher" service is running.

4) tried to start "VirtIO-FS Service" from Administrative command prompt, I got result :

C:\Windows\system32>sc start "VirtIO-FS Service"

SERVICE_NAME: VirtIO-FS Service
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 6012
        FLAGS              :

5) tried to run "virtiofs.exe" directly from Administrative command prompt, I got result :

C:\Windows\system32> "C:\Program Files\Virtio-Win\VioFS\virtiofs.exe"

The service VirtIO-FS has failed to start (Status=c0000008).

C:\Windows\system32> "C:\Program Files\Virtio-Win\VioFS\virtiofs.exe" -m z:

The service VirtIO-FS has failed to start (Status=c0000008).

6) following instruction from "https://virtio-fs.gitlab.io/howto-windows.html" :

C:\Windows\system32> sc create VirtioFsSvc binpath="C:\Program Files\Virtio-Win\VioFS\virtiofs.exe" start=auto depend="WinFsp.Launcher/VirtioFsDrv" DisplayName="Virtio FS Service"

C:\Windows\system32>sc start VirtioFsSvc
[SC] StartService FAILED 1075:

The dependency service does not exist or has been marked for deletion.

In virt-manager -> win10vm -> overview -> XML

here is filesystem section:

    <filesystem type="mount" accessmode="mapped">
      <source dir="/tmp/share/"/>
      <target dir="share"/>
      <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
    </filesystem>
	
based on these informations : 
"https://devicehunt.com/view/type/pci/vendor/1AF4/device/1049"

[Device ID]	 [Device Name]
105A		 Virtio filesystem	
1049		 Virtio filesystem
1009		 Virtio filesystem

Why viofs.inf is only valid for Device ID "105A" although there are 3 Device IDs for this filesystem ?

What can I do to get the desired DeviceID (105A)?	

What can I do to get filesystem working on windows 10 guest to access the files on my linux host ?
	
Thanks for any help.

**Comment by xiagao** [comment]
@zitamus99 hi, actually I can't reproduce it with the same env you mentioned.
guest:win10-64(20H2, BUILD 19042)
qemu: 6.1.0-6
driver: virtio-win-prewhql-208

qemu cmd line:
-chardev socket,id=char0,path=/tmp/vhostqemu1 \
-device vhost-user-fs-pci,chardev=char0,tag=myfs_11,queue-size=1024 \
Device id in device manager is PCI\VEN_1AF4&DEV_105A.

I attach a screenshot of my vm.
![virtiofs-hardware-id](https://user-images.githubusercontent.com/9928220/140742785-925361a8-9384-4f8b-bd18-101d61482041.png)

Thanks,
xiagao

**Comment by viktor-prutyanov** [comment]
Hi @zitamus99.

You've faced the issue because 0x1049 is **Virt-IO 9P** device, not **Virt-IO FS**. As you've mentioned **Virt-IO FS** is 0x105A.

XML should look like that:

```xml
<filesystem type="mount" accessmode="passthrough">
  <driver type="virtiofs"/>
  <source dir="/home/vp/vms/viofs"/>
  <target dir="mount_tag"/>
  <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
</filesystem>
```

> In virt-manager -> win10vm -> overview -> XML
> 
> here is filesystem section:

Your XML configuration doesn't contain
```xml
  <driver type="virtiofs"/>
```

Best regards,
Viktor Prutyanov

**Comment by zitamus99** [comment]
Hi @xiagao 
Thanks for your reply

Hi @viktor-prutyanov 
Thanks for your reply and useful help

after adding  <driver type="virtiofs"/>   and set the accessmode from "mapped" to "passthrough" and adding

      <memoryBacking>
        <source type='memfd'/>
        <access mode='shared'/>
      </memoryBacking>

the problem solved and now I can access to my linux host folder.

Appreciated
Best Regards
