### ISSUE TITLE
Can't find signed driver to install for a Windows 7 vm virtualized with bhyve.

### ISSUE THREAD

**Issue by Marietto2008** [virtio-win/kvm-guest-drivers-windows#678]
Hello to everyone.

I'm trying to virtualize Windows 7 with bhyve on FreeBSD,using the following parameters :+1: 

```
bhyve -c 2 -m 2G -w -H \
-s 0,hostbridge \
-s 1,ahci-cd,/mnt/da2s1/ISO/Windows/Win.All.x64.March.2020.iso \
-s 2,ahci-cd,/home/marietto/Downloads/virtio-win-0.1.208.iso \
-s 3,virtio-blk,/mnt/da2s1/OS/bhyve/Windows/win7.img \
-s 4,fbuf,tcp=0.0.0.0:5901,w=1440,h=900,wait \
-s 8,virtio-net,tap1 \
-s 30,xhci,tablet \
-s 31,lpc \
-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd \
vm1
```

as u can see I want to use the virtio-blk type disk,so I will need to load the virtio vio stor driver. So,I've started the installation of Windows 7 and at some point I tried to load the correct driver,but it didn't work. It says that It can't find a signed driver as u can see below. 

![Screenshot_20211122_145035](https://user-images.githubusercontent.com/755339/142874056-dee006f7-1e2d-4e8e-9822-682eabf94afb.png)

![Screenshot_20211122_145048](https://user-images.githubusercontent.com/755339/142874059-d62f84c8-ed5d-4862-88b5-b30df4885f88.png)

what should I do ?

**Comment by YanVugenfirer** [comment]
Try one of the old versions: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/485 - 171 and below.

**Comment by Marietto2008** [comment]
171 works.
