### ISSUE TITLE
This device generates a resource conflict (error 12). To use it,you need to disable one of the other system device.

### ISSUE THREAD

**Issue by Marietto2008** [virtio-win/kvm-guest-drivers-windows#679]
Hello to everyone,

I'm trying to configure correctly the passthrough of my graphic card (Nvidia RTX 2080 ti) from Linux Ubuntu 21.10 to a Windows 7 x64 bit vm. I think that I've configured everything correctly,but there is something wrong because it does not work correctly. I've installed the nvidia driver 472.12 for WIndows 7 x64,but despite this,it does not work. My graphic card is not passed correctly. Below you can see what errors there are. I can translate the error to something like this : "not enough resources for the device. To use it,you need to disable one of the other system device" ; and this : "this device generates a resource conflict (error 12). To use it,you need to disable one of the other system device". What's happening here ? I see that I have a lot of point exclamation marks. I see a lot of missing drivers. But I don't understand why,since I'm getting the drivers from here : 

https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/

this is the config file of the windows 7 vm :

https://pastebin.ubuntu.com/p/hF2d6rfYXm/

![Istantanea_2021-11-24_16-50-10](https://user-images.githubusercontent.com/755339/143272761-d6459a65-45e8-4e11-bc15-053165ac29db.png)

![Istantanea_2021-11-24_16-49-57](https://user-images.githubusercontent.com/755339/143272764-e8e40d16-4797-4075-aa82-296540cbe3b6.png)

![Istantanea_2021-11-24_16-49-42](https://user-images.githubusercontent.com/755339/143272766-c5917b10-7864-4dd1-a535-9802fdb41577.png)

![Istantanea_2021-11-24_16-49-21](https://user-images.githubusercontent.com/755339/143272769-b4f5acf9-f0dd-4eb7-8882-4ce485e62d51.png)

![Istantanea_2021-11-24_16-49-03](https://user-images.githubusercontent.com/755339/143272772-7a855355-e030-45fa-b5cd-1540595b4005.png)

![Istantanea_2021-11-24_12-14-20](https://user-images.githubusercontent.com/755339/143272774-829705a3-5edc-4a8e-a5c9-0fccc7a31424.png)

![Istantanea_2021-11-24_12-13-57](https://user-images.githubusercontent.com/755339/143272776-fee5e3f5-ebce-457b-bf06-f20a71f93c40.png)

![Istantanea_2021-11-23_22-07-52](https://user-images.githubusercontent.com/755339/143272779-a0edb184-eacb-489d-806a-2684416dd61f.png)

![Istantanea_2021-11-23_22-05-57](https://user-images.githubusercontent.com/755339/143272780-a25e20d5-7dbb-4694-a375-0e97a16872f7.png)

**Comment by YanVugenfirer** [comment]
Hi,

We provide virtio-gpu driver, not the NVIDIA driver.
If you are using QEMU\KVM to run VM, it is betters ask the question on qemu users list.
https://lists.nongnu.org/mailman/listinfo/qemu-discuss

The problem is probably in a way you are passing through the devices.

Best regards,
Yan.

**Comment by Marietto2008** [comment]
I know,infact Im here to understand how to solve the problems related to the drivers which don't work that belongs to you. even if I suspect that they are all connected together.

**Comment by jamelmaisonfree-maker** [comment]
https://wiki.gentoo.org/wiki/GPU_passthrough_with_virt-manager,_QEMU,_and_KVM#Code_12_.2F_PCI_Resource_Allocation_Errors_in_Guest
