### ISSUE TITLE
Ballon service is activated, and can change real used memory, but can not get memory stats.

### ISSUE THREAD

**Issue by sddwt** [virtio-win/kvm-guest-drivers-windows#680]
The service was correctly installed, and 

`virsh qemu-monitor-command --hmp r16 'info balloon'`

gets `balloon: actual=16380`,

`virsh qemu-monitor-command --hmp QENc6C 'balloon 1000'`

can change the real memory can be used, I  can see the task manager's memory stats increasing.

`virsh qemu-monitor-command --hmp r16 'info balloon'`

balloon: actual=1626

But when I tried `virsh dommemstat`, there is not data feed back, it shows:
```
actual 1665024
last_update 1637781329
rss 1904032
```

I would like to know what's the problem, could you please tell me how to fix that?

Virt-win is the latest version.

**Comment by sddwt** [comment]
bty, `last_update` never changes.

**Comment by sddwt** [comment]
similar bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1474452

I got almost same situation as this report mentioned.

**Comment by sddwt** [comment]
This problem shows on 2016, win10 and 2012r2 works totally OK.

**Comment by vrozenfe** [comment]
@sddwt 

Can you please confirm that the problem is reproducible on WS2016 only?
if so, then some of WMI queries from https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/Balloon/app/memstat.cpp must be failing on this platform.

Thanks,
Vadim.

**Comment by xiagao** [comment]
@sddwt 
Did you set the 'period' before get the memstat?
'       For  QEMU/KVM  with a memory balloon, setting the optional --period to a value larger
       than 0 in seconds will allow the balloon driver to return additional statistics which
       will  be  displayed by subsequent dommemstat commands. Setting the --period to 0 will
       stop the balloon driver collection, but does not clear the statistics in the  balloon
       driver. Requires at least QEMU/KVM 1.5 to be running on the host.
'

Before I set the period value, I get the previous value and there will be no change
# virsh dommemstat win2016
actual 4194304
last_update 1637889337
rss 4263708

Set period to 2s.
# virsh dommemstat win2016 --period 2

It works,and the value will be changed.
# virsh dommemstat win2016
actual 4194304
swap_in 552176
swap_out 0
major_fault 24881
minor_fault 589379
unused 3297048
available 4193760
usable 3308716
last_update 1637889494
disk_caches 23336
hugetlb_pgalloc 0
hugetlb_pgfail 0
rss 4255624

Thanks,
Xiaoling

**Comment by sddwt** [comment]
> @sddwt Did you set the 'period' before get the memstat? ' For QEMU/KVM with a memory balloon, setting the optional --period to a value larger than 0 in seconds will allow the balloon driver to return additional statistics which will be displayed by subsequent dommemstat commands. Setting the --period to 0 will stop the balloon driver collection, but does not clear the statistics in the balloon driver. Requires at least QEMU/KVM 1.5 to be running on the host. '
> 
> Before I set the period value, I get the previous value and there will be no change _virsh dommemstat win2016_ actual 4194304 last_update 1637889337 rss 4263708
> 
> Set period to 2s. _virsh dommemstat win2016 --period 2_
> 
> It works,and the value will be changed. _virsh dommemstat win2016_ actual 4194304 swap_in 552176 swap_out 0 major_fault 24881 minor_fault 589379 unused 3297048 available 4193760 usable 3308716 last_update 1637889494 disk_caches 23336 hugetlb_pgalloc 0 hugetlb_pgfail 0 rss 4255624
> 
> Thanks, Xiaoling

Thank you, Xiaoling.

I've forgotten to set period,
And after set this value, It's working When I used virsh  attach-disk to attach a virtio-win iso.
But if I don't do that, It's not working at all.
This usually occurred When I start a qemu-kvm using the qcow2 created with balloon.

I've to attach the iso otherwise the new kvm would not get data as above situation.

Thanks again.

**Comment by sddwt** [comment]
> @sddwt
> 
> Can you please confirm that the problem is reproducible on WS2016 only? if so, then some of WMI queries from https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/Balloon/app/memstat.cpp must be failing on this platform.
> 
> Thanks, Vadim.

It's wired, seems like all systems can get the problem. 
After trying many times, I found that I have to attach the iso no matter I used the blnexe in the iso dir nor I copied the ballom amd64 files into c:/program files/balloon/ and installed the service under that directory. The virtio win iso must be attached in the first time start, or It will not work.
Thank you.

**Comment by xiagao** [comment]
> > @sddwt
> > Can you please confirm that the problem is reproducible on WS2016 only? if so, then some of WMI queries from https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/Balloon/app/memstat.cpp must be failing on this platform.
> > Thanks, Vadim.
> 
> It's wired, seems like all systems can get the problem. 
After trying many times, I found that I have to attach the iso no matter I used the blnexe in the iso dir nor I copied the ballom amd64 files into c:/program files/balloon/ and installed the service under that directory. The virtio win iso must be attached in the first time start, or It will not work. Thank you.

Sorry, you mean when you attach a virtio-win iso after vm was started up, then you can't get memory state?
Did you check whether balloon service was started in service manager?

Thanks,
Xiaoling

**Comment by sddwt** [comment]
> Sorry, you mean when you attach a virtio-win iso after vm was started up, then you can't get memory state?

Thank you for reply.
I mean I have to attach virtio-win iso when the vm first time start up, then I can get memory state.
If I don't attach iso, then I can't.
The most wired thing is, no matter I attach the iso or not, the balloon service is running.

**Comment by vrozenfe** [comment]
@sddwt 

How did you install the balloon service?

**Comment by sddwt** [comment]
> @sddwt
> 
> How did you install the balloon service?

tried two ways.
- cd iso dir, cd balloon/2r12/amd/, ./bln.exe -i
- cp iso balloon/2r12/amd/* c:/program files/balloon/, cd c:/program files/balloon/, ./bln.exe -i
just simplified the path, but same affects.

**Comment by xiagao** [comment]
@sddwt
Actually, you can check the "Path to executable" in the properties  of balloon service.
If the path is in C: and the blnsrv.exe is in there, then balloon service will be running.
If the path is in cdrom volume,but you didn't attach an iso, then balloon service will stop

**Comment by sddwt** [comment]
> @sddwt Actually, you can check the "Path to executable" in the properties of balloon service. If the path is in C: and the blnsrv.exe is in there, then balloon service will be running. If the path is in cdrom volume,but you didn't attach an iso, then balloon service will stop

Thanks for your notes, I will try it when I got time. I close this issue right now, and if I got problems, I will reopen it again. 
Thank you again.
