### ISSUE TITLE
Having issue copying files from host to guest, and my IDE is having issues saving to virtiofs passthrough disk.

### ISSUE THREAD

**Issue by MostHated** [virtio-win/kvm-guest-drivers-windows#681]
Hey all,
    My host has a cifs share mapped to my nas at /mnt/nasdata/ then I was passing that through to the guest. I went to do a build, and it saved to that disk, but when I went to try and copy the files over to the guest local storage, I kept getting an error saying "Cant read from source file or disk".

 In addition to that, every time I try to save a file in my IDE, seemingly while/as it is in process of saving, I get a message saying "file was changed on disk" and it asks me to reload the file. I thought perhaps it was IDE related, but so far all roads seem to point to the virtiofs setup.

Is there anything that could be done to help with this by chance, or am I just stuck with it for the time being? Not being able to save most of the time, or copy files from the drive to the guest is killing me, but unfortunately, using this setup is the only way I have found that actually works/persists to access the host resources while connected to an AnyConnect VPN session that disables any other network/usb connections, modifies host file, etc.

Thanks,
-MH

**Comment by viktor-prutyanov** [comment]
Hi @MostHated,

could you please provide steps to reproduce your problem?

**Comment by MostHated** [comment]
Ah, well shoot, it's been a while and since I was able to get files from the host just fine I ended up creating another local disk on the host and connecting it to the VM instead of passing the mounted share after I discovered I could live mount that disk image in read-only mode, so I am just using rsync to copy the files to the network share periodically. I can't recall off-hand what my settings were at the time, but I will try and see if I can reproduce it either this evening or tomorrow and report back.

**Comment by YanVugenfirer** [comment]
Hello All,

Please help us understanding you use cases for using virtio-fs, and thus make us virtio-fs support better.
Please participate in the discussion and add your use cases: https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/726

Thanks a lot,
Yan.
