### ISSUE TITLE
virtio-9p / virtio-fs does not work on Windows 11 ?

### ISSUE THREAD

**Issue by Marietto2008** [virtio-win/kvm-guest-drivers-windows#682]
Hello.

I've virtualized Windows 11 with bhyve on FreeBSD 13R and It seems to me that the virtio-9p and or the virtio-fs driver does not work. I don't see the folder "mnt" mounted on the root folder of Windows 11. Below you can see which parameters I've used :

```
bhyve -S -c 4 -m 8G -w -H \
-s 0,hostbridge \
-s 1,ahci-cd,/home/marietto/Downloads/virtio/virtio-win-0.1.208.iso \
-s 2,ahci-hd,/mnt/da0p1/Backups/OS/bhyve/Windows/win11.img \
-s 3,fbuf,tcp=0.0.0.0:5900,w=1440,h=900,wait \
-s 8,virtio-net,tap0 \
----> -s 9,virtio-9p,sharename=/mnt \
-s 30,xhci,tablet \
-s 31,lpc \
-l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd \
vm0
```

Reading from this tutorial :

https://virtio-fs.gitlab.io/howto-windows.html

I've realized that there could be some kind of problem with the Win-Fsp- Windows File System Proxy and or with the virtio-fs PCI device driver because I'm not able to enable the virtio-fs service with the command used on the tutorial :

`C:\> sc start VirtioFsSvc`

it gives the error : "the dependency service does not exist or it has been marked for the elimination.

I've attached some screenshots to help you to understand what's happening.

https://ibb.co/m5vm1hd
https://ibb.co/Qd6TS5d
https://ibb.co/3018SGd

**Comment by Marietto2008** [comment]
> Hello.
> 
> I've virtualized Windows 11 with bhyve and It seems that the virtio-9p driver does not work inside the Windows 11 os emulated with bhyve. When Windows 11 is launched,I don't see the folder "mnt" mounted on the root folder of Windows 11. Below you can see which bhyve parameters I've used :
> 
> ```
> bhyve -S -c 4 -m 8G -w -H \
> -s 0,hostbridge \
> -s 1,ahci-cd,/home/marietto/Downloads/virtio/virtio-win-0.1.208.iso \
> ----> -s 2,ahci-hd,/mnt/da0p1/Backups/OS/bhyve/Windows/win11.img \
> -s 3,fbuf,tcp=0.0.0.0:5900,w=1440,h=900,wait \
> -s 8,virtio-net,tap0 \
> ----> -s 9,virtio-9p,sharename=/mnt \
> -s 30,xhci,tablet \
> -s 31,lpc \
> -l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd \
> vm0
> ```
> 
> Investigating a little bit more and reading from this tutorial :
> 
> https://virtio-fs.gitlab.io/howto-windows.html
> 
> I've realized that there should be some problem with the WinFsp- Windows File System Proxy and or with the virtiofs PCI device driver because I'm not able to enable the virtiofs service with the command used on the tutorial :
> 
> `C:\> sc start VirtioFsSvc`
> 
> it gives the error : "the dependency service does not exist or it has been marked for the elimination.
> 
> I've attached some screenshots to help you to understand what's happening.
> 
> https://ibb.co/m5vm1hd https://ibb.co/Qd6TS5d https://ibb.co/3018SGd

**Comment by YanVugenfirer** [comment]
Hello,

There are no virtio-9p  drivers for Windows. Please use virtio-fs.

Best regards,
Yan.

**Comment by Marietto2008** [comment]
your too short answer does not help me to understand if I can fix the error that I get inside windows 11.

**Comment by YanVugenfirer** [comment]
`-s 9,virtio-9p,sharename=/mnt \`

This is not the right device. The right device is virtio-fs.
Not knowing bvyve, this probably should be `-s 9,virtio-fs,<virtio-fs specific parameters>`

**Comment by Marietto2008** [comment]
ok. now I understand. I don't think virtio-fs is supported by bhyve. anyway,do u think that if it was supported,the error inside windows 11 could gone away ? I ask it because I suspect that that error does not depends about what bhyve can do or not,but it is internal to windows 11.

**Comment by YanVugenfirer** [comment]
virtio-fs works on Windows 11 and Windows Server 2022. 
The most probably reason for this error is that the virtio-fs driver is not loaded.

**Comment by Marietto2008** [comment]
ok.

**Comment by jchia** [comment]
For the Windows 11 guest, you can install the virtiofs driver from here: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
