### ISSUE TITLE
Is building Windows 7 with Windows 11 EWDK (and maybe others) still supported?

### ISSUE THREAD

**Issue by darrenkenny** [virtio-win/kvm-guest-drivers-windows#691]
Hi,

Looking at the build instructions, for building with Windows 11 EWDK, it states:

> Building drivers for Windows 7 / Server 2008R2 is optional. Use VIRTIO_WIN_BUILD_LEGACY=Win7 to include them into the build.

But I've tried doing this, and it fails now to build Windows 7, complaining:

```
 MSB4126: The specified solution configuration "Win7 Release|x86" is invalid. 
```

Looking at the `virtio-win.sln` it does look like this support was removed in the most recent commit, but that there are still entries for "Win7 Release|win32" in there, just not the mapping from the above solution name.

Mainly I'd like confirmation one way or the other as to whether it should be supported or not:

- If not, maybe remove the appropriate lines from the specific Wiki entry and remove the remaining Wni7 entries in the solution file
- If it is, then reverse that commit? (ff6cb46 "virtio-win: Update targets relations")

I'm presuming that the intention is to remove Windows 7 support, and it would be good to be clear on whether it is supported or not in the build instructions.

Thanks, Darren

**Comment by YanVugenfirer** [comment]
Hi Darren,

Windows 7 targets were removed from the master branch. To build Windows 7,  you will have to checkout the following tag [02.12.2021-last-buildable-point-Win7](https://github.com/virtio-win/kvm-guest-drivers-windows/tree/02.12.2021-last-buildable-point-Win7)

WiKi is here: 
* https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Old-build-configurations
* https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-drivers-for-Windows-7-and-below

Best regards,
Yan.

**Comment by kostyanf14** [comment]
Hi Darren,

Thanks for your report. About your question, we removed Windows 7 support from upstream. I updated the wiki page about building the drivers using Windows 11 EWDK.
