### ISSUE TITLE
virtio-win-0.1.208 not support Windows server 2022？

### ISSUE THREAD

**Issue by 1265578519** [virtio-win/kvm-guest-drivers-windows#694]
virtio-win-0.1.208 not support Windows server 2022？
```
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.208-1/virtio-win-0.1.208.iso
```

2k22 folder?

**Comment by ybendito** [comment]
You can use Server 2019 drivers also for 2022. Later version may include builds more targeted to 2022, but in general there are no new features in 2022 that require dedicated drivers.

**Comment by 1265578519** [comment]
> You can use Server 2019 drivers also for 2022. Later version may include builds more targeted to 2022, but in general there are no new features in 2022 that require dedicated drivers.

Thanks for, I hope the corresponding 2k22 version can be used to improve network io performance and reduce soft interrupts(si), new version be updated this year?

**Comment by YanVugenfirer** [comment]
@1265578519 If you are looking into soft interrupts reduction and performance improvement, please check eBPF usage https://www.youtube.com/watch?v=GP6kSs6vCH8
