### ISSUE TITLE
VM hangs while working with DPDK vhost-user when mrg_rxbuf=on

### ISSUE THREAD

**Issue by johnakawzh** [virtio-win/kvm-guest-drivers-windows#70]
Hey folks,

I'm running an Win7 VM with virtio driver released in April 29th, 2014, with DPDK vhost-user (16.04) as the backend.

When mrg_rxbuf is turned off, everything works fine.
But the Win VM hangs when mrg_rxbuf=on: It happens when the first packet is sent to VM, and qemu CPU usage goes to 100%. No desc is handled by virtio-net from vhost observation.
This is always reproducable in my test.

The way I launch DPDK testpmd:

`export RTE_SDK=<pwd>`
`make install T=x86_64-native-linuxapp-gcc -j32`
`./x86_64-native-linuxapp-gcc/app/testpmd -c 0xf -n 4 --socket-mem 4096,0 --vdev 'eth_vhost0,iface=/tmp/sock0,queues=1' -- -i --rxq=1 --txq=1 --nb-cores=1`

After VM starts I type "start tx_first" which means testpmd will send packets to each port connects to it and then start forwarding, and the Win7 VM hangs right there.

I've tried a lot of Linux VMs with DPDK and never see anything like this.
Does anybody have a clue what might be the cause?

Thanks so much!

**Comment by YanVugenfirer** [comment]
Hi,

Thank you for the report.

I suggest first to test with latest driver.

Also could you please send the QEMU's command line that you used to
initiate virtio device.

Thanks,
Yan.

**Comment by johnakawzh** [comment]
Thank you Yan!

Could you help me with driver update in Windows? A link to any BKM would be perfect.

The Qemu command I use: `sudo taskset -c 2-5 qemu-2.6.0/obj/x86_64-softmmu/qemu-system-x86_64 -cpu host -smp cores=4,sockets=1 -enable-kvm -m 1024 vm.img -object memory-backend-file,id=mem,size=1024M,mem-path=/mnt/huge_vm,share=on -numa node,memdev=mem -mem-prealloc -monitor stdio --vnc :10 -chardev socket,id=chr0,path=/tmp/sock0 -netdev vhost-user,id=net0,chardev=chr0,vhostforce,queues=1 -device virtio-net-pci,mac=00:11:22:33:44:11,netdev=net0,mrg_rxbuf=off -usbdevice tablet`

**Comment by YanVugenfirer** [comment]
Hi,

Here is the link to latest build: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso

Best regards,
Yan.

**Comment by mcoquelin** [comment]
Hi johnakawzh,

It seems you are not the only one to have the issue.
One patch on DPDK's dev ML is said to fix the issue among other changes:
http://dpdk.org/dev/patchwork/patch/15205/

Do you have some time to test it, and says if it fixes the issue on your side?
If it fixes, it will be a good starting point to understand what happens.

Thanks,
Maxime

**Comment by johnakawzh** [comment]
Thanks Maxime! That’s me sending the patch.  ☺

**Comment by YanVugenfirer** [comment]
Solved in DPDK
