### ISSUE TITLE
vgpusrv: Event ID 7030 interactive services disabled

### ISSUE THREAD

**Issue by kevinoid** [virtio-win/kvm-guest-drivers-windows#718]
After running `vgpusrv.exe -i` to create the vgpusrv Windows service, the System Event Log shows [Event ID 7030](https://social.technet.microsoft.com/wiki/contents/articles/1453.event-id-7030-basic-service-operations.aspx) on boot:

> The VioGpu Resolution Service service is marked as an interactive service.  However, the system is configured to not allow interactive services.  This service may not function properly.

My understanding is that [Interactive Services](https://docs.microsoft.com/en-us/windows/win32/services/interactive-services) have been disabled by default since Vista.  Perhaps the service should be created without `SERVICE_INTERACTIVE_PROCESS`?

https://github.com/virtio-win/kvm-guest-drivers-windows/blob/44dcbda7200489316828ce078349f012de2a7da3/viogpu/viogpusc/utils.cpp#L49

Alternatively, perhaps `vgpusrv.exe -i` could set `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Windows\NoInteractiveServices` to `0` or print a warning for the administrator to do so?

Thanks for considering,
Kevin

**Comment by vrozenfe** [comment]
@kevinoid 
But the service was started and running fine, right?
Yes, in the recent Windows platforms services are not supposed to be running in the interactive session. This is the reason why the dynamic resolution user mode code was split in two pieces - service that is running in non-interactive session0 and a use mode console application that is running in the context of active user session.

I needed this flag at the earliest development stage to help me out with some troubleshooting . But I don't see the reason to keep it now. Please feel free to fix it, test  and send a patch request.

Best regards,
Vadim.

**Comment by kevinoid** [comment]
> But the service was started and running fine, right?

That's correct, as far as I can tell.

> I needed this flag at the earliest development stage to help me out with some troubleshooting . But I don't see the reason to keep it now. Please feel free to fix it, test and send a patch request.

Makes sense.  Will do (although it's low priority for me, so it may be a while before I get to it).

Thanks @vrozenfe!
