### ISSUE TITLE
when I attached a openstack cinder lvm block volume （100G） to a windows server instance, windows cannot format it to ntfs ( dead loop in formatting), but if the vulme size is 10G, format will succced

### ISSUE THREAD

**Issue by abchujb** [virtio-win/kvm-guest-drivers-windows#720]
when I attached a openstack cinder lvm block volume （100G） to a windows server instance, windows cannot format it to ntfs ( dead loop in formatting), but if the vulme size is 10G, format will succced

**Comment by peixiu** [comment]
Hi @abchujb  Could you help to provide the qemu command line for this instance? and kernel version, qemu-kvm version, virtio-win version or osp version, thanks~

**Comment by abchujb** [comment]
hi, thanks for you reply!


my testing environment:  
openstack: xena (kolla-ansible deploy) on centos stream 8 
windows server instance:  2k22  (the same as w2k16,  w2k19)


windows 2k22 images create on centos stream 8:
1、qemu-img create -f qcow2 ws2022.qcow2 40G
2、virt-install --connect qemu:///system --name ws2022 --ram 4096 --vcpus 2 --network network=default,model=virtio --disk path=ws2022.qcow2,format=qcow2,device=disk,bus=virtio --cdrom /root/cn_windows_server_2022_x64_dvd.iso --disk path=/root/virtio-win-0.1.215.iso,device=cdrom --vnc --os-type windows --os-variant win2k22


3、create openstack win2k22 instance with the ws2022.qcow2
4、at openstack dashboard, create two volume, one 100G, another 10G
5、attach two volume to win2k22 instance
6、10G volume ntfs format normally,  but 100G volume formatting forerver ...



--

***@***.***
-------------------------------------




At 2022-01-17 13:03:39, "peixiu" ***@***.***> wrote:

Hi @abchujb Could you help to provide the qemu command line for this instance? and kernel version, qemu-kvm version, virtio-win version or osp version, thanks~

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peixiu** [comment]
Hi  @abchujb, thanks for your info, and could you help to try finding the total qemu-kvm command line of this instance? you can refer to follows steps:

(undercloud) [stack@hp-dl380g10-08 ~]$ openstack server list

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+

| ID                                   | Name                    | Status | Networks               | Image          | Flavor  |

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+

| ae5105db-9e28-4b34-8d67-c276ad24c411 | overcloud-controller-0  | ACTIVE | ctlplane=192.168.24.11 | overcloud-full | control |

| 69db07c7-3435-4542-a75c-fdce844dda6d | overcloud-novacompute-1 | ACTIVE | ctlplane=192.168.24.23 | overcloud-full | compute |

| d3a3eec2-6410-4d3d-bb82-313822aeb10f | overcloud-novacompute-0 | ACTIVE | ctlplane=192.168.24.24 | overcloud-full | compute |

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+
(undercloud) [stack@hp-dl380g10-08 ~]$ ssh heat-admin@overcloud-novacompute-0
[heat-admin@overcloud-novacompute-0 ~]$ sudo podman ps
[heat-admin@overcloud-novacompute-0 ~]$ sudo podman exec -it nova_libvirt /bin/bash
[root@overcloud-novacompute-0 /]# ps -aux| grep qemu
Pasted all qemu command lines of the instance, the info similar with follows:
"""
/usr/libexec/qemu-kvm -name guest=instance-00000001,debug-threads=on .......
....... -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on

And you can also check the qemu-kvm through [root@overcloud-novacompute-0 /]# rpm -qa| grep qemu.

Thanks a lot~
Peixiu

**Comment by abchujb** [comment]
hi, thanks!


***@***.*** ~]# docker exec -it nova_libvirt bash
***@***.*** /]# ps -aux| grep qemu
nova       36954  2.1 12.9 9159792 4184888 ?     Rl   Jan14 121:40 /usr/libexec/qemu-kvm -name guest=instance-00000006,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-2-instance-00000006/master-key.aes"} -machine pc-i440fx-rhel7.6.0,usb=off,dump-guest-core=off,memory-backend=pc.ram -accel kvm -cpu Cascadelake-Server,ss=on,vmx=on,pdcm=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,tsx-ctrl=on,hle=off,rtm=off -m 4096 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296} -overcommit mem-lock=off -smp 2,sockets=2,dies=1,cores=1,threads=1 -uuid 5c23d83f-c767-4a91-9849-8ae297e5fa00 -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=24.0.1,serial=5c23d83f-c767-4a91-9849-8ae297e5fa00,uuid=5c23d83f-c767-4a91-9849-8ae297e5fa00,family=Virtual Machine -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=35,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -blockdev {"driver":"file","filename":"/var/lib/nova/instances/_base/78c6534f6bceed34bb404a57a75ff5377735bdc6","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":true,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -blockdev {"driver":"file","filename":"/var/lib/nova/instances/5c23d83f-c767-4a91-9849-8ae297e5fa00/disk","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"} -device virtio-blk-pci,bus=pci.0,addr=0x4,drive=libvirt-1-format,id=virtio-disk0,bootindex=1,write-cache=on -netdev tap,fd=37,id=hostnet0,vhost=on,vhostfd=38 -device virtio-net-pci,host_mtu=1450,netdev=hostnet0,id=net0,mac=fa:16:3e:2c:1a:13,bus=pci.0,addr=0x3 -add-fd set=3,fd=39 -chardev pty,id=charserial0,logfile=/dev/fdset/3,logappend=on -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -audiodev {"id":"audio1","driver":"none"} -vnc 172.16.12.225:0,audiodev=audio1 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.0,addr=0x6 -device vmcoreinfo -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
nova     1018346  0.0  2.1 9158588 697440 ?      Sl   Jan16   1:55 /usr/libexec/qemu-kvm -name guest=instance-00000005,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-4-instance-00000005/master-key.aes"} -machine pc-i440fx-rhel7.6.0,usb=off,dump-guest-core=off,memory-backend=pc.ram -accel kvm -cpu Cascadelake-Server,ss=on,vmx=on,pdcm=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,tsx-ctrl=on,hle=off,rtm=off -m 4096 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296} -overcommit mem-lock=off -smp 2,sockets=2,dies=1,cores=1,threads=1 -uuid 33aa3e40-781d-4560-99e2-70e78fb0a35e -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=24.0.1,serial=33aa3e40-781d-4560-99e2-70e78fb0a35e,uuid=33aa3e40-781d-4560-99e2-70e78fb0a35e,family=Virtual Machine -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=40,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -blockdev {"driver":"file","filename":"/var/lib/nova/instances/_base/932ecac5f388111f283bd86767a37568730421dd","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":true,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -blockdev {"driver":"file","filename":"/var/lib/nova/instances/33aa3e40-781d-4560-99e2-70e78fb0a35e/disk","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"} -device virtio-blk-pci,bus=pci.0,addr=0x4,drive=libvirt-1-format,id=virtio-disk0,bootindex=1,write-cache=on -netdev tap,fd=41,id=hostnet0,vhost=on,vhostfd=42 -device virtio-net-pci,host_mtu=1450,netdev=hostnet0,id=net0,mac=fa:16:3e:6a:72:1f,bus=pci.0,addr=0x3 -add-fd set=3,fd=43 -chardev pty,id=charserial0,logfile=/dev/fdset/3,logappend=on -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -audiodev {"id":"audio1","driver":"none"} -vnc 172.16.12.225:2,audiodev=audio1 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.0,addr=0x6 -device vmcoreinfo -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
nova     1018525  0.0  2.1 9159792 695728 ?      Sl   Jan16   1:57 /usr/libexec/qemu-kvm -name guest=instance-00000004,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-5-instance-00000004/master-key.aes"} -machine pc-i440fx-rhel7.6.0,usb=off,dump-guest-core=off,memory-backend=pc.ram -accel kvm -cpu Cascadelake-Server,ss=on,vmx=on,pdcm=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,tsx-ctrl=on,hle=off,rtm=off -m 4096 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296} -overcommit mem-lock=off -smp 2,sockets=2,dies=1,cores=1,threads=1 -uuid 0eedc7a9-74b2-4400-af43-705cb3cf67e5 -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=24.0.1,serial=0eedc7a9-74b2-4400-af43-705cb3cf67e5,uuid=0eedc7a9-74b2-4400-af43-705cb3cf67e5,family=Virtual Machine -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=42,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -blockdev {"driver":"file","filename":"/var/lib/nova/instances/_base/932ecac5f388111f283bd86767a37568730421dd","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":true,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -blockdev {"driver":"file","filename":"/var/lib/nova/instances/0eedc7a9-74b2-4400-af43-705cb3cf67e5/disk","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"} -device virtio-blk-pci,bus=pci.0,addr=0x4,drive=libvirt-1-format,id=virtio-disk0,bootindex=1,write-cache=on -netdev tap,fd=43,id=hostnet0,vhost=on,vhostfd=44 -device virtio-net-pci,host_mtu=1450,netdev=hostnet0,id=net0,mac=fa:16:3e:79:2f:07,bus=pci.0,addr=0x3 -add-fd set=3,fd=45 -chardev pty,id=charserial0,logfile=/dev/fdset/3,logappend=on -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -audiodev {"id":"audio1","driver":"none"} -vnc 172.16.12.225:3,audiodev=audio1 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.0,addr=0x6 -device vmcoreinfo -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
nova     1018657  0.0  2.1 9156708 697196 ?      Sl   Jan16   1:56 /usr/libexec/qemu-kvm -name guest=instance-00000003,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-6-instance-00000003/master-key.aes"} -machine pc-i440fx-rhel7.6.0,usb=off,dump-guest-core=off,memory-backend=pc.ram -accel kvm -cpu Cascadelake-Server,ss=on,vmx=on,pdcm=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,tsx-ctrl=on,hle=off,rtm=off -m 4096 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296} -overcommit mem-lock=off -smp 2,sockets=2,dies=1,cores=1,threads=1 -uuid 1c18fdaf-8378-4a14-945f-d72a8fd8ffb5 -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=24.0.1,serial=1c18fdaf-8378-4a14-945f-d72a8fd8ffb5,uuid=1c18fdaf-8378-4a14-945f-d72a8fd8ffb5,family=Virtual Machine -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=44,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -blockdev {"driver":"file","filename":"/var/lib/nova/instances/_base/932ecac5f388111f283bd86767a37568730421dd","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":true,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -blockdev {"driver":"file","filename":"/var/lib/nova/instances/1c18fdaf-8378-4a14-945f-d72a8fd8ffb5/disk","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"} -device virtio-blk-pci,bus=pci.0,addr=0x4,drive=libvirt-1-format,id=virtio-disk0,bootindex=1,write-cache=on -netdev tap,fd=45,id=hostnet0,vhost=on,vhostfd=46 -device virtio-net-pci,host_mtu=1450,netdev=hostnet0,id=net0,mac=fa:16:3e:56:e6:7f,bus=pci.0,addr=0x3 -add-fd set=3,fd=47 -chardev pty,id=charserial0,logfile=/dev/fdset/3,logappend=on -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -audiodev {"id":"audio1","driver":"none"} -vnc 172.16.12.225:4,audiodev=audio1 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.0,addr=0x6 -device vmcoreinfo -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
nova     1444042 21.7 26.4 13512072 8516464 ?    Sl   Jan17 327:57 /usr/libexec/qemu-kvm -name guest=instance-00000007,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-9-instance-00000007/master-key.aes"} -machine pc-i440fx-rhel7.6.0,usb=off,dump-guest-core=off,memory-backend=pc.ram -accel kvm -cpu Cascadelake-Server,ss=on,vmx=on,pdcm=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,tsx-ctrl=on,hle=off,rtm=off -m 8192 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":8589934592} -overcommit mem-lock=off -smp 4,sockets=4,dies=1,cores=1,threads=1 -uuid 0905830f-496c-40b4-bd7e-7c00cb350fd0 -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=24.0.1,serial=0905830f-496c-40b4-bd7e-7c00cb350fd0,uuid=0905830f-496c-40b4-bd7e-7c00cb350fd0,family=Virtual Machine -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=38,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -blockdev {"driver":"file","filename":"/var/lib/nova/instances/_base/77f8a8c3d344cd9d961d9e161bebe7e5ab6b5f77","node-name":"libvirt-3-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-3-format","read-only":true,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-3-storage"} -blockdev {"driver":"file","filename":"/var/lib/nova/instances/0905830f-496c-40b4-bd7e-7c00cb350fd0/disk","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-2-storage","backing":"libvirt-3-format"} -device virtio-blk-pci,bus=pci.0,addr=0x4,drive=libvirt-2-format,id=virtio-disk0,bootindex=1,write-cache=on -blockdev {"driver":"host_device","filename":"/dev/sdc","aio":"native","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-1-storage"} -device virtio-blk-pci,bus=pci.0,addr=0x5,drive=libvirt-1-format,id=virtio-disk1,write-cache=on,serial=e520a974-4bbf-4f0c-ace3-475d44be83bb -netdev tap,fd=48,id=hostnet0,vhost=on,vhostfd=49 -device virtio-net-pci,host_mtu=1450,netdev=hostnet0,id=net0,mac=fa:16:3e:59:f6:7a,bus=pci.0,addr=0x3 -add-fd set=3,fd=50 -chardev pty,id=charserial0,logfile=/dev/fdset/3,logappend=on -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -audiodev {"id":"audio1","driver":"none"} -vnc 172.16.12.225:1,audiodev=audio1 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.0,addr=0x7 -device vmcoreinfo -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
root     1953023  0.0  0.0 221940  1204 pts/6    S+   12:05   0:00 grep --color=auto qemu
***@***.*** /]# rpm -qa| grep qemu
ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch
qemu-kvm-block-gluster-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-hw-usbredir-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
libvirt-daemon-driver-qemu-7.10.0-1.module_el8.6.0+1046+bd8eec5e.x86_64
qemu-kvm-ui-spice-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-img-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-docs-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-common-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-block-curl-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-block-iscsi-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-block-ssh-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-ui-opengl-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-block-rbd-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
qemu-kvm-core-6.1.0-5.module_el8.6.0+1040+0ae94936.x86_64
***@***.*** /]#















--

***@***.***
-------------------------------------




At 2022-01-18 11:22:36, "peixiu" ***@***.***> wrote:

Hi @abchujb, thanks for your info, and could you help to try finding the total qemu-kvm command line of this instance? you can refer to follows steps:

(undercloud) ***@***.*** ~]$ openstack server list

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+

| ID                                   | Name                    | Status | Networks               | Image          | Flavor  |

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+

| ae5105db-9e28-4b34-8d67-c276ad24c411 | overcloud-controller-0  | ACTIVE | ctlplane=192.168.24.11 | overcloud-full | control |

| 69db07c7-3435-4542-a75c-fdce844dda6d | overcloud-novacompute-1 | ACTIVE | ctlplane=192.168.24.23 | overcloud-full | compute |

| d3a3eec2-6410-4d3d-bb82-313822aeb10f | overcloud-novacompute-0 | ACTIVE | ctlplane=192.168.24.24 | overcloud-full | compute |

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+
(undercloud) ***@***.*** ~]$ ssh ***@***.***
***@***.*** ~]$ sudo podman ps
***@***.*** ~]$ sudo podman exec -it nova_libvirt /bin/bash
***@***.*** /]# ps -aux| grep qemu
Pasted all qemu command lines of the instance, the info similar with follows:
"""
/usr/libexec/qemu-kvm -name guest=instance-00000001,debug-threads=on .......
....... -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on

And you can also check the qemu-kvm through ***@***.*** /]# rpm -qa| grep qemu.

Thanks a lot~
Peixiu

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by abchujb** [comment]
***@***.*** ~]# . venv/bin/activate

(venv) ***@***.*** ~]#  openstack server list

+--------------------------------------+-----------+--------+------------------------------------+------------+-----------+

| ID                                   | Name      | Status | Networks                           | Image      | Flavor    |

+--------------------------------------+-----------+--------+------------------------------------+------------+-----------+

| 0905830f-496c-40b4-bd7e-7c00cb350fd0 | win2k2201 | ACTIVE | demo-net=10.0.0.246, 172.16.12.186 | win2k22img | m1.large  |

| 5c23d83f-c767-4a91-9849-8ae297e5fa00 | rocky01   | ACTIVE | demo-net=10.0.0.55, 172.16.12.195  | rocky85img | m1.medium |

| 0eedc7a9-74b2-4400-af43-705cb3cf67e5 | centos7-2 | ACTIVE | demo-net=10.0.0.128, 172.16.12.161 | centos7img | m1.medium |

| 33aa3e40-781d-4560-99e2-70e78fb0a35e | centos7-3 | ACTIVE | demo-net=10.0.0.52, 172.16.12.179  | centos7img | m1.medium |

| 1c18fdaf-8378-4a14-945f-d72a8fd8ffb5 | centos7-1 | ACTIVE | demo-net=10.0.0.158, 172.16.12.160 | centos7img | m1.medium |

+--------------------------------------+-----------+--------+------------------------------------+------------+-----------+

(venv) ***@***.*** ~]#
















--

------------------------------------
***@***.***
-------------------------------------




At 2022-01-18 11:22:36, "peixiu" ***@***.***> wrote:

Hi @abchujb, thanks for your info, and could you help to try finding the total qemu-kvm command line of this instance? you can refer to follows steps:

(undercloud) ***@***.*** ~]$ openstack server list

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+

| ID                                   | Name                    | Status | Networks               | Image          | Flavor  |

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+

| ae5105db-9e28-4b34-8d67-c276ad24c411 | overcloud-controller-0  | ACTIVE | ctlplane=192.168.24.11 | overcloud-full | control |

| 69db07c7-3435-4542-a75c-fdce844dda6d | overcloud-novacompute-1 | ACTIVE | ctlplane=192.168.24.23 | overcloud-full | compute |

| d3a3eec2-6410-4d3d-bb82-313822aeb10f | overcloud-novacompute-0 | ACTIVE | ctlplane=192.168.24.24 | overcloud-full | compute |

+--------------------------------------+-------------------------+--------+------------------------+----------------+---------+
(undercloud) ***@***.*** ~]$ ssh ***@***.***
***@***.*** ~]$ sudo podman ps
***@***.*** ~]$ sudo podman exec -it nova_libvirt /bin/bash
***@***.*** /]# ps -aux| grep qemu
Pasted all qemu command lines of the instance, the info similar with follows:
"""
/usr/libexec/qemu-kvm -name guest=instance-00000001,debug-threads=on .......
....... -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on

And you can also check the qemu-kvm through ***@***.*** /]# rpm -qa| grep qemu.

Thanks a lot~
Peixiu

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peixiu** [comment]
OK, thanks, I'll try to reproduce this issue, any result will update to here~

**Comment by peixiu** [comment]
Hi @abchujb 

As your provide qemu-command line shown, only one volume /dev/sdc was attached to your instance(instance-00000007):

-blockdev {"driver":"host_device","filename":"/dev/sdc","aio":"native","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-1-storage"} -device virtio-blk-pci,bus=pci.0,addr=0x5,drive=libvirt-1-format,id=virtio-disk1,write-cache=on,serial=e520a974-4bbf-4f0c-ace3-475d44be83bb

No 2 volumes were attached to your instance, only one /dev/sdc was attached, if you have attached both volumes from openstack, then maybe you can check if both 2 volumes status are normal  in openstack first? Since if 2 volums status are normal attached to instance, the qemu command will have 2 volumes device like /dev/sdc and /dev/sdd.

Thanks~

**Comment by peixiu** [comment]
Oh, sorry, maybe I need to confirm with you the number of your attached volumes first, I understand 2 volumes before, one for 10G and one for 100G~

**Comment by abchujb** [comment]
oh, the  10g  volume  format  ok. I  have  deleted  it!

在 2022-01-18 13:48:38，peixiu ***@***.***> 写道：


Oh, sorry, maybe I need to confirm with you the number of your attached volumes first, I understand 2 volumes before, one for 10G and one for 100G~

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peixiu** [comment]
Hi @abchujb , we have a similar issue now https://bugzilla.redhat.com/show_bug.cgi?id=2041757, you can track this bug for the fix status, thank you~

**Comment by YanVugenfirer** [comment]
Solved: https://bugzilla.redhat.com/show_bug.cgi?id=2022656
