### ISSUE TITLE
owerwrite files problem virtio-fs

### ISSUE THREAD

**Issue by agrisvv** [virtio-win/kvm-guest-drivers-windows#722]
Problem:
* can't overwrite files.
* sometimes saw message "file already exist then copied new file". After refresh new file seems copied.

Tested - work:
* copy 300 mb from and to drive.
* duplicate files with different name.
* creating new files and folders. But in Host OS perms for folders and files shows like 775 and then can't write anything inside.

Not work:
* edit same file. ( create new txt file, edit , and can't save). even with host perms 777.
* can't overwrite file with same name. even with host perms 777

no problems with linux guest. event with 770 perms on files.
no changes with DistinctPermsForSameOwnerGroup 1
on windows file perms shows as everyone read only and s-1-5-0 as modify.

env:
* fedora 35 host with LUKS+ btrfs(compress=zstd:1)
* libvirt runs ar qemu user.
* /shared_data owned by qemu
* host user same as guest linux user, but windows guest user name are different.
* win10 21h2 x64
* winFsp 1.10.22006
* virtio package 215
* from libvirt xml
 ````  
 <filesystem type="mount" accessmode="passthrough">
      <driver type="virtiofs" queue="1024"/>
      <source dir="/shared_data/untrusted"/>
      <target dir="shared_data"/>
    </filesystem>

**Comment by xiagao** [comment]
@agrisvv Could you provide virtiofsd command line? I test with win10-64, files can be overwritten(create new file->edit-> can save it and copy it to c: volume -> modify file on c: volume->copy back to the shared dir, all work)
Here are my test env.
win10 21h2 x64 guest
winFsp 1.10.22006
virtio package 215
qemu-kvm-6.2.0-4

[host]shared source: 
home]# ll
drwxr-xr-x   2 qemu qemu          52 Jan 24 00:50 test3

libvirt xml file:
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='virtiofs' queue='1024'/>
      <binary path='/usr/libexec/virtiofsd'>
      </binary>
      <source dir='/home/test3'/>
      <target dir='myfs'/>
      <alias name='ua-1035e984-8238-46e1-af56-b546246e1a39'/>
    </filesystem>

virtiofsd cmd line:
/usr/libexec/virtiofsd --fd=23 -o source=/home/test3 -d

**Comment by agrisvv** [comment]
@xiagao  Thanks for tests.
virtiofsd commandline same as your only without -d

I get it to work on another Windows virtual
virtual machine main differences:
* 21h2 vs 20h2
* domain joined with some security policies vs standalone with default settings.

I will try to repeat this problem:
Install clean win and try to get up to same as domain joined with policies to found where problem starts.

**Comment by agrisvv** [comment]
Tested with new windows + domain joined MS AD without special policies.
Problems starts then you want to use this drive with domain user ( this user has admin rights on local pc)

in 770 perms on host you can't write.
in 777 perms can write. but it saves as 770 and can't overwrite.

Security tab shows on one folder in drive:
Domain:
* Everyone (Read & List)
* S-1-5-0 ( Full )

Before join domain:
* Everyone ( Read & List )
* agris ( Full )
* None ( Read & List )

**Comment by viktor-prutyanov** [comment]
> Tested with new windows + domain joined MS AD without special policies.

Looks like https://github.com/virtio-win/kvm-guest-drivers-windows/issues/660

**Comment by YanVugenfirer** [comment]
Hello All,

Please help us understanding you use cases for using virtio-fs, and thus make us virtio-fs support better.
Please participate in the discussion and add your use cases: https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/726

Thanks a lot,
Yan.

**Comment by Daniel-Trevitz** [comment]
@YanVugenfirer & @viktor-prutyanov - Can we close this?

**Comment by YanVugenfirer** [comment]
> @YanVugenfirer & @viktor-prutyanov - Can we close this?

Yes. Closing.
