### ISSUE TITLE
Virtio-FS drivers for Windows 7

### ISSUE THREAD

**Issue by MrMineToons** [virtio-win/kvm-guest-drivers-windows#728]
**Is your feature request related to a problem? Please describe.**
Actually I have a virtual machine that uses Windows 7 and that machine is a little complicated... At the moment I cannot update to win 8 or win 10/11...

I'm trying to mount my Linux Folder as a Drive in the Windows 7 guest...

Before I had tried that with Windows 11, and worked very well! https://virtio-fs.gitlab.io/howto-windows.html
But now I cannot install the virtio-fs driver in windows 7 machine.
I saw that is possible to build the drivers... I'm kind newbie doing that, and I have no successful. (I have logs. But looks like I cannot select WIN 7 for virtio-fs)

I followed: https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers-using-Visual-Studio-2017
 and
https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers-using-EWDK-1903-2004
 using
https://github.com/virtio-win/kvm-guest-drivers-windows/releases/tag/02.12.2021-last-buildable-point-Win7

 I had no success.

May I did something wrong? Can I do something to it works in windows 7?

**Describe the solution you'd like**
A way that I could build those drivers for windows 7, if possible.

**Describe alternatives you've considered**
If that would not be possible, I will use something like google drive, but that requires internet and isn't fast as Local Files...

**Additional context**
Sorry if that is obvious that wouldn't works in windows 7, I really don't know if its possible...
Thanks in advance!!

**Comment by viktor-prutyanov** [comment]
Have you considered using Samba to share files between host and guest?

**Comment by MrMineToons** [comment]
Hello!

Actually I haven't tried it. I saw that is easy to do, I will test it today!
I'm worry if I could use the samba share to execute files inside the share, and have no delay on it, like and external hard drive for the VM.

Thanks for mentioning that, I will post results here soon 👍

**Comment by YanVugenfirer** [comment]
Sorry,
We don't intend to support older OSes, other than the support already existing in the code base.

Closing.
