### ISSUE TITLE
Opportunistic completion in SendSRB gone?

### ISSUE THREAD

**Issue by JonKohler** [virtio-win/kvm-guest-drivers-windows#729]
On #684 and more specifically on 28f16b0, opportunistic completion was removed from vioscsi -> SendSRB. Both the PR and the commit are light on details, any particular reason why? cc @irudakov77 and @vrozenfe 

Also while I'm at it here, any particular reason we'd want to get rid of work_item support in general?

```
    if (adaptExt->num_queues > 1) {
        if (CHECKFLAG(adaptExt->perfFlags, STOR_PERF_OPTIMIZE_FOR_COMPLETION_DURING_STARTIO)) {
            ProcessQueue(DeviceExtension, MessageId, FALSE);
        }
    }
```

**Comment by JonKohler** [comment]
Meant to ping @irudakov77 as well

**Comment by vrozenfe** [comment]
@JonKohler 

So, I guess the guestion is mostly about workitems, right?
It used to be a dead code for quite long time. This code was added mostly
as my initial attempt to see how to implement and probably try to optimize multiqueue.
While this code worked quite well and was quite stable, we didn't find it to be more efficient     
comparing with completion SRB from DPC.
This code (slightly modified) can be returned back (or reimplemented) in case if we
try moving toward threated DPC.

Best,
Vadim.
