### ISSUE TITLE
standalone Win8 and Win10 x64 is not buildable

### ISSUE THREAD

**Issue by JonKohler** [virtio-win/kvm-guest-drivers-windows#733]
Win8 x64 and Win10 x64 by themselves fail with the following error. All I'm doing is the following commands in a completely clean workspace each time, so this is 100% reproducible.
tools\build.bat virtio-win.sln Win8 x64
tools\build.bat virtio-win.sln Win10 x64

The error is coming from here, which doesn't make much sense to me at first glance: https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/viosock/ViosockPackage/ViosockPackage.vcxproj#L156

That code is saying, if we're packaging for x64, copy the x86 DLL as well. Is that required? cc @kostyanf14 @irudakov77 

```
       "D:\a\kvm-guest-drivers-windows\kvm-guest-drivers-windows\virtio-win.sln" (Build target) (1) ->
       "D:\a\kvm-guest-drivers-windows\kvm-guest-drivers-windows\viosock\ViosockPackage\ViosockPackage.vcxproj.metaproj" (default target) (37) ->
       "D:\a\kvm-guest-drivers-windows\kvm-guest-drivers-windows\viosock\ViosockPackage\ViosockPackage.vcxproj" (default target) (43) ->
       (CopyLibFiles target) -> 
         D:\a\kvm-guest-drivers-windows\kvm-guest-drivers-windows\viosock\ViosockPackage\ViosockPackage.vcxproj(165,5): error MSB3030: Could not copy the file "..\lib\x86\Win8Release\viosocklib.dll" because it was not found.
         D:\a\kvm-guest-drivers-windows\kvm-guest-drivers-windows\viosock\ViosockPackage\ViosockPackage.vcxproj(165,5): error MSB3030: Could not copy the file "..\lib\x86\Win8Release\viosocklib.pdb" because it was not found.```

**Comment by kostyanf14** [comment]
Hi @JonKohler,

In general, I think we should copy x86 when we're packaging x64.
Just for example. You have Windows x64, so you should install the x64 driver, but a client application can be x86 as well as x64.
If we will not have x86 lib for x64 that means we should compile all clients for x64.
This is just one point of view.

Anyway, you are right, that standalone x64 build does not work.

**Comment by JonKohler** [comment]
Let's say we didn't do this, In such cases, would a client just have to pull down the x86 binaries and pull the lib from there? Or is this solving some common use case that was requested in the past? Trying to understand the history and use case a little more.

**Comment by JonKohler** [comment]
Also this doesn't happen on Win8.1, I haven't checked the build log yet but I'm assuming viosock was excluded from the build. Do we know if that was intentional?

**Comment by YanVugenfirer** [comment]
Hi @JonKohler 
I think x86 dll is needed for WOW64 (32 bit support on 64 bit platforms). 
Win8.1 - is an invalid configuration in general. When using buildall batch for viosock Win8.1 configuration is not built, because it is redundant (Win8 is used instead). I also don't see Win8.1 configuration in viosock.sln.

In terms of defining dependencies for ViosockPackage - In the GUI you cannot define dependency from other platform, just another project as a dependency. Not sure if some hacking in sln file can be done.

**Comment by JonKohler** [comment]
Ok, I think we'd probably just keep this as a known issue then, probably not worth fixing by itself
