### ISSUE TITLE
Update build tags for this repo?

### ISSUE THREAD

**Issue by JonKohler** [virtio-win/kvm-guest-drivers-windows#738]
Can we update the tags for this repo to match up with what is being posted over on the fedora project?

https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/

If we look at that list of packages as well as the changelog, it is not clear what commit of this repo is actually being used for said builds: 
https://fedorapeople.org/groups/virt/virtio-win/CHANGELOG

Guessing it wouldn't be terribly hard, but it would be nice to have some traceability there

**Comment by vrozenfe** [comment]
I have added and pushed the following tags

 * [new tag]           mm205 -> mm205
 * [new tag]           mm207 -> mm207
 * [new tag]           mm209 -> mm209
 * [new tag]           mm210 -> mm210
 * [new tag]           mm216 -> mm216
 * [new tag]           mm224 -> mm224
 * [new tag]           mm228 -> mm228
 * [new tag]           mm235 -> mm235

which should be quite close to the the internal tags and can be mapped to the following internal builds and upstream virtio-win packages
 mm205 -> build 185  https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.185-2/
 mm207 -> build 187  https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.187-1/
 mm209 -> build 189   https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.189-1/
 mm210 -> build 190   https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/
 mm216 -> build 196   https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.196-1/
 mm224 -> build 204   https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.204-1/
 mm228 -> build 208   https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.208-1/
 mm235 -> build 215   https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.215-2/
