### ISSUE TITLE
VirtIO-9p can't start

### ISSUE THREAD

**Issue by dontknowhy** [virtio-win/kvm-guest-drivers-windows#744]
**Describe the bug**
driver is installed but device could't start
![Screenshot_20220313_214740.jpg](https://user-images.githubusercontent.com/85813508/158062633-55e06778-d9c3-4a90-9c67-8f547ae0b4fc.jpg)
There are not enough system resources to complete the api(Machine translated )
**To Reproduce**
Steps to reproduce the behaviour:
INSTALL DRIVER(Forced installation, can not be detected automatically )
**Expected behavior**
VirtFS NetDisk shows as a NetDrive
**Screenshots**
Before:
![Screenshot_20220313_213442.jpg](https://user-images.githubusercontent.com/85813508/158062778-a073fae7-4f89-43e2-8dac-3c0d7a97c881.jpg)
After:
![Screenshot_20220313_214740.jpg](https://user-images.githubusercontent.com/85813508/158062803-01c23a51-c60f-458f-a6e5-0af49c19b886.jpg)
**Host:**
 - Disto: Android/Termux/PRoot/debian bullseye
 - Kernel version: 4.14.186+ (Android 11)
 - QEMU version :5.2(from debian's offical deb package)
 - QEMU command line (realy long): qemu-system-x86_64 -vnc :0,audiodev=pa,display=video0,key-delay-ms=300,connections=1500 -k 'en-us'  -audiodev pa,server=127.0.0.1,id=pa -monitor stdio -machine 'q35',vmport='off',kernel-irqchip='off',dump-guest-core='off',mem-merge='off',usb='on',hmat='on' -cpu 'Cascadelake-Server-v4',model_id='Intel(R) Xeon(TM) Gold 5218 @ 2.30GHz',vendor=GenuineIntel,l3-cache='true',vmware-cpuid-freq='false',mds-no='off',fma='off',pcid='off',x2apic='off',tsc-deadline='off',f16c='off',invpcid='off',rdseed='off',spec-ctrl='off',arch-capabilities='off',ssbd='off',3dnowprefetch='off',xsavec='off',rdctl-no='off',ibrs-all='off',skip-l1dfl-vmentry='off',avx512-4fmaps='off',avx512-4vnniw='off',avx512-bf16='off',avx512-vp2intersect='off',avx512-vpopcntdq='off',avx512bitalg='off',avx512ifma='off',avx512pf='off',avx512vbmi2='off',avx512vbmi='off',avx='off',avx2='off',avx512f='off',avx512dq='off',avx512cd='off',avx512bw='off',avx512vl='off',avx512vnni='off' -smp 4,cores=2,threads=2,sockets=1,dies=1 -accel tcg,thread=multi,tb-size=2048 -object memory-backend-ram,id='mem0',size='1024m','share=on' -numa node,memdev='mem0',initiator='0' -object memory-backend-ram,id='mem1',size='1024m','share=on' -numa node,memdev='mem1',initiator='0' -m 2G,slots=1,maxmem=2052M -netdev 'user',id='n1',ipv4='on',ipv6='off',hostname='QEMUvm',tftp='/sdcard' -device 'virtio-net',netdev='n1' -rtc base='localtime' -uuid '1f8e6f7e-5a70-4780-89c1-464dc0e7f308' -smbios type='0',version='Intel-Xeon' -smbios type='1',manufacturer='ASUS',product=' Z10PE-D16 WS',version='2021.1' -smbios type='2',manufacturer='Intel',version='2021.7',product='Intel C612' -smbios type='4',manufacturer='Intel',max-speed='3600',current-speed='3600' -smbios type='17',manufacturer='Samsung',loc_pfx='DDR3',speed='2600',serial='1248DC',part='Samsung' -drive file=bios.fd,format=raw,aio=native,cache=none,if=pflash,id=bios -no-fd-bootchk -msg timestamp='off' -device virtio-vga,max_hostmem=536870912,xres=1280,yres=800,id=video0 -device virtio-keyboard -device virtio-tablet -device ich9-intel-hda -device hda-duplex,audiodev=pa -device virtio-serial -drive file=win8.qcow2,format=qcow2,aio=native,cache=none,if=none,id=disk0 -device virtio-scsi,id=scsi0 -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=disk0,vendor="QEMU",serial="VirtIO SCSI Disk",product="VirtIO " -drive file=/sdcard/virt/isos/qemudrv.iso,format=raw,aio=native,cache=none,if=none,id=cd0 -device virtio-scsi,id=scsi1 -device scsi-cd,drive=cd0,bus=scsi1.0 -fsdev local,path='/sdcard',security_model='none',id='hostfs' -device virtio-9p,fsdev='hostfs',mount_tag='hostfs'

 - libvirt version :none
 - libvirt XML file :none

**VM:**
 - Windows version or commit hash that was used to build the driver
latest
 - Which driver has a problem
VirtFS Device 
 - Driver version
latest 

**Additional context**
sorry about Chinese…

**Comment by dontknowhy** [comment]
PS: running on phone

**Comment by viktor-prutyanov** [comment]
Hi @dontknowhy,

VirtIO-9P isn't supported. Please use VirtIO-FS device:
https://virtio-fs.gitlab.io/howto-qemu.html
https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-A-shared-file-system

**Comment by dontknowhy** [comment]
> Hi @dontknowhy,
> 
> VirtIO-9P isn't supported. Please use VirtIO-FS device:
> https://virtio-fs.gitlab.io/howto-qemu.html
> https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-A-shared-file-system

WhaT???
but i can't use VirtFS too!

**Comment by viktor-prutyanov** [comment]
Your QEMU command-line shows that VirtIO-9P device is used, not VirtIO-FS:
`-device virtio-9p,fsdev='hostfs',mount_tag='hostfs'`

**Comment by dontknowhy** [comment]
i use it before…
it's driver problem too…
so i remove it…
and add virtio-9p…

**Comment by dontknowhy** [comment]
> Hello @dontknowhy , 
> 
> Unfortunately we do not support virtio-9p driver on Windows OS.
> 
> If you had driver problems with virtio-fs driver, please describe them.
> 
> 

YES…
BUT you can replace virtio-9p to VirtFS(laugh)
It's all same…
just the driver can't load and device can't start…

**Comment by viktor-prutyanov** [comment]
@dontknowhy, please write us the following things when launching QEMU with VirtIO-FS device:
1. Your QEMU command-line
2. Your `virtiofsd` command-line
3. What did the driver report

**Comment by dontknowhy** [comment]
> Hello @dontknowhy , 
> 
> Unfortunately we do not support virtio-9p driver on Windows OS.
> 
> If you had driver problems with virtio-fs driver, please describe them.
> 
> 

uhh…
I'm not in a hurry to use VirtFS yet…
Because i ""fix"" it with an ADVANCED feature:
-device virtio-scsi,id=scsi2 #yes i have 3 scsi controler -drive file=fat:rw:/sdcard/virt/share,format=raw,aio=native,cache=none,if=none,id=hostfolder -device scsi-hd,drive=hostfolder
(hhh)

**Comment by dontknowhy** [comment]
> @dontknowhy, please write us the following things when launching QEMU with VirtIO-FS device:
> 1. Your QEMU command-line
> 2. Your `virtiofsd` command-line
> 3. What did the driver report
> 
> 

1.qemu-system-x86_64 -vnc :0,audiodev=pa,display=video0,key-delay-ms=300,connections=1500 -k 'en-us'  -audiodev pa,server=127.0.0.1,id=pa -monitor stdio -machine 'q35',vmport='off',kernel-irqchip='off',dump-guest-core='off',mem-merge='off',usb='on',hmat='on' -cpu 'Cascadelake-Server-v4',model_id='Intel(R) Xeon(TM) Gold 5218 @ 2.30GHz',vendor=GenuineIntel,l3-cache='true',vmware-cpuid-freq='false',mds-no='off',fma='off',pcid='off',x2apic='off',tsc-deadline='off',f16c='off',invpcid='off',rdseed='off',spec-ctrl='off',arch-capabilities='off',ssbd='off',3dnowprefetch='off',xsavec='off',rdctl-no='off',ibrs-all='off',skip-l1dfl-vmentry='off',avx512-4fmaps='off',avx512-4vnniw='off',avx512-bf16='off',avx512-vp2intersect='off',avx512-vpopcntdq='off',avx512bitalg='off',avx512ifma='off',avx512pf='off',avx512vbmi2='off',avx512vbmi='off',avx='off',avx2='off',avx512f='off',avx512dq='off',avx512cd='off',avx512bw='off',avx512vl='off',avx512vnni='off' -smp 4,cores=2,threads=2,sockets=1,dies=1 -accel tcg,thread=multi,tb-size=2048 -object memory-backend-ram,id='mem0',size='1024m','share=on' -numa node,memdev='mem0',initiator='0' -object memory-backend-ram,id='mem1',size='1024m','share=on' -numa node,memdev='mem1',initiator='0' -m 2G,slots=1,maxmem=2052M -netdev 'user',id='n1',ipv4='on',ipv6='off',hostname='QEMUvm',tftp='/sdcard' -device 'virtio-net',netdev='n1' -rtc base='localtime' -uuid '1f8e6f7e-5a70-4780-89c1-464dc0e7f308' -smbios type='0',version='Intel-Xeon' -smbios type='1',manufacturer='ASUS',product=' Z10PE-D16 WS',version='2021.1' -smbios type='2',manufacturer='Intel',version='2021.7',product='Intel C612' -smbios type='4',manufacturer='Intel',max-speed='3600',current-speed='3600' -smbios type='17',manufacturer='Samsung',loc_pfx='DDR3',speed='2600',serial='1248DC',part='Samsung' -drive file=bios.fd,format=raw,aio=native,cache=none,if=pflash,id=bios -no-fd-bootchk -msg timestamp='off' -device virtio-vga,max_hostmem=536870912,xres=1280,yres=800,id=video0 -device virtio-keyboard -device virtio-tablet -device ich9-intel-hda -device hda-duplex,audiodev=pa -device virtio-rng,max-bytes=2048,period=1000 -drive file=win8.qcow2,format=qcow2,aio=native,cache=none,if=none,id=disk0 -device virtio-scsi,id=scsi0 -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=disk0,vendor="QEMU",serial="VirtIO SCSI Disk",product="VirtIO " -drive file=/sdcard/virt/isos/qemudrv.iso,format=raw,aio=native,cache=none,if=none,id=cd0 -device virtio-scsi,id=scsi1 -device scsi-cd,drive=cd0,bus=scsi1.0 -device virtio-scsi,id=scsi2 -drive file=fat:rw:/sdcard/virt/share,format=raw,aio=native,cache=none,if=none,id=hostfolder -device scsi-hd,drive=hostfolder,bus=scsi2.0,vendor='QEMU',serial='VirtIO fsdev Disk',product='VirtIO fsdev' -virtfs local,path='/sdcard',mount_tag='hostfs',security_model='none',id='hostfs'
2.-virtfs local,path='/sdcard',mount_tag='hostfs',security_model='none',id='hostfs'
3.The drivers included in the windows driver library are not installed 
![Screenshot_20220315_194722.jpg](https://user-images.githubusercontent.com/85813508/158372505-3d972fe1-a475-4f4f-9254-8306e14f2ba3.jpg)
 
the error code 10
![Screenshot_20220315_195307.jpg](https://user-images.githubusercontent.com/85813508/158372582-9e178eda-e17f-4f7f-b4ae-b66d42c2a560.jpg)

**Comment by viktor-prutyanov** [comment]
@dontknowhy, you are still using 9P (`-virtfs` in QEMU refers to VirtIO-9P), not VirtIO-FS. 

If you are still interested in VirtIO-FS, please read how to setup it: https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-A-shared-file-system

**Comment by dontknowhy** [comment]
> > Hello @dontknowhy , 
> > 
> > Unfortunately we do not support virtio-9p driver on Windows OS.
> > 
> > If you had driver problems with virtio-fs driver, please describe them.
> > 
> > 
> 
> uhh…
> I'm not in a hurry to use VirtFS yet…
> Because i ""fix"" it with an ADVANCED feature:
> -device virtio-scsi,id=scsi2 #yes i have 3 scsi controler -drive file=fat:rw:/sdcard/virt/share,format=raw,aio=native,cache=none,if=none,id=hostfolder -device scsi-hd,drive=hostfolder
> (hhh)

Linus is happy,because i used QEMU VVFAT to send this picture :
![Screenshot_20220315_200359.jpg](https://user-images.githubusercontent.com/85813508/158374148-9d66f4b3-23ea-4f1f-90e4-05f7198f8b1d.jpg)

**Comment by viktor-prutyanov** [comment]
So, VirtIO SCSI drive has solved your problem?

**Comment by dontknowhy** [comment]
> So, VirtIO SCSI drive has solved your problem?

NOPE
It's temporary 
i still need virtfs
and i also trying samba

**Comment by dontknowhy** [comment]
> > So, VirtIO SCSI drive has solved your problem?
> 
> NOPE
> It's temporary 
> i still need virtfs
> and i also trying samba
> 

You can see there is a 503MB limit from QEMU VVFAT

**Comment by viktor-prutyanov** [comment]
> i still need virtfs

There are 2 different devices:
* VirtIO-9P (`-device virtio-9p-type` in QEMU). It is used by `-virtfs` option. **It isn't supported in virtio-win**.
* VirtIO-FS (`-device vhost-user-fs-pci` in QEMU) which is supported and described in our wiki.

**Comment by dontknowhy** [comment]
> > i still need virtfs
> 
> There are 2 different devices:
> * VirtIO-9P (`-device virtio-9p-type` in QEMU). It is used by `-virtfs` option. **It isn't supported in virtio-win**.
> * VirtIO-FS (`-device vhost-user-fs-pci` in QEMU) which is supported and described in our wiki.

OK…

**Comment by dontknowhy** [comment]
> > i still need virtfs
> 
> There are 2 different devices:
> * VirtIO-9P (`-device virtio-9p-type` in QEMU). It is used by `-virtfs` option. **It isn't supported in virtio-win**.
> * VirtIO-FS (`-device vhost-user-fs-pci` in QEMU) which is supported and described in our wiki.

well…
i found **virtiofsd** program which is installed in /usr/lib/qemu
BUT i'm running QEMU on MY TABLET,and my TABLET can't root 
so i can't use virtfsd…
Is there another way to create virtual devices for QEMU that share folders with，guest?
