### ISSUE TITLE
Virtio-FS Windows service crashes

### ISSUE THREAD

**Issue by bobobo1618** [virtio-win/kvm-guest-drivers-windows#758]
**Describe the bug**
The Virtio-FS Windows service crashes, resulting in the disk being inaccessible and no longer visible. No data is accessible.

**To Reproduce**
- Start service through `services.msc` -> (Service name) -> Properties, set "Start Parameters" to `-d -1 -D C:\viofs.log -m X:` for debugging.
- Run `copy X:\FolderName\Filename C:\Users\Me\Desktop\`

Powershell shows the following:

```
copy : The operation was canceled.
At line:1 char:1
+ copy Z:\FolderName\Filename C:\Users\Me\Desktop\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], OperationCanceledException
    + FullyQualifiedErrorId : System.OperationCanceledException,Microsoft.PowerShell.Commands.CopyItemCommand
```

Once this happens, the drive letter vanishes from Explorer, Windows Event Viewer shows that the service has crashed and `services.msc` shows that the service is no longer running.

The problem isn't limited to Powershell. Opening any file causes the crash, as does opening any folder aside from the root.

I've tried `<source type='memfd'/>` in case hugepages were an issue but the problem persists.

I've tried setting permissive permissions on files and directories but no luck there either.

**Expected behavior**
File copy succeeds, data can otherwise be interacted with.

**Screenshots**
- [Windows service log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/8508215/viofs.log)
- [Windows Event Viewer log for service crash](https://github.com/virtio-win/kvm-guest-drivers-windows/files/8508217/crashevent.log)
- [`virtiofsd` log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/8508323/virtiofsdbuf.log)

**Host:**
 - Distro: Arch Linux
 - Kernel version `Linux Starlight 5.15.34-1-lts #1 SMP Thu, 14 Apr 2022 05:08:35 +0000 x86_64 GNU/Linux`
 - QEMU version `6.2.0-4`
 - QEMU command line 
   ```
   /usr/bin/qemu-system-x86_64 -name guest=win10-new,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-1-win10-new/master-key.aes"} -blockdev {"driver":"file","filename":"/usr/share/ovmf/x64/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/win10-new_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-i440fx-6.2,usb=off,vmport=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram -accel kvm -cpu host,migratable=on,topoext=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=whatever,kvm=off -m 16384 -object {"qom-type":"memory-backend-file","id":"pc.ram","mem-path":"/dev/hugepages/libvirt/qemu/1-win10-new","share":true,"x-use-canonical-path-for-ramblock-id":false,"prealloc":true,"size":17179869184} -overcommit mem-lock=off -smp 20,sockets=1,dies=1,cores=10,threads=2 -object {"qom-type":"iothread","id":"iothread1"} -uuid <redacted> -display none -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=32,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot menu=on,splash-time=1000,strict=on -device qemu-xhci,p2=8,p3=8,id=usb,bus=pci.0,addr=0x3 -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-1-win10-new/fs0-fs.sock -device vhost-user-fs-pci,id=fs0,chardev=chr-vu-fs0,tag=pics,bus=pci.0,addr=0xa -netdev tap,fds=<redacted>,id=hostnet0,vhost=on,vhostfds=<redacted> -device virtio-net-pci,mq=on,vectors=18,netdev=hostnet0,id=net0,mac=<redacted>,bus=pci.0,addr=0x2 -audiodev {"id":"audio1","driver":"none"} -device vfio-pci,host=0000:2e:00.0,id=hostdev0,bus=pci.0,addr=0x4,romfile=/var/lib/libvirt/3070.bin -device vfio-pci,host=0000:2e:00.1,id=hostdev1,bus=pci.0,addr=0x5 -device vfio-pci,host=0000:24:00.0,id=hostdev2,bus=pci.0,addr=0x6 -device vfio-pci,host=0000:30:00.3,id=hostdev3,bus=pci.0,addr=0x7 -device vfio-pci,host=0000:43:00.0,id=hostdev4,bootindex=1,bus=pci.0,addr=0x8 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x9 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
   ```
 - libvirt version `8.2.0`
 - libvirt XML file [win10-new.txt](https://github.com/virtio-win/kvm-guest-drivers-windows/files/8508236/win10-new.txt)

**VM:**
 - Windows version or commit hash that was used to build the driver: `virtio-win-0.1.217`
 - Which driver has a problem: `viofs.sys`
 - Driver version: `virtio-win-0.1.217`

**Comment by xiagao** [comment]
I see your vhost-user-fs-pci device has no queue-size=1024 parameter, could you have a try with it?
There is an existed bug about it.
