### ISSUE TITLE
Virtio-FS permissions with Windows guest are inconsistent

### ISSUE THREAD

**Issue by bobobo1618** [virtio-win/kvm-guest-drivers-windows#759]
**Describe the bug**
Permissions between the guest and host are inconsistent. The guest should act as a single (preferably configurable) uid/gid from the host perspective, or at least be consistent per Windows user.

**To Reproduce**

1. Using the guest, create a text file in a directory owned by `root:root` with mode `0775` on the host. This succeeds.
2. Using the guest, create a text file in a directory owned by `root:root` with mode `0755` on the host. This fails.
3. Using the host, inspect the ownership and mode of the text file created by the guest. For me, this shows owner `http:http`, mode `0664`.

Steps 1 and 2 indicate that the guest is acting as a user with membership in the `root` group that isn't the `root` user. The only such user on my system is `brltty` (uid/gid 947), which wouldn't make any sense.

Step 3 indicates that the guest is acting as `http:http`, which isn't consistent with steps 1 and 2 and isn't what I want.

Further, the guest _always_ seems to have write access to the shared directory itself, ignoring any permissions set on that directory. However the permissions of any files and directories within it are respected.

This inconsistency makes it really difficult to figure out how to make things work. Nearly all the files on my host have owner `1001:1001` and mode `0755` and so Virtio-FS is unable to write anything. If I knew which user/group permissions were evaluated using, maybe I'd be able to update my permissions.

**Expected behavior**
Consistency, preferably documented.

**Host:**
 - Distro: Arch Linux
 - Kernel version `Linux Starlight 5.15.34-1-lts #1 SMP Thu, 14 Apr 2022 05:08:35 +0000 x86_64 GNU/Linux`
 - QEMU version `6.2.0-4`
 - QEMU command line 
   ```
   /usr/bin/qemu-system-x86_64 -name guest=win10-new,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-1-win10-new/master-key.aes"} -blockdev {"driver":"file","filename":"/usr/share/ovmf/x64/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/win10-new_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-i440fx-6.2,usb=off,vmport=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram -accel kvm -cpu host,migratable=on,topoext=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=whatever,kvm=off -m 16384 -object {"qom-type":"memory-backend-file","id":"pc.ram","mem-path":"/dev/hugepages/libvirt/qemu/1-win10-new","share":true,"x-use-canonical-path-for-ramblock-id":false,"prealloc":true,"size":17179869184} -overcommit mem-lock=off -smp 20,sockets=1,dies=1,cores=10,threads=2 -object {"qom-type":"iothread","id":"iothread1"} -uuid <redacted> -display none -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=32,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot menu=on,splash-time=1000,strict=on -device qemu-xhci,p2=8,p3=8,id=usb,bus=pci.0,addr=0x3 -chardev socket,id=chr-vu-fs0,path=/var/lib/libvirt/qemu/domain-1-win10-new/fs0-fs.sock -device vhost-user-fs-pci,id=fs0,chardev=chr-vu-fs0,tag=pics,bus=pci.0,addr=0xa -netdev tap,fds=<redacted>,id=hostnet0,vhost=on,vhostfds=<redacted> -device virtio-net-pci,mq=on,vectors=18,netdev=hostnet0,id=net0,mac=<redacted>,bus=pci.0,addr=0x2 -audiodev {"id":"audio1","driver":"none"} -device vfio-pci,host=0000:2e:00.0,id=hostdev0,bus=pci.0,addr=0x4,romfile=/var/lib/libvirt/3070.bin -device vfio-pci,host=0000:2e:00.1,id=hostdev1,bus=pci.0,addr=0x5 -device vfio-pci,host=0000:24:00.0,id=hostdev2,bus=pci.0,addr=0x6 -device vfio-pci,host=0000:30:00.3,id=hostdev3,bus=pci.0,addr=0x7 -device vfio-pci,host=0000:43:00.0,id=hostdev4,bootindex=1,bus=pci.0,addr=0x8 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x9 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
   ```
 - libvirt version `8.2.0`
 - libvirt XML file [win10-new.txt](https://github.com/virtio-win/kvm-guest-drivers-windows/files/8508236/win10-new.txt)

**VM:**
 - Windows version or commit hash that was used to build the driver: `virtio-win-0.1.217`
 - Which driver has a problem: `viofs.sys`
 - Driver version: `virtio-win-0.1.217`

**Comment by viktor-prutyanov** [comment]
Hi @bobobo1618,

> 1. Using the guest, create a text file in a directory owned by root:root with mode 0775 on the host. This succeeds.
> 2. Using the guest, create a text file in a directory owned by root:root with mode 0755 on the host. This fails.
> 3. Using the host, inspect the ownership and mode of the text file created by the guest. For me, this shows owner http:http, mode 0664.

When creating files and directories the `virtiofsd` daemon temporarily sets `uid` and `gid` to values provided by the guest side. The guest sets values to shared directory owner's `uid` and `gid`. So, your shared folder owner seems to be `http:http`.

> Further, the guest always seems to have write access to the shared directory itself, ignoring any permissions set on that directory.

But what behavior do you expect?

> This inconsistency makes it really difficult to figure out how to make things work. Nearly all the files on my host have owner 1001:1001 and mode 0755 and so Virtio-FS is unable to write anything.

Try to check that combination of shared folder owner and owner of files you want to access are OK.

**Comment by bobobo1618** [comment]
> When creating files and directories the `virtiofsd` daemon temporarily sets effective `uid` and `gid` to values provided by the guest side. The guest sets these values to shared directory owner's `uid` and `gid`. So, your shared folder owner seems to be `http:http`.

I tested this to be sure and you're completely right.

It looks like this applies to all writes and solves my problem completely.

It also explains why there's always access to the shared directory: virtiofs uses the uid/gid of the shared directory's owner, so it always has access, even though the owner might not have access to some of the shared directory's contents.

Can you clarify though, is this determined entirely by virtiofsd? If so this issue should be closed and I can go suggest that they document this behaviour.

**Comment by viktor-prutyanov** [comment]
> Can you clarify though, is this determined entirely by virtiofsd? If so this issue should be closed and I can go suggest that they document this behaviour.

As far as I understand, it is not determined at all. For now, VirtIO specification contains FS device only as a draft and it says that "the device accepts the POSIX user ids and group ids provided by the driver and security is enforced by the driver rather than the device".

Whenever possible, in VirtIO-FS for Windows guest we try to copy the behavior of VirtIO-FS for Linux. But as far as file rights are concerned, it is very difficult. For example, VirtIO-FS device on Linux sets UID:GID for new files to the guest process UID:GID. But on Windows guest we doesn't have UIDs and GIDs at all. So, setting UID:GID on file creation to UID:GID of the / owner is most meaningful (from my point of view). But since VirtIO-FS in VirtIO for Windows [should be considered as a tech preview feature](../wiki/VirtIO-FS:-A-shared-file-system#status) even this behaviour may be changed in future.
