### ISSUE TITLE
Replace `.doc` files with `.txt`

### ISSUE THREAD

**Issue by jsoref** [virtio-win/kvm-guest-drivers-windows#766]
**Describe the bug**

WordPad as of mid 2009 retroactively dropped support for `.doc` and `.wri` files.

https://web.archive.org/web/20090901181012/http://www.microsoft.com/technet/security/bulletin/MS09-010.mspx
> This security update also addresses the vulnerabilities by implementing fixes to WordPad and by preventing WordPad on affected platforms from opening Word 6.0 and Windows Write files. 

The driver only includes docs for w7 and newer, which means none of the supported OSs would out of the box support the docs, it seems reasonable to expect documentation (especially for a network card) to not be shipped in those formats.

<details><summary>Doc files in iso as seen from Windows 10</summary>

```cmd
D:\>dir /s/b *.doc
D:\NetKVM\2k12\amd64\readme.doc
D:\NetKVM\2k12R2\amd64\readme.doc
D:\NetKVM\2k16\amd64\readme.doc
D:\NetKVM\2k19\amd64\readme.doc
D:\NetKVM\2k22\amd64\readme.doc
D:\NetKVM\2k8\amd64\readme.doc
D:\NetKVM\2k8\x86\readme.doc
D:\NetKVM\2k8R2\amd64\readme.doc
D:\NetKVM\w10\ARM64\readme.doc
D:\NetKVM\w10\amd64\readme.doc
D:\NetKVM\w10\x86\readme.doc
D:\NetKVM\w11\ARM64\readme.doc
D:\NetKVM\w11\amd64\readme.doc
D:\NetKVM\w7\amd64\readme.doc
D:\NetKVM\w7\x86\readme.doc
D:\NetKVM\w8\amd64\readme.doc
D:\NetKVM\w8\x86\readme.doc
D:\NetKVM\w8.1\amd64\readme.doc
D:\NetKVM\w8.1\x86\readme.doc
```
</details>

**To Reproduce**
Steps to reproduce the behaviour:
1. Download an .iso of the kvm-guest-drivers (either from RedHat, or the [spice tools](https://github.com/utmapp/qemu/releases/download/v6.2.0-utm/spice-guest-tools-0.164.3.iso))
2. Start a Windows VM (Windows 10)
    <details><summary>Windows 10</summary>

    ![image](https://user-images.githubusercontent.com/2119212/166845997-b28e1b30-8b59-4234-9ca4-f7bda5ea0ea1.png)
    </details>
3. Insert the iso (tested: `spice-guest-tools-0.164.3.iso` and `virtio-win-0.1.217.iso`)
4. Browse to `D:\NetKVM\w10\ARM64`
    ![image](https://user-images.githubusercontent.com/2119212/166846908-7d702b88-a09a-4b96-b696-70235c29f404.png)
5. Double click on `readme.doc`
    ![image](https://user-images.githubusercontent.com/2119212/166847043-d43f73a7-edc6-4424-a441-6b018365bd63.png)
6. Run WordPad and check to see what files it can open:
    ![image](https://user-images.githubusercontent.com/2119212/166847112-c5182132-f294-473e-9f2e-286fb39078fd.png)

**Expected behavior**
Read Me files associated with a network driver should be readable without a working network.

There's nothing fancy in the readme file, so I believe the right choice is `.txt` and to use markdown semantics if someone feels a real need to highlight things. Humans can infer enough from Markdown.

**Screenshots**

**Host:**
 - Disto: macOS
 - Kernel version
 - QEMU version
 - QEMU command line 
 - libvirt version
 - libvirt XML file

**VM:**
 - Windows version - Windows 10 ARM
 - Which driver has a problem - NetKVM
 - Driver version or commit hash that was used to build the driver - https://github.com/virtio-win/kvm-guest-drivers-windows/commit/4c6bff0102bee27503f019c2e74db49cf2767265

**Additional context**

**Comment by YanVugenfirer** [comment]
Hi @jsoref ,

Thank you for opening the issue.
The reason for having the DOC files is to describe the command line of command line configuration utility required by https://docs.microsoft.com/en-us/previous-versions/windows/hardware/cert-program/devicedevfund-requirements Device.DevFund.Server.CommandLineConfigurable requirement.
As far as I remember, on previous Windows OSes it was required to have explanation in .doc file.

If this is that painful for you, I suggest added .MD file. file keeping doc. You are more than welcomed to submit PR. Don't forget to add "Sign off" line in the commit message.

Thanks,
Yan.

**Comment by YanVugenfirer** [comment]
While this request looks benign the next actions are not: https://github.com/virtio-win/kvm-guest-drivers-windows/pull/768#issuecomment-1124561811

Therefore I am closing this issue. We can reconsider it, if any real user of virtio-win will need documentation in other format.
