### ISSUE TITLE
Windows virtio balloon driver fails to swap out cold guest pages

### ISSUE THREAD

**Issue by andrea-segalini** [virtio-win/kvm-guest-drivers-windows#772]
While testing the virtio balloon driver for windows, it seems that inflating the balloon does not produce the kind of memory pressure in the guest to cause cold pages to be swapped out (guest swapping). Memory gets swapped out, but only when a guest workload starts using further memory.

The Linux virtio balloon driver puts pressured on the guest as it inflates. When free memory falls below a certain threshold, the guest under-pressure starts to reclaim memory, including sending cold pages to swap. The balloon driver is then able to further allocate more memory, causing more pressured, and reclaiming cold memory via guest swapping.

It seems that VMWare Windows balloon drivers do behave like the Linux one:
> By default the balloon driver is used to reclaim idle memory. When the balloon inflates the GOS will first assign all “unused / free”  pages to the balloon driver. If this is enough it will stop. If this  isn’t enough the OS will decide which pages it will page out  until it  reaches its threshold.

(From [http://www.yellow-bricks.com/2010/03/11/mem-idletax/](http://www.yellow-bricks.com/2010/03/11/mem-idletax/))

We initially believed that the batch allocation introduced in [afe4a18c "balloon: bz#921891: improve ballooning's performance"](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/afe4a18c6fed9d4b32a214db1fb87ef29f3bd8e0) was responsible, in particular the deallocation of partial page batches returned by MmAllocatePagesForMdl() (see line Balloon/sys/balloon.c:185). However, trying to patch Balloon/sys/balloon.c to avoid releasing memory when the batch was not returned full, or even trying an old version (mm58) where memory was still allocated one page-at-a-time led to the same result.

Is this the intended behaviour for the Windows virtio balloon driver, or am I missing something in my setup? Is it a limitation of Windows API to allocate memory?

I have currently tested only on Windows server 2022, and Windows server 2008, with virtio balloon driver version (1) master, (2) mm201, and (3) mm58. Here are the steps to reproduce:
1. Take an 8GB Windows guest (e.g., server 2022).
2. Check the memory used in the guest (e.g., ~1.3GB in my case).
3. Start a workload consuming 4GB of memory via [TestLimit](https://docs.microsoft.com/en-us/sysinternals/downloads/testlimit) or by opening 40 Edge browser windows on a page (e.g., youtube.com). The workload keeps the memory allocated, but it shall not actively touch it (idle memory):
```
Testlimit64.exe -d 1 -c 4096
```
4. Wait 2 minutes for all the pages to become cold.
5. Set the balloon driver target to 3GB (e.g., virsh  qemu-monitor-command  guest '{ "execute": "balloon", "arguments": { "value": 4294967296}}'). 
6. Monitor the ballooned memory. It will start at 8GB, when the balloon is not inflated. Then, the ballooned memory decreases as free memory is reclaimed. The balloon driver stops when the system runs out of memory. Almost none of the workload memory gets swapped out, despite it being cold. On Linux, we would indeed see the cold pages be swapped out to relieve the pressure of an inflating balloon.
7. Kill the memory workload. Notice how the balloon suddenly reclaims all the memory.

**Comment by vrozenfe** [comment]
@andrea-segalini 
I might be missing something in your description, but technically inflating the balloon should introduce some extra memory 
pressure. After all the the balloon takes pages from non-paged pool making Windows to activate the Memory Management
write-back and lazy write mechanisms. I guess we can do it even better by adding some working set refreshing routine inside the balloon service.

Best,
Vadim.

**Comment by andrea-segalini** [comment]
Thank you @vrozenfe for your reply.

My expectation, and that is how the driver behaves on Linux, is that the extra memory pressure from an inflated balloon causes memory to be reclaimed. After any cache is dropped, cold memory would be swapped out, making more free available that the balloon driver can keep eating into until the target is met.  

This is not happening in Windows. It is pretty evident in my setup, and I managed to reproduced it multiple times. If I allocate X GB in a Windows guest, keep that memory allocated and let it go cold (e.g., via TestLimit as I posted), when I set the balloon target to a value lower than X, the balloon does not inflate to match the requested size, and it stalls right after having allocated all the free memory. It doesn't matter how long I wait, or re-issuing multiple times the command (I forgot to mention, I'm using QEMU 4.2.0 and libvirt 6), the balloon stops inflating and doesn't reach the desired target.

**Comment by YanVugenfirer** [comment]
From a very brief research, our option on Windows is to set memory priority for the processes in the system, thus hinting the system to swap out the pages https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setprocessinformation 
Looks like a cumbersome mechanism that might do more damage than good.

Other ideas are welcomed.

**Comment by JonKohler** [comment]
Do other hypervisors use that API as well? @YanVugenfirer

**Comment by YanVugenfirer** [comment]
@JonKohler I don't know. 
But frankly I doubt it. If we want to use this API, we will need to go over each process in the system and hint that memory should be swapped out. 
There are several reasons why this is not such a great idea. 
Mainly it will interfere with own Windows logic for swapping out processes.

**Comment by vrozenfe** [comment]
@andrea-segalini 
I wonder if disabling the super fetch function ( the "SysMain" service) and optionally increasing the pagefile size (3 times bigger than  the  RAM size) have any positive effect in your case.

Best,
Vadim.

**Comment by andrea-segalini** [comment]
Update:

We figured out (and let me credit @carl-nutanix for this finding) that the check for low memory in [sys\Balloon.c:154 ](https://github.com/virtio-win/kvm-guest-drivers-windows/blob/0196cb4779dd6017b735ce601dfd513a56bfa454/Balloon/sys/balloon.c#L154) is responsible for stopping the balloon driver from allocating further memory when pressure raises, and thus the guest from swapping out cold pages to relieve the pressure.

Removing the check modifies the behaviour of the balloon driver for Windows, making it similar to the virtio balloon driver for Linux, and thus enabling the hypervisor to reclaim cold pages from Windows guests. I tested it on Win10, and it worked fine. The guest was stable, and was able to swap out cold pages without any issue.

Of course, as for Linux, the balloon driver can now be set so low to cause harm to the system (e.g., crashing the guest, or thrashing the system). For instance, in Win10 the system crashes when the balloon inflated such as to leave ~400MB to the guest. We believe this not to be an issue as ballooning shall be used with care, and this is a well accepted behaviour for the not only for the Linux virtio balloon driver, but also for other balloon driver implementations such as VMware's.

We plan to propose a patch to remove the check for low memory. What do you think of this approach @vrozenfe @YanVugenfirer ? Was there a reason for low memory was there in the first place (the line was already present in the first commit)?

Thank you,
Andrea

**Comment by YanVugenfirer** [comment]
Hi Andrea,

I am a little hesitant to remove the restriction in code that can lead to crashes in production. 
Maybe the better solution is to notify the management layers that the guest is in low memory condition and cannot inflate the balloon. I know it is not a simple solution that might require virtio spec change and management layers changes, but it is more cleaner in my opinion than having Windows guests crashing from time to time.
@vrozenfe what do you think?

Best regards,
Yan.

**Comment by vrozenfe** [comment]
The logic behind of checking "LowMemoryCondition" was quite simple. This code was written many years ago, but IIRC all the details, the LowMemoryCondition happens when the number of free physical pages (nt!MmAvailablePages) is failing blow the value of  nt!MmLowMemoryThreshold. When it happens the properly written drivers supposed to release unused memory. While balloon driver supposed to be spinning until nt!MmAvailablePages will reach nt!MmHighMemoryThreshold value. This mechanism supposed to keep the entire system as robust as possible and avoid very drastic performance  degradation.
This is a very mild approach. However if you managed to implemented some quite sophisticated balloon/memory management mechanism in your VMM and want to get rid of IsLowMemory check, I think you can do it by adding a new  registry key
that will let you skip this logic, by default keeping the workflow unchanged. I completely agree with Yan on that matter.

Best,
Vadim.

**Comment by JonKohler** [comment]
Yea @vrozenfe we've been putting in a metric ton of work around memory management for overcommit in Nutanix AHV, which is why we're intensely looking at this. 

Alternatively @andrea-segalini we could remove it as a private patch to our drivers and/or wrap a reg key around it as mentioned; however, there are multiple ways for customers to install drivers many of which do not involve using our installer but rather just using the raw driver itself, so a source-level patch would be significantly easier. cc @sb-ntnx @carl-nutanix

**Comment by YanVugenfirer** [comment]
The other way to control behavior can be introducing virtio balloon feature for the device and then behaving differently in AHV based on this feature bit.

**Comment by JonKohler** [comment]
@YanVugenfirer what feature bit? We have the balloon device already presented to all guests since the beginning of time, but this new functionality is actually dealing with memory management, otherwise IIRC we just use it for stats.

**Comment by andrea-segalini** [comment]
Thanks @YanVugenfirer, @vrozenfe, and @JonKohler for your suggestions.

Upstreaming this change as feature bit for the virtio-balloon driver would be indeed a clever and clean way. However, the Linux driver would also consume this bit, and this behaviour of checking-and-stopping upon low memory only exists in Windows and not in the Linux Redhat implementation.

This means that either an additional mode of execution is eventually added, or the Linux driver would always ignore that feature bit. Would it be the right way to go? Are we sure we don't want the behaviour without the check for low memory being the default?

I understand that this exposes Windows to crashes caused by the hypervisor, but this is an intrinsic limitation of ballooning. Checking for low memory only exists in the "inflate" path. I now that is a stretch, but this means that we could "legitimately" take away memory via ballooning avoiding low memory, and yet causing a system crash if the guest OS eventually requires more memory that cannot be reclaimed. In a more common scenario, a guest can easily be brought to thrashing after ballooning, in the case guest workloads suddenly spike. As described on the official KVM page on "auto-ballooning", ballooning becomes really useful with some automation around.

**Comment by YanVugenfirer** [comment]
Hi @andrea-segalini ,

Sorry for the slow replies. I am on vacation until the next week.

First of all there is no problem adding feature bits for "Windows only" features. I remember several of those: ability to dynamically change virtio-net offloading settings, and support of RSS feature (although lately we added RSS support to Linux driver as well). You can also CC me and Vadim while sending the patch to Oasis mailing list and we can support you.

Regarding just removing the check, I think I am with agreement with @vrozenfe this is problematic. We already have a safeguard, removing it will cause additional probability to harm system stability.

Best regards,
Yan.

**Comment by vrozenfe** [comment]
I believe that in case of Windows virtio drivers, when it is possible, vendors should activate or deactivate their hypervisor specific features based on  vendors' subsystem id (which can be obtained by reading PCI device configuration space)

And btw, it will be very interesting to  see some results of your memory management optimization work. IIRC, it was
several attempts in the past to build some sophisticated memory ballooning mechanism for Windows VMs. But not
sure if anyone of them was finally turned into a product.

Cheers,
Vadim.

**Comment by YanVugenfirer** [comment]
Hi All,

We had some discussion during virtio-win community meeting regarding the possibility to use some vendor specific features.
Basically there are a lot of possibilities:

- Registry value
- Vendor according to PNP ID
- Vendor specific preprocessor variable
- Processor ID
- Virtio feature bits

According to @sb-ntnx  "Vendor specific preprocessor variable" is the most convenient. And actually there should be an example in Balloon driver for such case already (USE_BALLOON_SERVICE).

Best regards,
Yan.

**Comment by andrea-segalini** [comment]
Thanks @YanVugenfirer and @sb-ntnx. 

I'm preparing a PR with the preprocessor variable as in USE_BALLOON_SERVICE. Will post soon.

Best regards,
Andrea

**Comment by YanVugenfirer** [comment]
Solved by PR#786
