### ISSUE TITLE
Add VirtIO-GPU full graphics driver (with DirectX support)

### ISSUE THREAD

**Issue by matheuswillder** [virtio-win/kvm-guest-drivers-windows#773]
As commented in: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/668#issuecomment-1139595028

**Comment by Dave--G** [comment]
You might want to take a look at https://github.com/Arc-Compute/LibVF.IO

**Comment by gogo2464** [comment]
Should it fix https://gitlab.com/qemu-project/qemu/-/issues/1610 please? @matheuswillder

**Comment by Segment0895** [comment]
QEMU PR handles the 'engine' DirectX support.
You still need to 'teach' Windows to use the acceleration made available for the 'engine', which is what this ticket is about.
TL;DR: both tickets are required, and this one we're commenting on is non-trivial to implement.

**Comment by gogo2464** [comment]
Should we start with virtio-win? If we finish virtio-win directX support, qemu with handle directx11. After we will need an accelerator for perf...

**Comment by Segment0895** [comment]
I've no clue how it's made. Assuming you have 100+ hours you can use, my somewhat not very well founded suggestion would be to pickup the old GSoC project made in 2017 [1], be able to replicate and iterate from there. Interfaces probably changed a bit, you'll have to be stubborn.

[1] https://www.phoronix.com/news/QEMU-3D-Windows-Guests

**Comment by nooodles2023** [comment]
https://github.com/tenclass/mvisor-win-vgpu-driver
I have implemented it for win10 guest with opengl4.2 support. For directx, maybe you can translate it to opengl?

**Comment by nooodles2023** [comment]
> > https://github.com/tenclass/mvisor-win-vgpu-driver I have implemented it for win10 guest with opengl4.2 support. For directx, maybe you can translate it to opengl?
> 
> I never had heard of mvisor project before, it sounds interesting. I'll test it later when I have some free time. Thanks for indication!

It's my pleasure. Mvisor is a mini virtual machine that is based on KVM. We built it using C++ instead of C, and we have been using Mvisor in our production for 2 years.

**Comment by YanVugenfirer** [comment]
I suggest to gather every 3D related discussions in one thread for now: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/841
