### ISSUE TITLE
virtiofs service crashes when operating on certain git repositories

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [virtio-win/kvm-guest-drivers-windows#777]
**Describe the bug**
I updated to virtio-win-0.1.217-2 and WinFSP v1.10. Earlier I had even a problem with a simple git init, but that is fortunately gone now. The problem with LibreOffice binary bisect repositories remains. Even running git status in one of the repos causes virtiofs to crash.

**To Reproduce**
Steps to reproduce the behaviour:
In new Powershell, download LibreOffice 5.1 bibisect repo bundle (5.37GiB):
Invoke-WebRequest -Uri https://bibisect.libreoffice.org/win32-5.1.git-bundle -OutFile win32-5.1.git-bundle -Resume

Clone from the bundle:
git clone -o bundle win32-5.1.git-bundle bibisect-win32-5.1

Cloning will fail and virtiofs service will crash.

I took a log that includes the cloning crash after adding registry keys

```
reg add HKLM\Software\VirtIO-FS /v DebugFlags /d 0xFFFFFFFF /t REG_DWORD
reg add HKLM\Software\VirtIO-FS /v DebugLogFile /d C:\viofs.log /t REG_SZ
```

The log swelled to over 2 GB, but compressed rather nicely to 40 MB with 7-zip: https://ilmarilauhakangas.fi/viofs.7z

Something specific about the bibisect repos causes the crash as I can work fine with smaller repos in some quick random tests.

**Host:**
 - Disto: Arch Linux
 - Kernel version: 5.18.1
 - QEMU version: 7.0.0
 - QEMU command line: virt-manager
 - libvirt version: 8.4.0
 - libvirt XML file: https://ilmarilauhakangas.fi/viofs.7z (includes viofs.log)

**VM:**
 - Windows version: Windows 10 21H2
 - Which driver has a problem: Virtio-FS
 - Driver version or commit hash that was used to build the driver: virtio-win-0.1.217-2

**Comment by viktor-prutyanov** [comment]
Hi @ilmari-lauhakangas,

> Clone from the bundle:
> git clone -o bundle win32-5.1.git-bundle bibisect-win32-5.1
> 
> Cloning will fail and virtiofs service will crash.

Which error do you see when cloning?

I've faced the following:
```
PS Z:\> git clone -o bundle win32-5.1.git-bundle bibisect-win32-5.1
Cloning into 'bibisect-win32-5.1'...
Receiving objects: 100% (326590/326590), 5.36 GiB | 26.55 MiB/s, done.
Resolving deltas: 100% (298120/298120), done.
error: invalid path 'instdir/program/python-core-3.3.3/lib\__pycache__/quopri.cpython-33.pyc'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

But the service don't crash.

**Comment by ilmari-lauhakangas** [comment]
For me, it is:

```
PS Z:\> git clone -o bundle win32-5.1.git-bundle bibisect-win32-5.1
Cloning into 'bibisect-win32-5.1'...
Receiving objects: 100% (326590/326590), 5.36 GiB | 16.48 MiB/s, done.
Resolving deltas: 100% (298120/298120), done.
fatal: remote did not send all necessary objects
```

I checked again just now and confirmed the crash.

It seems the error you get is harmless.

Thanks for testing and I'm sorry that I didn't have a smaller test case.

**Comment by ilmari-lauhakangas** [comment]
> @ilmari-lauhakangas what is your host filesystem in shared folder?

It's ext4

**Comment by viktor-prutyanov** [comment]
@ilmari-lauhakangas 

Could you please try to replace
```xml
<driver type="virtiofs"/>
```
with
```xml
<driver type="virtiofs" queue="1024"/>
```

**Comment by ilmari-lauhakangas** [comment]
Thanks, adding that queue attribute helped!

I found advice to solve the git error [from our wiki](https://wiki.documentfoundation.org/QA/Bibisect/Windows#Downloading_Bibisect_Repository).

```
git config core.protectNTFS false
git reset --hard
git checkout oldest
```

However, I can't run the binaries with

`instdir\program\soffice`

Of course now we are dealing with a different issue than originally.

**Comment by ilmari-lauhakangas** [comment]
Ok, launching soffice.exe from Explorer was more informative: it could not find LCMS2.dll. After I added the dll to C:\Windows\SysWOW64 it fails to launch with error code 0xc000007b. I guess this is some 32-bit vs. 64-bit library mismatch and certainly off-topic by now :)

I tested our 64-bit 7.1 repo and it runs fine. Thanks again for your help and I guess I will close this.
