### ISSUE TITLE
Signed build of ivshmem

### ISSUE THREAD

**Issue by dionorgua** [virtio-win/kvm-guest-drivers-windows#778]
It looks like current version of ivshmem binary is very old here:
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/ 

It would be cool to have fresh binaries available

**Comment by vrozenfe** [comment]
there is a new one available at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/virtio-win-08032022.zip
Please note that only Win10 drivers are attestation signed. On Win8 platforms some extra test signing tweaks need to be done.

Best,
Vadim.

**Comment by dionorgua** [comment]
I was able to install Win10 drivers to Win11 booted with secureboot enabled. 
Thanks.

**Comment by YanVugenfirer** [comment]
Closing based on the last comment.
