### ISSUE TITLE
viosock driver downloading and installing problems

### ISSUE THREAD

**Issue by Youxu-Chen** [virtio-win/kvm-guest-drivers-windows#783]
Hi, guyz:

  I want to install viosock driver in my windows guest. But I can't find viosock driver files in the existing public package: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.217-2/

  So where can download the binary viosock driver?

  Thanks.

**Comment by Youxu-Chen** [comment]
After that, to install the viosock driver, I build the viosock repository based on the source code. But, I get an error when installing the driver.

The windows version is Win10 19044.1766 x64.

The installation instruction is "devcon install viosock.inf PCI\VEN_1AF4&DEV_1012&SUBSYS_00131AF4&REV_00" in viosock.inf.

Error: devcon failed.

Help me Please. Thanks!

**Comment by YanVugenfirer** [comment]
@Youxu-Chen Hello,

Did you test signed the driver and enabled test signing?
Try to install through device manager to get more meaningful error.

In anywise virtio-sock support is work in progress.

**Comment by Youxu-Chen** [comment]
> 

I test signed the driver and enabled test signing when building the binary and installing the driver, it failed again.

Four files are created: viosock.cat, viosock.inf, viosock.pdb and viosock.sys.

When I try to install it through device manager, I get an error:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/28796466/175892667-52d91f96-a2a1-4343-a3bd-07feb939ce5b.png">

Does viosock depend on other binary files or drivers I should build them together?

**Comment by irudakov77** [comment]
Greetings @Youxu-Chen.

Viosock driver package contains socket provider library(s), please build the Package project to make the proper install kit.

Regards,
Ilya

**Comment by Youxu-Chen** [comment]
> Greetings @Youxu-Chen.
> 
> Viosock driver package contains socket provider library(s), please build the Package project to make the proper install kit.
> 
> Regards, Ilya

@irudakov77 Thanks！The viosock driver is installed successfully in my windows vm with viosock library file. Thank you very much!

Regards,
youxu
