### ISSUE TITLE
amd gpu passthrough virtio redhat driver unable to duplicate nor utilize the gpu

### ISSUE THREAD

**Issue by fugbixer** [virtio-win/kvm-guest-drivers-windows#784]
**Describe the bug**
amd gpu passthrough virtio redhat driver unable to duplicate display over both monitors nor utilize the amd gpu.

goal would be with hdmi dummy to troll the amd gpu driver in order for games to use it instead of the Red  Hat VirtiO GPU DOD controller driver.

**To Reproduce**

gpu passthrough, windows kvm, add hdmi into gpu of kvm, install amd gpu driver, install virtio driver, use spice virtio 
try playing games or duplicate the monitor.

see it does not work currently.

when i add another hdmi adapter into the passthrough gpu, these two screen can get mirrored.
it would be very nice from you if there is any kind of solution for this. Thanks in advance!

**Expected behavior**
amd gpu passthrough virtio redhat driver unable to duplicate nor utilize the gpu
Being able to mirror / duplicate the screens or tell the vendor (amd) gpu driver to render virito spice screen with it. 

**Screenshots**

Thanks github trash upload does not work and closed tab bug report gone with everything well detailed

>  Something went really wrong, and we can’t process that file.

[https://i.imgur.com/zFSMhUB.png](https://i.imgur.com/zFSMhUB.png)

**Host:**
 - Disto: arch
 - Kernel version  5.17.15
 - QEMU version qemu-x86_64 version 7.0.0
 - QEMU command line 
 - libvirt version: libvirtd (libvirt) 8.4.0

**VM:**
 - Windows versions: all
 - Which driver has a problem: Red  Hat VirtiO GPU DOD controller
 - Driver version or commit hash that was used to build the driver: virtio-win-0.1.217

**Additional context**
github serious trash 

virtio great stuff

**Comment by YanVugenfirer** [comment]
Hello,

>> amd gpu passthrough virtio redhat driver unable to duplicate nor utilize the gpu
Those are two different things AMD GPU is passthrough to the guest and AMD driver should be install for it.
Spice (QXL device) is used for remote access and as paravirtualized graphic device. It doesn't work with another devices on Windows.
virtio-gpu is another paravirtualized device for Windows guest.

If you are trying to achieve monitor duplication with Spice from passthrough device, I suggest to open request on Spice mailing list: [spice-devel@lists.freedesktop.org](mailto:spice-devel@lists.freedesktop.org).

Best regards,
Yan.

**Comment by fugbixer** [comment]
> AMD driver should be install for it.

i did.

> Spice (QXL device) is used for remote access and as paravirtualized graphic device.

i tried, gpu utilization is very low and games as well as videos and gpu using browsers are lagging.

> trying to achieve monitor duplication with Spice from passthrough device

but its the red hat driver that is being used, how does spice provide a virtual display. you might be right about this, but i dont understand it currently since the red hat qxl or virtio drivers are used.

**Comment by fugbixer** [comment]
> AMD driver should be install for it.

i did.

> Spice (QXL device) is used for remote access and as paravirtualized graphic device.

i tried, gpu utilization is very low and games as well as videos and gpu using browsers are lagging.

> trying to achieve monitor duplication with Spice from passthrough device

but its the red hat driver that is being used, how does spice provide a virtual display. you might be right about this, but i dont understand it currently since the red hat qxl or virtio drivers are used.

my guess would be that there could be a workaround to enable duplicating the screen on windows, with the goal to force the gpu to be used for content rendering. is there any possibility that this is the case?

would it be helpful to provide a bug bounty for fixing this issue? (avg. suggestion welcome)

https://i.imgur.com/c7U8UGC.png

wow github rly does not like images with removed metadata what a trash company ms is.

>  Something went really wrong, and we can’t process that file.

if i had a nvidia card i would use moonlight / nice dvc to stream to host device. amd link does not provide a linux client.

for anyone reading this. deal with it, AMD is nice for host machine but trash for pass through.

**Comment by fugbixer** [comment]
is it reopen, man github sucks so hard

**Comment by vrozenfe** [comment]
@fugbixer 
If you are not going to use spice as a remote-display system, but run everything locally, you can try AMD for the GPU pass through + virtio-gpu as ('-device virtio-gpu-pci'). Running virtio-gpu in virtio-gpu-pci mode is very important for this scenario.

Best,
Vadim.

**Comment by fugbixer** [comment]
>Running virtio-gpu in virtio-gpu-pci mode is very important for this scenario.

not quite obvious how to achieve that. 
i guess `-device virtio-gpu-pci` is the kvm start parameter. but im a gui noob and use virt-manager

**Comment by danielwdlh** [comment]
I realize this thread is closed, but for what it's worth, it's definitely technically possible to do this, as if you _do_ _not_ install the qxl driver and just stick with the "Microsoft basic" display driver, mirroring works, albeit limited to lower resolutions. Only after installing the qxl driver does the "Mirror these Displays" option go away.

With QXL driver installed:
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/147875009/b6f70eef-560f-4515-b3e9-798268573899)

Without QXL driver installed: (not shown, SPICE display limited to 1280x800)
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/147875009/590954f7-41bf-4364-834b-afb66120dc11)
