### ISSUE TITLE
AD user does not have write access to virtio-fs

### ISSUE THREAD

**Issue by Daniel-Trevitz** [virtio-win/kvm-guest-drivers-windows#790]
**Describe the bug**
While logged into a VM that uses an active directory login there is no write access to the drive.

**To Reproduce**
I'm not really sure... 

**Expected behavior**

**Host:**
 - Debian GNU/Linux bookworm/sid
 - uname -a-->  Linux ******* 5.18.0-2-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux
 - qemu version 7.0.0
 - libvirt version 8.4.0-1
 - libvirt XML file

**VM:**
 - Windows 10 Enterprise 20H2 19042.1466
 - Component: virtio-fs
 - virtio source: virtio-win-0.1.164.iso

[win10_virt-manager.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9077706/win10_virt-manager.zip)

**Additional context**
On a VM I ported from VirtualBox, which uses an active directory corporate login, I do not have write access.
If I log in on this machine as a non-ad user, I have write access.

To evaluate who the guest /thinks/ is the owner of the network drive (Z:\ on my machines) I ran the command:
```
'C:\Program Files (x86)\WinFsp\bin\fsptool-x64.exe' perm Z:\
```  
When logged in as a normal user I get `...(perm=197609:197121:0775)` and as the AD-user machine: `...(perm=0:0:0775)`

When logged in as the normal user fsptool id returns (redacted version):
```
'C:\Program Files (x86)\WinFsp\bin\fsptool-x64.exe' id
User=S-1-5-21-994256757-583842975-1750328797-1001(***\User) (uid=197609)
Owner=S-1-5-21-994256757-583842975-1750328797-1001(***\User) (uid=197609)
Group=S-1-5-21-994256757-583842975-1750328797-513(***\None) (gid=197121)
```

When logged in as the AD user I get:
```
'C:\Program Files (x86)\WinFsp\bin\fsptool-x64.exe' id
User=S-1-5-21-***88198(***) (uid=1136774)
User=S-1-5-21-***88198(***) (uid=1136774)
Group=S-1-5-21-***-513() (gid=1049089)
```

Simply logging into the broken win10 install as a non AD user results in a working Z:\ drive.

Note that when switching from standard user to AD user fsptool perm Z:\ continues to return the uid/gid of the std User, but I do not have write access for this either.

**Comment by Daniel-Trevitz** [comment]
To diagnose the permissions issue I wanted to know what the userid was being communicated between host and guest. During this I found in virtiofs.cpp the function UpdateLocalUidGid.

I copied this code into a simple console application which can be found [here](https://github.com/Daniel-Trevitz/WindowsVirtioFSLocalUID)

While logged in as the normal user I get a simple 0x303E9 result/

When logged in as the AD user and running the console program  NetUserGetInfo fails with Status == 2221
When logged in as the AD user and running the console program with admin rights I get 2221.
When logged in as the AD user and running the console program as the standard User I still get 2221.
In each of these runs, the same user name (the AD user's name) is returned by WTSQuerySessionInformation.

**Comment by viktor-prutyanov** [comment]
Hi @Daniel-Trevitz,

Thanks for you investigation of the issue and sample program you wrote.
But, unfortunately, ActiveDirectory is not supported at the moment. It is planned for the future.
So, if you understand how to fix the problem and have a patch you are welcome.

There are some information about how NetUserGetInfo works with ActiveDirectory: https://docs.microsoft.com/en-us/windows/win32/api/lmaccess/nf-lmaccess-netusergetinfo
NetUserGetInfo seems to be inappropriate to get AD user information.
As far as I understand, the problem is that with AD the service must properly setup `SECURITY_DESCRIPTOR` here:
https://github.com/virtio-win/kvm-guest-drivers-windows/blob/79927c3521c9aed36b7ba10586ee83abd0bd8eb4/viofs/svc/virtiofs.cpp#L1290

**Comment by Daniel-Trevitz** [comment]
@viktor-prutyanov, Well that sure explains it! I just ran a check on the same VM image from virtualbox (pre when I converted the disc image over).

Though it is rather unfortunate that my example program in the other win10 AD enabled VM (same user, same permissions) works correctly - unfortunite as it's the one with visual studio... womp womp. I guess there is some difference between the two ... that I don't really care to investigate.

Are there written plans for the AD support?
Do you know of other parts in the virtio-fs or winfsp that'll need touched?

**Comment by Daniel-Trevitz** [comment]
Just for the records; Err 2221 is NERR_UserNotFound --- "The user name could not be found"

**Comment by Daniel-Trevitz** [comment]
@viktor-prutyanov, Is there any reason to not use WinFSP's FspPosixMapSidToUid? It definitely is a lot more code to run, but it also handles a lot of cases.


```
NTSTATUS FspToolGetTokenInfo(HANDLE Token,
   TOKEN_INFORMATION_CLASS TokenInformationClass, PVOID *PInfo)
{
   PVOID Info = 0;
   DWORD Size;
   NTSTATUS Result;

   if (GetTokenInformation(Token, TokenInformationClass, 0, 0, &Size))
   {
      Result = STATUS_INVALID_PARAMETER;
      goto exit;
   }

   if (ERROR_INSUFFICIENT_BUFFER != GetLastError())
   {
      Result = FspNtStatusFromWin32(GetLastError());
      goto exit;
   }

   Info = MemAlloc(Size);
   if (0 == Info)
   {
      Result = STATUS_INSUFFICIENT_RESOURCES;
      goto exit;
   }

   if (!GetTokenInformation(Token, TokenInformationClass, Info, Size, &Size))
   {
      Result = FspNtStatusFromWin32(GetLastError());
      goto exit;
   }

   *PInfo = Info;
   Result = STATUS_SUCCESS;

 exit :
   if (!NT_SUCCESS(Result))
      MemFree(Info);

   return Result;
}

int get_id(PSID Sid, UINT32 *Uid)
{
   PWSTR Str = 0;
   NTSTATUS Result;

   if (!ConvertSidToStringSidW(Sid, &Str))
   {
      Result = FspNtStatusFromWin32(GetLastError());
      goto exit;
   }

   Result = FspPosixMapSidToUid(Sid, Uid);
   if (!NT_SUCCESS(Result))
      goto exit;

   Result = STATUS_SUCCESS;

exit:
   LocalFree(Str);

   return Result;
}

int fsp_approach()
{
   NTSTATUS Result;

   HANDLE Token = 0;
   TOKEN_USER *Uinfo = 0;
   TOKEN_PRIMARY_GROUP *Ginfo = 0;

   if (!OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &Token))
   {
       Result = FspNtStatusFromWin32(GetLastError());
       return 0;
   }

   std::cout << "Got Token\n";

   Result = FspToolGetTokenInfo(Token, TokenUser, (void**)&Uinfo);
   if (!NT_SUCCESS(Result))
      goto exit;

   std::cout << "Got TokenUser\n";

   Result = FspToolGetTokenInfo(Token, TokenPrimaryGroup, (void**)&Ginfo);
   if (!NT_SUCCESS(Result))
      goto exit;

   std::cout << "Got TokenPrimaryGroup\n";

   UINT32 UID, GID;

   get_id(Uinfo->User.Sid, &UID);
   get_id(Ginfo->PrimaryGroup, &GID);

   std::cout << "FSP UID: " << UID << "\n";
   std::cout << "FSP GID: " << GID << "\n";

exit:
   MemFree(Uinfo);

   if (0 != Token)
      CloseHandle(Token);

}
```

**Comment by Daniel-Trevitz** [comment]
#791 seems to essentially work. When I start the process the correct UID/GID seems to be used as I now have write access.

However... If I start the process as a service the original problem manifests.

**Comment by YanVugenfirer** [comment]
> #791 seems to essentially work. When I start the process the correct UID/GID seems to be used as I now have write access.
> 
> However... If I start the process as a service the original problem manifests.

Sorry, do you mean virtiofs.exe process or the process that uses virtio-fs mount? 
If  virtiofs.exe, that it looks that you need to take a look at impersonation https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-impersonateloggedonuser

**Comment by Daniel-Trevitz** [comment]
@YanVugenfirer, When I start virtiofs.exe the log entry I added to state the detected UID/GID reads out the same value for both automatically running the service and manually running the service.
However, even though the localGID / localUID are now correct, when I start the service (either via boot or manually restarting) explorer.exe reports that it does not have access.

**Comment by Daniel-Trevitz** [comment]
When I run the service now, I get the message
```
*** UpdateLocalUidGid: Failed to impersonate logged on user
```

static VOID UpdateLocalUidGid(VIRTFS *VirtFs)
{
    NTSTATUS Result;

    HANDLE Token = 0;
    TOKEN_USER *Uinfo = NULL;
    TOKEN_PRIMARY_GROUP *Ginfo = NULL;

    if (!OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &Token))
    {
        VirtFs->LocalUid = 0;
        VirtFs->LocalGid = 0;
        DBG("Failed to open a process token");
        return;
    }

    if(!ImpersonateLoggedOnUser(Token))
    {
        VirtFs->LocalUid = 0;
        VirtFs->LocalGid = 0;
        DBG("Failed to impersonate logged on user");
        CloseHandle(Token);
        return;
    }

    Result = FspToolGetTokenInfo(Token, TokenUser, (PVOID*)&Uinfo);
    if (!NT_SUCCESS(Result))
       goto exit;

    Result = FspToolGetTokenInfo(Token, TokenPrimaryGroup, (PVOID*)&Ginfo);
    if (!NT_SUCCESS(Result))
       goto exit;

    Result = FspPosixMapSidToUid(Uinfo->User.Sid, &(VirtFs->LocalUid));
    Result = FspPosixMapSidToUid(Ginfo->PrimaryGroup, &(VirtFs->LocalGid));

    DBG("local UID=%u, local GID=%u", VirtFs->LocalUid, VirtFs->LocalGid);

exit:
    SafeHeapFree(Uinfo);
    SafeHeapFree(Ginfo);
    CloseHandle(Token);
}
```

**Comment by Daniel-Trevitz** [comment]
I've attached two log files. Same process for both, run once from powershell, and once from the "start" service button in the service manager. 

This has an implementation as the above comment, but without impersonate.

[Started_as_Service.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9084344/Started_as_Service.log)
[Started_From_Powershell.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9084346/Started_From_Powershell.log)

**Comment by Daniel-Trevitz** [comment]
The log file clearly shows on line 3 that the UID and GID are different...  leading credence to needing to do the impersonation - but since that doesn't run...

I also tried to start the service as my AD user, but the service manager says I'm not allowed to do that. What a pain...

**Comment by Daniel-Trevitz** [comment]
Ignore all my previous comments. WTSQueryUserToken did the trick. See PR #792.

**Comment by Corrupter-rot** [comment]
Don't think if my issue is related to this one but when copying large game file from Windows guest to a shared drive (virtiofs) with linux host, I get error such as `Permission denied to the folder`.
