### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by Daniel-Trevitz** [virtio-win/kvm-guest-drivers-windows#793]
Files and folders that start with "." should be flagged as hidden to windows.

Probably should have flag to enable or disable? Default of enabled?

**Comment by YanVugenfirer** [comment]
@Daniel-Trevitz 

I personally prefer not to have too much flags, as 99% of people will not use them :)
But, in case we have. My preference would be enabled (flag "." files as hidden on Windows).

Best regards,
Yan.

**Comment by Daniel-Trevitz** [comment]
@YanVugenfirer, Good with me. I also added a registry flag; do you want me to keep that?

**Comment by YanVugenfirer** [comment]
@Daniel-Trevitz Let's keep it.

**Comment by scottdmilner** [comment]
Is there an update on this? This would be a useful feature to have. This is the default behavior when mounting a Linux samba share: all files starting with `.` are automatically flagged as hidden.

**Comment by viktor-prutyanov** [comment]
> Is there an update on this? This would be a useful feature to have. This is the default behavior when mounting a Linux samba share: all files starting with `.` are automatically flagged as hidden.

What exactly is the benefit here?

**Comment by scottdmilner** [comment]
> What exactly is the benefit here?
The benefit is that the same files are shown/hidden in the Windows filesystem as are shown/hidden in the Linux filesystem. If I look at a filesystem in Nemo or Dolphin (or in a shell with ls), then I will see the same folders/files when looking at that filesystem in the Windows File Manager. It cleans up visual clutter.

**Comment by YanVugenfirer** [comment]
@scottdmilner Currently, we are not planning to implement file hiding. If someone is motivated enough to do it (controlled by the flag, with default off), we will happily review the patches.

**Comment by scottdmilner** [comment]
@YanVugenfirer if I'm reading the discussion correctly, I believe that this PR implemented this functionality? https://github.com/virtio-win/kvm-guest-drivers-windows/pull/797

**Comment by YanVugenfirer** [comment]
@scottdmilner  Thank you very much for finding this discussion!
I tried to recall yesterday where we documented the discussion regarding hidden files and could find out.
So trying to recap what was said and decided: because there is no exact specification on how the hidden files should be treated, we might end with strange corner case bugs.
