### ISSUE TITLE
AD doesn't work at boot

### ISSUE THREAD

**Issue by Daniel-Trevitz** [virtio-win/kvm-guest-drivers-windows#798]
Active Directory doesn't work at boot. Restarting the service after login fixes it.

Modding vitiofs.exe to always debug log, we see:
```
*** VIRTFS::Start: The service V was not run as the LocalSytem user
*** UpdateLocalUidGid: Local UID=18, local GID=18
```

Modding it further to print the SID strings:
```
*** VIRTFS::Start: The service VirtIO-FS was not run as the LocalSytem user, 1008
*** UpdateLocalUidGid: Local User  SID:S-1-5-18
*** UpdateLocalUidGid: Local Group SID:S-1-5-18
*** UpdateLocalUidGid: Local UID=18, local GID=18
```

1008 is the error code from WTSQueryUserToken at boot.

**Comment by Daniel-Trevitz** [comment]
Similar issue reported [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ad9f8095-87c9-4d54-a84c-bc62f0e0e8e0/wtsqueryusertoken-fails-with-error-1008-if-team-viewer-and-perhaps-remote-desktop-is-running-at?forum=windowssecurity)

A solution is to run the service as an "Automatic (Delayed Start)" service.

This solution sucks. delayed start on my box is /super/ delayed.

**Comment by YanVugenfirer** [comment]
What's the session ID in this case? Should be 0.
But, it is shared between different pseudo users "SYSTEM", NETWORK SERVICE," and "LOCAL SERVICE" - that should have different security tokens. 
Another direction could be try to understand after check which service start WTSQueryUserToken works and put this service as dependency for virtio-fs service.

**Comment by Daniel-Trevitz** [comment]
I was able to fix it last night; just ran out of steam to push it.
