### ISSUE TITLE
Update virtio-win signed drivers

### ISSUE THREAD

**Issue by fubar-1** [virtio-win/kvm-guest-drivers-windows#801]
As one of the users experiencing issues with virtio-win 217 drivers, I see there have been commits to address reported issues that I've also experienced, like not installing correctly & the numerous virtiofs patches to issues since 217 was published.  I'd like to install these updates, test, and provide feedback on these known bugs. 

217 is dated 5-31-22 (six weeks behind) and, like probably hundreds of other users, I've been patiently waiting for a new build to be published.  Unfortunately I don't have the time / resources to build & sign the drivers myself. Self-builds also unnecessarily open the door to more QA confusion by introducing additional variables into the discussion.  "What commit did you build??", etc.

Can the project team please produce an updated signed build some time soon?  Can someone give us an ETA on when we might expect it?

I'd suggest someone look into just automatically publishing builds out of your CI server when they pass validation (with appropriate warnings of course) so testers can provide better feedback and stop whining about stale builds :)

Along with this I'd include validation test output somewhere so testers can more easily see what's tested, how it's tested, and that it passes.

**Comment by JonKohler** [comment]
I took a stab at this in my dev branch to just have GitHub actions take care of this. That way you can have "a build" from a given commit in both pre and post commit workflows. That build may or may not have passed every validation test under the sun, but at least it would be "there".

That and having some of the CI actions in GitHub actions makes things quite a bit more transparent rather than having it locked behind a private CI exclusively 

Any thoughts? Happy to push a PR for this to at least have basic build matrix support, which could then publish an artifact

**Comment by vrozenfe** [comment]
@fubar-1 
Thank you for your feedback and suggestions. At the moment we are working on publishing a new "stable" based on build 221. We will try to push the new "latest" one right after that.

Best,
Vadim.

**Comment by YanVugenfirer** [comment]
@JonKohler We already copy some of the build artefacts for each PR. For example, you can see pvpanic driver package and the test results: https://www.dropbox.com/sh/nfywarl6wr40y6i/AACajqMTbhR2eJIBmM890TVza?dl=0&lst= 
We can change CI to publish all the drivers, but they will not be signed at all and we need to think about build versioning in order not to create confusion.
We don't want to use publicly available CIs as there is a restriction on free tiers for the time that CI can run. And we want to test SDV as part of the CI build. Currently for all the platform + SDV for all the drivers runs for ±two hours.

**Comment by vrozenfe** [comment]
Hi @fubar-1 
I'm really sorry for delay.
I will try pushing 221 on the weekend.  

The team is currently working on new features and internal releases,
this is the main reason why you don't see  many commits recently.

Cheers,
Vadim.

**Comment by vrozenfe** [comment]
We can  continue maintaining the upstream drives at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/ 
But it will take some time to make adjustments in our build and attestation signing process.
@YanVugenfirer Yan, what do you think?

**Comment by YanVugenfirer** [comment]
> We can continue maintaining the upstream drives at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/
> But it will take some time to make adjustments in our build and attestation signing process.
> @YanVugenfirer Yan, what do you think?

Yes, it looks like a good idea. There is a need for upstream builds.
Another thing is that we might need to mark somehow stable and integration builds.

**Comment by vrozenfe** [comment]
A new upstream build is available at 
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/virtio-win-08032022.zip
The build was done from the upstream snapshot on Aug 3rd, 2022. All Win10 binaries are attestation signed
by Microsoft.
Best,
Vadim.
