### ISSUE TITLE
[Windows 11][aarch64] how to configure virtio-gpu to run with Windows 11 for aarch64 VM? 

### ISSUE THREAD

**Issue by bryantclcqq** [virtio-win/kvm-guest-drivers-windows#805]
1. configure qemu with -device virtio-vga
2. install viogpu dod driver in win 11 vm
When I update the viogpu driver, it will get a bsod (Blue Screen Of Dead). As I know virtio-gpu works ok for windows 10 on X86 machine.
Does anyone know what's happening? Can virtio-gpu run with qemu kvm windows 11 on aarch64 machines?

-----------------------------------------------------------
qemu: v7.0.0
Linux: 4.19
Windows 11 guest: Windows 11 for arm 21H2

**Comment by vrozenfe** [comment]
@bryantclcqq 
Honestly, I've never tried to run virtio-gpu on ARM64, But I'm very interested in your experience and will
happy to investigate and try to fix this issue. 
Cany you please share the qemu command line, and if possible the crash dump file?

All the best,
Vadim.

**Comment by zyimin** [comment]
I also encountered this problem. The dump file showed the postion crashing was due to KeAcquireSpinLockRaiseToDpc in VioGpuBuf::GetBuf(). The code of BSOD is IRQL NOT Less or Equal.

**Comment by zyimin** [comment]
Is there any guide to build virtio gpu driver with win11 arm version?

**Comment by vrozenfe** [comment]
@zyimin 
Can you share the crash dump file and the qemu command line?

There are some instructions how to set up the build environment and how to build the virtio-win drivers at Wiki page https://github.com/virtio-win/kvm-guest-drivers-windows/wiki

Vadim.

**Comment by zyimin** [comment]
I used the 7.0.0 qemu compiled by myself. Qemu cmd line is
`qemu-system-aarch64  -nodefaults -m 6G -machine virt,kernel-irqchip=on,virtualization=off,its=off,gic-version=3 -accel kvm -cpu host -smp 4 -bios ./QEMU_EFI.fd  -device nec-usb-xhci -device usb-kbd -device usb-tablet -device usb-storage,drive=win11 -drive if=none,id=win11,format=qcow2,file=./win11_disk.qcow2,overlap-check=none,cache=unsafe -device ramfb -vnc :1 -device virtio-net-pci,netdev=user0 -netdev user,id=user0 -device virtio-gpu-pci`

The BSOD must be reproduced if viogpu driver starts up. Because of the network limitation, I can't send the dump file to you. Sorry about that.

**Comment by gaojinhao** [comment]
I want to run with windows 11 for aarch64 with virtio-gpu. How do I install viogpu dod driver?

**Comment by bryantclcqq** [comment]
hi @vrozenfe, as shown in this issue, virtio-gpu from spice guest tools could setup and run successfully. However virtio-gpu from virtio-win release iso cound not run, which suffer bsod (Blue Screen Of Deadth) problem.
https://github.com/utmapp/UTM/issues/3293

Do you know what is difference between them? Could virtio-win fix this bsod problem?

**Comment by vrozenfe** [comment]
@bryantclcqq 
Honestly, I'm really surprised that spice comes with virtio-gpu drivers, and especially with ARM64 version signed with Microsoft Windows Third Party Component signature. I need to confirm with our spice guys the origin of this driver, but it seems to be based on build 208..210
The latest virtio-win build available for download is 221. This build includes several virtio-gpu reelated fixes and optimisations, but AFAIK was never tested on ARM64 platforms. 
I would really like to make sure that ARM64 version of virtio-gpu driver working properly, but unfortunately I don't have any ARM64 system except for RPI 4 at the moment.
If you can share the crash dump file via google drive, dropbox or any other service, please ping me at vrozenfe_at_redhat_dot_com.

Best,
Vadim.

**Comment by Vogtinator** [comment]
FTR, I'm using `-device virtio-gpu-pci` on Win 11 in QEMU with the current latest virtio-win.iso driver, the only issue is that I'm unable to change the resolution (using the VNC backend).
My setup is this: https://gist.github.com/Vogtinator/293c4f90c5e92838f7e72610725905fd

**Comment by giantstars** [comment]
Use qemu-system-aarch64 version 8.0 Use 'virtio-gpu' graphics card to install the ARM64 'viogpudo' driver in 'virtio-win 0.1.229' in windows11 for arm. The installation is successful, but the resolution cannot be set. May I ask which great God can give some advice?

**Comment by Vogtinator** [comment]
If there's a way I haven't found it it

**Comment by giantstars** [comment]
> If there's a way I haven't found it it

This result is already very good for me, just a little greedy, thank you very much

**Comment by 414aaj** [comment]
我发现一个bug，当只使用-device virtio-gpu时也只有一个分辨率，但是同时使用-device virtio-gpu;-device ramfb并且将屏幕2设置为主屏后就会使qemu获得更多分辨率

I found a bug. When only using   -device virtio-gpu  , there is only one resolution available. However, when using   -device virtio-gpu   and   -device ramfb   simultaneously, and setting Screen 2 as the primary screen, QEMU will gain more resolutions.

sudo qemu-system-aarch64 \
  -m 4G -smp 4 -cpu host -M virt -accel hvf \
  -drive if=pflash,format=raw,file=edk2-aarch64-code.fd,readonly=on \
  -drive if=pflash,format=raw,file=edk2-arm-vars.fd \
  -device virtio-gpu \
  -device ramfb \
  -device qemu-xhci \
  -device usb-kbd \
  -device usb-tablet \
  -netdev vmnet-bridged,id=net0,ifname=en0 -device virtio-net-pci,netdev=net0 \
  -device usb-storage,drive=install \
  -drive if=none,id=install,format=raw,media=cdrom,readonly=on,file=virtio-win-0.1.262.iso  \
  -device virtio-blk,drive=system \
  -drive if=none,id=system,format=qcow2,file=win11.qcow2

![Image](https://github.com/user-attachments/assets/d894401a-2d1a-4536-ac74-b126be831c25)

只是在开机的时候会出现

It only occurs at startup.

![Image](https://github.com/user-attachments/assets/69db5d1c-fff5-4f50-b7df-d6aa806495d7)

等带一会儿就能获取到-device virtio-gpu设置的高分辨率了

After waiting for a while, the high resolution set by   -device virtio-gpu   can be obtained.

![Image](https://github.com/user-attachments/assets/a262c1c8-fcb8-40c2-b3b8-cab76e45487e)

同时也支持vnc后端

It also supports the VNC backend.

> 使用QEMU-SYSTEM-AARCH64版本8.0使用“ Virtio-GPU”图形卡在Windows11中的“ Virtio-Win 0.1.229”中安装ARM64'Viogpudo'Driver。安装成功，但无法设置分辨率。我可以问哪个伟大的上帝可以给出一些建议？

**Comment by 414aaj** [comment]
> 使用QEMU-SYSTEM-AARCH64版本8.0使用“ Virtio-GPU”图形卡在Windows11中的“ Virtio-Win 0.1.229”中安装ARM64'Viogpudo'Driver。安装成功，但无法设置分辨率。我可以问哪个伟大的上帝可以给出一些建议？


我发现一个bug，当只使用-device virtio-gpu时也只有一个分辨率，但是同时使用-device virtio-gpu;-device ramfb并且将屏幕2设置为主屏后就会使qemu获得更多分辨率

I found a bug. When only using   -device virtio-gpu  , there is only one resolution available. However, when using   -device virtio-gpu   and   -device ramfb   simultaneously, and setting Screen 2 as the primary screen, QEMU will gain more resolutions.

sudo qemu-system-aarch64 \
  -m 4G -smp 4 -cpu host -M virt -accel hvf \
  -drive if=pflash,format=raw,file=edk2-aarch64-code.fd,readonly=on \
  -drive if=pflash,format=raw,file=edk2-arm-vars.fd \
  -device virtio-gpu \
  -device ramfb \
  -device qemu-xhci \
  -device usb-kbd \
  -device usb-tablet \
  -netdev vmnet-bridged,id=net0,ifname=en0 -device virtio-net-pci,netdev=net0 \
  -device usb-storage,drive=install \
  -drive if=none,id=install,format=raw,media=cdrom,readonly=on,file=virtio-win-0.1.262.iso  \
  -device virtio-blk,drive=system \
  -drive if=none,id=system,format=qcow2,file=win11.qcow2

![Image](https://github.com/user-attachments/assets/d894401a-2d1a-4536-ac74-b126be831c25)

只是在开机的时候会出现

It only occurs at startup.

![Image](https://github.com/user-attachments/assets/69db5d1c-fff5-4f50-b7df-d6aa806495d7)

等带一会儿就能获取到-device virtio-gpu设置的高分辨率了

After waiting for a while, the high resolution set by   -device virtio-gpu   can be obtained.

![Image](https://github.com/user-attachments/assets/b42ad40b-18d3-4817-a3f5-91caa6615c70)

同时也支持vnc后端

It also supports the VNC backend.

> 使用QEMU-SYSTEM-AARCH64版本8.0使用“ Virtio-GPU”图形卡在Windows11中的“ Virtio-Win 0.1.229”中安装ARM64'Viogpudo'Driver。安装成功，但无法设置分辨率。我可以问哪个伟大的上帝可以给出一些建议？

**Comment by YanVugenfirer** [comment]
@414aaj can you please open a separate issue?

**Comment by 414aaj** [comment]
> [@414aaj](https://github.com/414aaj)您能打开一个单独的问题吗？

I don't have any issues. I just saw someone above saying that the resolution can't be adjusted, and I replied to them.
