### ISSUE TITLE
The doc should say that Windows XP is unsupported

### ISSUE THREAD

**Issue by oliviercailloux** [virtio-win/kvm-guest-drivers-windows#808]
**Describe the bug**
I lost hours trying to make Windows XP accept the Virtio-fs drivers, and just learnt that it is unsupported (#807). As I could easily find tutorials that talk about Windows XP and Virtio (https://www.youtube.com/watch?v=7Px1CvY5Pow, https://wiki.archlinux.org/title/QEMU#Preparing_a_Windows_guest mentions Windows XP, https://pve.proxmox.com/wiki/Windows_XP_Guest_Notes, …), this possibility didn’t even occur to me.

Also, the [README](https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/README.md) here indicates: “Cross-signed drivers can be used on all versions of Windows except for the latest Windows 10 with secure boot enabled.”

It would be great also if you could indicate whether “unsupported” means that it should work but you don’t provide support any more for this OS, or if it means that the drivers aren’t even supposed to work and it’s not even worth trying.

Also please consider not including an “xp” folder in the fedora ISO if it is not expected to work (I’m not sure this should be asked here or elsewhere).

Thanks for consideration.

**Comment by YanVugenfirer** [comment]
Hello @oliviercailloux, We are not developing new features\drivers for Windows XP\7.
Actually current master branch cannot be compiled for XP or Win7 (there are tags marking latest compilable code for those Windows versions).
As virtio-fs support was developed recently, from the beginning it was not intended to support Windows XP. Meaning, there are no binaries for Windows XP of virtio-fs. "Older" drivers have Windows XP drivers, so for example NetKVM (virtio-net) or viostor (virtio-block) drivers from XP directory should work on Windows XP.

We can create better description in README file regarding different drivers (@vrozenfe ).

Best regards,
Yan.

**Comment by oliviercailloux** [comment]
Thank you for the additional explanation, that is helpful and appreciated.

Yes, some short explanation in the README would be helpful, I believe. I think that one similar to the one you just gave would be adequate.
