### ISSUE TITLE
[vioscsi] saving BSOD crash dumps fails

### ISSUE THREAD

**Issue by main--** [virtio-win/kvm-guest-drivers-windows#809]
It seems that a similar issue was fixed back in #321, but I'm now observing the same problem again. Generating a minidump usually works, but other types of crash dump just fail/abort at 0% progress, producing a (very) corrupted dump file.

I can reproduce the problem with the latest build (221), but also with earlier builds, so not sure when it was introduced.

This is on Windows 10 21H2 x64 with qemu 7.0.0.

**Comment by vrozenfe** [comment]
@main-- 
Can you please post the qemu command line, and let me know how did you trigger the crash ?

Thanks,
Vadim.

**Comment by main--** [comment]
Sure!

Here is my command line:

```
cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd /tmp && qemu-system-x86_64 -enable-kvm -machine q35 -cpu host
-rtc base=localtime -nodefaults -net none -display gtk -vga qxl 
-drive if=pflash,format=raw,unit=0,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd 
-drive if=pflash,format=raw,unit=1,file=/tmp/OVMF_VARS.fd -device virtio-scsi-pci,id=scsi 
-m 8G -smp cores=22 -device qemu-xhci -device usb-kbd -device usb-tablet 
-drive file=windows.raw,id=disk,format=raw,if=none,cache=none,aio=io_uring,discard=unmap 
-device scsi-hd,drive=disk
```

I triggered the crash using the Sysinternals NotMyFault tool.

**Comment by vrozenfe** [comment]
@main-- 
Confirmed.
Reproduced on seabios setup with nmi interrupt as well.
I will ask QE to file a new bug in RH bugzilla and try to fix it
in the following days.

Thanks a lot for reporting the problem. 
Vadim.

**Comment by vrozenfe** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2118630
