### ISSUE TITLE
[virtio-win][viostor]windows server 2003 SP2 32bit stuck during installing after loading the virtio blk driver

### ISSUE THREAD

**Issue by vipmike007** [virtio-win/kvm-guest-drivers-windows#81]
package
RHEL7.1 standard host
qemu-kvm-1.5.3-86.el7.x86_64
3.10.0-229.el7.x86_64
virtio-win-prewhql-0.1.102
guest iso  :WIN_2003_SP2.iso

Steps to reproduce
1.# /usr/libexec/qemu-kvm -m 4G -smp 4 -drive file=CRM_Win2003SP2.qcow2,if=none,format=qcow2,werror=stop,cache=unsafe,id=drive-rhel -device virtio-blk-pci,id=rhel,drive=drive-rhel -netdev tap,id=netdev0,script=/etc/ovs-ifup,downscript=/etc/ovs-ifdown,vhost=on -device virtio-net-pci,id=net0,netdev=netdev0 -drive file=WIN_2003_SP2.iso,format=raw,media=cdrom,id=drive-cdrom1,if=none -device ide-drive,id=cdrom1,drive=drive-cdrom1 -drive file=virtio-win-0.1.102.iso,format=raw,media=cdrom,id=drive-cdrom2,if=none -device ide-drive,id=cdrom2,drive=drive-cdrom2 -device virtio-balloon-pci,id=balloon0 -device virtio-serial-pci,id=serial0 -device virtio-rng-pci,id=rng0 -vnc :6 -monitor stdio -fda ~/virtio-win-0.1.102_x86.vfd
1. press F6 to load virtio-win-prewhql-0.1.102 windows 2003 32 bit viostor driver

Actual Results:
guest stuck and can not continue installing.

Additional info:
switch virtio-blk-pci to ide-drive ,the issue has gone.

**Comment by vrozenfe** [comment]
Looks same as 
https://bugzilla.redhat.com/show_bug.cgi?id=1274048

Should be fixed in build 112.
Best regards,
Vadim.

**Comment by vipmike007** [comment]
Thanks Vadim.
I will try to verify it when I have rhe chance to get the driver >= 112

Best Regards,
Mike

**Comment by YanVugenfirer** [comment]
Hi Mike,

Was the issues solved?

Thanks,
Yan.

**Comment by YanVugenfirer** [comment]
Fixed according to https://bugzilla.redhat.com/show_bug.cgi?id=1274048
