### ISSUE TITLE
[Quesion]How can i install qemu-ga without WindowsInstaller?

### ISSUE THREAD

**Issue by dontknowhy** [virtio-win/kvm-guest-drivers-windows#817]
I have a Windows without WindowsInstaller.
I copied files to the right place.
But i cann't run because there were some registration entry didn't writed to system.
How can i fix it?

**Comment by vrozenfe** [comment]
You can find qemu-ga MSIs on virtio-win.iso under  "guest-agent" directory or on the rpm itself
under /usr/share/virtio-win/guest-agent/

**Comment by dontknowhy** [comment]
> You can find qemu-ga MSIs on virtio-win.iso under  "guest-agent" directory or on the rpm itself
> under /usr/share/virtio-win/guest-agent/ 

I said I don't have any Windows Installer service.
I did find the MSI package,But i cann't install it because the Windows Installer.
That's why i opened this issue.

**Comment by YanVugenfirer** [comment]
You need to register qemu-ga as a service (although you can run it manually as well as an application):
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.2

And you need to register vss service  (example from installer how to do it) https://github.com/qemu/qemu/blob/master/qga/installer/qemu-ga.wxs#L123 

You will need to extract from MSI dependency DLL as well and copy them with qemu-ga.exe : https://github.com/qemu/qemu/blob/master/qga/installer/qemu-ga.wxs#L78

**Comment by dontknowhy** [comment]
> You need to register qemu-ga as a service (although you can run it manually as well as an application):
> https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.2
> 
> And you need to register vss service  (example from installer how to do it) https://github.com/qemu/qemu/blob/master/qga/installer/qemu-ga.wxs#L123 
> 
> You will need to extract from MSI dependency DLL as well and copy them with qemu-ga.exe : https://github.com/qemu/qemu/blob/master/qga/installer/qemu-ga.wxs#L78
> 
> 
> 

I know what am i need to do now.
But i still don't know what's the  $(var.QEMU_GA_MANUFACTURER) and $(var.QEMU_GA_DISTRO) mean?

**Comment by YanVugenfirer** [comment]
You can disregard those keys

**Comment by dontknowhy** [comment]
> You can disregard those keys
But the system said i didn't have the dll file(the message box said)
But i didn't have one:
![Screenshot_20220901_231639.jpg](https://user-images.githubusercontent.com/85813508/187950422-55cb66d8-75e9-4c38-832f-d33cf182c583.jpg)
