### ISSUE TITLE
Support  building using Clang, MinGW, CMake and free and open source impls of DDK, like MinGW and ReactOS

### ISSUE THREAD

**Issue by KOLANICH** [virtio-win/kvm-guest-drivers-windows#820]
**Is your feature request related to a problem? Please describe.**
Currently this software depends on proprietary overbloated tools with telemetry, which makes its development extremily inconvenient.

**Describe the solution you'd like**
Supporting free toolchains and DDKs.

**Describe alternatives you've considered**

**Additional context**

**Comment by YanVugenfirer** [comment]
Another problem of course is that MingW and ReactOS are lagging after MS DDK. And that will make a support of new OS releases nearly impossible in timely manner.
