### ISSUE TITLE
VirtIO Balloon Driver Doesn't Support Dynamic Memory Allocation

### ISSUE THREAD

**Issue by MohammadrezaNasrabadi** [virtio-win/kvm-guest-drivers-windows#821]
Hi. Whenever I emulate a linux-based OS using `qemu`, I see the amount of memory that has been allocated to the VM via `htop` command is equal to the amount of memory that processes within the guest OS really consume.

But If I emulate a `Windows 10` OS with the same `qemu` options given for linux-based scenario, I saw from host point of view, all of the specified memory is allocated to the `qemu` process. ( for example, 8GB memory will be allocated if the `qemu` process launch with 8GB memory ). However, from the VM point of view, the amount of using memory observed from `task manager` is much lower. (for example 2GB)

I thought that maybe the `virtio ballooning driver` should not be installed properly. But I could manage memory allocation by issuing `qmp` ballooning query. So I am sure that the problem should not be either on the guest OS side or balloon driver misconfiguration.

How can I have dynamic memory allocation enabled for windows guest OS as well as for linux-based family?

Below is the `qemu` command I'm issuing for both linux-base and windows-base OSes.

```
qemu-system-x86_64 -accel kvm -machine q35 -smp 1 -m 8192M
-name test-ballooning -uuid ID
-cpu host,host-cache-info=on,l3-cache=off 
-device qemu-xhci,id=xhci -device usb-tablet,bus=xhci.0 
-daemonize 
-vnc IP:0,to=100,password=off,websocket=on 
-chardev socket,id=qmp,path=PATH.qmp,server=on,wait=off -mon chardev=qmp,mode=control,pretty=off 
-chardev socket,id=hmp,path=PATH.hmp,server=on,wait=off -mon chardev=hmp,mode=readline 
-chardev socket,path=PATH.qga,server=on,wait=off,id=qga0  -device virtio-serial -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 
-no-shutdown 
-drive file=IMAGE.img,if=none,id=disk0,l2-cache-size=8M,format=qcow2 -device virtio-blk-pci,drive=disk0,scsi=off,bootindex=2 
-drive if=none,id=cdrom0,file=CDROM.iso,format=raw -device virtio-scsi -device scsi-cd,drive=cdrom0,bootindex=1 
-nodefaults
-vga cirrus -device AC97 -chardev socket,id=serialport,path=PATH.tty,server=on,wait=off -serial chardev:serialport 
-netdev tap,id=nic0,ifname=IFNAME,script=no,downscript=no -device virtio-net-pci,netdev=nic0,mac=MAC 
-device virtio-balloon-pci,deflate-on-oom=on
```

My host operating system is `Debian 11` and the version of `qemu` I'm using is `QEMU emulator version 5.2.0 (Debian 1:5.2+dfsg-11+deb11u2)` and the version of virtio driver I'm using is the currently stable version.

**Comment by YanVugenfirer** [comment]
@MohammadrezaNasrabadi Hello, can you please post screenshots from Windows guest task manager with the memory consumption info?

**Comment by YanVugenfirer** [comment]
The VM has 8G of memory (so there is no problem).
2.1G is the consumption by the OS and the processes running in the VM.
And 5.8 are free for additional use by the OS and applications.

**Comment by MohammadrezaNasrabadi** [comment]
Yes, 5.8GB of memory is free on the guest OS side. But it is not the same on the host side.

5.8G of RAM is allocated to the VM without any special reason while the ballooning driver is working properly.

I think the ballooning driver should be helpful in such situation in order to have memory overcommitment.

**Comment by YanVugenfirer** [comment]
Yes, if you inflate the balloon: https://wiki.archlinux.org/title/QEMU#Balloon_driver

**Comment by YanVugenfirer** [comment]
With virsh (if you are using libvirt to execute VMs): https://unix.stackexchange.com/questions/413457/how-can-i-manually-trigger-the-virtio-balloon-driver-on-a-guest

**Comment by MohammadrezaNasrabadi** [comment]
Is there any way to have automatic ballooning instead of issuing qmp balloon query manually?

I'm wondering whenever I spawn a linux-guest OS, the host automatic memory ballooning is working perfectly. But this is not true for Windows family guest OS.

Below is an example of spawning qemu process for a linux-guest OS:

qemu memory consumption on host POV:

![image](https://user-images.githubusercontent.com/77168970/188633564-31e5b360-9d76-4a65-917f-c4c29ea7130a.png)


That is exactly the same with memory is consuming within the VM without issuing any balloon query:

![image](https://user-images.githubusercontent.com/77168970/188633237-71293b91-152e-4e05-9431-3fbb9ec387b6.png)

My main question is why automatic memory allocation is not enabled for windows case but it is enabled in linux case?

**Comment by MohammadrezaNasrabadi** [comment]
Finally found the problem.

The fact is windows kernel consumes all of the memory at boot time and because of this `qemu` process allocates all of the specified memory to the VM.
If we limit the maximum size of memory usage at boot time, we will prevent windows kernel from consuming all of the memory.


https://windowsreport.com/ram-limiter-for-pc
