### ISSUE TITLE
memory leak & can't access to disks during installation & boot (virtio disk)

### ISSUE THREAD

**Issue by unknown10777** [virtio-win/kvm-guest-drivers-windows#822]
**Describe the bug**
Before install the driver: Mem 1.3G of 4.0G, can't use any virtio things.
After: 4.0G of 4.0G, still can't use any virtio things.

**To Reproduce**
new vm
add sata disk
add sata installation disc
boot
install win2k22
reboot into windows & remove win disc
Install driver on Win2k22
reboot
done

**Expected behavior**
It shouldn't take any memory and all virtio device should work

**Host:**
 - Disto: kali
 - 5.16.0-kali7-amd64
 - 1:7.0+dfsg-7+b1 amd64
 - QEMU command line 
 - libvirt version
 `
gir1.2-libvirt-glib-1.0/kali-rolling,now 4.0.0-2 amd64 [已安装，自动]
libvirt-clients/kali-rolling,now 8.5.0-1 amd64 [已安装]
libvirt-daemon-config-network/kali-rolling,now 8.5.0-1 all [已安装，自动]
libvirt-daemon-config-nwfilter/kali-rolling,now 8.5.0-1 all [已安装，自动]
libvirt-daemon-driver-lxc/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-driver-qemu/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-driver-vbox/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-driver-xen/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-system-systemd/kali-rolling,now 8.5.0-1 all [已安装，自动]
libvirt-daemon-system/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-glib-1.0-0/kali-rolling,now 4.0.0-2 amd64 [已安装，自动]
libvirt-glib-1.0-data/kali-rolling,now 4.0.0-2 all [已安装，自动]
libvirt0/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
python3-libvirt/kali-rolling,now 8.4.0-0.1+b1 amd64 [已安装]
`
 - libvirt XML file
see document below

**VM:**
 - win2k22
 - I runned the installer. dunno which specific driver caused memory problem.
 - [Driver version or commit hash that was used to build the driver](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.221-1/virtio-win-0.1.221.iso)

**Additional context**

**Comment by unknown10777** [comment]
[新建文本文档.txt](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9499524/default.txt)

**Comment by unknown10777** [comment]
I apologize for my bad network. It somehow opened two duplicated issues.

**Comment by kostyanf14** [comment]
Only 2 VirtIO devices present in XML:

```
<video>
  <model type="virtio" heads="1" primary="yes">
    <acceleration accel3d="yes"/>
  </model>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
</video>
<memballoon model="virtio">
  <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
</memballoon
```

**Comment by unknown10777** [comment]
This is my bootable configuration. When switching disks or network cards to virtio, I can't connect to it.

**Comment by unknown10777** [comment]
oh and I thought my kernel cmdline may relevant with this. 
```
cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.16.0-kali7-amd64 root=UUID=fac5698c-5f67-457a-a0c4-35369e6e3623 ro quiet intel_iommu=on vfio-pci.ids=15b7:5019,8086:5a85 pci=noari splash
```

**Comment by unknown10777** [comment]
I tried reinstalling driver. Found the problem is caused by VirtIO balloon driver on PCI4 device0 function0. It immedant caused memory leak.

**Comment by xiagao** [comment]
> I tried reinstalling driver. Found the problem is caused by VirtIO balloon driver on PCI4 device0 function0. It immedant caused memory leak.

Hi, 
Could you please describe the reproduce steps more clearly?
From this issue title, this issue happened during os installation, but from the steps in comment 0, it saids "install driver on win2k22" ,is the OS installed succecssfully?
Thanks.

**Comment by xiagao** [comment]
> I tried reinstalling driver. Found the problem is caused by VirtIO balloon driver on PCI4 device0 function0. It immedant caused memory leak.

You mean after installing balloon driver, win2k22 is hang or BSOD?

**Comment by unknown10777** [comment]
> > I tried reinstalling driver. Found the problem is caused by VirtIO balloon driver on PCI4 device0 function0. It immedant caused memory leak.
> 
> You mean after installing balloon driver, win2k22 is hang or BSOD?

Yes. Its memory immedant goes to full and CPU goes to 100%. I think it's using disk space as swap to keep not to BSOD

**Comment by unknown10777** [comment]
> > I tried reinstalling driver. Found the problem is caused by VirtIO balloon driver on PCI4 device0 function0. It immedant caused memory leak.
> 
> Hi, Could you please describe the reproduce steps more clearly? From this issue title, this issue happened during os installation, but from the steps in comment 0, it saids "install driver on win2k22" ,is the OS installed succecssfully? Thanks.

The OS works perfectly before install the balloon driver.

**Comment by xiagao** [comment]
@unknown10777 Thanks for your quick update, I can have a try and paste the result here later.

**Comment by xiagao** [comment]
I test on qemu-kvm-7.0 and virtio-win-prewhql-221,after installing balloon driver, cpu/memory looks good(see the picture).Anyway I'm installing a RHEL850 guest to have a try.
![balloon-mem](https://user-images.githubusercontent.com/9928220/188823544-777e602a-53ef-42b2-b4e9-3c3d6e36f660.png)

**Comment by unknown10777** [comment]
Sorry, I don't understand why.

**Comment by xiagao** [comment]
I can't reproduce on RHEL8.5 yet.
VM: Win2k22
qemu-kvm-4.2.0-60.module+el8.5.0+14545
virtio-win-prewhql-0.1-221.iso

**Comment by unknown10777** [comment]
I retried delete full partition table then load driver in vm，it successed.
