### ISSUE TITLE
memory leak & can't access to disks during installation & boot (virtio disk)

### ISSUE THREAD

**Issue by unknown10777** [virtio-win/kvm-guest-drivers-windows#823]
**Describe the bug**
Before install the driver: Mem 1.3G of 4.0G, can't use any virtio things.
After: 4.0G of 4.0G, still can't use any virtio things.

**To Reproduce**
new vm
add sata disk
add sata installation disc
boot
install win2k22
reboot into windows & remove win disc
Install driver on Win2k22
reboot
done

**Expected behavior**
It shouldn't take any memory and all virtio device should work

**Host:**
 - Disto: kali
 - 5.16.0-kali7-amd64
 - 1:7.0+dfsg-7+b1 amd64
 - QEMU command line 
 - libvirt version
 `
gir1.2-libvirt-glib-1.0/kali-rolling,now 4.0.0-2 amd64 [已安装，自动]
libvirt-clients/kali-rolling,now 8.5.0-1 amd64 [已安装]
libvirt-daemon-config-network/kali-rolling,now 8.5.0-1 all [已安装，自动]
libvirt-daemon-config-nwfilter/kali-rolling,now 8.5.0-1 all [已安装，自动]
libvirt-daemon-driver-lxc/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-driver-qemu/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-driver-vbox/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-driver-xen/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon-system-systemd/kali-rolling,now 8.5.0-1 all [已安装，自动]
libvirt-daemon-system/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-daemon/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
libvirt-glib-1.0-0/kali-rolling,now 4.0.0-2 amd64 [已安装，自动]
libvirt-glib-1.0-data/kali-rolling,now 4.0.0-2 all [已安装，自动]
libvirt0/kali-rolling,now 8.5.0-1 amd64 [已安装，自动]
python3-libvirt/kali-rolling,now 8.4.0-0.1+b1 amd64 [已安装]
`
 - libvirt XML file
 `<domain type="kvm">
  <name>win2k22</name>
  <uuid>62b1ee3c-1b08-4a37-947a-63a5f67820e6</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/2k22"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">4194304</memory>
  <currentMemory unit="KiB">131072</currentMemory>
  <vcpu placement="static">2</vcpu>
  <os firmware="efi">
    <type arch="x86_64" machine="pc-q35-7.0">hvm</type>
    <bootmenu enable="no"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv mode="custom">
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
    </hyperv>
    <vmport state="off"/>
  </features>
  <cpu mode="host-passthrough" check="none" migratable="on"/>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="block" device="disk">
      <driver name="qemu" type="raw" cache="none" io="native" discard="unmap"/>
      <source dev="/dev/nvme0n1"/>
      <target dev="sdb" bus="sata"/>
      <boot order="1"/>
      <address type="drive" controller="0" bus="0" target="0" unit="1"/>
    </disk>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
    </controller>
    <controller type="pci" index="0" model="pcie-root"/>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="1" port="0x10"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="2" port="0x11"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1"/>
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="3" port="0x12"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2"/>
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="4" port="0x13"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3"/>
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="5" port="0x14"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4"/>
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="6" port="0x15"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5"/>
    </controller>
    <controller type="pci" index="7" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="7" port="0x16"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x6"/>
    </controller>
    <controller type="pci" index="8" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="8" port="0x17"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x7"/>
    </controller>
    <controller type="pci" index="9" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="9" port="0x18"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="10" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="10" port="0x19"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x1"/>
    </controller>
    <controller type="pci" index="11" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="11" port="0x1a"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x2"/>
    </controller>
    <controller type="pci" index="12" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="12" port="0x1b"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x3"/>
    </controller>
    <controller type="pci" index="13" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="13" port="0x1c"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x4"/>
    </controller>
    <controller type="pci" index="14" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="14" port="0x1d"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x5"/>
    </controller>
    <controller type="pci" index="15" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="15" port="0x1e"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x6"/>
    </controller>
    <controller type="pci" index="16" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="16" port="0x1f"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x7"/>
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2"/>
    </controller>
    <interface type="direct">
      <mac address="52:54:00:da:d5:0e"/>
      <source dev="eth0" mode="bridge"/>
      <model type="e1000e"/>
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
    </interface>
    <interface type="network">
      <mac address="52:54:00:44:fd:7c"/>
      <source network="network-1"/>
      <model type="e1000e"/>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </interface>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <graphics type="spice">
      <listen type="none"/>
      <image compression="off"/>
      <gl enable="yes" rendernode="/dev/dri/by-path/pci-0000:00:02.0-render"/>
    </graphics>
    <audio id="1" type="none"/>
    <video>
      <model type="virtio" heads="1" primary="yes">
        <acceleration accel3d="yes"/>
      </model>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
    </video>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </memballoon>
  </devices>
</domain>
`

**VM:**
 - win2k22
 - I runned the installer. dunno which specific driver caused memory problem.
 - [Driver version or commit hash that was used to build the driver](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.221-1/virtio-win-0.1.221.iso)

**Additional context**

**Comment by kostyanf14** [comment]
Duplicate: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/822

**Comment by unknown10777** [comment]
[新建文本文档.txt](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9499508/default.txt)
