### ISSUE TITLE
Video Virtio refuses to conform to desktop resolution.(1680x1050)

### ISSUE THREAD

**Issue by DaKingof** [virtio-win/kvm-guest-drivers-windows#828]
This issue arises sometimes where my resolution would not be adjusted properly but would fix after a restart of my Windows 11 guest. This time, however, it does not seem to be the case. No matter what I do, the resolution will not set to 1680x1050(16:10). Only 16:9 aspect ratios are shown. I've also changed the resolution in the bios setup and it's not being respected by the driver.

![image](https://user-images.githubusercontent.com/31186364/191953964-5b702847-24fc-4656-8c25-f803c6896c4d.png)

 -NixOS host
 -Linux Zen
 -QEMU 7.1.0
 - QEMU command line (Not sure what this is)
 - libvirt 8.7.0
 - libvirt XML file
```<?xml version="1.0" encoding="utf-8"?>
<zone target="ACCEPT">
  <short>libvirt</short>

  <description>
    The default policy of "ACCEPT" allows all packets to/from
    interfaces in the zone to be forwarded, while the (*low priority*)
    reject rule blocks any traffic destined for the host, except those
    services explicitly listed (that list can be modified as required
    by the local admin). This zone is intended to be used only by
    libvirt virtual networks - libvirt will add the bridge devices for
    all new virtual networks to this zone by default.
  </description>

<rule priority='32767'>
  <reject/>
</rule>
<protocol value='icmp'/>
<protocol value='ipv6-icmp'/>
<service name='dhcp'/>
<service name='dhcpv6'/>
<service name='dns'/>
<service name='ssh'/>
<service name='tftp'/>
</zone>
```

 - Windows 11 Guest
 - viogpudo(GPU DOD)
 - virtio-win-0.1.221.iso

**Comment by vrozenfe** [comment]
@DaKingof 
Can you try adding the following xres and yres parameters 
"-device virtio-vga,xres=1680,yres=1050"
Please see https://github.com/virtio-win/kvm-guest-drivers-windows/issues/560 for more details 
Vadim.

**Comment by DaKingof** [comment]
Ahh perfect. Set it up in Virt-Manger just fine. Thank you Vadim! Much appreciated.
