### ISSUE TITLE
windows netkvm: the minimum(32) of RxCapacity in 'defaultConfiguration' does not  equal the minimum(16) in inf.

### ISSUE THREAD

**Issue by zjmletang** [virtio-win/kvm-guest-drivers-windows#830]
**Describe the bug**
        the minimum(32) of RxCapacity in 'defaultConfiguration' does not  equal the minimum(16) in inf. 
        This will cause the value(16) set by Device manager does not take effect.

**Expected behavior**
the value in the code should equal the value in the inf
![bugreport](https://user-images.githubusercontent.com/114464945/192443999-1f25a226-ea87-4042-8a22-2d3e8dba9944.png)

**Screenshots**

**Host:**

**VM:**
 - netkvm

**Additional context**

**Comment by YanVugenfirer** [comment]
Fixed by PR#881
