### ISSUE TITLE
The VirtioFS service does not seem to be installed.

### ISSUE THREAD

**Issue by daiaji** [virtio-win/kvm-guest-drivers-windows#837]
The driver version is 100.91.104.22100.
Windows 10 LTSC 19044.1949
It seems that the VirtioFS service will not be installed either through the device manager or by right clicking on the inf file. However, I see the item of installing the service in the inf file. Why does it not work? Do I need to use command line parameters?

**Comment by viktor-prutyanov** [comment]
Hi @daiaji 
You should either install the service through command line (`sc create VirtioFsSvc binPath="<path to the binary>\virtiofs.exe" start=auto depend=VirtioFsDrv`) or through virtio-win installer

**Comment by daiaji** [comment]
It seems that there are related statements in the viofs.inf file, but I don't know how to call them.
```
[VirtioFs_Service_Install]
DisplayName    = %VirtioFs.Service%
ServiceType    = 1               ; SERVICE_KERNEL_DRIVER
StartType      = 3               ; SERVICE_DEMAND_START
ErrorControl   = 1               ; SERVICE_ERROR_NORMAL
ServiceBinary  = %12%\viofs.sys
LoadOrderGroup = Extended Base

; -------------------------------------
; WDF & Device CoInstaller Installation
; -------------------------------------
```
> virtio-win installer

I don't need to install all Virtio drivers.
