### ISSUE TITLE
Improper user/permissions after VirtIO-FS service restart

### ISSUE THREAD

**Issue by johnsanc314** [virtio-win/kvm-guest-drivers-windows#839]
UnRAID 6.11.1 added better support for virtiofs. I tried setting this up with my existing Windows 10 VM and was able to pass through a single share and mount it to a drive letter. I am using a local account with administrator access. Everything seems to work properly and I can read and write files without issue... unless I restart the VirtIO-FS service.

I stopped and started the service to change the mount point drive letter and I noticed when it starts back up I can create directories, but I cannot write any files to those directories (E.g. copying a folder of files to the mount). I then noticed that the directories and files it created are associated with a "broken" user called S-1-5-0. 

Is this a bug or is there a way around this? Everything seems to work properly as long as I let the service start automatically and do not touch it.

([UnRAID forum post for reference](https://forums.unraid.net/topic/129326-unraid-6111-virtiofs-with-windows-10-vm/))

**Comment by viktor-prutyanov** [comment]
Please indicate virtio-win version

**Comment by johnsanc314** [comment]
Its the one from the 0.1.221 driver ISO.
I'm using the Windows 10 version which I believe is: 100.91.104.22100

**Comment by pspfreak** [comment]
I'm re-opening because I am having a similar issue, I'm on 0.1.229 and i'm getting just "everyone" permission, and every time I try to set a permission, it either give me an "access is denied" or completely ignores me. I've also updated my winfsp.

**Comment by viktor-prutyanov** [comment]
Hi @pspfreak 

Could you please describe in detail what are you trying to do?
