### ISSUE TITLE
virt-serial call bsod 9f when os shutdown

### ISSUE THREAD

**Issue by zlxing** [virtio-win/kvm-guest-drivers-windows#84]
win7 32bit 7601.19135.x86fre OS bsod when shutdown, dmp file see attachment.

By debugging the dmp file, i find irp irp_mj_shutdown block in virt-serial too long time cause the bsod.

[102416-22906-01.zip](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/550067/102416-22906-01.zip)

**Comment by ladipro** [comment]
Please try the latest vioserial driver if you can. This is very likely
https://bugzilla.redhat.com/show_bug.cgi?id=1296099

where a request can get stuck in the driver due to a race condition. Out of curiosity, what is the serial port used for in this VM? Is it one of the standard guest agents or something else? Thanks!

**Comment by zlxing** [comment]
Thanks, I will try the latest version to check the problem.

**Comment by zlxing** [comment]
Thanks for reply.

The guest agent im my env is standard version spice-guest-tools-0.100.

In my env, the problem may be occured in any OS shutdown, but it's race condition. I don't have any certain  steps to reproduce Now.

I will try the latest version to see if the problem occuring or not. Thanks!



zlxing@os-easy.com
 
From: Ladi Prosek
Date: 2016-10-25 20:05
To: YanVugenfirer/kvm-guest-drivers-windows
CC: zlxing; Author
Subject: Re: [YanVugenfirer/kvm-guest-drivers-windows] virt-serial call bsod 9f when os shutdown (#84)
Please try the latest vioserial driver if you can. This is very likely
https://bugzilla.redhat.com/show_bug.cgi?id=1296099
where a request can get stuck in the driver due to a race condition. Out of curiosity, what is the serial port used for in this VM? Is it one of the standard guest agents or something else? Thanks!

**Comment by zlxing** [comment]
install spice-guest-tools-0.100 only update virtser to 0.126 version.

With windows task scheduler  auto reboot after enter OS 3 mins, 12 VMS continue running, 3 VMS BOSD 0x50 in a signle reboot.

what can i test next step?

**Comment by ladipro** [comment]
Is vioser.sys blamed for 0x50? Can you please share a dump? Kernel or full memory dump if possible. Thank you!

**Comment by zlxing** [comment]
No driver is blamed on BSOD screen.

I have configured to gen dump file, but  no dump file has gened.

**Comment by ladipro** [comment]
If you're not getting crash dumps, try live remote kernel debugging.

http://www.slideshare.net/YanVugenfirer/windows-guestdebugging-kvmforum2012
(start at slide 70)

Or if it's possible/easy for you to make one of the crashing VMs available for us to look at, that would work too.

**Comment by zlxing** [comment]
Thanks.

Of course, i have try live remote kernel debugging with two VMS in the same host, but the BSOD 0x50 problem don't reproduce again.

So now i don't known whether the problem is occured by virtser or not.

Is any other reason may cause the BSOD 0x50 problem?

**Comment by ladipro** [comment]
I can't find any relevant reports of BSOD 0x50 in the past, unfortunately. Do you see the BSOD in the System event log? Something like

`The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000050 ...
`

**Comment by zlxing** [comment]
Thanks, 
I can't find any log in the system event log.

**Comment by ladipro** [comment]
In that case, can you please take a screenshot of the BSOD? It sounds like whatever is displayed there is all we have. Thanks!

**Comment by zlxing** [comment]
Of course, BSOD screenshot see attachment.
![bsod_50](https://cloud.githubusercontent.com/assets/11532626/19884981/2e79398a-a057-11e6-948c-1cd191ebb8b8.jpg)

**Comment by ladipro** [comment]
Would it be possible to attach windbg to this VM and run the 'lm' command after it has fully booted up? That should tell us where the code at address 0x83CB790C comes from.

**Comment by zlxing** [comment]
Today, i have attached to the bsod VM, many useful info see attachment.
![1](https://cloud.githubusercontent.com/assets/11532626/19912979/7c9efc76-a0d9-11e6-94ce-d401209c55ff.png)
![2](https://cloud.githubusercontent.com/assets/11532626/19912981/7ca09ca2-a0d9-11e6-933d-456d99c99f64.png)
![3](https://cloud.githubusercontent.com/assets/11532626/19912978/7c9c8f2c-a0d9-11e6-880c-ca4c84a14a33.png)
![4](https://cloud.githubusercontent.com/assets/11532626/19912980/7c9f5bda-a0d9-11e6-9865-7ae71714b375.png)
![5](https://cloud.githubusercontent.com/assets/11532626/19912982/7ca2f6b4-a0d9-11e6-8592-5ffe166123ec.png)

**Comment by ladipro** [comment]
Nice! Can you please share the dump?

kd> .dump /f memory.dmp

Not sure if you saw this one:
https://support.microsoft.com/en-us/kb/2719594

It's a shot in the dark as there's not much information about the crash there. They mention srvnet.sys which doesn't seem to be loaded in your case.

**Comment by zlxing** [comment]
minidump see attachment, full memory dump is too big.
[bsod50.zip](https://github.com/YanVugenfirer/kvm-guest-drivers-windows/files/566079/bsod50.zip)

**Comment by rob-scheepens** [comment]
The bsod50 dump shows a very outdated Windows installation, mostly on SP1 level. Please update your machine, start with https://support.microsoft.com/en-us/kb/2775511, then run a full Windows update. Also, why share a 0x50 dump in a thread for a 0x9F, which is a timeout rather than a "real" crash like the 0x50?

**Comment by zlxing** [comment]
Yes, BSOD 9F may be caused by virser timeout, but BSOD 50 should be not.

**Comment by rob-scheepens** [comment]
@zlxing : please update the machine, then get a kernel dump of the 0x9F.

**Comment by zlxing** [comment]
@rob-scheepens In my env, i have not found certain  steps to reproduce BSOD 9F.

**Comment by YanVugenfirer** [comment]
Closing
