### ISSUE TITLE
Documentation issue - no program called virtiogfs.exe

### ISSUE THREAD

**Issue by MathieuCGit** [virtio-win/kvm-guest-drivers-windows#840]
Hello guys,

I'm trying to follow this guide : https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system

And notice a minor issue, but I may have misunderstood something I'd rather ask here. So the line 

``"C:\Program Files (x86)\WinFsp\bin\fsreg.bat" virtiofs "<path to the binary>\virtiogfs.exe" "-t %1 -m %2"``

should be 

``"C:\Program Files (x86)\WinFsp\bin\fsreg.bat" virtiofs "<path to the binary>\virtiofs.exe" "-t %1 -m %2"`` ?

Or is there a program called virtiogfs.exe ?? In this case, please let me know where I coud find it, because actually I can't :-/

**Comment by viktor-prutyanov** [comment]
@MathieuCGit thank you! I've fixed the wiki: virtiogfs.exe is a typo, right name is virtiofs.exe.
