### ISSUE TITLE
Driver build does not work on master branch.

### ISSUE THREAD

**Issue by asbalderson** [virtio-win/kvm-guest-drivers-windows#845]
**Describe the bug**
I'm trying to build the drivers from scratch using the current master branch and I am unable to do so. My current main goal is to build the Win10 drivers, but i will need to build for win 8 and win 8.1 in the future.

Logs are attached (2, 3) to the issue for both win8 and win10, however the first pass appears to be 2 major issues with win10 building:
* Signing fails because SignTool cant find a certificate which matches all given criteria
* VioSock can't find viosocklib.dll or viosocklib.pdb but files exist.

**To Reproduce**
I'm running on a windows server 2019 KVM, freshly installed. No windows updates.
Following the build instructions to build the drivers using ewdk 1903 and 2004 from the wiki (1) I setup the EWDK 2004 environment with the dvl files from EWDK 1903, and installed the required components (WinFsp, CPDK WIndows 10, .NET framework 4.8, VS 2013 redistribution x86)
* downloaded the .zip from the master.branch
* extracted the contents to the desktop
* ran `LaunchBuildEnv.bat` from the edwk2004 directory
* in the environment `set VIRIO_WIN_NO_ARM=True`
* change dir to the extracted contents
* `.\buildAll.bat AMD64`
* save `buildfre_win8_amd64.log
* edit the `.\BuilAll.bat` file to remove Win8 and Win8.1 such as `call tool\build.bat virtio-win.sln "Win10" %*`
* `.\BuildAll.bat AMD64`
* save `buildfree_win10_amd64.log`

1) https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers-using-EWDK-1903-2004
2) [buildfre_win8_amd64.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9814834/buildfre_win8_amd64.log)
3) [buildfre_win10_amd64.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9814835/buildfre_win10_amd64.log)

**Expected behavior**
Drivers build resulting in proper test signed (or unsigned) VirtIO drivers and .sdv files in the `<driver>\install\Win<version>\amd64\` directory in a sate where they can be signed and tested for WHQL certification.

**Screenshots**
N/A

**Host:**
 - Disto: Ubuntu 22.04
 - Kernel version: 5.15.0-50.56 
 - QEMU version: 1:5.2+dfsg-2ubuntu6.2
 - QEMU command line: N/A (can provide if needed)
 - libvirt version: 8.0.0-1ubuntu7.1
 - libvirt XML file: N/A (can provide if needed)

**VM:**
 - Windows version: Windows Server 2019 Datacenter 1809, os build 17763.107
 - Which driver has a problem: None
 - Driver version or commit hash that was used to build the driver: Drivers on system are from the mm220 commit, drivers being built are from the master branch.

**Comment by YanVugenfirer** [comment]
Hi @asbalderson ,

Several comments:

1. Unfortunately the link to the Wiki is missing from your post. Please double check that you are using ewdk11. This is the link for the setup: https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers-using-Windows-11--EWDK . While older EWDKs probably work, we don't intend to maintain such extensive test\support matrix
2. No need to run `LaunchBuildEnv.bat`. Build scripts should pick up default edwk installation dir. If you are using alternative directory, use EWDK11_DIR environment to set it
3. Run `build_AllNoSdv.bat` . It will save you a lot of time, as SDV tests might take several hours.

Best regards,
Yan.

**Comment by asbalderson** [comment]
Hi @YanVugenfirer 

Thanks for the follow up here.

1) I made the switch over to ewdk11, the link in the wiki to the iso in the wiki didnt work, and i grabbed the one at https://go.microsoft.com/fwlink/?linkid=2195661. I also totally understand not maintaining the extensive test matrix, its probably worth updating the README to point at the right wiki page for "building the drivers"
2)  I was having trouble getting the `BuildAll.bat` to run if i ran it outside the the `LaunchBuildEnv.bat` environment, but it was probably because i wasnt setting the build environment correctly.
3) I dont mind the SDV tests taking several hours, i'm happy to kick off the build and coming back after a couple days to see the result. Does the NoSDV build still return the required .dvl files for WHQL certification?

When i run with the given steps you gave above, the build is still failing, maybe because I'm running on Windows Server 2019. I get a lot of `Win32 is not a valid architecture for kernel mode drivers or UMDF drivers` as well as `build tools for Visual Studio 2019 (platform toolset = v142) cannot be found. To build using the v142 build tools, please install Visual Studio 2019 build tools. Alternatively, you may upgrade to the current Visual Studio tolls by selecting the Project menu or right-click the solution, and then selecting "retarget solution`

Logs are below.
[buildfre_win10_x86.log](https://github.com/virtio-win/kvm-guest-drivers-windows/files/9822899/buildfre_win10_x86.log)

Thanks,
Alex

**Comment by YanVugenfirer** [comment]
Hi @asbalderson,

How are you executing the build? Buildall.bat?

In any case, if you want DVL logs - you need to run regular build all.
Also, if you want to certify the drivers - please change PNP ID in the INF  (there is a way to set vendor string in the solution).

From our readme.md
> If you want to produce Microsoft-signed binaries (fully supported, like the ones that ship in the Red Hat Enterprise Linux RPM), you'll need to submit the drivers to Microsoft along with a set of test results (so called WHQL process). If you decide to WHQL the drivers, make sure to base them on commit eb2996de or newer, since the GPL license used prior to this commit is not compatible with WHQL. Additionally, we ask that you make a change to the Hardware IDs so that your drivers will not match devices exposed by the upstream versions of KVM/QEMU. This is especially important if you plan to distribute the drivers with Windows Update, see the [Microsoft publishing restrictions](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/publishing-restrictions) for more details.

**Comment by asbalderson** [comment]
Hi @YanVugenfirer 

From the output above, i was running `build_AllNoSdv.bat Win10` as you recommended, but it seems i was right in thinking i needed to run `Buildall.bat`

To be extra clear:
i followed the steps to setup the build environment for ewdk11 that you posted. and I am on windows server datacenter 2019 UI (i can switch to 2022 if i need to).
I copied the build environment to `c:\ewdk11`
from a bash terminal i ran
`cd c:\users\<user>\Desktop\kvm-guest-drivers-windows-master`
`set EWDK11_DIR=c:\ewdk11`
`set VIRTIO_WIN_NO_ARM=True
`.\build_AllNoSdv.bat Win10`

and then got the output posted above.

I am aware that i need to make the changes for the Vendor ID and update the hardware ID's. I have staged commits to do those things, but I thought it would be more clear and easier to reproduce build failures if i based them on the master branch without an changes.

Thanks,
Alex

**Comment by kostyanf14** [comment]
Hi @asbalderson,

You use new EWDK for Windows 11 22H2 build 22621. Currently, we don't support it. Please use [Windows 11 21H2 EWDK build 22000](https://learn.microsoft.com/en-us/legal/windows/hardware/enterprise-wdk-license-2019-New)

**Comment by asbalderson** [comment]
My KVM host has gotten into a bad state before i could test with this , I'll re open this issue if i keep having problems once i have a chance to test.

**Comment by asbalderson** [comment]
@AlekseyKostyushko @YanVugenfirer thank you both for your help! I got the drivers building.

I also found that i couldn't build for just x64, i had to build the x86 version first.

**Comment by kostyanf14** [comment]
>I also found that i couldn't build for just x64, i had to build the x86 version first.

@asbalderson, you are right. Looks like a bug.

**Comment by YanVugenfirer** [comment]
> @AlekseyKostyushko @YanVugenfirer thank you both for your help! I got the drivers building.
> 
> I also found that i couldn't build for just x64, i had to build the x86 version first.

No problem!
We are also working to enable build with latest eWDK. But it doesn't support Windows 8, so probably when\if we move forward "legacy" eWDK will be needed to build Windows 8.

Just wondering, if Windows 8 and Windows Server 2012 are still valid OS versions for you?

Best regards,
Yan.

**Comment by asbalderson** [comment]
@YanVugenfirer I dont think its seen very often, it goes EOL in less than a year id imagine most people are trying to migrate off.
