### ISSUE TITLE
Virtio network card 16 queues only half send packets

### ISSUE THREAD

**Issue by Lxiaoyouling** [virtio-win/kvm-guest-drivers-windows#854]
**Describe the bug**
My virtual machine is windows 2019 system(Red Hat VirtIO Ethernet Adapter version is 18500), configured with 16 queues to send network packets. Through the tool of dpdk, I see only 8 queues can send packets, and the remaining 8 queues do not send packets.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a windows 2019 VM with a NIC with 16 queues
2. Inside the VM, use "iperf-u -c 10.102.0.209-P 50 -t 10" send packes
3. Observe the packet sending status of the queue

**Expected behavior**
All 16 queues send packets, but only 8 queues send packets

**Screenshots**
![image](https://user-images.githubusercontent.com/10220220/199198929-d41d42e0-fd29-4b70-87a3-e8dad7cdd042.png)

**Host:**
 - Kernel version：4.18
 - QEMU version：2.12.0
 - QEMU command line 
 - libvirt version：4.5.0
 - libvirt XML file：
   <interface type='vhostuser'>
      <mac address='52:00:cf:d8:16:46'/>
      <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/>
      <model type='virtio'/>
      <driver name='vhost' queues='16'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>

**Comment by Lxiaoyouling** [comment]
libvirt xml:
<interface type='vhostuser'>
      <mac address='52:00:cf:d8:16:46'/>
      <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/>
      <model type='virtio'/>
      <driver name='vhost' queues='16'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>

**Comment by Lxiaoyouling** [comment]
libvirt xml:
`<interface type='vhostuser'>
      <mac address='52:00:cf:d8:16:46'/>
      <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/>
      <model type='virtio'/>
      <driver name='vhost' queues='16'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>`

**Comment by YanVugenfirer** [comment]
Hello,

How many vCPUs the VM has?

We do not use more queues than available vCPUs. 

Best regards,
Yan.

**Comment by Lxiaoyouling** [comment]
Hi,
My virtual machine has 16 Vcpus.

I wonder if windows has a limit of up to 8 send queues?
Thanks

**Comment by YanVugenfirer** [comment]
Hi,

On Server 2019 it should not be the limit.
Can you please try to gather logs?
https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/NetKVM/Documentation/Tracing.md

The neede logs are of the driver start up. Please go to device manager and disable/enable the driver.

thanks!

**Comment by 0x370** [comment]
try 32 or 64 vcpu.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 1, 2022 20:35 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [virtio-win/kvm-guest-drivers-windows] Virtio network card 16queues only half send packets (Issue #854)




 
Hi,
 My virtual machine has 16 Vcpus.
 
I wonder if windows has a limit of up to 8 send queues?
 Thanks

**Comment by YanVugenfirer** [comment]
> libvirt xml:
> `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`

BTW: Can you test with regular Linux bridge?

**Comment by Heathcliff4689** [comment]
> > libvirt xml:
> > `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`
> 
> BTW: Can you test with regular Linux bridge?

Hi. It's fine in the same environment that a Centos guest with 4 vcpus that contains 2 rx queues & 2 tx queues.

**Comment by Heathcliff4689** [comment]
> > libvirt xml:
> > `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`
> 
> BTW: Can you test with regular Linux bridge?

Hi. It's fine in the same environment that a Centos guest with 4 vcpus that contains 2 rx queues & 2 tx queues.
![image](https://user-images.githubusercontent.com/56949076/200273263-6f73b702-e419-4321-9c0d-f648503f6f74.png)

**Comment by Heathcliff4689** [comment]
> > > libvirt xml:
> > > `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`
> > 
> > 
> > BTW: Can you test with regular Linux bridge?
> 
> Hi. It's fine in the same environment that a Centos guest with 4 vcpus that contains 2 rx queues & 2 tx queues. ![image](https://user-images.githubusercontent.com/56949076/200273263-6f73b702-e419-4321-9c0d-f648503f6f74.png)

while in window server 2019, only half tx queues send packets.
![image](https://user-images.githubusercontent.com/56949076/200274646-d53b658c-ee40-4b8a-83c0-db4408758ce9.png)

**Comment by Heathcliff4689** [comment]
> > > libvirt xml:
> > > `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`
> > 
> > 
> > BTW: Can you test with regular Linux bridge?
> 
> Hi. It's fine in the same environment that a Centos guest with 4 vcpus that contains 2 rx queues & 2 tx queues. ![image](https://user-images.githubusercontent.com/56949076/200273263-6f73b702-e419-4321-9c0d-f648503f6f74.png)

while in window server 2019, only half tx queues send packets.
![image](https://user-images.githubusercontent.com/56949076/200274869-7c88a4d2-c813-4020-99ea-c728d6a02a00.png)

**Comment by Heathcliff4689** [comment]
> > > libvirt xml:
> > > `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`
> > 
> > 
> > BTW: Can you test with regular Linux bridge?
> 
> Hi. It's fine in the same environment that a Centos guest with 4 vcpus that contains 2 rx queues & 2 tx queues. ![image](https://user-images.githubusercontent.com/56949076/200273263-6f73b702-e419-4321-9c0d-f648503f6f74.png)

while in window server 2019 (8 vcpus with 4 tx queues & 4 rx queues), only half tx queues send packets.
![image](https://user-images.githubusercontent.com/56949076/200275499-924392ac-5d47-4fc6-aaf2-ff4ae17bbd5f.png)

**Comment by Heathcliff4689** [comment]
> > > libvirt xml:
> > > `<interface type='vhostuser'> <mac address='52:00:cf:d8:16:46'/> <source type='unix' path='/vm_data/sock/test_sn1.sock' mode='server'/> <model type='virtio'/> <driver name='vhost' queues='16'/> <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/> </interface>`
> > 
> > 
> > BTW: Can you test with regular Linux bridge?
> 
> Hi. It's fine in the same environment that a Centos guest with 4 vcpus that contains 2 rx queues & 2 tx queues. ![image](https://user-images.githubusercontent.com/56949076/200273263-6f73b702-e419-4321-9c0d-f648503f6f74.png)

while in window server 2019 (8 vcpus with 4 tx queues & 4 rx queues), only half tx queues send packets.
![屏幕截图 2022-11-07 173032](https://user-images.githubusercontent.com/56949076/200275736-a57b1ab4-30a5-4df5-8577-29ed7600333c.png)

**Comment by YanVugenfirer** [comment]
Can you please also add QEMU command line (I am wondering how XML configuration is translated to actual command  line)?
And also please describe how to setup the host side (are you using OvS., or some other DPDK app)?

Thanks a lot.

**Comment by YanVugenfirer** [comment]
Hi @Heathcliff4689 and @Lxiaoyouling ,

Can you please try to gather logs?
https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/NetKVM/Documentation/Tracing.md

The neede logs are of the driver start up. Please go to device manager and disable/enable the driver.

Thanks,
Yan.

**Comment by Lxiaoyouling** [comment]
Hello Yan,
Sorry, I was busy with other work recently and didn't reply in time.

I tested it with 4 vcpus and 4 queues. I found that when configure sockets='1' cores='4' threads='1', the tx queue was normal. However, if configure sockets='1' cores='2' threads='2', there will be only half of the tx queues send packets.

1. Here is the qemu command line configured with sockets='1' cores='4' threads='1'，

`/vm_data/lizhaoxin1/test_image/qemu-6.0.0-rc0/build/qemu-system-x86_64 -name guest=lzx_windows_1,process=qemu:lzx_windows_1,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-19-lzx_windows_1/master-key.aes -machine pc-i440fx-5.0,accel=kvm,usb=off,dump-guest-core=off -cpu Haswell,rtm=on,hle=on,hv_time,hv_relaxed,hv_spinlocks=0x1fff -m 4096 -mem-prealloc -mem-path /dev/hugepages/libvirt/qemu/19-lzx_windows_1 -smp 4,sockets=1,cores=4,threads=1 -uuid fec40974-e391-45e4-a7ce-c50559d466e3 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=28,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x5 -drive file=/vm_data/lizhaoxin1/test_image/lzx_win2019.img,format=qcow2,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1,write-cache=on -chardev socket,id=charnet0,path=/vm_data/lizhaoxin1/test_user_20220225104514/sock/test_user_sn2.sock,server -netdev vhost-user,chardev=charnet0,queues=4,id=hostnet0 -device virtio-net-pci,mq=on,vectors=10,netdev=hostnet0,id=net0,mac=52:54:b2:b8:ab:9d,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,fd=30,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.test_user_sn2_agent.100 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 0.0.0.0:0 -k en-us -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -msg timestamp=on`

![image](https://user-images.githubusercontent.com/10220220/200458936-7e4bc084-ea43-40b4-9cfa-d02b2a926d32.png)

I use traceview gather some logs:
![HGR973TpG2](https://user-images.githubusercontent.com/10220220/200459063-32b805cb-8e5a-4060-82f0-ae97daf550ad.jpg)

2.  Here is the qemu command line configured with sockets='1' cores='2' threads='2'，

`/vm_data/lizhaoxin1/test_image/qemu-6.0.0-rc0/build/qemu-system-x86_64 -name guest=lzx_windows_1,process=qemu:lzx_windows_1,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-20-lzx_windows_1/master-key.aes -machine pc-i440fx-5.0,accel=kvm,usb=off,dump-guest-core=off -cpu Haswell,rtm=on,hle=on,hv_time,hv_relaxed,hv_spinlocks=0x1fff -m 4096 -mem-prealloc -mem-path /dev/hugepages/libvirt/qemu/20-lzx_windows_1 -smp 4,sockets=1,cores=2,threads=2 -uuid fec40974-e391-45e4-a7ce-c50559d466e3 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=28,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=localtime,driftfix=slew -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x5 -drive file=/vm_data/lizhaoxin1/test_image/lzx_win2019.img,format=qcow2,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1,write-cache=on -chardev socket,id=charnet0,path=/vm_data/lizhaoxin1/test_user_20220225104514/sock/test_user_sn2.sock,server -netdev vhost-user,chardev=charnet0,queues=4,id=hostnet0 -device virtio-net-pci,mq=on,vectors=10,netdev=hostnet0,id=net0,mac=52:54:b2:b8:ab:9d,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,fd=30,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.test_user_sn2_agent.100 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 0.0.0.0:0 -k en-us -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -msg timestamp=on`

![image](https://user-images.githubusercontent.com/10220220/200459546-178ce18d-dac5-46a1-8ab0-f5ef3b7bb4f0.png)

I use traceview gather some logs and there is a different point.
![GR0mLcXuOu](https://user-images.githubusercontent.com/10220220/200459643-82a4fd51-93fc-4e94-99ad-a61189794099.jpg)

but 4 rx queues are worker normally.

Do you know this may be what causes?

Best regards,
Lxiaoyouling

**Comment by Lxiaoyouling** [comment]
![59fjAiyLt8](https://user-images.githubusercontent.com/10220220/200465789-880dd45a-ccdf-4ba8-a757-a0f3f144a8e3.jpg)

![bbIFDoxcLw](https://user-images.githubusercontent.com/10220220/200465799-02e670f0-40f5-4816-a457-7297fdff9394.jpg)

**Comment by YanVugenfirer** [comment]
@Lxiaoyouling Thank you very much for the investigation and the comments!

So from the driver perspective this is "normal" - we are using the amount queues as the amount of vCPUs OS is using.
Now we need to understand what's wrong with Windows detection of hyper threading. 

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
@Lxiaoyouling Sorry, my mistake with the previous comment. 
Can you please post how many CPUs are detected by Windows? You see it for example in task manager (taskmgr.exe) in performance tab.

**Comment by YanVugenfirer** [comment]
@Lxiaoyouling @Heathcliff4689 

So, it is actually in MS documentation: https://learn.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling

"Note:
Because hyper-threaded CPUs on the same core processor share the same execution engine, the effect is not the same as having multiple core processors. For this reason, RSS does not use hyper-threaded processors."

That's why you see the difference in the mapping - the mapping is passed to driver by the OS.

**Comment by YanVugenfirer** [comment]
@Lxiaoyouling @Heathcliff4689 Can you share please how SMP is configured in libvirt XML file?

**Comment by Lxiaoyouling** [comment]
Thisi is my xml，virsh dumpxml lzx_windows_1
```
<domain type='kvm' id='26'>
  <name>lzx_windows_1</name>
  <uuid>fec40974-e391-45e4-a7ce-c50559d466e3</uuid>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
  <vcpu placement='static'>4</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-5.0'>hvm</type>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='off'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
  </features>
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Haswell</model>
    <vendor>Intel</vendor>
    <topology sockets='1' cores='2' threads='2'/>
    <feature policy='require' name='vme'/>
    <feature policy='require' name='f16c'/>
    <feature policy='require' name='rdrand'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='arat'/>
    <feature policy='require' name='xsaveopt'/>
    <feature policy='require' name='abm'/>
  </cpu>
  <clock offset='timezone' timezone='Asia/Shanghai'>
    <timer name='hypervclock' present='yes'/>
    <timer name='rtc' tickpolicy='catchup'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/vm_data/lizhaoxin1/test_image/qemu-6.0.0-rc0/build/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/vm_data/lizhaoxin1/test_image/lzx_win2019.img'/>
      <backingStore type='file' index='1'>
        <format type='raw'/>
        <source file='/vm_data/base/win_2019_dc_zh_64bit.img.base.sparsify'/>
        <backingStore/>
      </backingStore>
      <target dev='vda' bus='virtio'/>
      <boot order='1'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </disk>
    <controller type='virtio-serial' index='0'>
      <alias name='virtio-serial0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </controller>
    <controller type='usb' index='0' model='piix3-uhci'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <interface type='vhostuser'>
      <mac address='52:54:b2:b8:ab:9d'/>
      <source type='unix' path='/vm_data/lizhaoxin1/test_user_20220225104514/sock/test_user_sn2.sock' mode='server'/>
      <model type='virtio'/>
      <driver name='vhost' queues='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <source path='/dev/pts/1'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
    <console type='pty' tty='/dev/pts/1'>
      <source path='/dev/pts/1'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <channel type='unix'>
      <source mode='bind' path='/var/lib/libvirt/qemu/f5f059fc-95e4-11ec-a46e-ec0d9a9621ee'/>
      <target type='virtio' name='org.qemu.test_user_sn2_agent.100' state='disconnected'/>
      <alias name='channel0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'>
      <alias name='input1'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input2'/>
    </input>
    <graphics type='vnc' port='5900' autoport='yes' listen='0.0.0.0' keymap='en-us'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='none' model='none'/>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+107:+107</label>
    <imagelabel>+107:+107</imagelabel>
  </seclabel>
</domain>
```

**Comment by Lxiaoyouling** [comment]
![image](https://user-images.githubusercontent.com/10220220/200512621-1cbcde5d-b576-4f81-8b55-023c0e9175a8.png)

**Comment by Lxiaoyouling** [comment]
> @Lxiaoyouling @Heathcliff4689
> 
> So, it is actually in MS documentation: https://learn.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling
> 
> "Note: Because hyper-threaded CPUs on the same core processor share the same execution engine, the effect is not the same as having multiple core processors. For this reason, RSS does not use hyper-threaded processors."
> 
> That's why you see the difference in the mapping - the mapping is passed to driver by the OS.

Thank you very much!
But I still have a question, because the rx queues look normal.

**Comment by Lxiaoyouling** [comment]
> @Lxiaoyouling @Heathcliff4689
> 
> So, it is actually in MS documentation: https://learn.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling
> 
> "Note: Because hyper-threaded CPUs on the same core processor share the same execution engine, the effect is not the same as having multiple core processors. For this reason, RSS does not use hyper-threaded processors."
> 
> That's why you see the difference in the mapping - the mapping is passed to driver by the OS.

Thank you very much!
But I still have a question, because the rx queues look normal.
And Could Rss affect the send queue?

**Comment by YanVugenfirer** [comment]
> > @Lxiaoyouling @Heathcliff4689
> > So, it is actually in MS documentation: https://learn.microsoft.com/en-us/windows-hardware/drivers/network/introduction-to-receive-side-scaling
> > "Note: Because hyper-threaded CPUs on the same core processor share the same execution engine, the effect is not the same as having multiple core processors. For this reason, RSS does not use hyper-threaded processors."
> > That's why you see the difference in the mapping - the mapping is passed to driver by the OS.
> 
> Thank you very much! But I still have a question, because the rx queues look normal. And Could Rss affect the send queue?

* "Could Rss affect the send queue" - yes, because when distributing packets to TX queue the driver uses the same hash function to calculate 
* You are looking at RX on the host side, right? So it can be virtio multi-queue auto steering or DPDK steering algorithm that is distributing the packets.  We added infrastructure to pass OS RSS configuration to virtio-net device into virtue spec and implemented the functionality in Windows and Linux drivers, but I don't think that there is any backend that uses it other than specifically configured TAP device with QEMU.

**Comment by YanVugenfirer** [comment]
@Lxiaoyouling @Heathcliff4689 

My suggestion is to change : `<topology sockets='1' cores='2' threads='2'/>` to be `cores='4' threads='1'`

**Comment by Lxiaoyouling** [comment]
I see.
Thanks a lot.

Best regards.
