### ISSUE TITLE
Can't create file in folder with group write access

### ISSUE THREAD

**Issue by KapJI** [virtio-win/kvm-guest-drivers-windows#857]
**Describe the bug**

I have folder where my user has write access as member of `debian-transmission` group:
```
drwxrwxr-x debian-transmission debian-transmission 4.0 KB Sat Nov 12 21:17:59 2022 downloads
```

I can create files there from my user on Debian host.

But from Windows VM I get "Catastrophic failure" when I try to create file there. 

**To Reproduce**

- Create folder which is owned by different user and their group
- Add current user to that group
- Try to create file there from mounted virtiofs share on Windows VM

If I change permissions to either of these, it works:
```
dr-xrwxr-x ruslan              debian-transmission 4.0 KB Sat Nov 12 21:27:04 2022 downloads
or
drwxrwxr-x debian-transmission ruslan              4.0 KB Sat Nov 12 21:33:41 2022 downloads
```

Also I can create file there when it mounted as Samba share.

So it seems that group membership is not checked properly.

**Expected behavior**
Files can be created in all these cases.

**Screenshots**
![error](https://user-images.githubusercontent.com/3767331/201495501-835f5070-7ac5-4b1d-a88e-017c918cd88d.PNG)

**Host:**
 - Disto: Debian
 - Kernel version: 5.18.0-2-amd64
 - QEMU version: 7.1.0 (Debian 1:7.1+dfsg-2+b2)
 - QEMU command line 
 - libvirt version: 8.5.0-1+b2
 - libvirt XML file

**VM:**
 - Windows version: Windows 10 22H2 19045.2006
 - Which driver has a problem: virtiofs
 - Driver version or commit hash that was used to build the driver: 0.1.225 (stable)

**Comment by viktor-prutyanov** [comment]
Hi @KapJI 

> Driver version or commit hash that was used to build the driver: 0.1.255 (stable)

Version 255 hasn't been released yet. Last version is 225. So, which virtio-win version do you use?

**Comment by KapJI** [comment]
You're right, I'm using 225.

Basically I installed:
- Virtio Guest Tools from https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.225-2/virtio-win-guest-tools.exe
- WinFSP 2022.2 from https://github.com/winfsp/winfsp/releases/tag/v1.12

**Comment by xiagao** [comment]
I hit a similar issue. @KapJI Could you help to check if we have the same steps? I use prewhql-228 version and ws2022 guest.

Detailed steps:
1.Add two users on host
# useradd u1
# useradd u2
2.Change permission of u1 home directory
# chmod -R 777 u1
u1]# ll
total 8
-rwxrwx---. 1 u1 u1 2730 Nov 14 22:53 boot.sh
srwxrwx---. 1 u1 u1    0 Nov 14 22:52 sock1
-rwxrwx---. 1 u1 u1    7 Nov 14 22:52 sock1.pid
drwxrwx---. 3 u1 u1   41 Nov 14 22:55 test

3.Change user u2's supplementary group to u1
# usermod -G u1 u2
# id u2
uid=1002(u2) gid=1002(u2) groups=1002(u2),1001(u1)

4. switch to u2 and start virtiofsd
[root@dell-per440-06 u1]# su u2
[u2@dell-per440-06 u1]$ /usr/libexec/virtiofsd -o source=test --socket-path=sock1

5. start ws2022 vm
6. start virtiofs service in guest and get z: volume
7. try to create a file in guest

Actual results:
Failed and it shows "File too Large" .....(see attachment)

![fail_to_create_file](https://user-images.githubusercontent.com/9928220/201826132-ae0ed7b8-4dd9-4ec3-8744-43ee36d18cd7.png)

**Comment by viktor-prutyanov** [comment]
Hi @xiagao 

Do you run `virtiofsd` as `u2` user?

**Comment by viktor-prutyanov** [comment]
@KapJI Which host directory do you try to share? In other words, what is virtio-fs host source path in libvirt? Please also share permissions for this directory.

**Comment by KapJI** [comment]
The shared directory is `/data/`:
```xml
<filesystem type='mount' accessmode='passthrough'>
    <driver type='virtiofs'/>
    <source dir='/data/'/>
    <target dir='data'/>
    <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
</filesystem>
```
```
drwxr-xr-x ruslan ruslan 4.0 KB Sun Nov 13 00:46:37 2022 data
```

**Comment by viktor-prutyanov** [comment]
I've reproduced the issue:
![image](https://user-images.githubusercontent.com/8286747/202269588-b31f872a-20cb-4a18-aa79-8772e81973de.png)

`virtiofsd` under `strace`:
![image](https://user-images.githubusercontent.com/8286747/202269678-f522cb22-9d0a-462b-ad8b-aa0ec5bf350c.png)

This is because `virtiofsd` uses `setresuid` and `setresgid` to change effective UID and GID but it doesn't change the list of supplementary group IDs:
1. https://unix.stackexchange.com/questions/118786/group-memberships-and-setuid-setgid-processes
2. https://github.com/virtio-win/kvm-guest-drivers-windows/issues/759
3. https://gist.github.com/viktor-prutyanov/fb12e64b173ea9f155642df16e9573bc 

Linux guest behaves in the same way:
![image](https://user-images.githubusercontent.com/8286747/202270296-48dfc3a7-1ecc-4b7c-9b15-4c72c3cadbfc.png)

So, the only thing that Virtio-FS service is doing wrong is "Catastrophic failure" message, it should be something like "Access Denied":
* https://github.com/virtio-win/kvm-guest-drivers-windows/pull/860

**Comment by viktor-prutyanov** [comment]
Hi @xiagao 

I guess you are running Rust virtiofsd, not C. Because C virtiofsd can't even run under unprivileged user:
```
vp@localhost ~/vms $ id
uid=1000(vp) gid=1000(vp) groups=1000(vp),10(wheel),972(wireshark),1001(docker)
vp@vp-pc ~/vms $ /usr/local/libexec/virtiofsd --version
setgroups() failed with error=1:Operation not permitted
vp@vp-pc ~/vms $ sudo /usr/local/libexec/virtiofsd --version
[sudo] password for vp: 
virtiofsd version 7.1.50 (v7.1.0-988-g133bdac3a1-dirty)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
using FUSE kernel interface version 7.36
```
I've reproduced the behavior and virtiofsd reports the following error:
```
[2022-11-17T08:56:15Z DEBUG virtiofsd::server] Received request: opcode=Create (35), inode=10, unique=276, pid=1612
[2022-11-17T08:56:15Z ERROR virtiofsd::passthrough] failed to change credentials back to root: Invalid argument (os error 22)
[2022-11-17T08:56:15Z ERROR virtiofsd::passthrough] failed to change credentials back to root: Invalid argument (os error 22)
[2022-11-17T08:56:15Z DEBUG virtiofsd::server] Replying ERROR, header: OutHeader { error: -22 (Invalid argument), unique: 276, len: 16 }
```
We process EINVAL (22) as STATUS_INVALID_ARGUMENT on the service side and this is why we can see the error message box.

**Comment by viktor-prutyanov** [comment]
So, `u2` user is not privileged enough to properly change his id and perform the operation.

**Comment by xiagao** [comment]
> he only thing that Virtio-FS service is doing wrong is "Catastrophic failure" message, it should be something like "Access Denied"

Yes, I use virtiofs in rust version. Thanks for clarifying.

**Comment by viktor-prutyanov** [comment]
After
* https://github.com/virtio-win/kvm-guest-drivers-windows/pull/860 

behavior is the same as Linux guest

I suggest to discuss Xiaoling's issue separately.
