### ISSUE TITLE
virtiofsd crashes after VM startup

### ISSUE THREAD

**Issue by rickyelopez** [virtio-win/kvm-guest-drivers-windows#875]
creating issue from https://gitlab.com/virtio-fs/virtiofsd/-/issues/72

versions when I made the original ticket:

virtio-win-guest-tools version `0.1.225`
winfsp version `1.11.22103`

versions now:
virtio-win-guest-tools version `0.1.229`
winfsp version `1.12.22301`

Hello,

I'm trying to share a dir with a windows guest using virtiofsd. Sometimes it stops working and I go through a bunch of debugging, find nothing, end up going back to the original setup, and then it works. Then it stops working again. I haven't been able to get any useful logs from anywhere, and I'm not finding anything on google.

Here are the relevant bits of my domain xml:
```xml
<memoryBacking>
    <source type="memfd"/>
    <access mode="shared"/>
</memoryBacking>
...
<filesystem type="mount" accessmode="passthrough">
  <driver type="virtiofs" queue="1024"/>
  <binary path="/opt/launcher"/>
  <source dir="/home/user/vm/shared"/>
  <target dir="HostShared"/>
  <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
</filesystem>
```

I couldn't figure out how to pass the `log-level` flag through this, so I made that `launcher` file which just contains
```bash
#!/bin/bash
/opt/virtiofsd --log-level debug "$@"
```

The resultant output when starting up the domain is:
```
[2022-12-18T02:47:49Z WARN  virtiofsd] Use of deprecated option format '-o': Please specify options without it (e.g., '--cache auto' instead of '-o cache=auto')
[2022-12-18T02:47:49Z INFO  virtiofsd] Waiting for vhost-user socket connection...
[2022-12-18T02:47:49Z INFO  virtiofsd] Client connected, servicing requests
[2022-12-18T02:48:00Z DEBUG virtiofsd] QUEUE_EVENT
[2022-12-18T02:48:00Z DEBUG virtiofsd::server] Received request: opcode=Init (26), inode=0, unique=1, pid=1
[2022-12-18T02:48:00Z DEBUG virtiofsd::server] Replying OK, header: OutHeader { len: 80, error: 0, unique: 1 }
[2022-12-18T02:48:00Z DEBUG virtiofsd] QUEUE_EVENT
[2022-12-18T02:48:04Z ERROR virtiofsd] Waiting for daemon failed: HandleRequest(InvalidMessage)
```

I have no idea what to make of this, or what else to try, and I'm not finding _any_ results for that particular error on google. 

Not sure what other information about my setup might be relevant, other than:
```
❯ ./virtiofsd -V
virtiofsd backend 1.4.0
```
and that I'm running qemu 6.2.0-16 on fedora 36 kernel version 5.18.19-200. Please let me know what other info I can provide to help.

Any suggestions that I can try? This is driving me nuts, especially the part where it (seemingly randomly) starts working after hours of debugging and no real changes.

Worth noting that I've tried to launch virtiofsd separately from the domain and use a socket, but libvirt spits out a `permission denied` error for the socket regardless of where I put it or what perms I assign. I _cannot_ figure out how to get it to launch, but happy to try any suggestions you may have.

Thanks in advance!

**Comment by xiagao** [comment]
@rickyelopez hi, could you provide the virtiofsd version you are using and if you started vm with UEFI(ovmf) firmware?

There is an internal issue with virtiofsd-C version and UEFI firmware.
There are two workarounds.
1.Updating virtiofsd from C version to rust version, you can update qemu-kvm to 7.0.0+ version and install vritiofsd-rs(https://gitlab.com/virtio-fs/virtiofsd) seperately.
2.using seabios firmware instead.

-Xiaoling

**Comment by xiagao** [comment]
I didn't reproduce this issue on the win2022 guest, what guest did you test? Also, what's the test in the shared directory in the guest?
I create a big file in the shared dir with dd command.
dd if=/dev/random of=z:\file.txt bs=1M count=200

# ps aux |grep virtiofsd
root      226540  0.0  0.0   5768  3748 pts/0    S+   Feb05   0:00 /usr/libexec/virtiofsd --socket-path /tmp/sock1 --shared-dir /home/test -d -o cache=always
root      226541  2.1  1.0 4318296 353324 pts/0  Sl+  Feb05   0:17 /usr/libexec/virtiofsd --socket-path /tmp/sock1 --shared-dir /home/test -d -o cache=always

qemu cmd line:
     -machine q35,pflash0=drive_ovmf_code,pflash1=drive_ovmf_vars \
     -m 4096 \
     -object memory-backend-memfd,size=4G,share=on,id=mem-mem1  \
     -smp 24,maxcpus=24,cores=12,threads=1,dies=1,sockets=2  \
     -numa node,memdev=mem-mem1,nodeid=0  \
     
     -chardev socket,id=char_virtiofs_fs,path=/tmp/sock1 \
     -device vhost-user-fs-pci,id=vufs_virtiofs_fs,chardev=char_virtiofs_fs,tag=HostShared,queue-size=1024,bus=pcie-root-port-3,addr=0x0 \

virtio-win version: virtio-win-prewhql-0.1-231.iso
winfsp version 1.12.22301
virtiofsd-1.5.0-1

**Comment by rickyelopez** [comment]
I'm using windows 10 LTSC as a guest. The shared directory does not appear on the guest, so there's not much I can test around the contents of it. It contains various CAD files, though.

I see your test uses a socket. I wasn't able to do that, I just got a permission denied error no matter what I did.

**Comment by viktor-prutyanov** [comment]
Hi @rickyelopez 

> I see your test uses a socket. I wasn't able to do that, I just got a permission denied error no matter what I did.

Which socket do you mean? If `-chardev socket,id=char_virtiofs_fs`, it is necessary for VirtIO-FS to work.

**Comment by viktor-prutyanov** [comment]
Hi @rickyelopez

Could you please try to capture debug logs on the guest side?
https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#options

**Comment by xiagao** [comment]
@rickyelopez If you don't specify NUMA topology,could you have a try with it? 


  <vcpu placement='static'>4</vcpu>
  <cpu mode='host-model' check='partial'>
    <numa>
      <cell id='0' cpus='0-3' memory='4194304' unit='KiB' memAccess='shared'/>
    </numa>
  </cpu>

**Comment by rickyelopez** [comment]
> Hi @rickyelopez
> 
> > I see your test uses a socket. I wasn't able to do that, I just got a permission denied error no matter what I did.
> 
> Which socket do you mean? If `-chardev socket,id=char_virtiofs_fs`, it is necessary for VirtIO-FS to work.

I meant the fact that you are launching virtiofsd separately from the VM with
```
$ ps aux |grep virtiofsd
root 226540 0.0 0.0 5768 3748 pts/0 S+ Feb05 0:00 /usr/libexec/virtiofsd --socket-path /tmp/sock1 --shared-dir /home/test -d -o cache=always
```
note the `--socket-path /tmp/sock1`. This doesn't work for me and fails out with permission errors, no matter what perms I assign. I have been using the `-fd` option, which is what virt-manager appears to use natively.



> Hi @rickyelopez
> 
> Could you please try to capture debug logs on the guest side? [virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#options](https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#options)

Yes I'll try this out, thanks! I hadn't seen this page. It seems unlikely to me that the guest is at fault since virtiofsd on the host crashes well before the OS has had a chance to launch anything on the guest side. I don't even think it makes it to the windows boot loader before it crashes. I'll try anyway, though.

> @rickyelopez If you don't specify NUMA topology,could you have a try with it? ` <vcpu placement='static'>4</vcpu> <cpu mode='host-model' check='partial'> <numa> <cell id='0' cpus='0-3' memory='4194304' unit='KiB' memAccess='shared'/> </numa> </cpu>`

Why would numa topology be relevant? I'm not passing through a GPU... I can try it I guess, though I don't know what this actually does.

**Comment by xiagao** [comment]
Why would numa topology be relevant? I'm not passing through a GPU... I can try it I guess, though I don't know what this actually does.
> There is an internal issue similar with yours if not specifying numa.
During vm boot up, virtiofsd will quit with "Waiting for daemon failed: HandleRequest(InvalidParam)"

**Comment by rickyelopez** [comment]
Ok, tried both of your suggestions @xiagao @viktor-prutyanov, no luck. Adding numa topology had no impact, neither did enabling debug logs on the guest. The latter makes sense to me since the service a) doesn't start automatically and b) virtiofsd crashes way before the OS boots.

I'm actually really surprised to hear everyone blaming the software on the guest-side here, since virtiofsd crashes before the os has booted. That being said, I don't really know what I'm talking about.

**Comment by viktor-prutyanov** [comment]
Hi @rickyelopez 

> I'm actually really surprised to hear everyone blaming the software on the guest-side here, since virtiofsd crashes before the os has booted. That being said, I don't really know what I'm talking about.

This is a new information for us. Does the daemon crash before guest OS has started in all of the cases or sometimes fall later? Have you tried Linux guest?

**Comment by rickyelopez** [comment]
Sorry, should have been more clear. I just noticed that I did mention it in a previous comment, but not in the OP.

Daemon appears to crash when windows is displaying the "spinning dots" loading screen, which I guess is when it's booting? I just tried with RockyLinux, and while I haven't been able to mount the shared dir on the guest yet (trying to figure out what I'm missing to get `mount -t <tag> <dir>` to work), the daemon does not appear to crash.

**Comment by viktor-prutyanov** [comment]
> Daemon appears to crash when windows is displaying the "spinning dots" loading screen, which I guess is when it's booting?

Is it 100% reproducible behavior or some other crash scenarios are also exist?

> I just tried with RockyLinux, and while I haven't been able to mount the shared dir on the guest yet (trying to figure out what I'm missing to get `mount -t <tag> <dir>` to work), the daemon does not appear to crash.

According to your XML from OP, tag is `HostShared`. Mount directory can be any directory.

**Comment by rickyelopez** [comment]
Yes, reproduces every time I start the VM currently. This worked, once upon a time. Not recently though.

Yes, that's what I'm trying, but I'm getting `'/mnt/HostShared' can't find in etc/fstab`. Maybe I'm missing a package? This is a fresh install, after all.

**Comment by viktor-prutyanov** [comment]
Does your VirtIO-FS Service configured to start automatically or manually? Does the daemon fail if running the guest service manually?

**Comment by rickyelopez** [comment]
The service is set to start manually, and yes that does cause it to crash

**Comment by viktor-prutyanov** [comment]
> The service is set to start manually, and yes that does cause it to crash

So, when the service starts manually, the daemon crashes right after the service start, but when the service starts automatically, the daemon crashes during Windows boot, right?

**Comment by rickyelopez** [comment]
No, I haven't tested with the service set to automatic. I can do that. With the service set to manual, the daemon crashes as soon as we get to the windows bootloader.

**Comment by viktor-prutyanov** [comment]
> With the service set to manual, the daemon crashes as soon as we get to the windows bootloader.

At least, it means that service can't cause the issue. The reason is either guest driver or daemon.

**Comment by viktor-prutyanov** [comment]
Could you please do the following:

1. Disable VirtIO-FS device in Device Manager
2. Restart the VM
3. Check virtiofsd
4. Enable VirtIO-FS device
5. Check virtiofsd
6. Start VirtIO-FS service
7. Check virtiofsd

**Comment by rickyelopez** [comment]
Progress! After disabling the VirtIO FS Device in the device manager, the virtiofsd daemon keeps running all the way to the desktop! Unfortunately, re-enabling the device immediately crashes it. Still, progress I think? Does this mean I have a bad driver?

**Comment by viktor-prutyanov** [comment]
> Still, progress I think? 

Yes

> Does this mean I have a bad driver?

Honestly, it doesn't show what is actually broken, the driver or the daemon. I will think how to debug this case.

**Comment by germag** [comment]
@rickyelopez I think you already mentioned it, but I just want to confirm, are you using a passthrough vGPU?

**Comment by rickyelopez** [comment]
I'm just using spice and qxl

**Comment by olhovpav** [comment]
The same for me.

Guest is Windows 10 Home 22H2, 19045.3208,
winfsp-2.0.23075,
virtio-win-0.1.229.

Host is Manjaro with kernel 6.1.41-1-MANJARO,
virtiofsd backend 1.7.0,
QEMU emulator version 8.0.3.

Command line:
```
/usr/lib/virtiofsd \
    --gid-map=:0:100000:65536: \
    --uid-map=:0:100000:65536: \
    --sandbox namespace\
    --socket-path=/home/user/vm/fsshare.sock \
    --shared-dir /home/user/vm/win-shared \
    --cache always --log-level debug &

qemu-system-x86_64 \
    -display spice-app \
    -cpu host \
    -m 8G \
    -vga virtio \
    -enable-kvm \
    -drive format=raw,file=/home/user/vm/win \
    -chardev socket,id=fsshare,path=/home/user/vm/fsshare.sock \
    -device vhost-user-fs-pci,chardev=fsshare,tag=win \
    -name win
```

When I enable VirtIO FS Device, I immediately get these errors:
```
[2023-08-02T19:33:01Z ERROR virtiofsd] Waiting for daemon failed: HandleRequest(InvalidParam)
qemu-system-x86_64: Unexpected end-of-file before all data were read
```
And virtiofsd process exits.

**Comment by xiagao** [comment]
> The same for me.
> 
> Guest is Windows 10 Home 22H2, 19045.3208, winfsp-2.0.23075, virtio-win-0.1.229.
> 
> Host is Manjaro with kernel 6.1.41-1-MANJARO, virtiofsd backend 1.7.0, QEMU emulator version 8.0.3.
> 
> Command line:
> 
> ```shell
> /usr/lib/virtiofsd \
>     --gid-map=:0:100000:65536: \
>     --uid-map=:0:100000:65536: \
>     --sandbox namespace\
>     --socket-path=/home/user/vm/fsshare.sock \
>     --shared-dir /home/user/vm/win-shared \
>     --cache always --log-level debug &
> 
> qemu-system-x86_64 \
>     -display spice-app \
>     -cpu host \
>     -m 8G \
>     -vga virtio \
>     -enable-kvm \
>     -drive format=raw,file=/home/user/vm/win \
>     -chardev socket,id=fsshare,path=/home/user/vm/fsshare.sock \
>     -device vhost-user-fs-pci,chardev=fsshare,tag=win
> ```
> 
> When I enable VirtIO FS Device, I immediately get these errors:
> 
> ```
> [2023-08-02T19:33:01Z ERROR virtiofsd] Waiting for daemon failed: HandleRequest(InvalidParam)
> qemu-system-x86_64: Unexpected end-of-file before all data were read
> ```
> 
> And virtiofsd process exits.

Hi @olhovpav , did you use memory backend device to share guest memory in qemu command line?

**Comment by germag** [comment]
@olhovpav as @xiagao said you forgot to define the shared memory backend:
instead of `-enable-kvm ` use:
```
    -object memory-backend-file,id=mem,size=8G,mem-path=/dev/shm,share=on \
    -machine memory-backend=mem,accel=kvm \
```

**Comment by olhovpav** [comment]
@germag, @xiagao, thank you! I replaced `-enable-kvm` with shared memory backend options and now it works!

**Comment by gogoprog** [comment]
> [@olhovpav](https://github.com/olhovpav) as [@xiagao](https://github.com/xiagao) said you forgot to define the shared memory backend: instead of `-enable-kvm ` use:
> 
> ```
>     -object memory-backend-file,id=mem,size=8G,mem-path=/dev/shm,share=on \
>     -machine memory-backend=mem,accel=kvm \
> ```

That helped me too, it wasn't obvious that memory share was mandatory when following the docs

**Comment by germag** [comment]
Just a minor adjustment, instead of `/dev/shm`, it's better to use the memfd memory backend:

``` 
-object memory-backend-memfd,id=mem,size=8G,share=on \
-machine memory-backend=mem,accel=kvm \
```

`/dev/shm`  (can) have some size limitation.
