### ISSUE TITLE
How to read fw_cfg value?

### ISSUE THREAD

**Issue by JonasJasas** [virtio-win/kvm-guest-drivers-windows#880]
Unable to find documentation about how to read `-fw_cfg` value using [this driver](https://github.com/virtio-win/kvm-guest-drivers-windows/tree/master/fwcfg).

If someone could answer my [question](https://serverfault.com/questions/1122411/how-to-read-qemu-fw-cfg-value-in-windows-guest) that would also help me and anyone else facing the same issue.

**Comment by viktor-prutyanov** [comment]
Hi @JonasJasas 

> Unable to find documentation about how to read -fw_cfg value using [this driver](https://github.com/virtio-win/kvm-guest-drivers-windows/tree/master/fwcfg).

The driver you mention can't do anything because it's just a stub.

The [fwcfg64](https://github.com/virtio-win/kvm-guest-drivers-windows/tree/master/fwcfg64) is able to read/write fw_cfg entries internally, but actually only writes `etc/vmcoreinfo` according to its original purpose (PR https://github.com/virtio-win/kvm-guest-drivers-windows/pull/270).

There was a similar isuue https://github.com/virtio-win/kvm-guest-drivers-windows/issues/412 4 years ago and there is a way to read fw_cfg entries manually  (https://github.com/virtio-win/kvm-guest-drivers-windows/issues/412#issuecomment-784661575).

**Comment by viktor-prutyanov** [comment]
At the moment we do not have on the agenda the addition of such functionality to read/write arbitrary entry, but PRs are welcome.

**Comment by viktor-prutyanov** [comment]
It depends on the task.

For example, you can use serial port, or shared file system, or virtual socket.

**Comment by viktor-prutyanov** [comment]
Or even `-cdrom` with an ISO with a text file with a needed info, if read-only is OK.

**Comment by JonasJasas** [comment]
I have two separate tasks:

- To pass configuration parameters from host to guest (win->lin) (previous question)
- To output windows console application stdout to the host stdout

could you point me in the right direction, I see many examples for Linux/Linux scenarios but not for Linux/windows.

**Comment by YanVugenfirer** [comment]
Hi @JonasJasas,

Let's start with the console app.
There is an existing mechanism of virtio-serial ports and consoles over virtio serial.
On the host side, you can bind virtio-serial port to chardev that can even be stdout.
Examples:
https://stackoverflow.com/questions/68277557/qemu-virtio-virtconsole-devices-explained
https://fedoraproject.org/wiki/Features/VirtioSerial
On the guest side, you will have to write some app that redirects the console to the virtio-serial port. Examples of the port usage can be found in qemu-ga (guest agent): https://github.com/qemu/qemu/blob/master/qga/channel-win32.c#L283 

Regarding config from host to guest. It can be using the same or another virtio-serial port as well. Let me think about other options.

Best regards,
Yzn.

**Comment by JonasJasas** [comment]
Thank you for helping me! If you will think of other ways how to do it please let me know. This is our architecture: `Kubernetes -> container with the Qemu -> windows -> application` Windows application output should go to the container output to act as if it is a native application.

**Comment by YanVugenfirer** [comment]
Is it any Windows application or your specific application?

**Comment by JonasJasas** [comment]
Our application that is written on almighty .net. If there is dll or other library that could ease virtio serial port usage please let me know. Also, there could be an option to use netcat on the host side, but I would like to avoid background processes inside the container.

**Comment by YanVugenfirer** [comment]
> Our application that is written on almighty .net. If there is dll or other library that could ease virtio serial port usage please let me know. Also, there could be an option to use netcat on the host side, but I would like to avoid background processes inside the container.

So in this case I really suggest looking into https://github.com/virtio-win/kvm-guest-drivers-windows/issues/880#issuecomment-1425283404 - using virtioconsole and redirecting it to stdio in qemu command line solves your host needs.

**Comment by viktor-prutyanov** [comment]
It seems that there are a lot of methods instead of accessing arbitrary fw_cfg entries. If this ability is still needed, we can come back to this question.

**Comment by JonasJasas** [comment]
Passing configuration was solved by creating qcow2 image and passing to the VM. Not an ideal way but straightforward and simple.
I was unable to solve console redirection. It was so easy to do it in other OS'es and it is so sad that there is no easy way to do it in this magical MS Windows OS.

**Comment by Jamesits** [comment]
@JonasJasas 
> I was unable to solve console redirection.
Did you mean enabling Windows EMS/SAC automatically?
