### ISSUE TITLE
Driver support for virtrio block disk type

### ISSUE THREAD

**Issue by MohammadrezaNasrabadi** [virtio-win/kvm-guest-drivers-windows#888]
I've searched for `vioblk` driver installation on the virtio iso file and found nothing related.

`vioscsi` driver is able to emulate block disk file but sometimes (especially on windows updating) it seems that using virtio-scsi driver on `virtio-blk` disk type leads to non-recognization of the disk file.

Is there any support for driving `virtio-blk` disk type on windows guest machines?

**Comment by vrozenfe** [comment]
viostor.sys 

Best,
Vadim.
