### ISSUE TITLE
viosock driver inf sign failed through microsoft

### ISSUE THREAD

**Issue by YanVugenfirer** [virtio-win/kvm-guest-drivers-windows#895]
### Discussed in https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/894

<div type='discussions-op-text'>

<sup>Originally posted by **xuehuihui** March 13, 2023</sup>
error log：
Error 1303 in viosock.Inf, line 99 : Found legacy AddReg operation defining co-installers (CoInstallers32).
Failed INF validation. INF did not pass Desktop validation (InfVerif /k).</div>

**Comment by xuehuihui** [comment]
i read this patch viorng: Remove coinstaller from the INF. Does viosock also need to be handled in this way? @MartinDrab

**Comment by YanVugenfirer** [comment]
@xuehuihui Yes, same should be done with the viosock driver
