### ISSUE TITLE
virtio-fs: Symlinks doesn't work

### ISSUE THREAD

**Issue by davispuh** [virtio-win/kvm-guest-drivers-windows#897]
**Describe the bug**
Can't navigate into directory symlink

**To Reproduce**
Steps to reproduce the behaviour:

```
Z:\>mkdir test
Z:\>echo a > test\a
Z:\>type test\a
a

Z:\>mklink /D t test
symbolic link created for t <<===>> test

Z:\>type t\a
The filename, directory name, or volume label syntax is incorrect.

Z:\>cd t

Z:\t>dir
 Volume in drive Z is Z
 Volume Serial Number is 0000-0000

 Directory of Z:\

27/03/2023  05:42    <SYMLINK>      t [...]
               1 File(s)              0 bytes
               0 Dir(s)  136,383,930,368 bytes free

Z:\t>type a
The filename, directory name, or volume label syntax is incorrect.
```

**Expected behavior**

To be able to double-click on symlink in Explorer to enter it and also see content with `cmd`. 

**Screenshots**

**Host:**
 - Disto: Arch Linux
 - Kernel version 6.2.8
 - QEMU version 7.2.0
 - QEMU command line 
 - libvirt version 9.1.0
 - libvirt XML file

**VM:**
 - Windows version 21H2 19044.2728
 - Which driver has a problem - virtio-fs
 - Driver version or commit hash that was used to build the driver - winfsp-2.0.23075

**Additional context**

**Comment by viktor-prutyanov** [comment]
Hi @davispuh 

Could you please tell us, how are you going to use symlinks?

**Comment by davispuh** [comment]
Some programs don't work with long paths (even when using Long Paths it needs to be explicitly enabled), so deep nested directory can be symlinked into drive's root dir thus bypassing path limitation.

Another use case is organizing folders with symlinks when multiple folders/files match several possible categories where it should be placed.

**Comment by viktor-prutyanov** [comment]
Currently, symlinks are rarely used on Windows, while reparse points (the Windows mechanism for symlinks) are not a well-documented feature. So, a lot of time has to be invested to fully support them in VirtIO-FS.

**Comment by xiagao** [comment]
I didn't reproduce with the same steps.
(virtiofsd)# /usr/libexec/virtiofsd --shared-dir /home/test --socket-path /tmp/sock1

kernel-5.14.0-226.el9.x86_64
qemu-kvm-7.2.0-8.el9.x86_64
virtio-win-prewhql-0.1-235
win2022 guest


```
Z:\>mkdir test

Z:\>echo a > test/a

Z:\>type test\a
a 

Z:\>
Z:\>mklink /D  t test
symbolic link created for t <<===>> test

Z:\>type t\a
a 


```
