### ISSUE TITLE
QXL graphics refresh rate 1hz on windows 10

### ISSUE THREAD

**Issue by screamo-boop** [virtio-win/kvm-guest-drivers-windows#898]
**Describe the bug**
QXL graphics, virtio-win latest version installed on windows 10. I have very small display refresh rate -- 1hz

**To Reproduce**
Steps to reproduce the behaviour:

1. Install windows 10 with qxl graphics
2. Install latest virtio-win drivers
3. Check refresh rate in display properties
4. Refresh rate = 1hz

**Expected behavior**

Refresh rate = 30hz or 60hz

**Screenshots**

https://imgur.com/a/JgEpv5Q

**Host:**
 - Disto: Debian 11.6
 - Kernel version: 5.15
 - QEMU version: 7.2.0
 - libvirt version: 8.5.0

**VM:**
 - Windows version: Windows 10.0.19044.1466
 - Which driver has a problem: Red Hat QXL controller
 - Driver version or commit hash that was used to build the driver: 10.0.0.21000

**Comment by YanVugenfirer** [comment]
Hi @screamo-boop,

Can actual physical manifestation of this setting be observed? After all, the actual rendering happens on the client side.

Also, in general, we are not tracking QXL bugs here. Please follow: https://www.spice-space.org/support.html

Best regards,
Yan.

**Comment by screamo-boop** [comment]
> 
Everything should be fine on the client side
I will follow the link you provided
Thanks for the answer!
