### ISSUE TITLE
Ballooning unstable on Windows servers

### ISSUE THREAD

**Issue by Directox01** [virtio-win/kvm-guest-drivers-windows#903]
**Describe the bug**
Greetings!

I hope you're all doing great. I've come across a couple of issues while using the virtio ballooning driver and I'm hoping you could help me figure out what's going on.

Issue 1: RAM Leak
So, I've got the virtio ballooning driver installed and it seems to be working fine, but there's a RAM leak happening in one of my virtual machines (VM 102). I've attached a screenshot to show you what I'm talking about. The weird thing is that there's still plenty of free RAM on the host, so I'm not sure why this is happening.

Issue 2: High Resource Usage
Another thing I've noticed is that the host's RAM usage is more than 50 GB even when my virtual machines aren't running any programs or applications. I'm kind of puzzled because I'd expect the resource usage to be around 4% when the virtual machines are idle.

I'd really appreciate any help or suggestions you can provide to resolve these issues. If you need any more info from me, just let me know and I'll be happy to give you whatever you need.

Thanks so much for your help and support!

Best regards,
Adam.

**Screenshots**
https://gyazo.com/359b58da8b38e93135f58172971cf3d2
https://gyazo.com/66a8f34fe968a75f10eb4b79c0c581fa
https://gyazo.com/feabda3b24f05f4d5a7e36e2693b304f
![image](https://user-images.githubusercontent.com/113183651/231345686-3958d980-9a68-44bb-b89c-a5a8345e0761.png)

**Host:**
 Debian 11.6 Proxmox 7.4.3]

** package version **
proxmox-ve: 7.4-1 (running kernel: 6.2.9-1-pve)
pve-manager: 7.4-3 (running version: 7.4-3/9002ab8a)
pve-kernel-6.2: 7.4-1
pve-kernel-5.15: 7.4-1
pve-kernel-6.2.9-1-pve: 6.2.9-1
pve-kernel-5.15.104-1-pve: 5.15.104-1
ceph-fuse: 14.2.21-1
corosync: 3.1.7-pve1
criu: 3.15-1+pve-1
glusterfs-client: 9.2-1
ifupdown: not correctly installed
ifupdown2: 3.1.0-1+pmx3
libjs-extjs: 7.0.0-1
libknet1: 1.24-pve2
libproxmox-acme-perl: 1.4.4
libproxmox-backup-qemu0: 1.3.1-1
libproxmox-rs-perl: 0.2.1
libpve-access-control: 7.4-2
libpve-apiclient-perl: 3.2-1
libpve-common-perl: 7.3-4
libpve-guest-common-perl: 4.2-4
libpve-http-server-perl: 4.2-1
libpve-rs-perl: 0.7.5
libpve-storage-perl: 7.4-2
libspice-server1: 0.14.3-2.1
lvm2: 2.03.11-2.1
lxc-pve: 5.0.2-2
lxcfs: 5.0.3-pve1
novnc-pve: 1.4.0-1
proxmox-backup-client: 2.4.1-1
proxmox-backup-file-restore: 2.4.1-1
proxmox-kernel-helper: 7.4-1
proxmox-mail-forward: 0.1.1-1
proxmox-mini-journalreader: 1.3-1
proxmox-widget-toolkit: 3.6.5
pve-cluster: 7.3-3
pve-container: 4.4-3
pve-docs: 7.4-2
pve-edk2-firmware: 3.20230228-2
pve-firewall: 4.3-1
pve-firmware: 3.6-4
pve-ha-manager: 3.6.0
pve-i18n: 2.12-1
pve-qemu-kvm: 7.2.0-8
pve-xtermjs: 4.16.0-1
qemu-server: 7.4-3
smartmontools: 7.2-pve3
spiceterm: 3.2-2
swtpm: 0.8.0~bpo11+3
vncterm: 1.7-1

**VM:**
 - windows server 2022
 - Ballooning
 - version driver 0.1.229-1

**Comment by YanVugenfirer** [comment]
Hello @Directox01 ,

1. Sorry, but I don't understand the anomalies. Could you please explain what you are trying to show in the screenshots? I also don't understand the following sentence: "The weird thing is that there's still plenty of free RAM on the host, so I'm not sure why this is happening." What do you expect to see?
2. There are many variables that affect host memory consumption, but in general I would expect that the memory for the VM will be preallocated. So only the memory from the inflated balloon will be returned to the host.
What I mean is that if you run VM with 4G, 4G will be used on the host in the general case - it doesn't matter how much of the RAM guest OS is actually using. If you use KSM and\or balloon (and the balloon is inflated), you can reclaim some of the memory 

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
If you are looking for general advice on memory overcommit techniques then:
1. Please check https://www.kernel.org/doc/html/latest/admin-guide/mm/ksm.html - it is very effective with Windows VMs as Windows VMs are zeroing the unallocated memory. 
2.  Inflate the balloon based on the memory usage of the guest

**Comment by Directox01** [comment]
Hello,

Sorry for the delayed response!

I have less than 4 GB of RAM usage, but the hosts show as 50+ and I was expecting it to work as it does on Linux VMs :)).

I see... thank you for the clarification.

Yes, I'm currently using KSM, but the problem with KSM is that it's not recommended by Proxmox for production use as it's not a secure way to save memory, and I'm using my VMs for production purposes.

Once again, sorry for the delayed response.

Best regards,
Adam.

**Comment by yangni2017** [comment]
> Hello,
> 
> Sorry for the delayed response!
> 
> 1. I have less than 4 GB of RAM usage, but the hosts show as 50+, and I was expecting it to work as it does on Linux VMs :)).
> 2. I see... thank you for the clarification.
> 3. Yes, I'm currently using KSM, but the problem with KSM is that it's not recommended by Proxmox for production use as it's not a secure way to save memory, and I'm using my VMs for production purposes.
> 
> Once again, sorry for the delayed response.
> 
> Best regards, Adam.

hi,have you solved your problem? I have the same problem,the used memory of the windows virtual machine would increase if Inflate  balloon. it was a bit strange that.
