### ISSUE TITLE
How to see the output of DbgPrintEx from ivshmem driver?

### ISSUE THREAD

**Issue by Youxu-Chen** [virtio-win/kvm-guest-drivers-windows#905]
Hi, all, I am new to develop ivshmem driver in Win10. I got a problem now. The release ivshmem driver does not print the debug information. So I build the ivshmem driver manually adding `DBG` macro and testsigning. I have installed this debug ivshmem driver successfully, however, I can not see any output about this driver with`Debugview` software(enabled kernel capturing)：
<img width="459" alt="image" src="https://user-images.githubusercontent.com/28796466/233533711-3b26568d-a88e-48cf-b450-7f41842b2b9e.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/28796466/233532647-1a5d9e2c-4d27-45b3-bbad-2eae7d9ba109.png">

I have searched some references and tried some methods. For example, like this:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/28796466/233533047-56a0a085-901f-4e97-9a75-7b3fdbb46776.png">

And I got these outputs:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/28796466/233532852-a2cd907e-cbba-4801-b3ad-478c1990f898.png">

I also cannot find any output of ivshmem. 

I just want to see the output of ivshmem.

Now, I don't know how to get it. Please help me! 

Thanks!!!

**Comment by YanVugenfirer** [comment]
Hi @Youxu-Chen ,

1. What do you mean "using DBG macro"? We are using following macros in the code:
```
#define DEBUG_ERROR(fmt, ...) do { KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, "[E:IVSHMEM] " fmt "\n", ## __VA_ARGS__)); } while (0)

#define DEBUG_INFO(fmt, ...) do { KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, "[I:IVSHMEM] " fmt "\n", ## __VA_ARGS__)); } while (0)
```
If you use some generic macro, we do not compile debug version - it could be empty in release driver.

2. Did you change the registry value and reboot  as seen in the screen shot you posted?
 https://www.slideshare.net/YanVugenfirer/windows-guestdebugging-kvmforum2012 (page 21)

Best regards,
Yan.

**Comment by Youxu-Chen** [comment]
Hi @YanVugenfirer, 
1. The `DBG` macro is the pre-definition in project resolution to enable `KdPrintEx` and `DbgPrintEx`：
![image](https://user-images.githubusercontent.com/28796466/234167372-a321708d-0ca9-4fe7-9af1-d32ac0eb9b09.png)

2. I've tried add a "Default" item in registry. And now, I can see the output of IVSHMEM when I changing the driver to the driver I built.
![image](https://user-images.githubusercontent.com/28796466/234167607-f6d06b08-aa59-405b-ab00-2517e701c4c8.png)

Thanks，It works for me.

But，unfortunately, I cannot see my new modification in log when I added some comments. I tried add some new comments like this:
- I add some flags to represent another IVSHMEM: 
![image](https://user-images.githubusercontent.com/28796466/234168069-eee53caa-c277-4a8b-a38e-f123798a5a3d.png)
- I update the driver:
![image](https://user-images.githubusercontent.com/28796466/234168250-f4827a5c-f21d-49ba-843f-db35c487cad9.png)
![image](https://user-images.githubusercontent.com/28796466/234168297-bed2be7e-0195-4830-afc6-74a22bc2e400.png)
![image](https://user-images.githubusercontent.com/28796466/234168422-3ee11c14-9fb6-4e55-867d-7eef1a6eff81.png)
![image](https://user-images.githubusercontent.com/28796466/234168461-acc876c3-bb19-484e-bb79-c639c106d2ca.png)
![image](https://user-images.githubusercontent.com/28796466/234168511-4d474add-0c49-4c4d-acc9-3c12eb75f900.png)

But the output is still `IVSHMEMCreateDevice`, not `IVSHMEMCreateDevice 123456789`.

Where am I doing it wrong? How can I see the new log with new built driver?

Thank you very much if you can help!

**Comment by Youxu-Chen** [comment]
I uninstall the origin driver, and reinstall the new driver, rather than update it. Now, I can see the `IVSHMEMCreateDevice 123456789`.

Thanks @YanVugenfirer

**Comment by YanVugenfirer** [comment]
@Youxu-Chen no problem!
