### ISSUE TITLE
Changing the reported network speed from 1 Gbit/s to 10 Gbit/s in virt-io causes a bluescreen in Windows XP (Fedora 38 x64 host, Virtualbox 7.0.97)

### ISSUE THREAD

**Issue by FranceBB** [virtio-win/kvm-guest-drivers-windows#906]
## Software environment
 - Host Operating system: Fedora 38
 - Host Architecture: x64
 - Host kernel version: 6.2.12
 - Host Hypervisor and version: Virtualbox 7.0.97 r156983
 - Guest Operating system: Windows XP Professional (with Microsoft Premier Support Updates 'till July 2019)
 - Guest Architecture: x86
 - Guest libvirt version: virtio-win-0.1.229

## Hardware environment
- CPU: i7 6700HQ 4c/8th 2.60GHz
- RAM: 64GB DDR4 (2x32)
- GPU: NVIDIA GTX 950M 4GB GDDR5
- SSD: Samsung EVO 1TB Sata III (OS)
- SSD: Samsung QVO 1TB Sata III (Data)
- SSD: Intel 660p NVME 1TB (Virtual Machines)

## Description of problem

I noticed that, when switching to virtio, the default reported connection speed reported was 1 Gbit/s despite the fact that the virtual adapter should support 10 Gbit/s. I went in the settings and changed the reported speed from 1 Gbit/s to 10 Gbit/s (it's possible to do it from the registry as well, eventually), however it bluescreened.

## Steps to reproduce
1. Choose virt-io in Virtualbox as network adapter
2. Boot Windows XP Pro x86
3. Install the virt-io Windows drivers from the latest ISO (virtio-win-0.1.229.iso)
4. Reboot
5. Go to the correctly recognized virt-io network adapter and change the configuration from 1 Gbit/s to 10 Gbit/s
6. Confirm, apply, ok, close all the windows and wait for the bluescreen 

## Additional information

Logs:
[WindowsEmbedded-2023-04-23-13-47-46.zip](https://github.com/virtio-win/kvm-guest-drivers-windows/files/11307611/WindowsEmbedded-2023-04-23-13-47-46.zip)

Pictures showing the issue:
![Screenshot from 2023-04-23 13-45-03](https://user-images.githubusercontent.com/18946343/233923925-cc9a8f26-ea44-4a4a-9fef-53d6a2555bf6.png)
![Screenshot from 2023-04-23 13-45-20](https://user-images.githubusercontent.com/18946343/233923929-ea463b37-514b-41f0-83f0-00ca01f96975.png)
![Screenshot from 2023-04-23 13-45-42](https://user-images.githubusercontent.com/18946343/233923934-1226e41c-f34e-4ac5-bac0-f889cbae7c01.png)
![Screenshot from 2023-04-23 13-46-02](https://user-images.githubusercontent.com/18946343/233923938-fa824f05-1a5e-4bcc-855d-fd2bc7974d16.png)
![Screenshot from 2023-04-23 13-47-52](https://user-images.githubusercontent.com/18946343/233923940-face5f55-c754-4f71-b8a1-6a6b85ded5da.png)

**Comment by YanVugenfirer** [comment]
Hello @FranceBB,

Thank you for reporting the issue. 
Unfortunately, we are no longer handling Windows XP-related issues. And In any case, adapter speed in XP is mostly a cosmetic property. If you want to improve network performance in Windows XP, better follow this guide: http://www.linux-kvm.org/page/WindowsGuestDrivers/kvmnet/registry

Thanks,
Yan.
