### ISSUE TITLE
Error 0x8000FFFF Catastrophic Failure

### ISSUE THREAD

**Issue by wheelloader** [virtio-win/kvm-guest-drivers-windows#912]
**Describe the bug**
I Got Error 0x8000FFFF Catastrophic Failure when creating new Folder. I can delete file, right click and create new file without error, but when I do right click -->create folder, it will error

**To Reproduce**
Right click -- new folder

**Expected behavior**
New Folder  should be created without error

**Screenshots**
![image](https://user-images.githubusercontent.com/28740952/235824150-aaf99f7c-8cac-4131-9565-bf0507e9d739.png)

**Host:**
 - Disto: EndeavourOS
 - Kernel version : 6.2.13-arch1-1 

 - QEMU version : qemu-full 8.0.0.1
 - QEMU command line 
 - libvirt version : libvirt 1 :9.2.0-1
 - libvirt XML file : https://pastebin.com/JXfDMj8c

**VM:**
 - Windows version : Windows 10 Pro build 19045
 - Which driver has a problem : WinFSP 2023
 - Driver version or commit hash that was used to build the driver :2.0.23075

**Additional context**

**Comment by viktor-prutyanov** [comment]
Please, tell us your virtio-win version

**Comment by wheelloader** [comment]
Hi, I install VirtioFS driver from virtio-win10-prewhql-0.1-161

> Please, tell us your virtio-win version

**Comment by viktor-prutyanov** [comment]
> Hi, I install VirtioFS driver from virtio-win10-prewhql-0.1-161
> 
> > Please, tell us your virtio-win version
> 
> 

This is a very old version.

**Comment by wheelloader** [comment]
Sorry, my fault, I installed very old driver. Reinstall new driver and no issue. 
Thank you,
