### ISSUE TITLE
File Transfer, size limit with Windows 8.1

### ISSUE THREAD

**Issue by github2099** [virtio-win/kvm-guest-drivers-windows#915]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Windows 8.1 VM
2. Install Guest Tool (latest supported as in #914, is version 0.1.215)
3. Install [VIrtio FS](https://virtio-fs.gitlab.io)
4. Transfer file from host to guest, file size larger than 4 MB will give an error.
5. It will also stop the VirtIO-FS Service.

**Expected behavior**
Able to transfer any files, without file size limit.

**Screenshots**

![Screenshot from 2023-05-16 18-22-25](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/49584984/e6230322-2fb6-4ca2-954e-d70a49c5e990)

![Screenshot from 2023-05-16 18-22-52](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/49584984/e0d44687-5b69-499a-84c5-8288355dcd71)

![Screenshot from 2023-05-16 18-23-28](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/49584984/0432e719-3342-4aff-bb9e-b7fa76b19081)

![Screenshot from 2023-05-16 18-24-14](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/49584984/8e570f15-02fb-4f8c-b248-9a718dc5469f)

![Screenshot from 2023-05-16 18-31-09](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/49584984/d7fbaa83-ca28-41eb-8229-55be4e115e21)

**Host:**
 - Disto: Pop!_OS
 - Kernel version 6.2.6
 - QEMU version 6.2.0
 - libvirt version 8.0.0

**VM:**
 - Windows version Windows 8.1
 - Which driver has a problem Virtio FS
 - Driver version or commit hash that was used to build the driver  0.1.215

**Additional context**

**Comment by github2099** [comment]
Note to add, to avoid confusion.
I have the VirtIO-FS service "on" before transferring the files. When the error message pops up, the service is "stopped" automatically.

**Comment by viktor-prutyanov** [comment]
0.1.215 is too old
Please, try 0.1.229

**Comment by github2099** [comment]
> 0.1.215 is too old Please, try 0.1.229

this is a separate issue related to #914 
tried 0.1.229, but VirtioFS won't work on Windows 8 at all.

**Comment by YanVugenfirer** [comment]
Please reopen if it still happens.
