### ISSUE TITLE
virtio-fs: Cannot run executables in Windows guest

### ISSUE THREAD

**Issue by mriedel87** [virtio-win/kvm-guest-drivers-windows#917]
**Describe the bug**
It's not possible to run executables from virtio-fs share.
I didn't find any similar bug report, nor a hint in the documentation, except an 11 month bug report for [virtiofsd](https://gitlab.com/virtio-fs/virtiofsd/-/issues/51) with no outcome.

**To Reproduce**
Copy or install any executable to the share from within the guest and try to run it.

**Expected behavior**
Run executables from virtio-fs share.

**Screenshots**
See [virtiofsd bug report](https://gitlab.com/virtio-fs/virtiofsd/-/issues/51) 

**Host:**
 - Disto: Debian sid
 - Kernel version: 6.3.2
 - QEMU version: 8.0
 - QEMU command line: -device '{"driver":"vhost-user-fs-pci","id":"fs0","chardev":"chr-vu-fs0","queue-size":1024,"tag":"games","bus":"pci.11","addr":"0x0"}' \
 - libvirt version: 9.3.0
 - virtiofsd version: 1.6.0
 - virtiofsd command line: /usr/libexec/virtiofsd --inode-file-handles=mandatory --sandbox=chroot --allow-direct-io --log-level=trace --fd=33 -o source=/media/smb/games,cache=always,xattr

**VM:**
 - Windows version: 10 22H2
 - Which driver has a problem: virtio-fs
 - Driver version or commit hash that was used to build the driver: 0.1-229-1 ([feodora](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/virtio-win-pkg-scripts-input/virtio-win-0.1.229-1/))
 - winfsp version: 1.9.21096

**Additional context**
Only error on host side is: Replying ERROR, header: OutHeader { error: -2 (No such file or directory), unique: 2729, len: 16 }
The guest asks the host for "7z1805-x64.exe.Config" after double click on "7z1805-x64.exe" which does not exists.

**Comment by mriedel87** [comment]
I did some more testing.
You cannot run executables which require elevation (e.g. 7zip installer).
When you launch them via an elevated shell it works.

**Comment by mriedel87** [comment]
Windows is somewhat strange ...
Look at the rclone mount [caveat](https://rclone.org/commands/rclone_mount/#windows-caveats).
As a workaround you must not mount it as a drive letter, instead mount it as directory (e.g. C:\share).
This should be mentioned in the wiki, that if UAC functionality is required you must specify a directory as mount point.

**Comment by viktor-prutyanov** [comment]
Hi  @xiagao 

May I ask you to try to reproduce this issue on RHEL?

Thank you in advance

**Comment by xiagao** [comment]
> Hi @xiagao
> 
> May I ask you to try to reproduce this issue on RHEL?
> 
> Thank you in advance

Sure. 
I try to understand the issue described in comment 0. Hi @mriedel87 , you are trying to run some executable binary in the shared dir right? And you're a standard user(non-admin) in the windows VM, right?

Besides, : Replying ERROR, header: OutHeader { error: -2 (No such file or directory), unique: 2729, len: 16 } , this kind of error message also appears in the normal usage of shared dir, it seems not the cause of your issue.

**Comment by mriedel87** [comment]
Hi @xiagao,

yes it's a standard user and not a domain user nor the administrative account and yes I'm trying to run it in the shared dir. The error is tied to user account control mechanism. The executable has to enforce this mechanism to reproduce the error. Just try the 7zip installer or any executable which wants administrative rights.
The strange thing is, the error only occurs when the shared dir is mounted as a drive letter (e.g. X:).

Best regards,

Marc

**Comment by viktor-prutyanov** [comment]
Hi @mriedel87 

The issue described in this PR https://github.com/virtio-win/kvm-guest-drivers-windows/pull/920 looks similar, what do you think?

**Comment by mriedel87** [comment]
HI @viktor-prutyanov,

yes it looks like it's the same issue.
