### ISSUE TITLE
if=virtio “BIOS: could not read the boot disk” | Windows Server 2022

### ISSUE THREAD

**Issue by SystemOfTheCSGO** [virtio-win/kvm-guest-drivers-windows#938]
**Describe the bug**
I have tried everything, but the qemu-system-x86_64 does not boot with virtio, while other side loading devices like addtional drivers are successfully loaded with virtio drivers (the driver is installed in guest), whenever i set the main boot/system disk to virtio it fails to boot.

**To Reproduce**
Fresh installed qemu on debian, kvm enabled.
install windows server 2022 + virtio drivers without if=virtio.
add another disk with virtio and making windows organize the driver.
boot into windows fine with the main disk not having virtio
add if=virtio to main disk.
boot BIOS failed with message: “Boot failed: Could not read from the boot disk”

**Host:**
 - Disto: Debian 11
 - Kernel version 6.1.0-10-amd64
 - QEMU 7.2.2
 - QEMU command line 
 - libvirt version: not installed
 - libvirt XML file: not installed

**VM:**
 - Windows version: Windows Server 2022 latest
 - Which driver has a problem: Disk
 - Driver version or commit hash that was used to build the driver: virtio-win-0.1.229.iso

**Comment by SystemOfTheCSGO** [comment]
Booting fine: qemu-system-x86_64 -enable-kvm -cpu host,kvm=on -smp cpus=16,sockets=1,cores=8,threads=2,maxcpus=16 -boot menu=on -drive index=1,file=/[redacted]/disk1.img,if=virtio -drive index=2,file=/[redacted]/disk2.img,if=virtio -drive index=3,file=/[redacted]/disk3.img,if=virtio -drive index=4,file=/[redacted]/disk4.img,if=virtio -drive index=0,file=/[redacted]/system.img -m 24G -mem-prealloc -vga virtio -parallel none -serial none -monitor stdio -net nic,model=virtio -net nic,model=virtio -net user,hostfwd=tcp::3389-:3389 -vnc 127.0.0.1:0 -k en-us


Booting failed: qemu-system-x86_64 -enable-kvm -cpu host,kvm=on -smp cpus=16,sockets=1,cores=8,threads=2,maxcpus=16 -boot menu=on -drive index=1,file=/[redacted]/disk1.img,if=virtio -drive index=2,file=/[redacted]/disk2.img,if=virtio -drive index=3,file=/[redacted]/disk3.img,if=virtio -drive index=4,file=/[redacted]/disk4.img,if=virtio -drive index=0,file=/[redacted]/system.img,if=virtio -m 24G -mem-prealloc -vga virtio -parallel none -serial none -monitor stdio -net nic,model=virtio -net nic,model=virtio -net user,hostfwd=tcp::3389-:3389 -vnc 127.0.0.1:0 -k en-us

**Comment by menli820** [comment]
@SystemOfTheCSGO Thanks for reporting this issue.

I can reproduce the issue you described. And could you please try to move ' -drive index=0,file=/[redacted]/system.img ' 
before  '-drive index=1,file=/[redacted]/disk1.img,if=virtio' , it works on my side.

eg:
    -drive index=0,file=win2022-64-virtio.qcow2,if=virtio \
    -drive index=1,file=data1.qcow2,if=virtio \
    -drive index=2,file=data2.qcow2,if=virtio \
    -drive index=3,file=data3.qcow2,if=virtio \
    -drive index=4,file=data4.qcow2,if=virtio \

******************************************

reproduce command line:
 /usr/libexec/qemu-kvm \
    -name 'avocado-vt-vm3' \
    -machine q35 \
    -nodefaults \
    -vga std  \
    -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 \
    -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 \
    -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 \
    -device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 \
    -device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 \
    -device pcie-root-port,port=0x15,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5 \
    -device pcie-root-port,port=0x16,chassis=7,id=pci.7,bus=pcie.0,addr=0x2.0x6 \
    -device pcie-root-port,port=0x17,chassis=8,id=pci.8,bus=pcie.0,addr=0x2.0x7 \
    **-drive index=1,file=data1.qcow2,if=virtio \
    -drive index=2,file=data2.qcow2,if=virtio \
    -drive index=3,file=data3.qcow2,if=virtio \
    -drive index=4,file=data4.qcow2,if=virtio \
    -drive index=0,file=win2022-64-virtio.qcow2,if=virtio \**
    -device virtio-net-pci,mac=9a:36:83:b6:3d:05,id=idJVpmsF,netdev=id23ZUK6,bus=pci.6  \
    -netdev tap,id=id23ZUK6,vhost=on \
    -m 24G  \
    -smp cpus=16,sockets=1,cores=8,threads=2,maxcpus=16 \
    -cpu host,kvm=on \
    -vnc :1  \
    -boot menu=off,order=cdn,once=d,strict=on \
    -enable-kvm \
    -qmp tcp:0:1231,server,nowait \
    -monitor stdio \




@YanVugenfirer 

I didn't reproduce this issue with blockdev mode.  

 /usr/libexec/qemu-kvm \
    -name 'avocado-vt-vm3' \
    -machine q35 \
    -nodefaults \
    -vga std  \
    -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 \
    -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 \
    -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 \
    -device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 \
    -device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 \
    -device pcie-root-port,port=0x15,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5 \
    -device pcie-root-port,port=0x16,chassis=7,id=pci.7,bus=pcie.0,addr=0x2.0x6 \
    -device pcie-root-port,port=0x17,chassis=8,id=pci.8,bus=pcie.0,addr=0x2.0x7 \
    -blockdev node-name=file_stg1,driver=file,cache.direct=on,cache.no-flush=off,filename=data1.qcow2,aio=threads \
    -blockdev node-name=drive_stg1,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg1 \
    -device virtio-blk-pci,id=stg1,drive=drive_stg1,bus=pci.2,addr=0x0,bootindex=1 \
    -blockdev node-name=file_stg2,driver=file,cache.direct=on,cache.no-flush=off,filename=data2.qcow2,aio=threads \
    -blockdev node-name=drive_stg2,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg2 \
    -device virtio-blk-pci,id=stg2,drive=drive_stg2,bus=pci.3,addr=0x0,bootindex=2 \
    -blockdev node-name=file_stg3,driver=file,cache.direct=on,cache.no-flush=off,filename=data3.qcow2,aio=threads \
    -blockdev node-name=drive_stg3,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg3 \
    -device virtio-blk-pci,id=stg3,drive=drive_stg3,bus=pci.4,addr=0x0,bootindex=3 \
    -blockdev node-name=file_stg4,driver=file,cache.direct=on,cache.no-flush=off,filename=data4.qcow2,aio=threads \
    -blockdev node-name=drive_stg4,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_stg4 \
    -device virtio-blk-pci,id=stg4,drive=drive_stg4,bus=pci.5,addr=0x0,bootindex=4 \
    -blockdev node-name=file_sys,driver=file,cache.direct=on,cache.no-flush=off,filename=win2022-64-virtio.qcow2,aio=threads \
    -blockdev node-name=drive_sys,driver=qcow2,cache.direct=on,cache.no-flush=off,file=file_sys \
    -device virtio-blk-pci,id=sys,drive=drive_sys,bus=pci.1,addr=0x0,bootindex=0 \
    -device virtio-net-pci,mac=9a:36:83:b6:3d:05,id=idJVpmsF,netdev=id23ZUK6,bus=pci.6  \
    -netdev tap,id=id23ZUK6,vhost=on \
    -m 14336  \
    -smp cpus=16,sockets=1,cores=8,threads=2,maxcpus=16 \
    -cpu host,kvm=on \
    -device piix3-usb-uhci,id=usb -device usb-tablet,id=input0 \
    -vnc :1  \
    -rtc base=localtime,clock=host,driftfix=slew  \
    -boot menu=off,order=cdn,once=d,strict=on \
    -enable-kvm \
    -qmp tcp:0:1231,server,nowait \
    -monitor stdio \


Thanks
Menghuna

**Comment by YanVugenfirer** [comment]
Closing. 
Not related to virtio-win. 
If the command line order issue can be reported to QEMU.

Best regards,
Yan.
