### ISSUE TITLE
Http protocol related issue

### ISSUE THREAD

**Issue by DanielSarf** [virtio-win/kvm-guest-drivers-windows#949]
The website listed in this repo's description leads to a linux-kvm.org webpage that does not have the https protocol on it. Instead it is http, which is insecure especially because there is a log in functionality on the page.

Steps to reproduce the behaviour:
Click on the link in this repo's description, or go to http://www.linux-kvm.org/page/WindowsGuestDrivers

Expected behavior:
The page should route to a secure https:// version

![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/72676273/aa8e7748-b83d-4ae3-9975-0349c9587ed4)

**Comment by YanVugenfirer** [comment]
Fixed.
