### ISSUE TITLE
virtofs: errors when accessing with c++ std::filesystem

### ISSUE THREAD

**Issue by MichaelDietzel** [virtio-win/kvm-guest-drivers-windows#950]
**Describe the bug**
I am trying to launch the game factorio (1.1.87) from my virtiofs. However I get an error message that apparently originates from c++ std::filesystem. Translated to english it is something like: "weakly_canonical: There is no file system detected on the disk. Make sure all required file system drivers are loaded and the disk is not damaged." Launching from a real ntfs works flawlessly.

I tried the following, but it did not help:
- I tried the factorio-version from steam as well as the paid version and the free demo directly downloaded from factorio.com (afaik without drm).
- I first tried the drivers from virtio-win-0.1.229.iso from fedora, then I copiled them myself from master.
- I set the registry key for virtiofs to be case insensitive (does not seem to work well with the drivers from virtio-win-0.1.229.iso, works kind of ok with master)
- I set the registry key for virtiofs to report itself as nfts (does not work at all with the drivers from virtio-win-0.1.229.iso, but it works with master).

[My bug report in the factorio forums](https://forums.factorio.com/viewtopic.php?f=49&t=106460) where they tell they just use c++ std::filesystem.

**To Reproduce**
Steps to reproduce the behaviour:
1. set up a windows 10 vm that can run factorio from a regular ntfs. It probably needs graphics acceleration, I passed through a Nvidia GTX 1060. Maybe you do not even need the graphics acceleration as the error may trigger before needing any. I have not tested it without, though.
3. install virtiofs using winfsp 2.0
4. set up virtiofs on Z:, configured to be case insensitive + report to be ntfs
5. download the zip-version of the free demo of factorio from [factorio.com](https://factorio.com/download) and unpack it on Z:
6. launch factorio (\bin\x64\factorio.exe)

**Expected behavior**
Factorio launches without any error message. As do a few other steam-games I tested.

**Screenshots**
![Factorio virtiofs](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/14862324/c9c8ffeb-231f-4a95-b6f2-ecc95328c3a4)

**Host:**
 - Disto: Ubuntu 22.04
 - Kernel version: 5.15.0-67 with a patch for creative x-fi soundcard passthrough
 - QEMU version: 6.2.0
 - libvirt version: 8.0.0
 - The storage for virtiofs is on zfs

**VM:**
 - Windows 10 21H2
 - virtiofs
 - Driver version or commit hash that was used to build the driver: 0.1.229.iso and 65cea19

**Comment by viktor-prutyanov** [comment]
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/517

**Comment by viktor-prutyanov** [comment]
The issue is the same as #517 

```cpp
#include <iostream>
#include <filesystem>

int main()
{
	auto p = std::filesystem::path("Z:\\");

	try
	{
		auto p2 = std::filesystem::weakly_canonical(p);
		std::cout << p2 << std::endl;
	}
	catch (const std::exception& ex)
	{
		std::cout << ex.what() << std::endl;
	}

	return 0;
}
```

With `-m Z:`

```
weakly_canonical: The volume does not contain a recognized file system.                                                 Please make sure that all required file system drivers are loaded and that the volume is not corrupted.: "Z:\" 
```

With `-m \\.\Z` (global mount):

```
Z:\\
```

**Comment by viktor-prutyanov** [comment]
@MichaelDietzel
There is a workaround for your use: use global mount (i.e. mount `\\.\Z:` instead of `Z:\`)
