### ISSUE TITLE
Audio not working on Windows 11

### ISSUE THREAD

**Issue by EvansPM** [virtio-win/kvm-guest-drivers-windows#958]
I installed Windows 11 using virtio-win-0.1.229.iso, following this [tuto](https://www.youtube.com/watch?v=0RiUrsljD_E).
All working except audio.

Audi driver installed, but no sound.
I reinstalled it , no changes.

**Host:**
 - Disto:  Ubuntu 22.04
 - QEMU [Sound]: HDA (ICH9) , I tried the other on list also.

I tried [this](https://getlabsdone.com/kvm-windows-no-sound-lets-fix-it/), no changes.

Any ideas?

Thanks.

**Comment by YanVugenfirer** [comment]
Hi,

Sorry, this issue is not related to virtio-win drivers.
In any case, please check that you are using HDA device with Windows 11.

Best regards,
Yan.
