### ISSUE TITLE
virtiofs.exe won't mount to custom mount letter when run as a service.

### ISSUE THREAD

**Issue by chrisposito** [virtio-win/kvm-guest-drivers-windows#968]
virtiofs.exe ignores the parameter when set via ImagePath value of a service in the registry like so:
C:\Program Files\Virtio-Win\VioFS\virtiofs.exe -m k:

**To Reproduce**
Attempt to add the drive letter parameter on the ImagePath value or as a Parameter key in the registry.
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/80066321/90ce0883-7748-4554-a728-c8b836d176ed)

**Expected behavior**
A way to persistently set a custom drive letter that doesn't conflict with other mounts, which behaves the same way as using the service properties dialog box to set a temporary "Launch parameter" like so:
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/80066321/20622916-00ae-46ce-a27b-2e8e2b399d11)

**Host:**
Ubuntu 22.04.2 LTS
6.2.0-26-generic
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.12)
libvirtd (libvirt) 8.0.0

**VM:**
 - Windows version Windows 10 21H2 (OS Build 19044.3086)
 - VioFS
 - Virto-win-guest-tools version 0.1.229

**Additional context**

**Comment by viktor-prutyanov** [comment]
Please read about MountPoint registry key https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Virtiofs:-Shared-file-system#options

**Comment by chrisposito** [comment]
Thanks so much, sorry I missed that! I was trying to figure that one out for hours.
