### ISSUE TITLE
In the scenario of continuous transmission of small TCP packets, this may result in excessive paging. ultimately leading to packet loss in netkvm driver

### ISSUE THREAD

**Issue by zjmletang** [virtio-win/kvm-guest-drivers-windows#972]
**Describe the bug**
the maximum number of fragments that can be accommodated by one descriptor is 256.However, in the scenario of sending small TCP packets, one NB_BUFF may have more than 256 fragments, which can cause sending to fail.
//related code
virtio_get_indirect_page_capacity()
{

return PAGE_SIZE / sizeof(struct vring_desc);

}

//related code

bool CTXDescriptor::AddDataChunk(const PHYSICAL_ADDRESS &PA, ULONG Length)

{
    if (m_CurrVirtioSGLEntry < m_VirtioSGLSize)
    {
        m_VirtioSGL[m_CurrVirtioSGLEntry].physAddr = PA;
        m_VirtioSGL[m_CurrVirtioSGLEntry].length = Length;
        m_CurrVirtioSGLEntry++;
  DPrintf(0, "zjm current < viritoSGLSize [%d] [%d] Length [%d]\n", m_CurrVirtioSGLEntry, m_VirtioSGLSize, Length);

        return true;
    }
   else
   {
       DPrintf(0, "zjm current > viritoSGLSize fail [%d] [%d]\n", m_CurrVirtioSGLEntry, m_VirtioSGLSize);   // it may happen
   }

    return false;
}

**To Reproduce**
just like https://github.com/virtio-win/kvm-guest-drivers-windows/issues/942. 
The issue 942 primarily emphasizes the limitations on the network card hardware, while this case mainly illustrates the limitations of our own driver. However, the method of reproduction is the same.

**Comment by ybendito** [comment]
@zjmletang   !IUC, we need the steps to reproduce the case when we get more than 256 fragments.
