### ISSUE TITLE
virtio-win binary drivers are only legal for use on RHEL hosts?

### ISSUE THREAD

**Issue by ArrayBolt3** [virtio-win/kvm-guest-drivers-windows#975]
**Describe the bug**
I stopped to read some of the license agreements in the virtio-win drivers before installing them, and discovered the following rather surprising terms in the installer, specified as applying to the virtio-win drivers themselves:

```
2. Program License Grant.

Red Hat grants User a non-exclusive, non-transferable license to use the Program during the term of and on systems with fully-paid applicable Red Hat subscription(s) provided User may not:
...
```

I don't have any problems with the rest of the license (including the terms against modification of the software), but the bit about "fully-paid applicable Red Had subscription(s)" is throwing me off. These drivers are available for public download for free. Proxmox and Fedora both suggest using them to enhance Windows guests. I personally would like to use them to enhance a Windows guest running on an Ubuntu device. I don't own any RHEL subscriptions, and don't use RHEL at all.

Does this mean that I don't have a license to use the virtio-win drivers? If not (i.e., I can use these), it would be ideal if this could be made more clear. If so (i.e., I can't use these), then some explicit notice along the lines of "You may not use these drivers on a guest running on a host that is not licensed with an applicable Red Had subscription" would be helpful, ideally if it were on the first page of the installer.

**Screenshots**
![image](https://github.com/virtio-win/kvm-guest-drivers-windows/assets/104878738/f19d91ad-b62d-4964-ab93-70c519fee39c)

**Host:**
 - Disto: Kubuntu 22.04 LTS

**VM:**
 - Windows version: Windows 11 Enterprise Evaluation

**Comment by ArrayBolt3** [comment]
More confusing, the driver ISO file ships a file titled "virtio-win_license" which appears significantly newer due to the copyright dates, and just contains a generic BSD-3-Clause license. Which license is the right one?

**Comment by vrozenfe** [comment]
@ArrayBolt3 
Thank you for reporting this issue.
There is definitely a problem with the license agreement in the public virtio-win package. This agreement is  just a copy of the license agreement which comes with internal package, available for the RH customers. 
We will try to fix this issue in the next public release. Meanwhile nothing stops you from using the public virtio-win package on non-RH products.

All the best,
Vadim.
