### ISSUE TITLE
Support for 'VssOption'

### ISSUE THREAD

**Issue by NiceRath** [virtio-win/kvm-guest-drivers-windows#984]
**Is your feature request related to a problem? Please describe.**
VM's running databases like MSSQL-Server have issues when the qemu-agent is using full VSS freezing.
Reference: [Proxmox Backups breaking SQL-Backups](https://forum.proxmox.com/threads/pbs-breaking-customer-sql-backups-backups-without-fs-freeze.111526/)

Grepping over the whole repository did not show any references to 'VssOptions' (_see below_)

**Describe the solution you'd like**
Implement the VssOption setting as seen in these qemu commits:
* [qemu VSS backup type](https://github.com/qemu/qemu/commit/410542d4a2d7c1d8136d3e49fc3ca29fbb76789a)
* [qemu installer VssOption](https://github.com/qemu/qemu/commit/fe67fc0eb47834840c54a065c99b55b5ff5120a6)

**Describe alternatives you've considered**
Disabling qemu VSS handling

**Comment by kostyanf14** [comment]
Hi @NiceRath,

VssOption is a setting of QEMU guest agent. This repository does not edit the QEMU guest agent.  https://github.com/virtio-win/virtio-win-guest-tools-installer contains an installer but it also does not touch the QEMU guest agent, it just gets compiled qga.msi and runs it as is.

Please describe what you mean by "Support for 'VssOption'" in this repository.

**Comment by NiceRath** [comment]
Greetings!

@kostyanf14 Thank you for the clarification.
If I understand it correctly the installers listed at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/ are compiled like that, am I correct?
So in the next virtio-win version (_the last one seems to be from Jan 2023_) this option should be available?

I understand if that information is not known to you - but it would be important to know for users that have these issues with their virtio-win installation.

**Comment by kostyanf14** [comment]
@NiceRath 

>So in the next virtio-win version (the last one seems to be from Jan 2023) this option should be available? (as the option as commited at Mar 2023 to qemu)

Yes, in the next release, this option should be available.

**Comment by NiceRath** [comment]
@kostyanf14 Thank you for the helpful information!
Is there any known release-schedule for the virtio-win installers? (_6 months, 1 year_)
I haven't seen any mentioned in the 'virtio-win-guest-tools-installer' repository readme.

Just so the affected users know how long they will approximately need to wait.

Have a nice day!

**Comment by kostyanf14** [comment]
Hi @vrozenfe,

Can you please answer about "release-schedule for the virtio-win installers"?

**Comment by NiceRath** [comment]
Seems there was a new release in the meantime.

**Comment by vrozenfe** [comment]
Technically we can publish a new stable virtio-win package every 6 months approximately.    
This schedule is mostly related to our internal virtio-win package releasing work flow.  

Best regards,
Vadim.

**Comment by NiceRath** [comment]
Thank you for the information.

Have a nice day!
