### ISSUE TITLE
[Question] What's wrong about the git and developing history of spice' virtio-gpu-dod and viogpudo?

### ISSUE THREAD

**Issue by Andy312432** [virtio-win/kvm-guest-drivers-windows#986]
I know this repository does not care about spice, but I got confused of some repository having same name...

1. spice' [virtio-gpu-dod](https://gitlab.com/spice/win32/virtio-gpu-wddm-dod)
This project seems to have no activities since 2017.

2. spice's [qxl-wddm-dod](https://gitlab.freedesktop.org/spice/win32/qxl-wddm-dod)
This project seems to not in active developing state in recent years.

3. utm's modified [virtio-gpu-wddm](https://github.com/utmapp/virtio-gpu-wddm-dod/commits/main)
This project seems to have forked from somewhere else in 2017. 

4. this repository since 2020.

All of the above seems to share the exact same code (from Microsoft's demo?), but having different states...

My question is,1. What's wrong between 2017..2020 ?(And where's the git history?) 
2. And, if I use spice as frontend, and virtio-gpu as backend, what should I use?
3. If #943 gets merged, will it support my setup?

(Currently my setup is a mac(iPadOS) program called UTM, a Win11 arm64 VM, and using 
3, results in some qxl functions(resolution, cursor accl. works
4. results in more bug fixes(WDDM3.1, and better PnP support.))
Thanks!

**Comment by YanVugenfirer** [comment]
Hi @Andy312432,

Let's try to make some sense of all the repositories.

First of all, what is Spice? Spice is a way to accelerate 2D graphics for VMs. There were some attempts to add 3D, but I am not sure that the repo was eventually public (one less repo to discuss :) ). Spice uses "QXL" para-virtualized device.  
So:
* https://gitlab.com/spice/win32/qxl - this is a QXL driver for Windows XP and 7 (It still can be used on 8, if I am not mistaken, and no one cases about Vista - but it works there too). This is a driver built according to the old (Windows XP) architecture for graphic adapters drivers. One kernel module for a driver.
* https://gitlab.com/spice/win32/qxl-wddm-dod - This is a QXL driver for Windows 10 (can also be used on 8.1) and up. There is a new architecture (WDDM) for graphic adapter drivers. The full solution should have a kernel module and user space driver. We have only a kernel module as we provide a "display only" driver. Meaning we support only frame buffer without any 3D acceleration.

Meanwhile a virtio-gpu device was created. Mind - this is a separate device. It is not related to Spice or QXL device. The idea of virtio-gpu is to pass the graphic commands to the host. All the work that was done around this device is now merged or related to this repo. As this repo hold Windows implementation of the drives for virtio devices.
* https://github.com/virtio-win/kvm-guest-drivers-windows/tree/master/viogpu - current display-only driver (as mentioned above, this is framebuffer only. no acceleration).
* https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943 - PR to add 3D support. If you are a technical person, and can compile code - I suggest to test it and report issues. 

Best regards,
Yan.

**Comment by Andy312432** [comment]
Thanks for your reply! I didn't know about that spice has ever tried to make 3d accl. It all makes sense now thanks!
