### ISSUE TITLE
windows install fails with error 0x80070001

### ISSUE THREAD

**Issue by daggs1** [virtio-win/kvm-guest-drivers-windows#999]
I have a windows vm executed via libvirt, I run it on a physical drive passing it into the guest. when I pass it via sata pt and try to install windows 11 on it, the install fails with error 0x80070001. I had an installation there which resulted with periodic bosd when sata pt was used.
if I pass the /dev node, I don't get the errors but the performance is horrible due to high hdd usage

reproduction can be done using the attached libvirt xml

I'd expect the sata pt to work without any issues like dev node pt.

host info:
 - Disto: Gentoo
 - Kernel 6.6.1
 - QEMU 8.1.2
 - QEMU cmd: [qemu cmd.txt](https://github.com/virtio-win/kvm-guest-drivers-windows/files/13379607/qemu.cmd.txt)
 - libvirt 9.9.0
 - libvirt xml: [save.xml.txt](https://github.com/virtio-win/kvm-guest-drivers-windows/files/13379495/save.xml.txt)
 
vm info:
 - Windows 11
 - SCSI pt virtio controller
 - virtio-win 0.1.240.1

I've tested the same setup with ubuntu, doing read and write to the device of multiple GB, no issue at all

**Comment by YanVugenfirer** [comment]
Hello @daggs1,

I suggest opening this issue with the QEMU community.
If you are using SATA passthrough, virtio-win drivers are not involved.

Best regards,
Yan.

**Comment by daggs1** [comment]
Greetings @YanVugenfirer,

do you say that despite the fact that the same vm doesn't reproduces the issue when running ubuntu still means this is a qemu issue?

Dagg

**Comment by YanVugenfirer** [comment]
Hi @daggs1 , first of all, what I mean is that it's not a virtio-win issue. 
I would suggest to try using the latest QEMU. Then you can try to understand if this is a distro or QEMU issue. In any case, qemu community is the better place for it.

Best regards,
Yan.
